### ISSUE TITLE
Can not connect to web when the device has been authed

### ISSUE THREAD

**Issue by BingzheHan** [nodogsplash/nodogsplash#100]
Dear sir,
I have a problem with the nodogsplash.

I config the nodogsplash with no user auth method, but when my device authed with click the image, I still can not connect to web, it return the splash.jpg to me. And I use the ndstl to check the status of nodogsplash, it shows the dev is authed.

I don't why, could you help me analysis the problem.

Thanks and best regard.

**Comment by bluewavenet** [comment]
@BingzheHan This is most likely to have been a configuration error. Apologies for the lack of replies to your issue.
