### ISSUE TITLE
where should I modify splash.html before compile in openwrt

### ISSUE THREAD

**Issue by rophie123** [nodogsplash/nodogsplash#101]
openwrt/feeds/nodogsplash/resources/splash.html
it doesn't work

**Comment by bluewavenet** [comment]
It is easy enough to overwrite or edit post install. It is just a simple html file in plain text. Why do you need to do it before compiling?

**Comment by bluewavenet** [comment]
If you need an image with changes incorporated for rolling out in production just use the OpenWrt Image Generator and include NodogSplash with your own configuration files and your splash.html or anything else you need.
It is very simple and quick to use.
https://wiki.openwrt.org/doc/howto/obtain.firmware.generate

**Comment by mwarning** [comment]
@rophie123 In case you want to include some custom files into the images, place them into
openwrt/files/etc/nodogsplash/htdocs/
(everything inside files will be placed into the file system of the image)
