### ISSUE TITLE
Possiblility to pass $redir to BinVoucher or enable php for splash?

### ISSUE THREAD

**Issue by 3gem** [nodogsplash/nodogsplash#103]
Is it possible to pass $redir to BinVoucher?  I am trying to do auth depending on what url was entered for redirection.  

Is  there a way to enable php for the splash page?

Thanks

**Comment by bluewavenet** [comment]
You can run php on the OpenWrt box and link to a page served by uhttpd that is running for Luci web interface. I do this for TOS acceptance and advertising pages and it works very well. I have not tried to use BinVoucher yet.

**Comment by 3gem** [comment]
Thanks for the suggestion, but since the user is not authenticated yet it will not allow access to the uhttpd web server just ends up in an endless loop.  The goal is to pass credentials automatically for some users, but I do not want to use the mac, just a generic password since the user will not have a static device.

**Comment by bluewavenet** [comment]
Just add the following to nodogsplash.conf to allow access for preauth users:
# FirewallRuleSet: preauthenticated-users
      FirewallRule allow tcp port 80 to [ip address of your hotspot]
Then you can build whatever you like into the /www directory and have it served to the preauth client.

**Comment by willmkt** [comment]
Hi,

I want the splash page to be a external page on my web server

How to i do it? any suggestions? 

Thanks

**Comment by bluewavenet** [comment]
You can create a walled garden with FirewallRuleSet: preauthenticated-users but have to put in the ip address of each web site. 
I tend to think of the "Splash Page" separately from the "Authentication Page". The actual authentication call into Nodogsplash must ultimately happen on the router so you must leave a path back to that point for the user somehow.
I would however ask the question why do you want to go to an external web server as preauthenticated?

**Comment by willmkt** [comment]
Hi @bluewavenet,

I want to go to an external web server as preauthenticated, when the user connects to the server it autheticates.
 
With nocatsplash i was able to do it using ddwrt, but it is very limited.

Do you have any idea on how to do it?

Thanks.

**Comment by bluewavenet** [comment]
Hi @willmkt ,
Do you want the external server to do some kind of authentication eg Facebook or Google login etc. ?
Or is it something you are writing for the external site?
Ultimately you have to pass the nodogsplash token ($tok) back to the nodog server.

**Comment by bluewavenet** [comment]
See Forward Authentication Service in master.
