### ISSUE TITLE
Question rather than issue - how to build ipk?

### ISSUE THREAD

**Issue by silarsis** [nodogsplash/nodogsplash#104]
Heya,

I'd like to be able to compile my own ipk from this codebase, but I'm relatively new to openwrt and package management - I can't see how the release ipk is built from this repo, do you have any pointers please? I can build the binaries, but can't find how the structure is put together for the final packaging.

Thanks,

**Comment by mwarning** [comment]
The neccessary package files are located here: https://github.com/openwrt-routing/packages/tree/master/nodogsplash (i is the location of the so called openwrt-routing feed)

You can also just build OpenWrt

    git clone git://git.openwrt.org/15.05/openwrt.git
    cd openwrt
    
    ./scripts/feeds update -a
    ./scripts/feeds install -a
    
    make defconfig
    make menuconfig

In the menu, select some router model and nodogsplash.
When you execute "make" afterwards, the router images are build,
but you can also find the ipk packages (e.g. of nodogsplash) somewhere
in the generated ./bin/ folder.

**Comment by silarsis** [comment]
Thank you for that - very helpful :)
