### ISSUE TITLE
Can javascript libraries like AngularJS be used in splash page?

### ISSUE THREAD

**Issue by hezhijun** [nodogsplash/nodogsplash#105]

**Comment by bluewavenet** [comment]
Yes - as long as the client can find the library before being authenticated.

**Comment by hezhijun** [comment]
@bluewavenet , thanks. I am new to nodogsplash, my htdocs directory looks like below
#### /nodogsplash/htdocs/
##### splash.html
##### dist/

All my javascript libraries are located under the dist directory, the splash.html runs correctly in my local PC, but the splash page can not be displayed when I copy it to the router. What can I do to let splash page  find the the libraries under dist directory? thanks in advance.

**Comment by bluewavenet** [comment]
It is probably best to let the OpenWrt web server (used for Luci web interface) serve up your libraries.
To do this add the following line to nodogsplash.conf under the FirewallRuleSet preauthenticated-users  section:
FirewallRule allow tcp port 80 to [IP Address of your router]
Ten create a folder /www/dist and put your libraries in there.
Finally in your splash.html file, point to the libraries with the URL http://openwrt.lan/dist

**Comment by hezhijun** [comment]
@bluewavenet, thank you very much, that works.

**Comment by bluewavenet** [comment]
You are welcome @hezhijun .
Hint: You can also install php on OpenWrt. Then suddenly it all becomes very powerful ;)

**Comment by hezhijun** [comment]
Hi @bluewavenet , thanks for the information. I am not very familiar with php, I am planning to use Nodejs.  But before that, I have another problem. The splash page with javascript library under /www works in browser, but does not work in the popup authentication window on iPhone and Android. Do you know how to solve this problem?  thanks in advance.

**Comment by bluewavenet** [comment]
Captive portal detection on mobiles does seem to be a black art and varies between OS versions as well as devices. Nodogsplash does not do anything to break this and it works for me, even with the entire splash page moved to /www.
Does it eventually display, after a long delay of many seconds?
There are numerous tweaks that can be done on your splash page to help speed up display with the difficult mobile OS versions. 
A quick test: On a device that is not detecting - in your WiFi setup on the device, "Forget" the ssid of your Nodog box. Then re-select the ssid. Does it work then?
