### ISSUE TITLE
How can i redirct the client to splash page when AP is offline? thx a lot!

### ISSUE THREAD

**Issue by mail2keen** [nodogsplash/nodogsplash#106]
first of all, many thanks for your great work,  splash so quickly than others.
@smoe @lynxis @gazambuja @mwarning @KeaneWang 

My question now is how to use nodogsplash in local when there is no connection to the internet 。When the AP is offline, DNS doesn't work, so the client cannot redirect to the portal page through the domain。However it works via ip。what should I do to resolve the problem under this circumstance? Please response at your earliest convenience. Your great help would be highly appreciated.

**Comment by mail2keen** [comment]
The problem regarding to offline splash has been resolved. 
Here is how I get it done:

- Change the dnsmasq,l Add one line “address=/#/1.1.1.1

-  Point all DNS requests to the same IP, in order to active the splash page. 

Then new problem comes. How to get it easily switched between these two models: 

- using the normal DNS to visit the page via internet when online 

- and using the dnsmasq as the fake DNS to visit the splash page when offline. 

Judging the network connection, then changing and restarting the dnsmasq should be alright, but it will result response delay. 

Please let me know if you have a better solution. THX!

**Comment by mwarning** [comment]
Please use the mailing list for question: nodogsplash@ml.ninux.org
Not the Bug-Tracker..

**Comment by chengdanhao** [comment]
@mail2keen 
I am experiencing the same issue. 

I tryied to follow your solution, but didn't know where should I to add the line:

Change the dnsmasq,Add one line “address=/#/1.1.1.1"

**Comment by mwarning** [comment]
@chengdanhao it is mentioned here: https://github.com/nodogsplash/nodogsplash/wiki/FAQ

**Comment by chengdanhao** [comment]
@mwarning Thanks very much! I will transplant commotion-dnsproxy into my openwrt source.

**Comment by chengdanhao** [comment]
@mwarning 
I want to ask you some problems, I send a e-mail each to **nodogsplash@ml.ninux.org** and **nodogsplash-owner@ml.ninux.org**, both of them were rejected. :(

You are not allowed to post to this mailing list, and your message has been automatically rejected.  If you think that your messages are being rejected in error, contact the mailing list owner at nodogsplash-owner@ml.ninux.org.

Here is my e-mail content:

In this issue, you give me a solution to show splash page when AP is offline. Now I have port the commotion-dnsproxy in OpenWrt, but I don't know how to make it works.

I use the following steps, but the splash page didn't popup:
1. Type command : **dnsproxy -n -b 8006 -p /tmp/cdh -s 53 -i br-lan**
2. Then screen prints the debug message
```
[LOG_DEBUG] (dnsproxy.c:226) Executing command: iptables -I PREROUTING -t nat -i br-lan -p udp -d 192.168.88.254 --dport 53 -j DNAT --to-destination 192.168.88.254:8006 -m comment --comment "Commotion DNS proxy"
[LOG_DEBUG] (dnsproxy.c:243) Process PID 1799 exited normally, status 0
```
3. Type command : **iptables -t nat -nvL --line-number**
```
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination        
1        0     0 DNAT       udp  --  br-lan *       0.0.0.0/0            192.168.88.254       udp dpt:53 /* Commotion DNS proxy */ to:192.168.88.254:8006
2     1908  132K delegate_prerouting  all  --  *      *       0.0.0.0/0            0.0.0.0/0          
3     1908  132K ndsOUT     all  --  br-lan *       0.0.0.0/0            0.0.0.0/0   
```       

Did I miss something?

I guess maybe you have already used this dnsproxy, I hope you can give me a little hint.

I am looking forward to your reply, thanks very much.

**Comment by bluewavenet** [comment]
If you are wanting to use NodogSplash for an unconnected wifi service like museum or gallery information etc. the dnsmasq method is all you need.

Edit /etc/init.d/dnsmasq 

Find the start_service() section.

Find the line
echo "# auto-generated config file from /etc/config/dhcp" > $CONFIGFILE"

After this line add
echo "address=/#/1.2.3.4" >> $CONFIGFILE"

Save, then in a terminal type /etc/init.d/dnsmasq stop
followed by /etc/init.d/dnsnasq start

Then EVERYTHING will resolve as 1.2.3.4 and get captured by NodogSplash. The splash page can then be in turn redirected to your information page. This should work flawlessly on mobile devices, taking them to the Info page on the device's browser.

**Comment by chengdanhao** [comment]
@bluewavenet 
Glad to see you again :)

Yes, you are right, in these places, add a line is enough, I tried and also succed.

My device will connect internet in most of the time. But sometimes, maybe cable disconnect by accident, device will offline. At this time, the splash page won't popup again.

I want the splash page popup when I connect the wifi for the first time whether device is online or not. so I want to use the dnsproxy.
