### ISSUE TITLE
Binvoucher Atuth not sending user to redirecturl

### ISSUE THREAD

**Issue by 3gem** [nodogsplash/nodogsplash#107]
I am using Binvoucher it works great to authorize.  I have the RedirectURL parameter defined within nodogsplash.conf, but it does not work when binvoucher is used. It just passes the user to theier originally requested page.  If the user is not authorized, and is sent to the splash page to enter a password, then the redirect works.  Below is the conf file:
`GatewayInterface wlan0-1
gatewayname nodog
maxclients 15
redirecturl http://local.lan/redir.php
enablepreauth yes
binvoucher /bin/binvoucher
PasswordAuthentication yes
Password 123
FirewallRuleSet authenticated-users {
    FirewallRule allow tcp port 22
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 53
    FirewallRule allow tcp port 80
    FirewallRule allow tcp port 443

}
FirewallRuleSet preauthenticated-users {
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 53

}
FirewallRuleSet users-to-router {
    FirewallRule allow tcp port 22
    FirewallRule allow tcp port 23
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 53
    FirewallRule allow udp port 67
    FirewallRule allow tcp port 80
    FirewallRule allow tcp port 443
    FirewallRule allow tcp port 8080
}
FirewallRuleSet trusted-users {
}
FirewallRuleSet trusted-users-to-router {
}

`
Thanks for any help.

**Comment by bluewavenet** [comment]
What do you do once your binvoucher script terminates? It might just be a matter of over riding $redir as passed from Nodogsplash to splash.html.
I tried the RedirectUrl parameter a few years ago when I first started with Nodogsplash and could not get it to work but did not need it so did not investigate. Perhaps it does not work. No matter, it is easy to send clients wherever you like using $redir once you return to Nodogsplash with the token.
Which version are you using and which version of OpenWrt?

**Comment by 3gem** [comment]
I'm using the newest Caos Calmer 15.05. the script passes 0 0 0, or 22000 0 0(authorized status).  Once it is successfully authorized how do I redirect it.  The goal is to redirect it to the routers uhttpd server so I can utilize php scripting.  I tried FirewallRule allow tcp port 80 to 192.168.1 to redirect all port 80 traffic as stated in the conf file, but nothing happened

Thanks

**Comment by bluewavenet** [comment]
Which version of Nodogsplash are you using? 

Also, what router are you using?

I could not get Binvoucher to work correctly, so I bypassed it completely, in html and php. This is done in splash.html, redirecting to php on uhttpd, passing $authaction, $tok and $redir to php. It works perfectly, whereas Binvoucher was problematic, for me anyway. If you did this you could run your Binvoucher script from php if required.

**Comment by 3gem** [comment]
Nodog is 0.9_beta9.9.9-5
Do I need to add anything special to the nodogsplash config for it to allow pre-authed users to hit the uhttpd pages? or do I need to pass the $token before I direct to the php pages?

**Comment by bluewavenet** [comment]
Here is an example of the only entry required in nodogsplash.conf
Of course you do need to put in the actual IP address of your router if it is not 192.168.1.1
`# FirewallRuleSet: preauthenticated-users
FirewallRuleSet preauthenticated-users {
      FirewallRule allow tcp port 80 to 192.168.1.1
}
# end FirewallRuleSet preauthenticated-users
`

**Comment by bluewavenet** [comment]
Yes, as soon as you submit authaction and tok the client moves from preauth to auth.

**Comment by 3gem** [comment]
I have added the rule, and modified the splash.html to redirect, but it just ends up in and endless loop of authentication.  Below is the redirect in the splash.html 

<meta http-equiv="refresh" content="0; URL=http://nodog.lan/test_auth.php?clientip=$clientip&tok=$tok&redir=$redir&authaction=$authaction" />

Am I missing somethig?  I also noticed within the http.c code "remote_auth_action"  do I need to add this to the nodogsplash.conf file?

**Comment by bluewavenet** [comment]
I cannot see your splash.html.
Here is an example of mine - redirecting to /www/nodog/login.php
note this passes all the nodogsplash variables to the php file.
[splash.html.txt](https://github.com/nodogsplash/nodogsplash/files/159237/splash.html.txt)

**Comment by bluewavenet** [comment]
Try putting a simple html file (eg test.htm) in /www then point to it with the URL http://openwrt.lan/test.html
If this goes into the endless loop then something is wrong.
Can you access OpenWrt Luci when preauth?
I am using 0.9_beta9.9.9-1 on ar71xx and x86, (both on OpenWrt BB for now). 
I'll post my nodogsplash.conf next.

**Comment by bluewavenet** [comment]
[nodogsplash.conf.txt](https://github.com/nodogsplash/nodogsplash/files/159278/nodogsplash.conf.txt)
Note, binvoucher parts are disabled as it does not work in 0.9_beta9.9.9-1 
Don't need it once you break out to php.

**Comment by bluewavenet** [comment]
And finally here is an example login.php that simply returns the token to authaction with redir pointing back to a welcome.php page for display once authenticated by nodogsplash.
[login.php.txt](https://github.com/nodogsplash/nodogsplash/files/159282/login.php.txt)

**Comment by 3gem** [comment]
My html redirect mimics the one you posted just in a different order.  I removed enablepreauth from my conf file, but I am sill getting the endless loop. logread is showing continuous 404 catches by nodogsplash when attempting to connect to the local php pages.  Thanks for your help.  I think I am going to dive into the source code and see if I can find the solution.  I will post back if I make any progress.

**Comment by bluewavenet** [comment]
Sounds like it is either the version you are using, or enabling binvoucher breaks something. A quick test would be to comment out all the binvoucher stuff in nodogsplash.conf and see if as preauth, you can access Luci. Remembering to restart nodogsplash after editing the config ;)
Is the version you are using even looking at nodogsplash.conf?

**Comment by bluewavenet** [comment]
#97

**Comment by 3gem** [comment]
Solved!!  I have two networks defined br-lan and wlan0.  nodogsplash resides on wlan0.  I was enabling access to the wlan0 ip, but not the br-lan ip which hosts  /www.  Everything works great now.  Thanks for all your help @bluewavenet

**Comment by bluewavenet** [comment]
Excellent!
By the way, which model router are you using?

**Comment by 3gem** [comment]
Currently I am running it on a Dragino, but it works on all my Atheros based routers in addition to my old wrtsl54gs.  Binvoucher works properly, along with the redirect you helped me with.

**Comment by wrrr** [comment]
I'm just digging into NDS and appreciate this is one of the few posts I've found to address the issue raised.  

On your login.php.txt and splash.html.txt samples you are redirecting to - http://openwrt.lan/nodog/login.php

How do/did you derive that url?  I'm using Openwrt/LEDE and don't understand the convention (dot.lan)? How do I create that kind of url in my environment? (Hopefully not too lame a question:)

Thanks for any insight you can provide!
Stu

**Comment by bluewavenet** [comment]
@wrrr 
This thread is pretty old but actually very relevant as Binvoucher is not supported in V2 and pretty much broken elsewhere as far as I can see. I am thinking of writing a proper guide and providing some functional example code by way of example.
The .lan domain is managed by dnsmasq. It provides a simple way of accessing connected devices by [hostname].lan, including the router itself. By default on OpenWrt this is openwrt.lan. For LEDE this is lede.lan.
You can of course set your own router hostname in the /etc/config/system file.

**Comment by wrrr** [comment]
Got it. Thanks so much @bluewavenet  for the info will be interested if you keep digging in and sharing functional code, to get updates here.

Thanks
Stu

**Comment by bluewavenet** [comment]
@wrrr 
I have just merged Forward Authentication Service into master.
