### ISSUE TITLE
Support for ipset

### ISSUE THREAD

**Issue by vavrecan** [nodogsplash/nodogsplash#108]
I was wondering how difficult would it be to add support for ipset rules. 

Currently I am executing these two commands
iptables -I ndsNET -m set --match-set WHITELISTED_DOMAINS dst -j ACCEPT
iptables -t nat -I ndsOUT -m set --match-set WHITELISTED_DOMAINS dst -j ACCEPT

but I was hopping for some direct way over configuration for preauthorized users e.g.
FirewallRule allow tcp port 80 ipset WHITELISTED_DOMAINS
FirewallRule allow tcp port 443 ipset WHITELISTED_DOMAINS

What would you suggest - how to implement this? Also noting that "ipset create WHITELISTED_DOMAINS iphash" needs to be called before creating those rules - should be nodogsplash taking care of it?

**Comment by vavrecan** [comment]
here is what i came up with - https://github.com/vavrecan/nodogsplash/commit/7f8cc3f44fb845ff41f7008737bd97c40cf0e342

**Comment by mwarning** [comment]
has been merged - thanks
