### ISSUE TITLE
 0.9_beta9.9.9-5 not passing $clientmac or $gatewaymac to splash.html 

### ISSUE THREAD

**Issue by 3gem** [nodogsplash/nodogsplash#110]
Every variable except for $clientmac and $gatewaymac are being passed to splash.html.  It works in previous versions, but not the current version. Below is a sample of the HTML splash page output. It starts with the name of the variable separated by space(gatewayname:$gatewayname tok:$tok etc).

`gatewayname:nodog tok:b24a159f redir:http://www.google.com/ authaction:http://192.168.77.1:2050/nodogsplash_auth/ denyaction:http://192.168.77.1:2050/nodogsplash_deny/ authtarget:http://192.168.77.1:2050/nodogsplash_auth/?redir=http%3A%2F%2Fwww.google.com%2F&tok=b24a159f clientip:192.168.77.196 clientmac:$clientmac gatewaymac:$gatewaymac nclients:1 maxclients:15 uptime:0d 0h 52m 49s imagesdir:/images pagesdir:/pages`

**Comment by bluewavenet** [comment]
I have not seen $clientmac or $gatewaymac work on any version up to .9.9-1.
To get the client mac I use this php code:
list($mac, $clientmac) = explode("=", (exec("ndsctl clients | grep -A 1 ip=" . $_SERVER['REMOTE_ADDR'])));
Hope this helps.

**Comment by bluewavenet** [comment]
Here is one for $gatewaymac:
`list($mac, $gatewaymac) = explode("HWaddr", (exec("ifconfig wlan0 | grep -A 0 HWaddr")));
$gatewaymac = trim($gatewaymac);`

**Comment by 3gem** [comment]
Thanks I use that instead.

**Comment by mwarning** [comment]
$clientmac or $gatewaymac is available in the 1.0.0 release

**Comment by lenovadev01** [comment]
Hi' I've just tested the last release "nodogsplash_1.0.0-1_ar71xx.ipk" on OpenWrt and the $clientmac is always empty. Any idea why ?
