### ISSUE TITLE
Running  0.9_beta9.9.9-5 on OpenWrt Barrier Breaker final release.

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#111]
I am having to use Barrier Breaker for a project as OpenWrt Chaos Calmer for Ubiquiti AirRouter is broken - at least is is just now.
After installing 0.9_beta9.9.9-5 you will have to replace the installed init.d script with the version in 
0.9_beta9.9.8 as in the attached file here otherwise Nodogsplash fails to start up.
[nodogsplash.init.d.txt](https://github.com/nodogsplash/nodogsplash/files/175947/nodogsplash.init.d.txt)

Works perfectly after this. I have not had time to investigate what is causing the problem, but this fix works.

**Comment by bluewavenet** [comment]
OK - now looked into this. The 9.9.9-5 init.d script fails to start NDS as /etc/config/nodogsplsh has -
  option enabled 0. Changing to option enabled 1 should fix this.

**Comment by mwarning** [comment]
@bluewavenet is to set enabled to 1 the only issue here; in this case I would close the ticket. As this is the safe default (afaik, NDS will lock you out using the default options and enabled set to 1).

**Comment by bluewavenet** [comment]
I'm not sure. I had a working .conf needed for a rollout and made it work by reverting to the original inet.d script and have not had time to look back in more detail.
Do we need this? Is it an unnecessary complexity or does it have potential I have not had time to think about? It seems to be a recurring question - people install and it fails to start.
By the way - the current Openwrt release in Chaos calmer is rock solid on CC and BB. We have a hotel/restaurant/bar running with an average of over 300 NDS clients per day (on a PC Engines Alix 2d2 feeding into 9 access points).

**Comment by mwarning** [comment]
@bluewavenet please try the current release and check if it works for you

**Comment by bluewavenet** [comment]
I experimented with 0.9_beta9.9.9 as was using this on CC for a rollout. Changing the init.d script to include START=198 seemed to do the trick.
Problem is caused by the interface used by NDS not being UP when NDS starts. NDS then unloads.
START=198 makes init.d wait longer before starting NDS. 
I have not had time to investigate further.

**Comment by bluewavenet** [comment]
Works fine in V1 and V2
