### ISSUE TITLE
nodogsplash uses obsolete (PF_INET,SOCK_PACKET)

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#112]
Running on OpenWrt Chaos Calmer 15.05.1, all runs fine but the Kernel log reports:
"nodogsplash uses obsolete (PF_INET,SOCK_PACKET)"
Probably something for later releases...

**Comment by bluewavenet** [comment]
@lynxis 
Is this addressed in v1 or v2?

**Comment by lynxis** [comment]
I can not see this message in v2.
Neither can I find PF_INET or SOCK_PACKET in v1.
Closing the ticket now. It looks to me this is fixed. Please reopen if not.
