### ISSUE TITLE
create Social auth

### ISSUE THREAD

**Issue by 1xs** [nodogsplash/nodogsplash#114]
Hi there, this solution is really great for a lot of scenarios. But could there somehow be a way to use a social login to authenticate people? Or i.e. a checkin on facebook or some kind of other action? I think there must be a way to setup the splash page where it pulls data from an online page or something like that. does anyone has a solution for this?

**Comment by bluewavenet** [comment]
Your router has access to the internet at all times so you can use php to do these sort of things. You cannot use Javascript however as this runs on the client browser. The standard Facebook API uses a mix of php and js so cannot be used without some re-writing. It can and has been done.
