### ISSUE TITLE
cannot install nodogsplash 0.9_beta9.9.9-6

### ISSUE THREAD

**Issue by pavlosipress** [nodogsplash/nodogsplash#116]
I have a tp-link wr1043nd v3 and i have install the latest openwrt version ( r49166). When i install nodogsplash i get following error:

Installing nodogsplash (0.9_beta9.9.9-6) to root...
Downloading http://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/routing/nodogsplash_0.9_beta9.9.9-6_ar71xx.ipk.
Multiple packages (kmod-ipt-core and kmod-ipt-core) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for nodogsplash:
 * 	kernel (= 4.1.23-1-1931ec3417c43588aa602fdb67e7f807) * 
 * opkg_install_cmd: Cannot install package nodogsplash.

**Comment by bluewavenet** [comment]
If you try the latest RELEASE version of OpenWrt there should be no problem. I am using this with with both ar71xx and x86 hardware. The development snapshots of OpenWrt are using a later kernel as far as I know.
[https://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/](url)

**Comment by pavlosipress** [comment]
i had install the version r49166 but not the last. i found the latest version from openwrt website and i made sysupgrade. now everything is ok.
