### ISSUE TITLE
Unable to reference resources with query parameters.

### ISSUE THREAD

**Issue by TonyTromp** [nodogsplash/nodogsplash#12]
Hello,

It should be made possible to serve pages which have query paramters.
However it is permitted to serve custom (html) content from the /images folder, when adding queryparamters, nodogsplash return its main page.
This way its impossible to add/communicate through other resources or pass values between iframes.

Thanks,
Tony

**Comment by lynxis** [comment]
it works in v2.

**Comment by bluewavenet** [comment]
It actually works in all versions as long as you do not try to access anything on port 80.
Hosting custom pages is best done elsewhere eg on uhttpd where php support can be enabled.
