### ISSUE TITLE
release v2.0.0

### ISSUE THREAD

**Issue by lynxis** [nodogsplash/nodogsplash#120]
What's missing to release v2.0.0?

**Comment by bluewavenet** [comment]
I can't think of anything missing but there are some, hopefully minor, issues still.
#112 -  it keeps coming up in OpenWrt kernel logs. Will this go away along with libhttp?
#80 - would be nice but not essential.
Do you have a feel for the memory footprint of v2?

**Comment by lynxis** [comment]
on my list are #146  #147

**Comment by lynxis** [comment]
I think v2.0.0 is ready for release.
Any idea's what's left?

@mwarning  @bluewavenet

**Comment by bluewavenet** [comment]
Does it build on the openwrt cc sdk? I have not had time to try.

**Comment by lynxis** [comment]
i don't think so. because it's depending on a new libmicrohttpd version

**Comment by bluewavenet** [comment]
@lynxis Which version of libmicrohttpd and will that build on CC? LEDE? What OS/Hardware are you running v2 on? Sorry for the list of questions but with Opwnwrt looking dead and Lede looking like it has stalled/died, will we have lost the rich target hardware list we currently have?

**Comment by mwarning** [comment]
@bluewavenet lede has not stalled, the release is scheduled for this week.

**Comment by mwarning** [comment]
@lynxis looks ok to me. But I haven't tested it yet.

**Comment by bluewavenet** [comment]
@mwarning Good news re lede. I have not seen anything new for over six months and was beginning to think...

**Comment by bluewavenet** [comment]
Testing Lede 17.01.0-rc2 on an Alix 2d(x86) and looks stable. Will try with the bundled NDS v1 next.

**Comment by bluewavenet** [comment]
Does anyone have a feel for the memory (RAM) footprint of V2? 
LEDE seems to use much more RAM and Flash than the equivalent in OpenWrt CC and can be a struggle with small RAM devices in particular (eg Ubiquiti airGateway etc).
