### ISSUE TITLE
ClientIdleTimeout does not deauthenticate clients in PREAUTHENTICATED state

### ISSUE THREAD

**Issue by ansanto** [nodogsplash/nodogsplash#122]
ClientIdleTimeout does not deauthenticate clients in PREAUTHENTICATED state. This is a problem when using EnablePreAuth feature since such clients are summed to AUTHENTICATED clients and so the MaxClients threshold could be quickly triggered. 
Proposed patch:

--- a/firewall.c    2016-07-13 12:22:14.000000000 +0200
+++ b/firewall.c    2016-07-13 12:15:59.000000000 +0200
@@ -184,7 +184,7 @@
                debug(LOG_NOTICE, "%s %s inactive %d secs. kB in: %llu  kB out: %llu",
                      cp1->ip, cp1->mac, config->checkinterval \* config->clienttimeout,
                      cp1->counters.incoming/1000, cp1->counters.outgoing/1000);
-               if(cp1->fw_connection_state == FW_MARK_AUTHENTICATED) {
-               if(cp1->fw_connection_state == FW_MARK_AUTHENTICATED || cp1->fw_connection_state == FW_MARK_PREAUTHENTICATED) {
                  iptables_fw_access(AUTH_MAKE_DEAUTHENTICATED, cp1);
              }
              client_list_delete(cp1);

**Comment by lynxis** [comment]
* v2: I would like to investigate this as soon #144 is merged and some documentation is added from the PR.
* v1: @mwarning do you want try to test this?

**Comment by mwarning** [comment]
@lynxis: I do not have much motivation/time for this right now. Maybe I can give it a spin next week. No promises. :-D

**Comment by bluewavenet** [comment]
This is very old now and as Binvoucher has not been implemented in v2 ( #144 ) and there is little interest or effort available to do this, it is sensible to close this now and reopen later if required.
