### ISSUE TITLE
Active duration exhibits big big values in ndsct status

### ISSUE THREAD

**Issue by ansanto** [nodogsplash/nodogsplash#123]
since format_time() in util.c is used to compute the duration, and duration is negative (now - added_time), in my opinion the argument should be defined as %d and not as %ul
 
char * format_time(unsigned long int secs)
should be:
char * format_time(signed long int secs)

**Comment by ansanto** [comment]
...or better
		durationsecs = now - client->added_time;
		durationsecs = client->added_time - now;

**Comment by mwarning** [comment]
fixed already (in the next release)
