### ISSUE TITLE
Password authentication isn't working, can't forward https to splash page.

### ISSUE THREAD

**Issue by autocar23** [nodogsplash/nodogsplash#126]
Here is what i have done:
1. reset to factory setting
2. run opkg update
3. run opkg install /tmp/nodogsplash*.ipk
4. change /etc/config/nodogsplash line 4 to 'option enabled 1'
5. run /etc/init.d/nodogsplash start
6. reboot the router
After that, every thing works fine, but several issues comes up:

1. After turn on password authentication by editing nodogsplash.conf then insert the HTML form into splash.html then run /etc/init.d/nodogsplash reload then reboot the router. 
No matter what i type at the authentication form then enter, i always get authenticated.

2. When i am unauthenticated, i can be forwarded to the splash page by visiting a http page. but if what i click is a https link like https://github.com, i am unable to be forwarded to the splash page, and get an ERR_CONNECTION_TIMED_OUT.

I am using openwrt-15.05.1-ar71xx-generic-wndr3800-squashfs-factory and 
nodogsplash_1.0.0-1_ar71xx.ipk.
Here is my conf file:
```
root@OpenWrt:/# cat /etc/nodogsplash/nodogsplash.conf
PasswordAuthentication 1
UsernameAuthentication 1

Password 123
Username 123
PasswordAttempts 5
```
```
root@OpenWrt:/# cat /etc/config/nodogsplash

config nodogsplash
  # Set to 1 to enable nodogsplash
  option enabled 1

  # Use plain configuration file
  #option config '/etc/nodogsplash/nodogsplash.conf'

  # The network the users are connected to
  option network 'lan'
  option gatewayname 'OpenWrt Nodogsplash'
  option maxclients '250'
  option idletimeout '1200'

  # Your router may have several interfaces, and you
  # probably want to keep them private from the network/gatewayinterface.
  # If so, you should block the entire subnets on those interfaces, e.g.:
  list authenticated_users 'block to 192.168.0.0/16'
  list authenticated_users 'block to 10.0.0.0/8'

  # Typical ports you will probably want to open up.
  list authenticated_users 'allow tcp port 22'
  list authenticated_users 'allow tcp port 53'
  list authenticated_users 'allow udp port 53'
  list authenticated_users 'allow tcp port 80'
  list authenticated_users 'allow tcp port 443'

  # For preauthenticated users to resolve IP addresses in their
  # initial request not using the router itself as a DNS server,
  list preauthenticated_users 'allow tcp port 53'
  list preauthenticated_users 'allow udp port 53'

  # Allow ports for SSH/Telnet/DNS/DHCP/HTTP/HTTPS
  list users_to_router 'allow tcp port 22'
  list users_to_router 'allow tcp port 23'
  list users_to_router 'allow tcp port 53'
  list users_to_router 'allow udp port 53'
  list users_to_router 'allow udp port 67'
  list users_to_router 'allow tcp port 80'
  list users_to_router 'allow tcp port 443'

  # See https://github.com/nodogsplash for a full list of available options.
```
```
root@OpenWrt:/# cat /etc/nodogsplash/htdocs/splash.html
<html>
<head>
        <title>$gatewayname Entry</title>
        <meta HTTP-EQUIV="Pragma" CONTENT="no-cache">
</head>
<body bgcolor="#DDDDDD" text="#000000">
  <form method='GET' action='$authaction'>
  <input type='hidden' name='tok' value='$tok'>
  <input type='hidden' name='redir' value='$redir'>
  username: <input type='text' name='nodoguser' value='' size='12' maxlength='12'>
  <br>
  password: <input type='password' name='nodogpass' value='' size='12' maxlength='10'>
  <br>
  <input type='submit' value='Enter'>
  </form>

<table border="0" cellpadding="2" cellspacing="0" width="100%">
<tr>
        <td align="center"><h2>$gatewayname</h2></td>
</tr>
<tr>
        <td align="center" height="120">
        <a href="$authtarget">
        <img src="$imagesdir/splash.jpg" width="71" height="49" border="0"
                alt="Click to enter" title="Click to enter">
        </a>
        </td>
</tr>
</table>

</body>
</html>
```

sorry for the poor english, hope you understand.

**Comment by bluewavenet** [comment]
Nodogsplash only redirects http requests to the splash page, everything else is blocked by default.
This is actually NOT an issue as almost 100% of clients accessing Hotspots will be using smart phones or tablets and those devices have a "portal detection" function that uses an http request.

Also running the script /etc/init.d/nodogsplash will reset your /etc/nodogsplash/nodogsplash.conf so in actual fact you will be running with username and password authentication disabled which means your form will just let you in regardless of what is entered.

**Comment by autocar23** [comment]
Thanks for the help. so how do i turn on the password authentication ?

**Comment by bluewavenet** [comment]
Try replacing /etc/init.d/nodogsplash with the contents of the nodogsplash.init.d.txt I have attached here. Then replace /etc/nodogsplash/nodogsplash.conf with the contents of nodogsplash.conf.simple.txt attached here. Run /etc/init.d/nodogsplash/enable then reboot. Then check that nodogsplash is running by typing ndsctl. If not then type /etc/init.d/nodogsplash start.
Now try connecting a client to check if it is all working. If it is then edit nodogsplash.conf to enable username/password authentication and see if it works then.

[nodogsplash.conf.simple.txt](https://github.com/nodogsplash/nodogsplash/files/381046/nodogsplash.conf.simple.txt)
[nodogsplash.init.d.txt](https://github.com/nodogsplash/nodogsplash/files/381047/nodogsplash.init.d.txt)

**Comment by mwarning** [comment]
On 07/25/2016 10:43 AM, bluewavenet wrote:
> Try replacing /etc/init.d/nodogsplash with the contents of the nodogsplash.init.d.txt I have attached here. Then replace /etc/nodogsplash/nodogsplash.conf with the contents of nodogsplash.conf.simple.txt attached here. Run /etc/init.d/nodogsplash/enable then reboot. Then check that nodogsplash is running by typing ndsctl. If not then type /etc/init.d/nodogsplash start.
> Now try connecting a client to check if it is all working. If it is then edit nodogsplash.conf to enable username/password authentication and see if it works then.
> 
> [nodogsplash.conf.simple.txt](https://github.com/nodogsplash/nodogsplash/files/381046/nodogsplash.conf.simple.txt)
> [nodogsplash.init.d.txt](https://github.com/nodogsplash/nodogsplash/files/381047/nodogsplash.init.d.txt)
> 
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nodogsplash/nodogsplash/issues/126#issuecomment-234890170
> 

I think he meant
/etc/init.d/nodogsplash enable

**Comment by bluewavenet** [comment]
Indeed I did.
/etc/init.d/nodogsplash enable

**Comment by autocar23** [comment]
Thank you guys, i have turn on the password authentication.

**Comment by tbeiei** [comment]
@autocar23 u can working username and password ?
