### ISSUE TITLE
Persisting trusted/allowed MAC's

### ISSUE THREAD

**Issue by glomotion** [nodogsplash/nodogsplash#127]
Hey there!

So i'm having some problems trying to configure my nodogsplash instance, and was hoping for just a tiny bit of guidance. (Apologies if i'm asking this in the wrong place).

Could someone help me understand how to setup the /etc/config/nodogsplash file such that on-startup it adds certain MAC addresses to the trusted or allowed MACLists?

The documentation only seems to cover the old style of config where you use: /etc/nodogsplash/nodogsplash.conf (I have tried making this conf file and pointing to it using "option config '/etc/nodogsplash/nodogsplash.conf'", but get missing file errors when nodogsplash tries to startup - seems to be this issue: https://forum.openwrt.org/viewtopic.php?id=58652).

After looking through /etc/init.d/nodogsplash - I can see where you loop through /etc/config/nodogsplash and pull out options:

```
echo "GatewayInterface $ifname" >> $CONFIGFILE

  append_config_option "$CONFIGFILE" "$cfg" gatewayname
  append_config_option "$CONFIGFILE" "$cfg" gatewayaddress
  append_config_option "$CONFIGFILE" "$cfg" gatewayport
  append_config_option "$CONFIGFILE" "$cfg" maxclients
  append_config_option "$CONFIGFILE" "$cfg" webroot
  append_config_option "$CONFIGFILE" "$cfg" debuglevel
  append_config_option "$CONFIGFILE" "$cfg" splashpage
  append_config_option "$CONFIGFILE" "$cfg" pagesdir
  append_config_option "$CONFIGFILE" "$cfg" checkinterval
  append_config_option "$CONFIGFILE" "$cfg" syslogfacility
  append_config_option "$CONFIGFILE" "$cfg" gatewayiprange
  append_config_option "$CONFIGFILE" "$cfg" imagedir
  append_config_option "$CONFIGFILE" "$cfg" redirecturl
  append_config_option "$CONFIGFILE" "$cfg" clientidletimeout
  append_config_option "$CONFIGFILE" "$cfg" clientforcetimeout
  append_config_option "$CONFIGFILE" "$cfg" gatewayiprange
  append_config_option "$CONFIGFILE" "$cfg" passwordattempts
  append_config_option "$CONFIGFILE" "$cfg" macmechanism
  append_config_option "$CONFIGFILE" "$cfg" uploadlimit
  append_config_option "$CONFIGFILE" "$cfg" downloadlimit
  append_config_option "$CONFIGFILE" "$cfg" remoteauthenticatoraction
  append_config_option "$CONFIGFILE" "$cfg" enablepreauth
  append_config_option "$CONFIGFILE" "$cfg" binvoucher
  append_config_option "$CONFIGFILE" "$cfg" forcevoucher
  append_config_option "$CONFIGFILE" "$cfg" passwordauthentication
  append_config_option "$CONFIGFILE" "$cfg" usernameauthentication
  append_config_option "$CONFIGFILE" "$cfg" passwordattempts
  append_config_option "$CONFIGFILE" "$cfg" username
  append_config_option "$CONFIGFILE" "$cfg" password
  append_config_option "$CONFIGFILE" "$cfg" authenticateimmediately
  append_config_option "$CONFIGFILE" "$cfg" decongesthttpdthreads
  append_config_option "$CONFIGFILE" "$cfg" httpdthreadthreshold
  append_config_option "$CONFIGFILE" "$cfg" httpdthreaddelayms
  append_config_option "$CONFIGFILE" "$cfg" fw_mark_authenticated
  append_config_option "$CONFIGFILE" "$cfg" fw_mark_trusted
  append_config_option "$CONFIGFILE" "$cfg" fw_mark_blocked
```

Only, there seems to be nothing here that allows one to specify Trusted MAClists or any other maclist for that matter. (also, just by the by, 'gatewayiprange' is listed twice). 

Also, adding the line (under config instance): 
   option macmechanism 'allow'
to /etc/config/nodogsplash seems to cause nodogsplash's startup to silently fail. 

I've figured out how to use ndsctl to add trusted mac's on-the-fly - but was hoping I might be able to avoid having to do this every time i start up nodogsplash.
 
Can anyone help me? Thanks in advance

**Comment by glomotion** [comment]
I've made a temporary solution which does what I need to by creating a small script to initiate the nodogsplash startup:

`#!/bin/bash
function addmacs () { 
 #user-1:
 /usr/bin/ndsctl trust xx:xx:xx:xx:xx:xx:xx
 #user-2:
 /usr/bin/ndsctl trust xx:xx:xx:xx:xx:xx:xx
}

/etc/init.d/nodogsplash start
sleep 2
addmacs`

This solution feels a little hacky though. :)

**Comment by bluewavenet** [comment]
When the UCI configuration first appeared in a new version of Nodogsplash, I could not get it to work and was in a rush so went back to the "old" way of configuring it thinking I would revisit it later, but so far have not done so.
A bit less of a hack is to change the init.d script back like I did and edit the .conf file. I answered issue #126 by attaching "old " style files to get started. Only problem with this is, depending on hardware, Nodogsplash can start before the network interfaces have come up so worst case you may have to add a sleep for a few seconds in the init.d script.

**Comment by mwarning** [comment]
Hi Tim,

see function setup_mac_lists() in /etc/init.d/nodogsplash. [0]

Adding the following additional lines to /etc/config/nodogsplash should work:

  # 'allow' (uses allowedmac list) or 'block' (uses blockedmac list)
  option macmechanism 'allow'

  #list of mac addresses to be allowed to access the splash page.
  list allowedmac '00:00:C0:01:D0:0D'
  list allowedmac '00:00:C0:01:D0:1D'

  # mac addresses of pre-authenticated users. This option does not depend on option macmechanism.
  list trustedmac '00:00:C0:01:D0:1D'


I will add some example lines to /etc/conf/nodogsplash if it works for you. Please let us know.

The option names from nodogsplash.conf [1]  as similar as the nodogplash.conf file as possible.
But in truth, it is not trivial and change afterwards is messy.

I hope it helps,
mwarning

[0] https://github.com/openwrt-routing/packages/blob/master/nodogsplash/files/nodogsplash.init#L63
[1] https://github.com/nodogsplash/nodogsplash/blob/master/resources/nodogsplash.conf

**Comment by glomotion** [comment]
Moritz Thank you!!! Those list lines were exactly what I was looking for. :)

**Comment by mwarning** [comment]
I suppose it works for you then?

**Comment by glomotion** [comment]
Sure does! Thanks again. :)
