### ISSUE TITLE
how to change call splash.html

### ISSUE THREAD

**Issue by nhimcoi30889** [nodogsplash/nodogsplash#129]
Hi @mwarning @lynxis @bluewavenet,
I can change to call from splash.html to other file ?
For example, i customize a php file and i want to replace splash.html

**Comment by bluewavenet** [comment]
Just use a meta refresh, passing all the parameters to the target for eventual return to Nodog. You have to set up access to the target (as an IP address) in nodogsplash.conf of course, otherwise you will end up in a loop.

**Comment by nhimcoi30889** [comment]
Ok tks Blue,
i used a meta tag for this problem

**Comment by mwarning** [comment]
Please use the mailing list for question: nodogsplash@ml.ninux.org
Not the Bug-Tracker..
