### ISSUE TITLE
Is there any way to set IP whitelist and blacklist ?

### ISSUE THREAD

**Issue by chengdanhao** [nodogsplash/nodogsplash#130]
Users can visit the IP in whitelist freely. If users visit the IP in the blacklist, the browser will jump to the router LuCI login page or the webserver in the subnet.

**Comment by mwarning** [comment]
Maybe look here https://github.com/nodogsplash/nodogsplash/blob/master/resources/nodogsplash.conf#L229

Better ask on the mailinglist first: nodogsplash@ml.ninux.org

**Comment by chengdanhao** [comment]
I tried to send a e-mail to you, but received the reject message below:

You are not allowed to post to this mailing list, and your message has
been automatically rejected.  If you think that your messages are
being rejected in error, contact the mailing list owner at
nodogsplash-owner@ml.ninux.org.

**Comment by chengdanhao** [comment]
Thanks for your reply.

I want to block IP address, not MAC address. I read the source code, and found that NodogSplash didn't support this feature.

I realize it with iptables command finally.
