### ISSUE TITLE
Getting traffic control in Chaos Calmer to work with wshaper...

### ISSUE THREAD

**Issue by glomotion** [nodogsplash/nodogsplash#131]
So we're now trying to get traffic control working within Nodog - still using the latest build of OpenWRT (CHAOS CALMER (15.05.1, r48532)) - and getting a little lost.

We've added the lines to /etc/config/nodogsplash:
```
list trafficcontrol 1
list downloadlimit 100
```

And also installed 'wshaper'. It's current config (taken from /etc/config/wshaper) is:
```
config 'wshaper' 'settings'
	option 'network' 'wan'
	option 'downlink' '2000'
	option 'uplink' '240'
```

We're just a little unsure how to tell nodogsplash to use wshaper, instead of imq (which apparently no longer comes with OpenWRT after Attitude Adjustment).  
When booting up using the current nodogsplash config (including the trafficconrol lines mentioned above) nodogsplash errors out on-startup:
```
 Testing required modules
  Testing module ipt_mac 
   ipt_mac is working
  Testing module ipt_mark 
   ipt_mark is working
  Testing module imq numdevs=2
   Module imq numdevs=2 needed
   Scanning disk for imq module
   imq module missing: please install it
```

https://wiki.openwrt.org/doc/howto/wireless.hotspot.nodogsplash mentions some other packages which used to be needed:
```
opkg install iptables-mod-imq
opkg install kmod-ipt-imq
opkg install kmod-sched
```

as well as:
```
opkg install ip
opkg install tc
```

Are any of these still needed to use nodog with traffic control inside Chaos Calmer? Have any of them also changed? 

Again, huge thanks in advance for any help you guys can offer. :) *nodog rocks!*

**Comment by mwarning** [comment]
The dependencies are about right. But I haven't had my hands in there.

I doubt that NDS traffic shaping works on chaos calmer anymore. imq is not supported anymore by the Kernel.

There is some ticket that explains that better. I might be easier to fix that in NDS.
It is probably one code or two that need to be fixed to work with something different that imq.

Anyway, please use the mailing list for questions - not the ticket system.. :]

**Comment by bluewavenet** [comment]
I have had great success using SQM as in the standard release of OpenWrt. It works at a connection level and does not require any NoDogSplash configuration. True that you cannot define individual upload/download rates per user but for most applications dramatically improves overall performance per user on a busy Internet feed.
Certainly worth trying.
[https://wiki.openwrt.org/doc/howto/sqm](url)

**Comment by nicopace** [comment]
@bluewavenet can you share your findings on using SQM with NoDogSplash? I'm starting to work on the same thing and it would be great not to do things twice! :D

**Comment by bluewavenet** [comment]
@nicopace 
I have this running on OpenWrt CC in production on numerous large sites and in development on LEDE Reboot 17xx, and find it very effective.
You cannot define individual rates for clients but this is not necessary for the types of Public Hotspot I am involved with. The "Fair Queueing" works on a connection basis and if you reverse the "standard" configuration and have it running on the LAN side of the router it will queue manage on a connection basis from clients to the router. I add a fairly high traffic control rate as per the instructions. The overall effect is to limit each client to that TC limit on average. I have found the fq_codel qdisc the best so far.
A typical busy hotel with some 200 active clients was grinding to a halt without it with lots of photos being shared, browsing, emails, chats, voip and video calls etc. With it running it is all smooth, quick and usable, voip calls clean and unbroken, video calls pretty good and no big latency on browsing. An amazing difference. We also often run mwan3 to load balance two vdsl links as well and it all works well together. 
Here is a typical /etc/config/sqm uci file extract.  Note "upload" is from router to client and "download" is from client to router. A reverse of the standard default type of config. Note also the interface binding to br-lan.
	option qdisc 'fq_codel'
	option script 'simple.qos'
	option qdisc_advanced '0'
	option interface 'br-lan'
	option debug_logging '0'
	option verbosity '5'
	option linklayer 'ethernet'
	option overhead '8'
	option upload '25000'
	option download '10000'
	option enabled '1'

**Comment by nicopace** [comment]
Oh... I know about SQM and BufferBloat... I've been looking at that myself... but for the usecase I want to accomplish (And the general feature that was being provided by NoDogSplash) this solution does not solve this ticket :(
the implementaiton I feel it should be done using https://wiki.linuxfoundation.org/networking/ifb

**Comment by bluewavenet** [comment]
@nicopace , you should do what I did and review what the actual requirement is. For me it was to stop one or two clients being able to saturate the Internet connection by uploading/downloading massive amounts of data - streaming in a hotel room for example. I was convinced I had to limit each client to a pre-set value for each client. It turned out I needed something else!

**Comment by nicopace** [comment]
For us the Use Case is for a Community to be able to allow getting to the Internet to those that have payed the monthly contribution.

**Comment by bluewavenet** [comment]
Can they get to the Internet without a contribution?

**Comment by nicopace** [comment]
The idea is for the community to be able to decide that.
We are building a software that talks to NoDogSplash (other captive portals will be supported in the near future) that allows the communities to manage a voucher system with a certain validity date. If that date exceeds, two things can happen: the user is not allowed to get to the internet, or it gets a lower speed.
There might be also a 'visitor' voucher that allows to use the connection at a lower speed.
https://github.com/libremesh/voucher

**Comment by bluewavenet** [comment]
An all or nothing type of system is easy to implement but requiring the two levels of connectivity is more complex. Our splash page forces clients to create an account to log in. Requiring payment is easy. Requiring variable client based connection speed does of course require something like ifb.
I believe incorporating this into NDS version 2 is being worked on.

**Comment by nicopace** [comment]
And how would you do all or nothing using NDS?
Will look into NDSv2 code then... thanks!

**Comment by bluewavenet** [comment]
See Pull Request 155:
 Update to use IFB, HFSC and FQ_CODEL #155

**Comment by nicopace** [comment]
Excelent! will definitely try it out!

**Comment by bluewavenet** [comment]
All - Create account and pay then be allowed to log in
Nothing - Create account and not pay  - access denied
Of course you need your own code to do this, NDS is just the gatekeeper.

**Comment by nicopace** [comment]
oh... duh! you are right... i replied without thinking!

**Comment by ashbenz** [comment]
@bluewavenet 
Was checking out SQM setups and came across this discussion.

I'm curious, isn't it typical to have SQM instance on the wan interface? (in your case, two instances, one for each of your WANs).
Why did you setup yours on the LAN? (sorry if this is obvious, I'm not familiar with NDS and was just wondering about the rationale).

Have you experimented with other qdiscs, cake: layer_cake,etc..
Thanks

**Comment by bluewavenet** [comment]
@ashbenz 
First, we use mwan3 to load balance on a connection by connection basis as well as providing resilience in the case of a line failure and SQM seems to be incompatible with this as more than one client could be connected to a server with mwan3 choosing either wan interface thus confusing sqm.
Second, we found by experimentation that SQM works well on the lan interface. It seems to manage its queues between the router interface and the target. Running on the lan interface means it manges queues for targets that are individual connections to clients. Running on the wan interface would mean it would manage its queues for targets that are connections to servers out on the Internet.

**Comment by ashbenz** [comment]
@bluewavenet 
Interesting :) Thanks for the explanation.
I guess the behavior differs greatly depending upon your choice of qdisc (in your particular use case).
Looking at your download and upload numbers above, can you tell me what your vdsl speeds are like for both lines?

**Comment by mwarning** [comment]
Since libremesh is mentioned here: https://github.com/nodogsplash/nodogsplash/issues/320
