### ISSUE TITLE
Authentication problem vers. 1.0.0

### ISSUE THREAD

**Issue by claud43** [nodogsplash/nodogsplash#133]
Today, I installed version 1.0.0 but still presents the problem user and password authentication. I corrected that had been posted in this forum.

file: /etc/init.d/nodogsplash

config_get val "$cfg" username
  if [ -n "$val" ] ; then
    echo "UsernameAuthentication 1" >> $CONFIGFILE
    echo "Username $val" >> $CONFIGFILE
  fi

  config_get val "$cfg" password
  if [ -n "$val" ] ; then
    echo "PasswordAuthentication 1" >> $CONFIGFILE
    echo "Password $val" >> $CONFIGFILE
  fi
}

**Comment by claud43** [comment]
# auto-generated config file from /etc/config/nodogsplash
GatewayInterface wlan0-2
gatewayname OpenWrt Nodogsplash
maxclients 250
passwordauthentication yes
usernameauthentication yes
username ninux
password ninux
UsernameAuthentication 1
Username ninux
PasswordAuthentication 1
Password ninux
FirewallRuleSet authenticated-users {
    FirewallRule allow tcp port 22
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 53
    FirewallRule allow tcp port 80
    FirewallRule allow tcp port 443
}
FirewallRuleSet preauthenticated-users {
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 53
}
FirewallRuleSet users-to-router {
    FirewallRule allow tcp port 22
    FirewallRule allow tcp port 23
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 53
    FirewallRule allow udp port 67
    FirewallRule allow tcp port 80
    FirewallRule allow tcp port 443
}
FirewallRuleSet trusted-users {
}
FirewallRuleSet trusted-users-to-router {
}

**Comment by mwarning** [comment]
The issue should have been fixed here https://github.com/openwrt-routing/packages/blob/master/nodogsplash/files/nodogsplash.init
That file will be used when you use OpenWrt trunk.

The "nodogsplash -v" should report version 1.0.1 by now.
