### ISSUE TITLE
How to change session timeout to some device?

### ISSUE THREAD

**Issue by gazambuja** [nodogsplash/nodogsplash#136]
I want to autenticate some device with a custom session timeout... for example:

> ndsctl auth xx:xx:xx:xx:xx:xx # auth for default ClientForceTimeout time.
> ndsctl auth xx:xx:xx:xx:xx:xx 600 # auth for 10 minutes.

I suppose can use some thing related to EnablePreAuth to simulate this. Any idea where can I start?

**Comment by gazambuja** [comment]
Ok, I make some progress but not work... the nodogsplash crash when I run this command...
can you help?

I attach two patchs to create the function ndsctl timeout, the idea is you use like:
> ndsctl timeout xx:xx:xx:xx:xx:xx 600
then, nds add 600 seconds to timeout session of user.




[timeout.zip](https://github.com/nodogsplash/nodogsplash/files/481178/timeout.zip)

**Comment by mwarning** [comment]
I do not see anything outright wrong about your patch. But I do not have time to have a proper look at the code. I can give it a look in the next view days.

**Comment by bluewavenet** [comment]
Could be useful. The idea is here if someone needs it.
