### ISSUE TITLE
open access by domain name

### ISSUE THREAD

**Issue by ArtMartin89** [nodogsplash/nodogsplash#137]
I need to open some domains by name because of it's often ip changing.(for example api.twitter.com, accounts.google.com & etc)
In openWRT wiki there's an example how to Restrict access https://wiki.openwrt.org/doc/howto/wireless.hotspot.nodogsplash#restrict_access_to_domains

I'm totally not good with coding, but and as far as I understand if we change this line
`iptables -t nat -I ndsOUT -p tcp -s 10.20.30.0/24 -d $ip --dport 80 -j DNAT --to 10.20.30.1:80`
to the rule which will open the access to $ip it'll work

So the question is how to change it for not restricting but for allowing access?

**Comment by gazambuja** [comment]
In my experience, the best you can do, is have some script, resolve domains in your list, get the IP and add this lines to /etc/hosts and allow in iptables.
