### ISSUE TITLE
BinVoucher script is not being called

### ISSUE THREAD

**Issue by diegohdk** [nodogsplash/nodogsplash#139]
I have the following config:

```
BinVoucher /my/script/auth
ForceVoucher yes
EnablePreAuth yes
```

When a client is registered, it goes directly to the splash page. The script is not even called.

My script has executable permission. I can call it manually from the shell.

Am I missing something?

**Comment by lynxis** [comment]
@diegohdk which version of nodogsplash do you use?

**Comment by rosbergrodrigues** [comment]
I have the same problem, my version is 0.9-beta, can you help me?

**Comment by diegohdk** [comment]
Sorry for the late response. I'm now using nodogsplash anymore. I managed to build my own captive portal solution for the project I'm working on, 'cause I was in a hurry and couldn't wait.

Anyway, I was using the lastest version. I think it was 0.9.

Great project, keep improving it!
