### ISSUE TITLE
test_sch_htb () fails in openwrt trunk

### ISSUE THREAD

**Issue by hero18688** [nodogsplash/nodogsplash#14]
I am using openwrt trunk at kernel 3.10

root@OpenWrt /root [#] /etc/init.d/nodogsplash start
Starting nodogsplash ... 
 Testing required modules
  Testing module ipt_mac 
   ipt_mac is working
  Testing module ipt_mark 
   ipt_mark is working
  Testing module imq numdevs=2
   imq is working
  Testing module ipt_IMQ 
   ipt_IMQ is working
  Testing module sch_htb 
   Module sch_htb  needed
   Scanning disk for sch_htb module
   sch_htb exists, trying to load
   Error: insmod sch_htb  failed

 ### Test sch_htb with tc; requires imq0
    test_sch_htb () {
        (tc qdisc del dev imq0 root 2>&1) > /dev/null
        (tc qdisc add dev imq0 root htb 2>&1) > /dev/null
        TC_OK=$?
        if [ "$TC_OK" -eq 0 ]; then
            (tc qdisc del dev imq0 root 2>&1) > /dev/null
            return 0
        else
            return 1
        fi
    }
It return 2 to TC_OK

tc qdisc add dev imq0 root htb
RTNETLINK answers: Invalid argument

**Comment by mwarning** [comment]
See https://github.com/nodogsplash/nodogsplash/issues/74

**Comment by lynxis** [comment]
This issue is duplicated and resolved, because nobody migrate the tc.c code to the new traffic control code of linux.
