### ISSUE TITLE
Issue redirect to facebook on IOS

### ISSUE THREAD

**Issue by nhimcoi30889** [nodogsplash/nodogsplash#143]
Hi @bluewavenet, @lynxis, @mwarning ,
I have a problem of nodogsplash with redirect to facebook on IOS
After press authent button on landing page, facebook app on IOS (iphone, ipad) will popup about 2 seconds and lost. Continue pop-up browser and redirect through to google.com
When i try on android or windows , it working normal ( redirect to facebook and hold app)

**Comment by bluewavenet** [comment]
This is a function of the implementation of the Captive Portal Detection (CPD) on the device. There are many implementations from each vendor and each version of the operating system on the device. 
Later versions of CPD are now beginning to automatically close the browser used for authentication. This is in fact much more useful in a typical public hotspot environment, ie, not leaving stray browser windows open to confuse the user. 
If you want users of your hotspot to be redirected to Facebook, you really need to force the FB app on the device to open if it exists. To do this you will need your own post authentication redirect page with in turn a redirect to the FB app. You an use uhttp on OpenWrt to host this and an example of the code required to do it is here:
http://stackoverflow.com/questions/13675535/how-to-launch-apps-facebook-twitter-etc-from-mobile-browser-but-fall-back-to-h
