### ISSUE TITLE
Failed to trust/allow/block MAC

### ISSUE THREAD

**Issue by chengdanhao** [nodogsplash/nodogsplash#148]
nodogsplash runs on OpenWrt 14.04, I tried to let a MAC visit Internet freely. I type the following command, all of them are failed.
```
root@rtl819xd:/# ndsctl trust 6a:4d:ac:26:b1:bc
Failed to trust MAC 6a:4d:ac:26:b1:bc.
root@rtl819xd:/# ndsctl allow 6a:4d:ac:26:b1:bc     
Failed to allow MAC 6a:4d:ac:26:b1:bc.
root@rtl819xd:/# ndsctl block 6a:4d:ac:26:b1:bc     
Failed to block MAC 6a:4d:ac:26:b1:bc.
```
Anyone knows why did this happend?

**Comment by bluewavenet** [comment]
Are you using the version of Nodogsplash distributed with Barrier Breaker?
You can try 0.9_beta9.9.9 as distributed with Chaos Calmer - works fine on that.

**Comment by mwarning** [comment]
@chengdanhao the MAC address might already have been added.
Try "ndsctl status" and check for the "Allowed MAC addresses:" section.

**Comment by chengdanhao** [comment]
@mwarning 
as you said, I type the command and check "ndsctl status" output, the section is still empty.
```
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
```
ndsctl auth/deauth works well.

@bluewavenet 
Yes, I use "./scripts/feeds install nodogsplash" to get nodogsplash package.

I think I need to read the source code and find the reason by myself. Thank you.

**Comment by bluewavenet** [comment]
Which version are you using? ndsctl status will tell you.

**Comment by mwarning** [comment]
I assume this is some usage problem.
@chengdanhao open a new ticket if you find any buggy/bad behavior by nds.
