### ISSUE TITLE
Mobile and Client Friendly infoskel.html

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#149]
Often, a client will connect to NDS but not authenticate for a while. When they do, very often the token will have timed out and they are served up infoskel.html. 
This is neither mobile or client friendly and leaves them in limbo.
Here is a new version with a button for them to continue. Tested on Apple, Windows, Android and various desktops/laptops.
[infoskel.html.txt](https://github.com/nodogsplash/nodogsplash/files/594673/infoskel.html.txt)

**Comment by mwarning** [comment]
Please make a merge request.
It might be good to keep your change very simple. This is an example file and it is not meant for production.

**Comment by bluewavenet** [comment]
Merge request done :)
