### ISSUE TITLE
nodogsplash for per-user authentication

### ISSUE THREAD

**Issue by sgaseretto** [nodogsplash/nodogsplash#153]
Is there a known way to tweak nodog to allow per-user authentication?

**Comment by mwarning** [comment]
You can use the BinVoucher feature: https://github.com/nodogsplash/nodogsplash/blob/v1/resources/nodogsplash.conf#L365

It is available in NDS 1.x

**Comment by sgaseretto** [comment]
Sorry, I wasn't very specific, I want to authenticate the user with his own user and password

**Comment by sgaseretto** [comment]
Sorry, I wasn't very specific, I want to use a Radius server and make register each user with an username and password

**Comment by mwarning** [comment]
I do not think this is possible. I think the WifiDog project supports Radius Servers.
For NDS, you can only specify user names and passwords in the nodogsplash.conf file.

**Comment by bluewavenet** [comment]
@sgaseretto @mwarning Actually it is quite easy.
First create an Authentication web page as a front end for your radius server (or whatever you need for user handling). Then modify splash.html to do a meta redirect to your web page, passing $authaction, $tok, $redir via get or post.
When authenticated in your radius, pass all the variables back to NDS at $authaction.
If authentication fails, do nothing.
Finally, to make it work, add the IP address of your Authentication page to the NDS config:
For example
FirewallRuleSet preauthenticated-users {
FirewallRule allow tcp port 443 to 123.23.2.1}

**Comment by mwarning** [comment]
@bluewavenet you should write a howto section for the docs :-)

**Comment by bluewavenet** [comment]
@mwarning 
Me and my big mouth ;)
I might make time to do something later after current project is done.

**Comment by mwarning** [comment]
xD

no problem. Let us know. I can give you access if that comes handy for you.
