### ISSUE TITLE
Master fails to build in Openwrt SDK

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#157]
I've just been trying to build master in the OpenWrt SDK and it is failing with missing microhttpd.c and microhttpd.h
Am I missing a step or are these files genuinely missing? Has anyone else succeeded in building this?
@mwarning @lynxis

**Comment by mwarning** [comment]
The master branch contains the new nds code that relies on libmicrohttpd.
The nds openwrt package needs to be updated.
I've put the new openwrt package code here:
https://github.com/nodogsplash/nodogsplash/tree/openwrt-package

Works for me.
