### ISSUE TITLE
v2.0.0 not work well at port 80?

### ISSUE THREAD

**Issue by jiqianghu** [nodogsplash/nodogsplash#159]
Browser is long time no response when set port 80 at v2.0.0.
I use wireshark and find no http packets between browser and router.
Maybe a firewall issue?
My envirement is openwrt15.05 with libmicrohttpd library. 

(V2.0.0 with other port is ok; V0.9 is ok at port 80.)

**Comment by mwarning** [comment]
Be aware that v2.0.0 has not been released yet.
Is nodogsplash running?

**Comment by bluewavenet** [comment]
@jiqianghu 
On OpenWrt (or LEDE) NodogSplash will conflict with uHTTPd, also on port 80 by default.
Do you have a specific requirement to run NDS on port 80?

**Comment by jiqianghu** [comment]
@mwarning :
enabled it.

@bluewavenet :
I set uhttpd another port, and set NDS at 80.
If NDS V2 support port 80, the url address will show perfect. I know v0.9 supports 80 successfully.

**Comment by jiqianghu** [comment]
And another issue, to build it, openwrt1505 seems no libmicrohttpd-no-ssl, I change the make file with libmicrohttpd to comile ok. It depends other ssl libs.

**Comment by bluewavenet** [comment]
@jiqianghu There may well be a bug, I have not tested this. 
With NDS running try:
http://openwrt.lan:2050/images/splash.jpg
and
http://openwrt.lan:80/images/splash.jpg
Does either of these URLs produce an image?

**Comment by bluewavenet** [comment]
@jiqianghu 
In normal operation as a hotspot, https support is not needed as all devices these days do an initial request on port 80 via their built in Captive Portal Detection regardless of any "home page" that may be set in the browser. So the build will be for libmicrohttpd-no-ssl to remove unnecessary code and significantly reduce the installed size.
It would be a nice thing to have https support for some specialised applications, but would always produce a certificate error as far as I can see.

**Comment by jiqianghu** [comment]
@bluewavenet 
It has response now.
But the splash.html $imagesdir is not changed.

**Comment by bluewavenet** [comment]
port 80 or port 2050?
Are you changing $imagesdir for some reason?

**Comment by jiqianghu** [comment]
the splash is shown, but it's image can not see. Open html source code, $imagesdir is not changed at broswser.

**Comment by bluewavenet** [comment]
Did you try http://openwrt.lan:2050/images/splash.jpg ?

**Comment by bluewavenet** [comment]
I think you need to use something other than port 80 as it will be trying to redirect to its self and you can end up in a loop.....

**Comment by bluewavenet** [comment]
I don't see this as a bug. It does not make any sense to have NDS serve the splash page on port 80 in my opinion.
