### ISSUE TITLE
Unable to load iframe content 

### ISSUE THREAD

**Issue by TalkativeSpoon** [nodogsplash/nodogsplash#161]
Hi guys, 
I have loaded chaos calmer with nodogsplash on a Ubiquity Nano Loco M2.
Currently the nodogsplash works perfectly with the standard setup. I have now included an iframe to authenticate using an external Facebook log in using javascript, however the iframe loads the nodogsplash splash page in the iframe. When I click on the splash within the iframe, I am able to see the external site as needed.
I have tried editing /etc/nodogsplash/nodogsplash.conf to allow pre authenticated users access to the IP of the external website, as per the instructions in the file but the problem persists.
Please can some assist with the correct code to be added to the /config/nodogsplash file to allow access for the iframe.

**Comment by bluewavenet** [comment]
Facebook is a particularly difficult one as the hostname can resolve to any one of many ip addresses. 
However in this case are you sure nds is using /etc/nodogsplsh/nodogsplash.conf and not the system generated version in /tmp ?

**Comment by TalkativeSpoon** [comment]
I have checked the /tmp/etc folder and found a nodogsplash_cfg0221da.conf file there. Inside the file it says `# auto-generated config file from /etc/config/nodogsplash`

I then went and edited /etc/config/nodogsplash to use the plain config as well to see if this might help...
`  # Use plain configuration file as well
  option config '/etc/nodogsplash/nodogsplash.conf'`
but now nodogsplash wornt start, i get the following error:
`root@ ~# /etc/init.d/nodogsplash start
nodogsplash: Configuration file '' doesn't exist
 Testing required modules
  Testing module ipt_mac
   ipt_mac is working
  Testing module ipt_mark
   ipt_mark is working`
I have confirmed that the file is in the correct place. When I comment out the plain config line nodogsplash runs correctly. Would you advise that perhaps use another location to store the plain config? or should i add the relevant lines of code to /etc/config/nodogsplash?

Thanks in advance

**Comment by bluewavenet** [comment]
@TalkativeSpoon 
Comment out the Use plain config... line again and after the line:
  list preauthenticated_users 'allow udp port 53'
add the line:
  list preauthenticated_users 'allow tcp port 80 to 10.1.1.1'
changing the port number and ip address to what you need it to be.
