### ISSUE TITLE
BinVoucher not call my auth_myscript

### ISSUE THREAD

**Issue by rosbergrodrigues** [nodogsplash/nodogsplash#166]
Hi, guys, please help me to fix this

1 - My script is not even called.
2 - My script has executable permission. [chmod a+x myscript]
3 - I can call it manually from the shell. [ ./myscript 00:00:00:00:00:00 1234 ]
4 - The captive portal sends to my computer : ERROR: Tokens no match

**Nodogslpash.conf**

BinVoucher /etc/nodogsplash/myscript
ForceVoucher yes

**OPENWRT:** ChaosCalmer
**NODOGSPLASH:** v 0.9_beta9.9.9-5
**DEVICE:** TP-Link WR740nd v4.23

Sorry for my bad english

**Comment by bluewavenet** [comment]
The binvoucher functionality is broken in 0.9_beta9.9.9-5.
It may be fixed in v1 but I have not tried it.
However if you are trying to do a remote authentication you do not actually need binvoucher at all.

In your splash.html, add the line
` <meta http-equiv="refresh" content="0;URL='http://yoururl/yourcode.php?authaction=$authaction&amp;tok=$tok&amp;redir=$redir&amp'" />`
Then once you have authenticated on your remote php site send the client back to nodogsplash with:
`<form method='get' action='$authaction'>
<input type='hidden' name='tok' value='$tok'>
<input type='hidden' name='redir' value='$redir'>
<input type='submit' value='Continue'></form>`

**Comment by coldfeetx** [comment]
Hi @bluewavenet,

Thanks for the info.
Can you please elaborate a little more on your above statement?
If you could provide an example of the remote php code that would help.

I need to do the following on an openwrt box containing nodogsplash:
1. Have the user enter his email and mobile number once he opens the openwrt router url on his browser (after connecting to the router wifi network).
2. Use the entered mobile number to perform OTP-based authentication (probably through a remote PHP server). Till now the user is still in pre-authenticated state wrt nodogsplash.
3. If authentication is successful, redirect the user back to a custom url. Now the user moves to authenticated state wrt nodogsplash.
What would be the best way achieve the above steps?

PS:
Sorry for requesting for some hand-holding on this as I am new to html and php.

Thanks

**Comment by bluewavenet** [comment]
Steps as follows:
1. Allow access to the IP address of your php server to preauthenticated clients.
2. Use PHP $_get[ ] in your remote code to pick up the data from NDS
3. Use a PHP generated form method='get' to return to NDS as in my example above.

**Comment by coldfeetx** [comment]
@bluewavenet,
Thanks.
Few points to confirm here.
* NDS is running inside my openwrt wireless AP which does not have a publically reachable ip (its NATed via the edge router its connected to).
In that case, I would need the php server to have a public IP and be accessible from NDS, for the redirection in step 1 to happen, isn't it?
Then in step 3, can the PHP generated form method='get' (on php server with public IP) redirect back to NDS (on private IP) when the user presses "Continue" in your example above? I would not need to mention NDS IP/URL on the remote PHP code form for the reverse redirection to work, right?

**Comment by bluewavenet** [comment]
The PHP server needs to be accessible from NDS, public or not it does not matter, as long as NDS can access it.
<form method='get' action='$authaction'> is the key to returning to NDS. $authaction contains the return URL
