### ISSUE TITLE
make will not work in Raspben Jessie 

### ISSUE THREAD

**Issue by klint-k** [nodogsplash/nodogsplash#171]
I used sudo apt-get install to install libmicohttpd-dev 
then used sudo dpkg-buildpackage -d -b -rfakeroot -us -uc to try and "make"
got this error
src/gateway.c:256:7: error: ‘MHD_OPTION_LISTENING_ADDRESS_REUSE’ undeclared (first use in this function)

**Comment by mwarning** [comment]
MHD_OPTION_LISTENING_ADDRESS_REUSE is defined in /usr/include/microhttpd.h.
Please make sure thatlibmicrohttpd version 0.9.51 or newer is installed.

**Comment by klint-k** [comment]
I just loaded the latest libmicrohttpd-dev. 

 

 

 

Klint

**Comment by mwarning** [comment]
We do not have the hardware to test this setup.
Maybe the include paths for the compiler call need to be adjusted.
Hard to tell...
