### ISSUE TITLE
version 9.9.9. on Chaos calmer where to config and how?

### ISSUE THREAD

**Issue by kalich007** [nodogsplash/nodogsplash#173]
when i use 9.9.9 and uncomment the  option config '/etc/nodogsplash/nodogsplash.conf' line, it says: configuration file '' doesnt exist, even when i have put the file in there, i am looking for some configuration adjustments but the commands in /etc/config/nodogsplash seem different than from nodogsplash.conf so how can i start playing with the settings please?
my goal overall is to make our external web app as a splash page (in native browser, not cna) and to be able to catch macs of our users to count their visits in our establishment...
thank you very much

**Comment by bluewavenet** [comment]
I had the same problem and looked briefly but had a system to get out so reverted the init.d script to an earlier version.
[nodogsplash.txt](https://github.com/nodogsplash/nodogsplash/files/798667/nodogsplash.txt)
 Copy this into /etc/init.d/ then rename without the .txt extension. Should work ok then. I should make time to look into this in more detail. On some hardware the interface NDS is on may not be up in time for NDS to start so it fails on a reboot but will start manually with /etc/init.d/nodogsplash start
If you do have this issue you can add /etc/init.d/nodogsplash start to /etc/rc.local as a work around. (This startup issue has been fixed in later versions).

**Comment by kalich007** [comment]
im getting really sad cause it doesnt work, now with your fix i cant run /et/init.d/nodogsplash because it says permission denied...
Only thing that works on Chaos Calmer seems the basic version 0.9_beta9.9.9-5 (from package repository) with only one configuration file /etc/config/nodogsplash to which i cant find any documentation how to wield it. when i uncomment /etc/nodogsplash/nodogsplash.conf file (which is well commented), it wont start cause it says file doesnt exist...
i tried installing version 1.0.1.ipk from github, but it wont go through because there are some libpthread and some ip tables dependencies missing
Is there any way somebody has gone over these obstacles and actually started using some of the described functionalities of nodogsplash? I would hate to have to change to coova after i spent days tryin to figure this thing out...
Thank you all

**Comment by bluewavenet** [comment]
Assuming you are logged in as root, you must run the command:
chmod +x /etc/init.d/nodogsplash to make the script executable, then run the command to start nodogsplash:
/etc/init.d/nodogsplash start

Run /etc/init.d/nodogsplash enable
to make it start on reboot.

If you put a space in, ie /etc/init.d nodogsplash start it will still give the permission denied message. (I have done this myself when in a hurry!).

There are two ways to configure NDS, 
1. the way we are trying here (I do this historically as it was how it was done in older versions - but there is a bug of some sort in the newer init.d script).
2. By using the /etc/config UCI script that builds a start time temporary version of nodogsplash.conf in the /tmp/etc directory.

Using the UCI  script is probably better but needs a bit of knowledge of using UCI.

We have numerous systems in production using the first method, but the latest versions of our system (that uses NDS) will use the UCI method. Both do work.

Try my file again, running the command without the space and let me know what happens.
I can also give you some pointers to using the UCI method if you wish.

**Comment by mwarning** [comment]
@kalich007: OpenWrt chaos calmer is rather old by now and NDS from its package feed is also old. You can give https://lede-project.org/ a try, it is an OpenWrt fork and has an up to date NDS available.

**Comment by kalich007** [comment]
Thank you both very much!
@bluewavenet : as i updated, i got it working by changing the content of the file instead of handling the file physically :) 
@mwarning : i didnt know about that, will look into it first thing tommorow

Both of yall: I have just prepared kickass secure cookie autologin system ( first try working smoothly :) ) that is ready to mark user's visit to the app from our hotspot network. Only thing which is left, is to get the splashscreen open in a native browser which can work with those cookies. I configured NDS to open up my 'on external server sitting' login page (thru bluewaves' meta tagging splash page redirection :) ) but it opens in a CNA browser (some weak built in thing just for the easiest tasks) and it has no cookie nor some advanced programming tech support. So is there a way to make NDS on OpenWRT show a splash screen in a native browser or redirect to it? Or can it be achieved thru lede-project?

Thank you very much again, its my last struggle i hope )

**Comment by bluewavenet** [comment]
The "CNA browser" is part of the iOS implementation of the Captive Portal Detection (CPD) protocol. On Android. the "default" browser is used (this can be set by the user). On Windows mobile and desktop it is similar. On Linux it is usually the Gnome authentication GUI (a very stripped down open source browser).
Basically there is no way to override this from the hotspot point of view. It is possible to redirect to an app on Android but this depends on OS version as well as a particular app being installed.

You can get the latest stable release of LEDE at:
[https://downloads.lede-project.org/releases/](url)
It has the latest NDS release version, currently 1.0.1-2

**Comment by kalich007** [comment]
Thank you for clarification, although not exactly what i wanted to hear :). I am actually testing it home on my android 5.1 phone and so far found no way how to get from that "default" browser in authomatic kind of manner into a native browser and if i understand correctly, thats what u (and a ton of google searches) are saying cant be done.  
My intention was to pass to my webapp some variable sayin that the access comes from our walled garden, with the help of cookies recognize signed in user and automatically while logging in also check him in with a datestamped record in mysql database. 
Can you please help me understand what those bin vouchers are for, and if they can help me find a solution? And what would i get from upgrading to LEDE and using NDSv1.0.1-2?

**Comment by kalich007** [comment]
from what i see, LEDE probably wont work well on TP-link mr3020 since it doesnt have 64MBytes of ram right?

**Comment by kalich007** [comment]
How can i use the UCI as you mentioned earlier please?

**Comment by mwarning** [comment]
@kalich007 I use LEDE on 32MB RAM devices with no problem.

**Comment by bluewavenet** [comment]
LEDE is fine with 32MB with room for NDS. I have it on a Ubuquiti AirGateway . You also have the opportunity of using the Imagebuilder to customise the standard installed applications. For example you can remove USB support or even IPv6 for a NDS system leaving loads of space.

UCI support is mainly provided to allow a universal configuration interface and support in NDS means it will be possible to write a LUCI web interface for configuring NDS although no-one has yet done so.
The UCI command line interface can be used to configure NDS, but I think most people edit /etc/config/nodogsplash directly. I will post a couple of examples later when I have some time.

**Comment by bluewavenet** [comment]
@kalich007 As for your application of NDS, you do not need to use cookies, NDS will already send the mac address amongst other things and my meta redirect can be used to send anything you like eg a unique identifier for your NDS instance. Then your webapp can pick this up and use as required. In this way you will not need anything special on the client device.

**Comment by bluewavenet** [comment]
LEDE is really OpenWrt brought up to date with many many upgrades and fixes both in the OS and its packages. It has the most up to date release of NDS.  Most significantly in my opinion, LEDE fully supports f2fs for flash devices.

**Comment by kalich007** [comment]
Thanks, think i will transfer to it laters and use the system by the book :-) right now im just really tryin to put this all together. I have managed to bind the authenticating and loging system via NDS together so it actually works pretty neat :) . 
The only thing though which keeps my app alive is that i dont offer the "Connect to the internet" button until after authentication and on the bottomest bottom under all of my apps features so users really have to at least notice its purpose, because once they click "to connect" the whole default browser falls.. :/ and i am left with no option on how to automatically reopen it in the native browser which offers "save app to desktop" function. 
here: http://stackoverflow.com/questions/34933146/prevent-captive-portal-auto-close-after-authentication-android 
the very last comment says something about some web utility able to navigate to other browsers but doesnt clarify how it might be done...

**Comment by bluewavenet** [comment]
This aspect of CPD is for security reasons. Without it a hotspot could spoof requested sites, insert content etc etc. Any possible hacks for Android or iOs would likely be very quickly patched in my opinion.

**Comment by kalich007** [comment]
Makes a lotta sense :) got it all running thanks to you guys, i guess im just gonna stick with a popup sayin smtng like "you will get a better experience through regular browser" before they actually connect with CPD.
I also wanted to ask if I can upgrade to LEDE from my Chaos Calmer with "Flash new firmware" in LuCI? Or do i need to take some other steps before flashing to LEDE?

**Comment by bluewavenet** [comment]
LEDE uses f2fs which is much faster and more advanced than jffs2 that is used in OpenWrt. However using sysupgrade in Luci from OpenWrt fails to change filesystem. The resulting effect is the squashfs overlay becomes volatile effectively resetting to default on every reboot. This looks to me like a bug in OpenWrt sysupgrade.
I have found that using tftp to reflash your router works fine however. Once you are running LEDE, its sysupgrade works fine.

**Comment by kalich007** [comment]
what exactly do you mean by tftp? just overwrite the OpenWRT filetree with LEDE through WinSCP for example?
And what all kinds of information can you send through that beforementioned meta-tag? im interested anything which would identify the users and the instance from our venue (MAC of his device?, IP of my router on the internet?, anything else?) and in what variables would they be to find?

**Comment by bluewavenet** [comment]
Almost all routers support TFTP for reflashing, usually invoked by keeping the reset button pressed while powering up. See your router's documentation. You need TFTP server software running on your computer. I use Linux on my laptop and tftp is included by default. I have not used windows for many years but I'm sure tftp in some form is available. 

You cannot just overwrite files, for a start, the image is usually ends up in a read only squashfs partition.

**Comment by bluewavenet** [comment]
A full list of variables available in NDS splash page can be seen here:
[https://github.com/nodogsplash/nodogsplash/blob/master/resources/splash.html](url)
You can send anything with the meta tag, not just these variables.
