### ISSUE TITLE
NDS works not well with iPhone

### ISSUE THREAD

**Issue by chengdanhao** [nodogsplash/nodogsplash#174]
When I use iPhone to connect OpenWRT 14.04, the NDS authenticate page pops up. The page top right corner have a **Cancel** button, and wait for a while, it changes to **Done**. This is the normal process.

But sometimes I met the following problems:
1. It took a long time to wait the authenticate page pops up.
2. It took a long time to wait **Cancel** button changed to **Done**, or never changed to **Done**, iPhone just disconnected from the router.

Android is hard to met problem 2, problem 1 also had a low probalility to met.

My colleague also have the same puzzle.

**Comment by mwarning** [comment]
What version of nodogsplash do you use?

**Comment by bluewavenet** [comment]
@chengdanhao 
See issue #113  This could be what you are seeing. iOS does seem to be prone to this issue more than Android but it is version dependent.

I assume the Cancel/Done button is a function of your custom splash page?

**Comment by chengdanhao** [comment]
@mwarning 
The version I used is 0.9_beta9.9.8

@bluewavenet 
The Cancel/Done button is provied by iOS, see [this link](https://www.intego.com/mac-security-blog/wp-content/uploads/2016/01/captiveportal-600x300.jpeg), it show the button.

The solution you give in issue 113 didn't work for me, I already disable those options when I met these problems. As you said, maybe these problems depend on NDS version. I want to upgrade the NDS for 14.04, but I didn't know the way.

**Comment by bluewavenet** [comment]
The quickest and simplest way to get the latest release of NDS is to reflash with LEDE. Currently version 1.0.1-2 is included with this.
[https://downloads.lede-project.org/releases/](url)

**Comment by mwarning** [comment]
@chengdanhao the version you use is very old. Please try a newer version like @bluewavenet mentions.

**Comment by chengdanhao** [comment]
@mwarning 
@bluewavenet 

Because time is limited, I didn't reflash my router to LEDE. 
I modify the Makefile and recompile, the latest NDS is running in my router now.
```
--- a/feeds/routing/nodogsplash/Makefile
+++ b/feeds/routing/nodogsplash/Makefile
@@ -9,13 +9,13 @@ include $(TOPDIR)/rules.mk
 
 PKG_NAME:=nodogsplash
 PKG_FIXUP:=autoreconf
-PKG_VERSION:=0.9_beta9.9.8
+PKG_VERSION:=1.0.1
 PKG_RELEASE:=2
 
 PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)/
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
 PKG_SOURCE_URL:=git://github.com/nodogsplash/nodogsplash.git
-PKG_SOURCE_VERSION:=v0.9_beta9.9.8
+PKG_SOURCE_VERSION:=v1.0.1
 PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
 PKG_BUILD_PARALLEL:=1
```

Then, I face a new issue, no matter what device I connect to router, the NDS clients count is always 0.

```
==================
NoDogSplash Status
====
Version: 1.0.1
Uptime: 0d 0h 3m 51s
Gateway Name: NoDogSplash
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: 192.168.88.254:2050
Splashpage: /etc/nodogsplash/htdocs/splash.html
Redirect URL: http://192.168.88.100/
Traffic control: no
Total download: 211 kByte; avg: 7.31023 kbit/s
Total upload: 326 kByte; avg: 11.303 kbit/s
====
Client authentications since start: 0
Httpd request threads created/current: 0/0
Current clients: 0
====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========
```

**Comment by chengdanhao** [comment]
I found a topic here : [captive portal issue with iOS devices ](https://community.aerohive.com/aerohive/topics/captive_portal_issue_with_ios_devices)

**Comment by bluewavenet** [comment]
We would have go at length through your configuration to find what is wrong as this **does** work. Really, you will save time reflashing with LEDE and then installing  NDS. I have NDS on various hardware with no problems at all and some very busy production sites. Looking at the logs of the busiest, there have been 20K client logins since early October, some 80% of them from iOs devices. There have been no complaints received with regard to your issue.

**Comment by chengdanhao** [comment]
@bluewavenet I used the offical configuration, didn't change any line.

The version of OpenWrt I used is customized by IC vendor and the BSP is also maintain by them. Also, some products used this IC are not in support lists. ☺

**Comment by bluewavenet** [comment]
Captive Portal Detection (CPD) has matured significantly in recent years on just about all operating systems and devices. Most issues these days are due to misconfiguration, for example long delays caused by ipv6 being preferred if available on the router. NDS version 1 is well tested and fits perfectly into the de-facto CPD standards and no known bugs have come to light. Version 2 of NDS does not work in any significantly different way to version 1 so I do not expect any problems to arise but it is still to be tested in a busy, live production environment as far as I am aware. Anyone?

**Comment by bluewavenet** [comment]
Some  detailed testing on version 2 completed and no problems with CPD found.
Issues with CPD outside control of NDS:
1. If another previously used SSID is present, the client will try us then fall back to the previous SSID immediately. If that fails client can go into a loop. "Forgetting" the NDS SSID then re-connecting will allow CPD to pop up the splash page.
2. CPD may well get out of sync if NDS is restarted. Switching off WiFi and switching back on will usually fix the problem.
3. Some implementations of CPD, particularly older ones, do not cope with inactivity timeouts. again, switching off WiFi and switching back on will usually fix the problem.

I have found, interestingly, that regulars on a large site running NDS have, for the most part, figured this out for themselves. I guess they are so desperate to get connected they just keep trying. ;-)
