### ISSUE TITLE
How to modify nodogsplash and compile it to ipk using sdk?

### ISSUE THREAD

**Issue by ram19890** [nodogsplash/nodogsplash#178]
Using Ubuntu as my base and installed all the dependencies to make the SDK work. I downloaded the OpenWrt SDK from the recent github repository. After that I removed the nodogsplash from the feeds and created a new Makefile from the openwrt-routing git. Generated a menuconfig file and created the ipk using the make command. Everything went successful, but when I try to change the splash.jpg image file and edited the makefile of nodogsplash to my own fork of nodogsplash github, it would not change the image splash.jpg from the forked github of mine. How to tinker with the package and how does it get the files even though I delete the build_dir/target_mips_musl 1.1.16/nodogsplash?

**Comment by mwarning** [comment]
Maybe this helps (also applies to OpenWrt):
https://github.com/nodogsplash/nodogsplash/tree/openwrt-package/lede
https://github.com/mwarning/lede-examples

**Comment by mwarning** [comment]
Have you removed this line?
https://github.com/openwrt-routing/packages/blob/master/nodogsplash/Makefile#L53

**Comment by ram19890** [comment]
@mwarning Thank you very much!
