### ISSUE TITLE
How does the native browser pops up with the splash screen in IOS and android?

### ISSUE THREAD

**Issue by ram19890** [nodogsplash/nodogsplash#179]
In my computer whether it is Linux or Windows, I don't see the native browser popping up immediately as Android (s6) or IOS10 (5) does! How can I stop the splash screen appearing on the native browser on my phones, instead I want the same splash screen on the Firefox or Chrome Mobile browsers?

If you can give me a start, I would understand it well!

**Comment by bluewavenet** [comment]
I'm not sure what you are asking.
On Android, ios, osx, windows and linux it is the default browser that opens. On each type of client the user can change the default one way or another but a captive portal has no control over this.

**Comment by ram19890** [comment]
Thank you for replying!
The default browser on linux doesn't popup the browser screen automatically , like the android phone does, my question is how is it triggering the google webview?

**Comment by bluewavenet** [comment]
On Linux it depends on the distribution. Some have CPD enabled and some you have to enable it. But all have it as far as I'm aware.
Where does Google Webview come into it? I'm still not sure what you mean.

**Comment by bluewavenet** [comment]
#140 has a good descrition of how it works.

**Comment by ram19890** [comment]
@bluewavenet Yup,this is what I need, thank you!
