### ISSUE TITLE
Nodogsplash not working with iptables 1.6.1

### ISSUE THREAD

**Issue by pmosse** [nodogsplash/nodogsplash#180]
After installing nodogsplash 1.0.1-2 in LEDE for TP w1043 v4, It cannot start due to problems with firewall rules. I checked and the problem seems to be with iptables when executing something simple as this:

root@LEDE:/etc/nodogsplash# iptables -A INPUT -m --state NEW,ESTABLISHED -j ACCEPT
iptables v1.6.1: Couldn't load match `--state':No such file or directory

I think there is a problem with the new version of iptables as this was working fine in TP w1043 v3 with iptables 1.4.21

**Comment by bluewavenet** [comment]
Which version of LEDE are you running?
I have LEDE 17.01.1 r3316-7eb58cf109 (stable release) with NDS 1.0.1-2 on x86 Geode running here with no problems.

**Comment by bluewavenet** [comment]
LEDE 17.01.1 r3316-7eb58cf109 comes with iptables 1.4.21 ....

**Comment by pmosse** [comment]
Hey! Thanks for the reply. I will confirm you the version later tonight, but I got the lastest version last night from here https://downloads.lede-project.org/snapshots/targets/ar71xx/generic/, for tl-wr1043nd-v4. I tried downgrading iptables but it says the architecture is not compatible. I will try using your version of LEDE :)

**Comment by bluewavenet** [comment]
[https://downloads.lede-project.org/releases/](url)
You are on the daily snapshot so may well be a problem with that for now. Worth keeping an eye on this though ;)

**Comment by pmosse** [comment]
You are totally right, that solved my problem, thank you very much :D (I hope iptables 1.4.21 stays in the next release of LEDE too ;) )

**Comment by 809205580** [comment]
I have solved this problem.
Replace "-m state --state " with "-m conntrack --ctstate"

**Comment by 809205580** [comment]
The "-m state --state" will gradually be replaced by "-m conntrack --ctstat".

**Comment by mwarning** [comment]
@809205580 good to know. If that is already valid syntax, it can be replaced already.

**Comment by bluewavenet** [comment]
LEDE 17.01.1 (latest release) comes with iptables 1.4.21 but snapshots have v1.6.1.
If the new syntax works with 1.4.21 it can be replaced now - a wee problem....

**Comment by mwarning** [comment]
@809205580 the change looks good. Thanks again & merged: https://github.com/nodogsplash/nodogsplash/commit/1be1395548c26184dcc9be99cb47becfbced8906
