### ISSUE TITLE
Splash page not served on jolla.com

### ISSUE THREAD

**Issue by V10lator** [nodogsplash/nodogsplash#181]
I tried nodogsplash with a Jolla C. This mobile opens jolla.com to access the splash page.

Now the problem is that all I get is "Unable to connect" - "The connection was refused when attempting to contact jolla.com." - If I manualla try to browse another website (i.e. google.com) the splash page is served.

Manually resolving the DNS adresses of google.com and jolla.com on the mobile shows the IP 10.0.0.1 (so the correct IP of the router) for both adresses.

**Comment by mwarning** [comment]
I think the jolla uses https, which cannot be intercepted without interfering with https.
Most smartphones have an captive portal detection that tries to reach some domain via http

**Comment by bluewavenet** [comment]
As far as I know, Sailfish does not have a CPD implementation.

**Comment by bluewavenet** [comment]
Looking again at your post.... DNS should always resolve the actual ip not the ip of your router.. unless you are running a very bleeding edge version of NDS. So lets start again - which version of NDS are you using? :)

**Comment by bluewavenet** [comment]
There is nothing we can do here if Sailfish OS has not implemented CPD. All other mobile OS's have this and it has become a mature "defacto" standard.
