### ISSUE TITLE
username & password auth doesn't work on 2.0.0

### ISSUE THREAD

**Issue by odkrys** [nodogsplash/nodogsplash#182]
I compiled the latest master version for asuswrt-merlin and applied the 1 line patch in the process.

-MHD_OPTION_LISTENING_ADDRESS_REUSE, 1,
+MHD_OPTION_LISTENING_ADDRESS_REUSE, 0,

Because asus router is using old kerner and doesn't support SO_REUSEPORT.
Anyway after cross-compiling, I tested basic functions.

And I noticed that username and password authentication didn't work.

Clients can access the internet without typing username and password, when I set each features on.
Yeah everybody can do log in with blank name and password. lol

It seems that http_microhttpd* don't have any related codes.

Has anyone tested this?

* It worked on 1.0.1.

**Comment by mwarning** [comment]
I do not think this was tested.
Any help fixing this is welcome. :)

**Comment by bluewavenet** [comment]
Try Forward Authentication Service in master. This uses PHP scripts running on either the local router or an external server.
