### ISSUE TITLE
font patch.

### ISSUE THREAD

**Issue by odkrys** [nodogsplash/nodogsplash#183]
+	{ "ttc",		"application/x-font-ttf" },
+	{ "ttf",		"application/font-sfnt" },
+	{ "otf",		"application/font-sfnt" },
+	{ "sfnt",		"application/font-sfnt" },
+	{ "woff",		"application/font-woff" },
+	{ "woff2",		"application/font-woff" },
+	{ "eot",		"application/vnd.ms-fontobject" },

Then we can make splash page better.

http://imgur.com/a/QuMAz

**Comment by bluewavenet** [comment]
@odkrys Specifying particular fonts to use is client os/browser specific. 
As almost 100% of clients using a typical WiFi hotspot these days are using mobile devices, it is far more important to have the splash page (and indeed the error page) designed to be fully responsive. This has been done for version 2. You can download  both splash.html and infoskel.html from V2 and use with V1.
Adding CSS for your own fonts is then simple but be aware your selection will not be available on most mobile devices so the CPD/browser will only be able to make "best efforts" to display what you intended. We are always looking for improvements so feel free to attach a file here and I will give it a shot.

**Comment by odkrys** [comment]
that's right. I understand :)
