### ISSUE TITLE
cannot compile on debian

### ISSUE THREAD

**Issue by paolomeraviglia** [nodogsplash/nodogsplash#184]
Version: raspbian jessie latest (2017-4-2)

After doing apt-get install libmicrohttpd-dev, cannot do dpkg-buildpackage, with error dpkg-checkbuilddeps: Unmet build dependencies: libmicrohttpd-dev (>= 0.9.51)

Trying making and installing libmicrohttpd-dev with version 0.9.54 gave me the same error.

**Comment by paolomeraviglia** [comment]
I can compile on debian jessie with configure, make, make install... but when I try to start nodogsplash:

[3][Mon May  8 03:17:58 2017][9762](src/gateway.c:258) Could not create web server: No such file or directory

So I retried the not working method described here, without success.

How can I solve this!?

**Comment by mwarning** [comment]
It works for me..
I have not seen this message in nds:
"Could not create web server: No such file or directory"

**Comment by bluewavenet** [comment]
This is a configuration issue at startup of NDS. It means NDS is unable to find nodogsplash.conf and therefore fails to start it's web server. The error appears in the system log.
