### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by paolomeraviglia** [nodogsplash/nodogsplash#185]
http://nodogsplash.readthedocs.io/en/latest/compile.html

doing make, I got

root@raspberrypi:/tmp/nodogsplash# make
cc  -O0 -g -Wall -Isrc -c src/auth.c -o src/auth.o
cc  -O0 -g -Wall -Isrc -c src/client_list.c -o src/client_list.o
cc  -O0 -g -Wall -Isrc -c src/commandline.c -o src/commandline.o
cc  -O0 -g -Wall -Isrc -c src/conf.c -o src/conf.o
cc  -O0 -g -Wall -Isrc -c src/debug.c -o src/debug.o
cc  -O0 -g -Wall -Isrc -c src/firewall.c -o src/firewall.o
cc  -O0 -g -Wall -Isrc -c src/fw_iptables.c -o src/fw_iptables.o
cc  -O0 -g -Wall -Isrc -c src/gateway.c -o src/gateway.o
src/gateway.c: In function 'main_loop':
src/gateway.c:251:7: error: 'MHD_USE_EPOLL_INTERNALLY' undeclared (first use in this function)
       MHD_USE_EPOLL_INTERNALLY,
       ^
src/gateway.c:251:7: note: each undeclared identifier is reported only once for each function it appears in
src/gateway.c:256:7: error: 'MHD_OPTION_LISTENING_ADDRESS_REUSE' undeclared (first use in this function)
       MHD_OPTION_LISTENING_ADDRESS_REUSE, 1,
       ^
Makefile:20: set di istruzioni per l'obiettivo "src/gateway.o" non riuscito
make: *** [src/gateway.o] Errore 1

**Comment by mwarning** [comment]
Works for me on amd64 debian stable and manually compile&installed libmicrohttpd (./configure && make && sudo make install).

I think your raspi has a slight different environment.
Please consider to submit a merge request or patch if you figure out how to fix this.

**Comment by paolomeraviglia** [comment]
trying to fixing the other ticket I opened I got this error.

**Comment by lynxis** [comment]
I can not find any other issue. the problem is that libmicrohttpd (0.9.50) is too old for this. I'll create PR for 0.9.54 after limited testing the release with NDS on a embedded device.

**Comment by mwarning** [comment]
I have added a macro check for libmicrohttps >= 0.9.51.
https://github.com/nodogsplash/nodogsplash/commit/41bdcf02bbfd8e73fa7eb348fd3ddd16a11ce3b6

I assume that is all we can do for now.
