### ISSUE TITLE
Nonzero exit status 2 from command: iptables -t filter -A ndsRTR -m state --state INVALID -j DROP

### ISSUE THREAD

**Issue by sepa85** [nodogsplash/nodogsplash#186]
Hi, I have this problem with a LEDE Reboot SNAPSHOT r4103-5f93298 / LuCI Master (git-17.129.46128-757cdbb) installation on a TP-Link Archer C7 v2.

When I try _/etc/init.d/nodogsplash_ start everything seems to work well, but if I try _ndsctl status_ the terminal prints 

`ndsctl: nodogsplash probably not started (Error: No such file or directory)`

The errors in logread are:
- Nonzero exit status 2 from command: iptables -t filter -A ndsRTR -m state --state INVALID -j DROP
- Nonzero exit status 2 from command: iptables -t filter -A ndsRTR -m state --state RELATED,ESTABLISHED -j ACCEPT
- Nonzero exit status 2 from command: iptables -t filter -A ndsNET -m state --state INVALID -j DROP
- Nonzero exit status 2 from command: iptables -t filter -A ndsAUT -m state --state RELATED,ESTABLISHED -j ACCEPT
- Error initializing firewall rules! Cleaning up
- Exiting because of error initializing firewall rules

Is this a my issue or is it replicable? Thanks..

**Comment by bluewavenet** [comment]
See #180 
If you use the release version of LEDE rather than Snapshot it will be ok.
