### ISSUE TITLE
LEDE & Traffic Control

### ISSUE THREAD

**Issue by mikysal78** [nodogsplash/nodogsplash#187]
This is still an unresolved issue? 
`Testing required modules
  Testing module ipt_mac
   ipt_mac is working
  Testing module ipt_mark
   ipt_mark is working
  Testing module imq numdevs=2
   Module imq numdevs=2 needed
   Scanning disk for imq module
   imq module missing: please install it`

IMQ is not present in Chaos and Lede.
Best regards,
Miky

**Comment by bluewavenet** [comment]
Yes this is still an issue although some work has been done on it.
However SQM works extremely well on LEDE along with NDS. It works best configured on the LAN/Bridge interface, configured by LUCI, making a huge improvement to performance on a busy router. It is a little confusing unless you remember that "upload" will be traffic to clients and download will be traffic from clients. You cannot configure different data rates to different clients however.
