### ISSUE TITLE
EnablePreauth not working on 2.0

### ISSUE THREAD

**Issue by phenobarbital** [nodogsplash/nodogsplash#190]
Hi, I compiled NDS 2.0 for openWRT (trunk), I've migrated from 1.0.2, where it was working very well, but with the same configuration, enablePreauth is not executing preauth script.
Although is working on 1.0.2, options in /etc/nodogsplash/nodogsplash.conf like enablePreauth or BinVoucher are not working
My options:
    BinVoucher /usr/local/bin/auth
    ForceVoucher 0
    EnablePreAuth 1
in /etc/config/nodogsplash
      # Use plain configuration file
      option config '/etc/nodogsplash/nodogsplash.conf'

Best Regards
Jesus

**Comment by bluewavenet** [comment]
Binvoucher functionality is not implemented in V2 yet.
