### ISSUE TITLE
Version 2 on LEDE

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#191]
What is required to get the v2 release included in LEDE  /releases/17.01.2?
It would be useful to have this AS WELL as NDS 1.0.1-2. We might then have some real testing in the wild!

**Comment by mwarning** [comment]
There is nothing stopping this. Me and @lynxis planed to create a nodogsplash2 package. Let's see who is first. :-)

**Comment by bluewavenet** [comment]
It's available in LEDE Snapshots - testing now :-D

**Comment by bluewavenet** [comment]
@mwarning @lynxis 
Any chance of a version 2.0.0-2 in LEDE? There are a few fixes that are pretty important, not least the streams of debug messages patch. It would be good to have this in before the next major release of OpenWrtLEDE. I'm happy to help in any way I can.

**Comment by mwarning** [comment]
Good idea. Feel free to go ahead. I have a bad cold.

**Comment by mwarning** [comment]
The next version would be 2.0.1, since we use semantic versioning. The -2 suffix is package revisions, when we change the package.

**Comment by mwarning** [comment]
@bluewavenet I have created a release draft. Please check if there is something missing and then just release and we can update the openwrt package.

**Comment by bluewavenet** [comment]
@mwarning 
Released ;-)

**Comment by mwarning** [comment]
:-)
