### ISSUE TITLE
 Nodogsplash has the option walled garden?

### ISSUE THREAD

**Issue by juliocdn** [nodogsplash/nodogsplash#192]
Nodogsplash has the option for the walled garden, I need to give access to certain domains, before clicking the button to accept the portal. Greetings

**Comment by bluewavenet** [comment]
Unfortunately NDS only supports "walled garden" by web server IP address, not domain name.

**Comment by pallas** [comment]
@juliocdn try using something like https://git.zx2c4.com/ipset-dns/about/ and add an ip-set rule to the `FirewallRuleSet`.
