### ISSUE TITLE
NDS is outputing some log data which cant be turned off

### ISSUE THREAD

**Issue by osiloke** [nodogsplash/nodogsplash#193]
NDS is spitting out some debug variables. I cant turn it off using the the current loglevel param. It even still spits out even if the log data is redirected to syslog using the -s param
The data looks like the following 
`authaction 0vari authtarget = authtarget 1vari clientip = clientip 2vari clientmac = clientmac 3vari denyaction = denyaction 5vari error_msg = error_msg 6vari gatewaymac = gatewaymac 7vari gatewayname = gatewayname 8vari imagesdir = imagesdir 9vari pagesdir = pagesdir 12vari maxclients = maxclients 10vari nclients = nclients 11vari redir = redir 13vari tok = tok 15vari token = token 16vari uptime = uptime 17vari version = version 18vari gatewayname = gatewayname 8vari authaction = authaction 0vari authtarget = authtarget 1vari clientip = clientip 2vari clientmac = clientmac 3vari denyaction = denyaction 5vari error_msg = error_msg 6va` 
How do i turn it off, or where in the code can i stop this, its filling up my logs

**Comment by mwarning** [comment]
@osiloke what version of NDS is this?
@lynxis any idea?

**Comment by osiloke** [comment]
@mwarning the master branch, v2.x

**Comment by mwarning** [comment]
@lynxis I think the output comes from this line: https://github.com/nodogsplash/nodogsplash/blob/master/src/template.c#L42
Any objections before I remove it? :-)

**Comment by lynxis** [comment]
that looks like a debug leftover. please remove it.

**Comment by mwarning** [comment]
fixed: https://github.com/nodogsplash/nodogsplash/commit/1fa350795cbab99575bc48a5ae71a42e80ff4efd
