### ISSUE TITLE
redirect all traffic for logged in users

### ISSUE THREAD

**Issue by joernroeder** [nodogsplash/nodogsplash#195]
Hey, i've successfully installed nodogsplash on my LEDE / OpenWRT router but now i'm struggeling with modified access rules for logged in users. 
I'd like to redirect all (outgoing) traffic to a local machine (i've already added it's mac address to the trusted list) and process it there afterwards.

The following Iptable modifications are looking promising https://superuser.com/a/661778 but don't now how i can integrate them with nodogsplash.

Hopefully someone can help me out. thanks in advance!

**Comment by mwarning** [comment]
It sounds like you just want to change the default gateway of your device running nodogsplash to the local machine.
But if you only want to redirect NDS traffic only, then you might use the fact that NDS marks it's traffic:
```
#define DEFAULT_FW_MARK_AUTHENTICATED 0x400
#define DEFAULT_FW_MARK_TRUSTED 0x200
```
You can create filter that traffic to a routing table that has it's own default route.
Out of my head you need to do these steps:
- create a separate routing table in /etc/iproute2/rt_tables (let's call it nds) and say there that you want all packets marked 0x400 to be handled by this routing table. Something along the lines of  "32764:	from all fwmark 0x400 lookup nds"
- add a default route in that table "ip route add default via 192.168.0.2 dev eth0 table nds" (192.168.0.2 is your local target machine)

I haven't tested this. But this concept should work.
