### ISSUE TITLE
Question about firewall

### ISSUE THREAD

**Issue by jlcmoore** [nodogsplash/nodogsplash#197]
Hi,
I posted a question on the openwrt forum about using nodogsplash with transparent proxy firewall rules. Could anyone help me with this?
Thanks a bunch!

[here is the link](https://forum.openwrt.org/viewtopic.php?id=71693) with attached config files and more details

**Comment by bluewavenet** [comment]
The file /etc/config/nodogsplash is a UCI config file. 
For simplicity, you are better off using the "Use plain configuration file" option and follow the workarounds in #126 and put your TrustedMACList entry in /etc/nodogsplash/nodogsplash.conf
I am not clear what you are actually trying to do - but you cannot redirect port 443 using Captive Portal Detection - it is specifically designed to use port 80 and is a function of the OS running on the client devices, not Nodogsplash.
It is very simple to redirect ALL clients to your server by redirecting in the splash page and not authenticating at all, not forgetting to add
FirewallRule allow tcp port [your server port] to [your server ip address]
to the FirewallRuleSet preauthenticated-users section of nodogsplash.conf

**Comment by jlcmoore** [comment]
Okay, I'll look into doing that and report back. Thanks for the help!

**Comment by jlcmoore** [comment]
Hi I successfully completed the workarounds that you mentioned and can now properly set up trusted mac addresses, but I am still not sure how to address my other problem. 

That is, I have a proxy server on the local network running at 192.168.1.125:10000
and firewall rules in `/etc/config/firewall` to the effect that all http traffic is redirected to the proxy, but when I run nodogsplash the firewall rules no longer take effect. Is it possible to first force users to authenticate and then, once authenticated, redirect traffic as I have done with the firewall? 

Thanks a bunch.

**Comment by bluewavenet** [comment]
Restarting the firewall will clear the NDS iptables entries, but starting NDS should not have any effect on the firewall settings....
I still do not have it clearly in my head what you are trying to achieve, but it seems to me that you want a transparent proxy to intercept all traffic and thereafter "do" whatever it is you are after.
Try the following:
1. Make sure your proxy is running in transparent mode on port 80.
2. in the workaround /etc/nodogsplash/nodogsplash.conf remove all entries in the FirewallRuleSet preauthenticated-users section thus preventing preauth users from accessing external dns.
3. Configure your NDS router's DHCP to point to your proxy's ip address as its gateway address AND its DNS server.
4. Set your proxy server to manually use an external DNS server if not already doing so.
5. Set your proxy server to reply to DNS requests if not already doing so.
Now, any client coming online will get the gateway and dns server address of your proxy and be able to authenticate through NDS but end up pointing at your proxy server for everything. This is not secure of course and could be overridden after authentication, but I think you are doing this for the purposes of demonstration/training?

**Comment by jlcmoore** [comment]
What I am using is really https://github.com/byt3bl33d3r/MITMf (on 192.168.1.125 port 10000 for http and 53 for dns), which handles http and some dns, but it is not really a proxy.

I am trying to increase the prevalence of http pages by stripping out attempts to establish https connections over http which the mitmf 'proxy' does. 

For some reason, whenever I start nodogsplah, I no longer see any redirected traffic on my machine, despite what you say about nds not having an effect on firewall rules. 

I tried to do what you said, but, possibly because mitmf is not really a proxy, when I try to do step three and set the lan gateway and dns server to 192.168.1.125, I am not able to resolve dns queries and it all seems to loop.

**Comment by jlcmoore** [comment]
My redirect rules seem to be rewritten both from running
`/etc/init.d/nodogsplash start` and `/usr/bin/nodogsplash -c /etc/nodogsplash/nodogsplash.conf`
As soon as I restart the firewall, I see the traffic again on 192.168.125
As soon as I start NDS, I no longer see the redirect traffic on 192.168.1.125

**Comment by bluewavenet** [comment]
Restart the firewall and yes you will see the traffic. Start NDS and the traffic will be blocked until the client authenticates. 
The splash page should be served as soon as the client tries to access any ip on port 80.
This is how it works.

**Comment by jlcmoore** [comment]
Thanks for responding!
Yes that is correct with respect to the behavior of the captive portal, but what I am saying is that enabling no dog splash seems to disable the `config redirect` rules that I have in `/etc/config/firewall`. What can I do if that is the case? I would like both a captive portal and redirection to a transparent proxy.

**Comment by jlcmoore** [comment]
I also tried just executing the following iptables rules (which I think are the relevant ones extracted from `fw3 -d reload 2 ` ) after starting up NDS, but this does not do anything. 
```
iptables -t nat -A zone_lan_prerouting -p tcp -s 192.168.1.125/255.255.255.255 -m tcp --dport 80 -m comment --comment "http to proxy" -j DNAT --to-destination 192.168.1.125:10000
iptables -t nat -A zone_lan_prerouting -p udp -s 192.168.1.125/255.255.255.255 -m udp --dport 80 -m comment --comment "http to proxy" -j DNAT --to-destination 192.168.1.125:10000
iptables -t nat -A zone_lan_postrouting -p tcp -d 192.168.1.125/255.255.255.255 -m tcp --dport 10000 -m comment --comment "wan to proxy" -j SNAT --to-source 192.168.1.1
iptables -t nat -A zone_lan_prerouting -p tcp -s 192.168.1.125/255.255.255.255 -m tcp --dport 53 -m comment --comment "dns to proxy" -j DNAT --to-destination 192.168.1.125:53
iptables -t nat -A zone_lan_prerouting -p udp -s 192.168.1.125/255.255.255.255 -m udp --dport 53 -m comment --comment "dns to proxy" -j DNAT --to-destination 192.168.1.125:53
```

**Comment by bluewavenet** [comment]
Once you start NDS the traffic forwarded to your proxy should indeed stop, this is what NDS does. Clients think they are looking out  and trying to access external ip addresses. As soon as a client authenticates (and reads your notification), that client's traffic should then be redirected to the proxy as it was before NDS started.

**Comment by jlcmoore** [comment]
Hi
I understand that is what is supposed to happen, but that is not what is happening in my case. Even after authenticating clients traffic is not redirected. Given that, what could be causing the discrepancy? 
Thanks!

**Comment by bluewavenet** [comment]
In the NDS config in the FirewallRuleSet authenticated-users section, you should have:
    FirewallRule allow all and nothing else.
If you do not you must explicitly allow the ip and port used by your proxy. I think by default there is a list of ports?

**Comment by bluewavenet** [comment]
The defaults for authenticated users, I think, are:
FirewallRule allow tcp port 53	
FirewallRule allow udp port 53	
FirewallRule allow tcp port 80
FirewallRule allow tcp port 443
FirewallRule allow tcp port 22

Change this to:
FirewallRule allow all
and see what happens.

**Comment by jlcmoore** [comment]
I already had only FirewallRule allow all in `/etc/nodogsplash/nodogsplash.conf`, but I tried also commenting out all lines in `/etc/config/nodogsplash`
Unfortunately, I still don't see the traffic on my 192.168.1.125 machine for authenticated users. 

```
cat /etc/config/nodogsplash
config instance
  # Set to 1 to enable nodogsplash
  option enabled 1

  #option gatewayinterface 'br-lan'
  # Use plain configuration file as well
  option config /etc/nodogsplash/nodogsplash.conf
  option network 'lan'
  #option gatewayname 'vuExposed'
  #option maxclients '20'
  #option idletimeout '360'

  # Your router may have several interfaces, and you
  # probably want to keep them private from the network/gatewayinterface.
  # If so, you should block the entire subnets on those interfaces, e.g.:
  # list authenticated_users 'block to 192.168.0.0/16'
  #list authenticated_users 'block to 10.0.0.0/8'

  # Typical ports you will probably want to open up.
  #list authenticated_users 'allow tcp port 22'
  #list authenticated_users 'allow tcp port 53'
  #list authenticated_users 'allow udp port 53'
  #list authenticated_users 'allow tcp port 80'
  #list authenticated_users 'allow tcp port 443'

  # For preauthenticated users to resolve IP addresses in their
  # initial request not using the router itself as a DNS server,
  #list preauthenticated_users 'allow tcp port 53'
  #list preauthenticated_users 'allow udp port 53'

  # Allow ports for SSH/Telnet/DNS/DHCP/HTTP/HTTPS
  #list users_to_router 'allow tcp port 22'
  #list users_to_router 'allow tcp port 23'
  #list users_to_router 'allow tcp port 53'
  #list users_to_router 'allow udp port 53'
  #list users_to_router 'allow udp port 67'
  #list users_to_router 'allow tcp port 80'
  #list users_to_router 'allow tcp port 443'

  # See https://github.com/nodogsplash for a full list of available options.
```

```
cat /etc/nodogsplash/nodogsplash.conf 
#
# Nodogsplash Configuration File
#

# Parameter: GatewayInterface
# Default: NONE
#
# GatewayInterface is not autodetected, has no default, and must be set here.
# Set GatewayInterface to the interface on your router
# that is to be managed by Nodogsplash.
# Typically br0 for the wired and wireless lan on OpenWrt White Russian.
# May be br-lan on OpenWrt Kamikaze.
#
GatewayInterface br-lan

# FirewallRuleSet authenticated-users
#
# Control access for users after authentication.
# These rules are inserted at the beginning of the
# FORWARD chain of the router's filter table, and
# apply to packets that have come in to the router
# over the GatewayInterface from MAC addresses that
# have authenticated with Nodogsplash, and that are
# destined to be routed through the router. The rules are
# considered in order, and the first rule that matches
# a packet applies to it.
# If there are any rules in this ruleset, an authenticated
# packet that does not match any rule is rejected.
# N.B.: This ruleset is completely independent of
# the preauthenticated-users ruleset.
#
FirewallRuleSet authenticated-users {

 # You may want to open access to a machine on a local
 # subnet that is otherwise blocked (for example, to
 # serve a redirect page; see RedirectURL). If so,
 # allow that explicitly here, e.g:
 # FirewallRule allow tcp port 80 to 192.168.254.254

 # Your router may have several interfaces, and you
 # probably want to keep them private from the GatewayInterface.
 # If so, you should block the entire subnets on those interfaces, e.g.:
    #FirewallRule block to 192.168.0.0/16
    #FirewallRule block to 10.0.0.0/8

 # Typical ports you will probably want to open up include
 # 53 udp and tcp for DNS,
 # 80 for http,
 # 443 for https,
 # 22 for ssh:
    #FirewallRule allow tcp port 53
    #FirewallRule allow udp port 53
    #FirewallRule allow tcp port 80
    #FirewallRule allow tcp port 443
    #FirewallRule allow tcp port 22
    FirewallRule allow all

}
# end FirewallRuleSet authenticated-users


# FirewallRuleSet: preauthenticated-users
#
# Control access for users before authentication.
# These rules are inserted in the PREROUTING chain
# of the router's nat table, and in the
# FORWARD chain of the router's filter table.
# These rules apply to packets that have come in to the
# router over the GatewayInterface from MAC addresses that
# are not on the BlockedMACList or TrustedMACList,
# are *not* authenticated with Nodogsplash. The rules are
# considered in order, and the first rule that matches
# a packet applies to it. A packet that does not match
# any rule here is rejected.
# N.B.: This ruleset is completely independent of
# the authenticated-users and users-to-router rulesets.
#
FirewallRuleSet preauthenticated-users {
 # For preauthenticated users to resolve IP addresses in their initial
 # request not using the router itself as a DNS server,
 # you probably want to allow port 53 udp and tcp for DNS.
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 53
 # For splash page content not hosted on the router, you
 # will want to allow port 80 tcp to the remote host here.
 # Doing so circumvents the usual capture and redirect of
 # any port 80 request to this remote host.
 # Note that the remote host's numerical IP address must be known
 # and used here.
 # FirewallRule allow tcp port 80 to 123.321.123.321
}
# end FirewallRuleSet preauthenticated-users


# FirewallRuleSet: users-to-router
#
# Control access to the router itself from the GatewayInterface.
# These rules are inserted at the beginning of the
# INPUT chain of the router's filter table, and
# apply to packets that have come in to the router
# over the GatewayInterface from MAC addresses that
# are not on the TrustedMACList, and are destined for
# the router itself. The rules are
# considered in order, and the first rule that matches
# a packet applies to it.
# If there are any rules in this ruleset, a
# packet that does not match any rule is rejected.
#
FirewallRuleSet users-to-router {
 # Nodogsplash automatically allows tcp to GatewayPort,
 # at GatewayAddress, to serve the splash page.
 # However you may want to open up other ports, e.g.
 # 53 for DNS and 67 for DHCP if the router itself is
 # providing these services.
    FirewallRule allow udp port 53
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 67
 # You may want to allow ssh, http, and https to the router
 # for administration from the GatewayInterface. If not,
 # comment these out.
    FirewallRule allow tcp port 22
    FirewallRule allow tcp port 23
    FirewallRule allow tcp port 80
    FirewallRule allow tcp port 443
}
# end FirewallRuleSet users-to-router

# EmptyRuleSetPolicy directives
# The FirewallRuleSets that NoDogSplash permits are:
#
# authenticated-users
# preauthenticated-users
# users-to-router
# trusted-users
# trusted-users-to-router
#
# For each of these, an EmptyRuleSetPolicy can be specified.
# An EmptyRuleSet policy applies to a FirewallRuleSet if the
# FirewallRuleSet is missing from this configuration file,
# or if it exists but contains no FirewallRules.
#
# The possible values of an EmptyRuleSetPolicy are:
# allow -- packets are accepted
# block -- packets are rejected
# passthrough -- packets are passed through to pre-existing firewall rules
#
# Default EmptyRuleSetPolicies are set as follows:
# EmptyRuleSetPolicy authenticated-users passthrough
# EmptyRuleSetPolicy preauthenticated-users block
# EmptyRuleSetPolicy users-to-router block
# EmptyRuleSetPolicy trusted-users allow
# EmptyRuleSetPolicy trusted-users-to-router allow


# Parameter: GatewayName
# Default: NoDogSplash
#
# Set GatewayName to the name of your gateway. This value
# will be available as variable $gatewayname in the splash page source
# and in status output from ndsctl, but otherwise doesn't matter.
# If none is supplied, the value "NoDogSplash" is used.
#
GatewayName vuExposed

# Parameter: GatewayAddress
# Default: Discovered from GatewayInterface
#
# This should be autodetected on an OpenWRT system, but if not:
# Set GatewayAddress to the IP address of the router on
# the GatewayInterface. This is the address that the Nodogsplash
# server listens on.
#
# GatewayAddress 192.168.1.1

# Parameter: ExternalInterface
# Default: Autodetected from /proc/net/route
#
# This should be autodetected on a OpenWRT system, but if not:
# Set ExtrnalInterface to the 'external' interface on your router,
# i.e. the one which provides the default route to the internet.
# Typically vlan1 for OpenWRT.
#
# ExternalInterface vlan1

# Parameter: RedirectURL
# Default: none
#
# After authentication, normally a user is redirected
# to their initially requested page.
# If RedirectURL is set, the user is redirected to this URL instead.
#
RedirectURL https://jlcmoore.github.io/vuExposed

# Parameter: GatewayPort
# Default: 2050
#
# Nodogsplash's own http server uses GatewayAddress as its IP address.
# The port it listens to at that IP can be set here; default is 2050.
#
# GatewayPort 2050

# Parameter: MaxClients
# Default: 20
#
# Set MaxClients to the maximum number of users allowed to
# connect at any time. (Does not include users on the TrustedMACList,
# who do not authenticate.)
#
# MaxClients 20

# ClientIdleTimeout
# Parameter: ClientIdleTimeout
# Default: 10
#
# Set ClientIdleTimeout to the desired of number of minutes
# of inactivity before a user is automatically 'deauthenticated'.
#
ClientIdleTimeout 10

# Parameter: ClientForceTimeout
# Default: 360
#
# Set ClientForceTimeout to the desired number of minutes before
# a user is automatically 'deauthenticated', whether active or not
#
ClientForceTimeout 10

# Parameter: AuthenticateImmediately
# Default: no
#
# Set to yes (or true or 1), to immediately authenticate users
# who make a http port 80 request on the GatewayInterface (that is,
# do not serve a splash page, just redirect to the user's request,
# or to RedirectURL if set).
#
# AuthenticateImmediately no

# Parameter: MACMechanism
# Default: block
#
# Either block or allow.
# If 'block', MAC addresses on BlockedMACList are blocked from
# authenticating, and all others are allowed.
# If 'allow', MAC addresses on AllowedMACList are allowed to
# authenticate, and all other (non-trusted) MAC's are blocked.
#
# MACMechanism block

# Parameter: BlockedMACList
# Default: none
#
# Comma-separated list of MAC addresses who will be completely blocked
# from the GatewayInterface. Ignored if MACMechanism is allow.
# N.B.: weak security, since MAC addresses are easy to spoof.
#
# BlockedMACList 00:00:DE:AD:BE:EF,00:00:C0:1D:F0:0D

# Parameter: AllowedMACList
# Default: none
#
# Comma-separated list of MAC addresses who will not be completely
# blocked from the GatewayInterface. Ignored if MACMechanism is block.
# N.B.: weak security, since MAC addresses are easy to spoof.
#
# AllowedMACList 00:00:12:34:56:78

# Parameter: TrustedMACList
# Default: none
#
# Comma-separated list of MAC addresses who are not subject to
# authentication, and are not restricted by any FirewallRuleSet.
# N.B.: weak security, since MAC addresses are easy to spoof.
#
TrustedMACList <MAC_ADDRESS>


# Parameter: PasswordAuthentication
# Default: no
# Set to yes (or true or 1), to require a password matching
# the Password parameter to be supplied when authenticating.
#
#
# PasswordAuthentication no

# Parameter: Password
# Default: none
# Whitespace delimited string that is compared to user-supplied
# password when authenticating.
#
#
# Password nodog

# Parameter: UsernameAuthentication
# Default: no
# Set to yes (or true or 1), to require a username matching
# the Username parameter to be supplied when authenticating.
#
#
# UsernameAuthentication no

# Parameter: Username
# Default: none
# Whitespace delimited string that is compared to user-supplied
# username when authenticating.
#
#
# Username guest

# Parameter: PasswordAttempts
# Default: 5
# Integer number of failed password/username entries before
# a user is forced to reauthenticate.
#
#
# PasswordAttempts 5

# Parameter: TrafficControl
# Default: no
#
# Set to yes (or true or 1), to enable traffic control in Nodogsplash.
#
# TrafficControl no

# Parameter: DownloadLimit
# Default: 0
#
# If TrafficControl is enabled, this sets the maximum download
# speed to the GatewayInterface, in kilobits per second.
# For example if you have an ADSL connection with 768 kbit
# download speed, and you want to allow about half of that
# bandwidth for the GatewayInterface, set this to 384.
# A value of 0 means no download limiting is done.
#
# DownloadLimit 384

# Parameter: UploadLimit
# Default: 0
#
# If TrafficControl is enabled, this sets the maximum upload
# speed from the GatewayInterface, in kilobits per second.
# For example if you have an ADSL connection with 128 kbit
# upload speed, and you want to allow about half of that
# bandwidth for the GatewayInterface, set this to 64.
# A value of 0 means no upload limiting is done.
#
# UploadLimit 64

# Paramter: GatewayIPRange
# Default: 0.0.0.0/0
#
# By setting this parameter, you can specify a range of IP addresses
# on the GatewayInterface that will be responded to and managed by
# Nodogsplash. Addresses outside this range do not have their packets
# touched by Nodogsplash at all.
# Defaults to 0.0.0.0/0, that is, all addresses.
#
# GatewayIPRange 0.0.0.0/0
```

**Comment by jlcmoore** [comment]
I've also tried putting my test computer on the trusted list with `ndsctl trust <TEST_MACHINE_MAC>` but I don't see its traffic on the proxy machine with that either.
```
ndsctl status
==================
NoDogSplash Status
====
Version: 0.9_beta9.9.9
Uptime: 0d 0h 6m 29s
Gateway Name: vuExposed
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: 192.168.1.1:2050
Splashpage: /etc/nodogsplash/htdocs/splash.html
Redirect URL: https://jlcmoore.github.io/vuExposed
Traffic control: no
Total download: 0 kByte; avg: 0 kbit/s
Total upload: 0 kByte; avg: 0 kbit/s
====
Client authentications since start: 1
Current clients: 1

Client 0
  IP: 192.168.1.241 MAC: <TEST_MACHINE_MAC>
  Added:   Wed Aug  9 15:07:17 2017
  Active:  Wed Aug  9 15:09:03 2017
  Active duration: 0d 0h 1m 46s
  Added duration:  0d 0h 6m 14s
  Token: a6659396
  State: Authenticated
  Download: 5012 kByte; avg: 107.218 kbit/s
  Upload:   150 kByte; avg: 3.22518 kbit/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses:
  <PROXY_MACHINE_MAC>
========
```

**Comment by jlcmoore** [comment]
I've tried to compare the iptables rules with nodogsplash active and not, but I can't figure out how to properly read the files. I'm inclined to think that th issue is something to do with the prerouting nature of the redirect rules and the fact that they are triggered later than nds rules. 

[iptables_rules_without_nds.txt](https://github.com/nodogsplash/nodogsplash/files/1212894/rules.txt)
[iptables_rules_with_nds.txt](https://github.com/nodogsplash/nodogsplash/files/1212895/rules_nds.txt)
[diff.txt](https://github.com/nodogsplash/nodogsplash/files/1212899/diff.txt)

**Comment by cilix-lab** [comment]
@jlcmoore did you ever figure this out? I’m having the same issue. NDS is supposed to pass-through my authenticated clients to the previously set firewall rules, but the redirection stops working if NDS is up.  

Just to be clear:  
* NDS down, iptables rules set: clients go through proxy.  
* NDS up, iptables rules previously set, clients are redirected to splash page -> authenticate -> proxy redirection rules are disregarded.

**Comment by bluewavenet** [comment]
@cilix-lab 
Is it not just a case of the first match in the firewall rules is always NDS?
Have you tried setting the default gateway on your NDS machine to point at your proxy so all traffic goes through it?

**Comment by cilix-lab** [comment]
Thanks for your reply. I’m guessing that’s the issue here, since NDS will input its rules and that’s ok. But when set up to “pass-through” authenticated clients, the documentation says it’s supposed to behave as if no NDS rules are being applied, so previously defined rules apply only. 

That said, since redirection will work before starting NDS, I’m guessing there’s still an NDS rule that will match after authentication, letting the clients forward through WAN and never matching the redirection. 

I’ll try to figure it out trying to make sense of all the rules that are input by NDS and post my conclusions.

**Comment by jlcmoore** [comment]
Hiya. Unfortunately, I was not able to figure out this issue myself and had to give up on redirection.

**Comment by bluewavenet** [comment]
Interesting, It works well this things like mwan3 and sqm.
Has anyone tried setting the default gateway?

**Comment by cilix-lab** [comment]
Finally found it!!!  

So... trying to make sense of all the iptables rules in the NDS chains, I realized that the problem was in the ndsOUT chain, since instead of doing iptables -j RETURN when the client is authorized/trusted, it does -j ACCEPT, stopping the chain there.  

From iptables-save:  
```
(...)
-A ndsOUT -m mark --mark 0x200/0x700 -j ACCEPT
-A ndsOUT -m mark --mark 0x400/0x700 -j ACCEPT
-A ndsOUT -p udp -m udp --dport 53 -j ACCEPT
-A ndsOUT -p tcp -m tcp --dport 80 -j DNAT --to-destination 172.16.7.254:2050
-A ndsOUT -j ACCEPT
(...)
```
You can see there that instead of doing RETURN to evaluate the rest of the iptables rules, it ACCEPTS. Is this the expected behaviour? Shouldn't it be RETURN??

**Comment by bluewavenet** [comment]
@cilix-lab 
You might be onto something there. Should ALL the ACCEPTs in your example be RETURNs?

**Comment by bluewavenet** [comment]
@cilix-lab 
Check the output of: iptables -L ndsOUT -t nat

Count the number of lines starting at "1"
The last line should be: ACCEPT     all  --  anywhere             anywhere 
In your example above this will be line 5 I think.
Enter the command (replacing the "5" with the actual line count if different):
iptables -R ndsOUT 5 -j RETURN -t nat 

Now try!

If this works it would be possible to write a script to count the lines and get the rule number and update iptables as NDS starts, as a temporary work around, and we can do a PR to fix.

**Comment by bluewavenet** [comment]
A few quick tests and I think the first two rules should also be RETURN.

**Comment by cilix-lab** [comment]
Yep. That works. I've put a script together to modify the first two rules (accepted and trusted) and it's run after 3 seconds of NDS being restarted.  

I'm guessing the last rule should also be RETURN, though only modifying the first two works as expected for my scenario. Now my `iptables -L ndsOUT -t nat` output looks like:  

```
Chain ndsOUT (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere             mark match 0x200/0x700
RETURN     all  --  anywhere             anywhere             mark match 0x400/0x700
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
DNAT       tcp  --  anywhere             anywhere             tcp dpt:http to:172.16.7.254:2050
ACCEPT     all  --  anywhere             anywhere 
```

**Comment by cilix-lab** [comment]
My script:  

```
#!/bin/bash

LAST=$((`iptables -t nat -L ndsOUT | wc -l`-2))
for r in 1 2 $LAST; do
        iptables -t nat -R ndsOUT $r -j RETURN
done

exit 0
```
