### ISSUE TITLE
username and password not working

### ISSUE THREAD

**Issue by haryows** [nodogsplash/nodogsplash#198]
I already instal nodogsplash n tryin to make captive login with password and username.
but when I already set the password in nodogsplasg.conf and change splash.html ,every single word u write in username and password, it can make authentic user.
i already try step in this page : https://github.com/nodogsplash/nodogsplash/issues/126 but still not work

im using 
openwrt-15.05.1-ar71xx-generic-tl-wr740n-v4-squashfs-sysupgrade
nodogsplash_0.9_beta9.9.8-2_ar71xx

**Comment by haryows** [comment]
CC: @bluewavenet can u help me?

**Comment by bluewavenet** [comment]
Version 0.9_beta9.9.8-2 is very old and actually broken.
The version available to download with OpenWrt  15.05.1 is 0.9_beta9.9.9-5 and does work very well although there are some config issues, worked around in #126
From memory the username/password authentication does work in 9.9.9-5 but is very limited with only one username/password possible.

**Comment by mwarning** [comment]
Maybe try this newer image that comes with a newer NDS package in its package feed:
http://downloads.lede-project.org/releases/17.01.2/targets/ar71xx/generic/lede-17.01.2-ar71xx-generic-tl-wr740n-v4-squashfs-sysupgrade.bin

**Comment by haryows** [comment]
@bluewavenet thx for ur answer sir, i will try it. but how abt nodogslash 2.0.0? there is some bug in there?

**Comment by haryows** [comment]
@mwarning thx sir, i will try it.

**Comment by tbeiei** [comment]
i use openwrt chaos_calmer/15.05.1/ and This is nodogsplash version 0.9_beta9.9.9

but i can't setting authen 

every single word u write in username and password, it can make authentic user.

config instance                                                                                                                                                                                                    
  # Set to 1 to enable nodogsplash                                                                                                                                                                                 
  option enabled 1                                                                                                                                                                                                 
                                                                                                                                                                                                          
authenticateimmediately 0                                                                                                                                                                                          
UsernameAuthentication yes                                                                                                                                                                                         
Username guest                                                                                                                                                                                                     
PasswordAuthentication yes                                                                                                                                                                                         
Password pass                                                                                                                                                                                                      
                                                                                                                                                                                                                   
  # Use plain configuration file as well                                                                                                                                                                           
  #option config '/etc/nodogsplash/nodogsplash.conf'                                                                                                                                                               
  option network 'lan'                                                                                                                                                                                             
  option gatewayname 'OpenWrt Nodogsplash'                                                                                                                                                                         
  option maxclients '250'                                                                                                                                                                                          
  option idletimeout '1200'                                                                                                                                                                                        
                                                                                                                                                                                                                   
  # Your router may have several interfaces, and you                                                                                                                                                               
  # probably want to keep them private from the network/gatewayinterface.                                                                                                                                          
  # If so, you should block the entire subnets on those interfaces, e.g.:                                                                                                                                          
  list authenticated_users 'block to 192.168.0.0/16'                                                                                                                                                               
  list authenticated_users 'block to 10.0.0.0/8'                                                                                                                                                                   
                                                                                                                                                                                                                   
  # Typical ports you will probably want to open up.                                                                                                                                                               
  list authenticated_users 'allow tcp port 22'                                                                                                                                                                     
  list authenticated_users 'allow tcp port 53'                                                                                                                                                                     
  list authenticated_users 'allow udp port 53'                                                                                                                                                                     
  list authenticated_users 'allow tcp port 80'                                                                                                                                                                     
  list authenticated_users 'allow tcp port 443'                                                                                                                                                                    
                                                                                                                                                                                                                   
  # For preauthenticated users to resolve IP addresses in their                                                                                                                                                    
  # initial request not using the router itself as a DNS server,                                                                                                                                                   
  list preauthenticated_users 'allow tcp port 53'                                                                                                                                                                  
  list preauthenticated_users 'allow udp port 53'                                                                                                                                                                  
                                                                                                                                                                                                                   
  # Allow ports for SSH/Telnet/DNS/DHCP/HTTP/HTTPS                                                                                                                                                                 
  list users_to_router 'allow tcp port 22'                                                                                                                                                                         
  list users_to_router 'allow tcp port 23'                                                                                                                                                                         
  list users_to_router 'allow tcp port 53'                                                                                                                                                                         
  list users_to_router 'allow udp port 53'                                                                                                                                                                         
  list users_to_router 'allow udp port 67'                                                                                                                                                                         
  list users_to_router 'allow tcp port 80'                                                                                                                                                                         
  list users_to_router 'allow tcp port 443'                                                                                                                                                                        
                                                                                                                                                                                                                   
  # See https://github.com/nodogsplash for a full list of available options.   

and splash.html

<form method='GET' action='$authaction'>                                       
<input type='hidden' name='tok' value='$tok'>                                  
<input type='hidden' name='redir' value='$redir'>                              
username: <input type='text' name='nodoguser' value='' size='12' maxlength='12'
<br>                                                                           
password: <input type='password' name='nodogpass' value='' size='12' maxlength=
<br>                                                                           
<input type='submit' value='Enter'>                                            
</form>     


help me pls sir @bluewavenet  @mwarning

**Comment by tbeiei** [comment]
i use openwrt chaos_calmer/15.05.1/ and This is nodogsplash version 0.9_beta9.9.9

but i can't setting authen

every single word u write in username and password, it can make authentic user.

config instance                                                                                                                                                                                                    
  # Set to 1 to enable nodogsplash                                                                                                                                                                                 
  option enabled 1                                                                                                                                                                                                 
                                                                                                                                                                                                                   
passwordauthentication yes                                                                                                                                                                                         
usernameauthentication yes                                                                                                                                                                                         
username guest                                                                                                                                                                                                     
password pass                                                                                                                                                                                                      
authenticateimmediately 0                                                                                                                                                                                          
UsernameAuthentication yes                                                                                                                                                                                         
Username guest                                                                                                                                                                                                     
PasswordAuthentication yes                                                                                                                                                                                         
Password pass                                                                                                                                                                                                      
                                                                                                                                                                                                                   
  # Use plain configuration file as well                                                                                                                                                                           
  #option config '/etc/nodogsplash/nodogsplash.conf'                                                                                                                                                               
  option network 'lan'                                                                                                                                                                                             
  option gatewayname 'OpenWrt Nodogsplash'                                                                                                                                                                         
  option maxclients '250'                                                                                                                                                                                          
  option idletimeout '1200'                                                                                                                                                                                        
                                                                                                                                                                                                                   
  # Your router may have several interfaces, and you                                                                                                                                                               
  # probably want to keep them private from the network/gatewayinterface.                                                                                                                                          
  # If so, you should block the entire subnets on those interfaces, e.g.:                                                                                                                                          
  list authenticated_users 'block to 192.168.0.0/16'                                                                                                                                                               
  list authenticated_users 'block to 10.0.0.0/8'                                                                                                                                                                   
                                                                                                                                                                                                                   
  # Typical ports you will probably want to open up.                                                                                                                                                               
  list authenticated_users 'allow tcp port 22'                                                                                                                                                                     
  list authenticated_users 'allow tcp port 53'                                                                                                                                                                     
  list authenticated_users 'allow udp port 53'                                                                                                                                                                     
  list authenticated_users 'allow tcp port 80'                                                                                                                                                                     
  list authenticated_users 'allow tcp port 443'                                                                                                                                                                    
                                                                                                                                                                                                                   
  # For preauthenticated users to resolve IP addresses in their                                                                                                                                                    
  # initial request not using the router itself as a DNS server,                                                                                                                                                   
  list preauthenticated_users 'allow tcp port 53'                                                                                                                                                                  
  list preauthenticated_users 'allow udp port 53'                                                                                                                                                                  
                                                                                                                                                                                                                   
  # Allow ports for SSH/Telnet/DNS/DHCP/HTTP/HTTPS                                                                                                                                                                 
  list users_to_router 'allow tcp port 22'                                                                                                                                                                         
  list users_to_router 'allow tcp port 23'                                                                                                                                                                         
  list users_to_router 'allow tcp port 53'                                                                                                                                                                         
  list users_to_router 'allow udp port 53'                                                                                                                                                                         
  list users_to_router 'allow udp port 67'                                                                                                                                                                         
  list users_to_router 'allow tcp port 80'                                                                                                                                                                         
  list users_to_router 'allow tcp port 443'     

and splash html
''<form method='GET' action='$authaction'>                                       
<input type='hidden' name='tok' value='$tok'>                                  
<input type='hidden' name='redir' value='$redir'>                              
username: <input type='text' name='nodoguser' value='' size='12' maxlength='12'
<br>                                                                           
password: <input type='password' name='nodogpass' value='' size='12' maxlength=
<br>                                                                           
<input type='submit' value='Enter'>                                            
</form>''          

thank 
help me pls @bluewavenet  @mwarning

**Comment by tbeiei** [comment]
@haryows u can working ?

**Comment by haryows** [comment]
@tbeiei yes dude
