### ISSUE TITLE
V2 on LEDE - 404 error on CPD

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#199]
On LEDE version 2 installs the splash page files in /etc/nodogsplash2/ but libmicrohttpd expects /etc/nodogsplash/

Workaround is to rename /etc/nodogsplash2 to /etc/nodogsplash

**Comment by mwarning** [comment]
@bluewavenet thanks for the hint. I will fix it.

**Comment by mwarning** [comment]
See https://github.com/openwrt-routing/packages/pull/317
