### ISSUE TITLE
V2 - "$" char in splash.html

### ISSUE THREAD

**Issue by atken** [nodogsplash/nodogsplash#201]
Hi,
why version 2.0 deletes  **all** "$" symbols and not just for variables like in lower version?

**Comment by bluewavenet** [comment]
Try putting `&#36;`  in your non-variable text instead of the $ character and let us know what happens.

**Comment by atken** [comment]
I'm sorry for really late reply. Ascii works well. In case of use jquery short $, i used long prefix 'jQuery'. 
**Btw.** I don't know if I should create new topic. So i write here.
I would like to send token from C via POST to server, before rendering page. 
In which file should i write code?
