### ISSUE TITLE
Version 2 - Invalid Token error not processed.

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#202]
reference #200 
Version 2 does not serve infoskel.html on invalid token.
This has the potential to break authentication if GET authaction is used externally to splash.html.
Splash.html provides $authaction, $tok and $redir; essential for returning to NDS with a form get.
Version 2 does not trap invalid tokens like version 1 did, instead it just returns to splash.html with a new token. If splash.html in turn redirects to an external (to NDS) html page for authentication processing and the token times out before returning, then the "bounce" back to splash.html will return the externally supplied authaction url (including its get parameters). This will contain not only the new token but also the old eg two instances of &tok= , the last being the invalid token. As html get picks up the LAST instance of a parameter in a get, authentication will fail again, resulting in a loop.
@lynxis @mwarning was this a deliberate change in coding or is it a bug?

**Comment by mwarning** [comment]
I think this was an oversight.

**Comment by bluewavenet** [comment]
@mwarning 
In version 1 it is in http.c as http_nodogsplash_serve_info
Version 2 has check_token_is_valid in  http_microhttpd.c but there is no reference to serving infoskel.
I guess it is more than a bug, more like missing functionality. My c is not up to the job unfortunately at least not without spending a lot of time on it, otherwise I would have a close look. Happy to help in any other way.

**Comment by bluewavenet** [comment]
**Workaround**
If working with external splash authentication, a workaround is to append a token check in the GET query string on returning to NDS, for example &amp;tokchk=true . In version 2, if the token is invalid (eg expired) this can be checked for on entry into your authentication code. If found this means you are in a loop triggered by an invalid token and allows you to detect the loop and break out of it.

**Comment by bluewavenet** [comment]
@lynxis 
I just found in release notes:
"redirect wrong token auths to the splashpage [lynxis]"
Was this to fix something else? Just wondering. It did cause me a few minor problems but I am happy with my workaround. ;-)
