### ISSUE TITLE
Does not work on Raspbian

### ISSUE THREAD

**Issue by sekrett** [nodogsplash/nodogsplash#208]
Any example of config file would be nice. The daemon starts without warnings, `ndsctl status` appears to be ok, but I don't see the AP on wifi client. Logs are silent. Have no idea what to do. Tried on v2.0, 1.0.2 and master.

**Comment by sekrett** [comment]
Please give a short answer. The phrase "The default installed configuration may be all you need, though." is referring to OpenWRT on is good for Debian also? In other words do I need some extra software on Debian like hostapd, dnsmasq or everything should be managed by nodogsplash?

**Comment by bluewavenet** [comment]
Nodogsplash requires to be installed on a device set up as a router.
So yes, you need all the things required to make a router eg. Wan connection, Lan connection (including WiFi support if you require it) as well as routing software.

**Comment by sekrett** [comment]
Thanks. I understood it later and finally I got it working. The most difficult part was to understand that I need to add one NAT MASQUERADE rule to iptables, because it may look like nodogsplash manages NAT but it creates NAT rules for other purposes.

Maybe a little paragraph in documentation would be great and even better two examples, one with NAT and another with bridged interface. Another option is to create a Chef cookbook which configures the routes and installs nodogsplash. Let's see if I can find time for that. Great software you did btw.

**Comment by bluewavenet** [comment]
@sekrett Glad you got it working.
Your suggestions are more fundamentals of routing configuration and outside the normal scope of NDS but feel free to put forward any additions to documentation.
