### ISSUE TITLE
How to include external resources before authentication

### ISSUE THREAD

**Issue by abitbul6** [nodogsplash/nodogsplash#214]
I want to include CDN's (such as jquery and bootstrap) and external images from a specific domains from the web (such as storage.google.com) in my splash.html file.
How can I configure the NDS configuration file to support it?

Thank you

**Comment by bluewavenet** [comment]
You can create an IP address based "Walled Garden" in NDS, but usually the NDS hosted splash page is intended to provide either directly or indirectly a means of authentication.
Perhaps take a look at the NDS Forwarding Authentication.
https://github.com/nodogsplash/nodogsplash/tree/master/forward_authentication_service
You could use this and on an external server use curl or even wget to relay web content to the NDS clients.
