### ISSUE TITLE
[Solved] MWAN3: Stops NoDogSplash from working.

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#218]
This happens with NDS v1 and v2 and is similar to the very old problem described in:
https://wiki.openwrt.org/doc/howto/mwan3
However is not fixed by changing the NDS marking flags.
Tested on a Ubiquiti EdgeRouterX with LEDE 17.01.04 and the latest version of MWAN3 (2.6.9).

**Comment by mwarning** [comment]
:-(

**Comment by bluewavenet** [comment]
Yes :-(
I will do a bit more work on this as time allows. Hopefully fairly quickly.

**Comment by bluewavenet** [comment]
@mwarning 
I have tried this on a Ubiquiti ERX (mt7621 chipset) and a GL-iNet MT300A (mt7620 chipset) and am coming to the conclusion it is an issue with vlan tagging in the chipsets or drivers... More work required. Next I will try on an ar71xx device probably over the weekend.

**Comment by mwarning** [comment]
.. so, the change of the firewall markers had no effect?

**Comment by bluewavenet** [comment]
It had no effect. NDS immediately starts working as soon as mwan3 is stopped.
I want to try on a non-mt76 device as some other strange things are happening not NDS related.

**Comment by mwarning** [comment]
Why did you change it in the nds openwrt package then? https://github.com/openwrt-routing/packages/commit/5e96695d523c7c9397033391fe065bb6434d80bb#diff-cd08efd370f3d294e2b392f07cb0263dR65

**Comment by bluewavenet** [comment]
For compatibility with other things as well such as sqm-scripts. I think the problem with mwan3 will be fixed also so will be needed for that as well. It causes no problems when changed and also gives information by way of example.

**Comment by bluewavenet** [comment]
If you feel uneasy about the changes to the OpenWrt package we can make them commented out. The main purpose is to show by example as well as make it work "out of the box".

**Comment by bluewavenet** [comment]
@mwarning 
Finally I have spent some time on this and got it working.
The issue was to do with how mwan3 handles the fw_mark mask.
The latest mwan3 2.6.11-2 when I tried it, failed to load, I then spent some time debugging its scripts
Now I can make it start and see how it has changed since its version 1, it was a fairly simple job to prevent clashes with NDS.
I will do a pull request for NDS to fix at our end. I have already done one for mwan3.
I have been testing with a GL-AR300M-EXT, LEDE 170104 and NDS v 1.0.1
Version 2 should be ok too, will shortly test.

**Comment by bluewavenet** [comment]
To make it work with mwan3 2.6.11-2, we need to modify the config files for both mwan3 and nds.
In /etc/config/nodogsplash:
list fw_mark_authenticated '30000'
list fw_mark_trusted '20000'
list fw_mark_blocked '10000'

and in /etc/config/mwan3:
config globals 'globals'
	option enabled '1'
