### ISSUE TITLE
Client state Authenticated but Webpage not opening

### ISSUE THREAD

**Issue by souravndp** [nodogsplash/nodogsplash#219]
I am using NoDogSplash (version 0.9_beta9.9.9) on my GL-INET AR150 running OpenWRT (Chaos Calmer, r47065). But I am facing some problem after authentication.

==steps==
1. stop the firewall
2. start NDS (default config. edited "option enabled 1" and commented out "'list authenticated_users 'block to 192.168.0.0/16'")
3. Connected to the wifi SSID

==observations==
1. The captive portal splash page is automatically opened by client network manager
2. 'ndsctl status' and 'ndsctl clients' is showing the client state as 'Preauthenticated'
3. Clicked the splash icon
4. 'ndsctl status' and 'ndsctl clients' is showing the client state as 'Authenticated'
5. But no webpage is opening. Browser error 'taking too long to respond'

I tried to see the 'mangle' table and noticed that new rule has been added. **I then tried to do all the above steps after setting log level to 7. the log can be found [here](https://gist.github.com/souravndp/f69dbca2bb16b7a1e7d835d7e2d1addb)**

## If I stop NDS and restart the firewall, web pages are opening again. So, There is no problem in the internet connection.

Can anyone please help? I have attached some iptables table screenshots (after authentication) below. Thank you.

## table mangle

![mangle](https://user-images.githubusercontent.com/652191/34905058-2b9e640a-f877-11e7-9fe2-722a471ee151.PNG)

## table nat

![nat](https://user-images.githubusercontent.com/652191/34905061-39a0ca8e-f877-11e7-8407-838e409b09cb.PNG)

## table filter

![filter](https://user-images.githubusercontent.com/652191/34905066-46ed7ce6-f877-11e7-96c4-2ac8aec8d56e.PNG)

## packets count against different rules in filter table

![packet count](https://user-images.githubusercontent.com/652191/34905090-ccc1f130-f877-11e7-92bd-73e8d2a83f75.PNG)

**Comment by bluewavenet** [comment]
@souravndp 
This looks like a commonly recurring misconfiguration issue and is most likely something simple.

Why have you stopped the firewall? Starting it again will prevent NDS from working at all. Normally the firewall needs to be running before NDS is started.

However I would advise you to use LEDE 1(Openwrt)7.01.04 instead on your AR150 at it is fully supported there.
Download from here:
https://downloads.lede-project.org/releases/17.01.4/targets/ar71xx/generic/lede-17.01.4-ar71xx-generic-gl-ar150-squashfs-sysupgrade.bin

This will give you NDS version 1 by default and this has a lot of fixes over the beta version.

However, better still download the latest release of NDS (v2.0.1-1) .
This works very well with the 17.01.4 OS, in fact should work straight away without having to change any configurations. 
Download  from here:
https://downloads.lede-project.org/snapshots/packages/mips_24kc/routing/nodogsplash2_2.0.1-1_mips_24kc.ipk

Let us know how you get on :-)

**Comment by souravndp** [comment]
1. Thank you @bluewavenet for your prompt response. And Yes, keeping the firewall enabled before starting NDS solved the issue. I think the misconception came from [OpenWRT wiki:](https://wiki.openwrt.org/doc/howto/wireless.hotspot.nodogsplash)

> Because nodogsplash uses iptables to mark/handle packets, you have to turn off the built-in firewall:
>/etc/init.d/firewall stop
>/etc/init.d/firewall disable

However, I had mwan3 installed and the splash page didn't work. Internet connectivity was working fine even without authentication. Then I remembered the issue you posted some days ago and removed mwan3. NDS started working. So, I second the fact that NDS is not working with mwan3.

2. I understand that my version is the beta version and it has lots of bugs. Migrating to LEDE will help to get the latest NDS. But GL-INET has another interface above Luci and I find it useful sometimes. (eg: in Luci, searching for available package returns installed packages too with a link to install them. suppose, I search with the string 'luci-app-*' but looking at the results, there is no way to know which packages are already installed and which are not installed. But in Gl-inet interface, installed packages are marked as installed. Moreover, I find it easier to setup OpenVPN on Gl-inet interface. I just need to import the .opvn file. OpenVPN setup on Luci seems complicated. I think you know OpenWRT system very well, so, can you please suggest a good tutorial to setup OpenVPN from the Luci interface? ie, luci-app-openvpn. The interface seems complicated. Will the command `sudo openvpn --config /path/to/config.ovpn` work on OpenWRT too? Then I don't have to bother about the Web UI) However, thanks for pointing me to LEDE, I will definitely try that in future.

3. Do you have any compiled .ipk of NDS V1/2.0 for OpenWRT Chaos Calmer? Will the LEDE version of NDS package work if I try to install it in OpenWRT? v0.9 causing some problem as expected. eg: just now, it automatically started even though I did `ndsctl stop` sometimes ago.

**Comment by bluewavenet** [comment]
In OpenWrt CC and pre v1 NDS if you need mwan3 then as long as it is mwan3 as in OpenWrt CC you need to add the following lines to the NDS UCI config:
list fw_mark_authenticated '262144'
list fw_mark_trusted '131072'
list fw_mark_blocked '65536'
It should then work. It is on my TODO list to make NDS v2.x work with mwan3 v2.x ;-)

Version 1 onwards of NDS will I think will have an iptables incompatibility with OpenWrt CC as CC is very old. You could try it though.

NDS will start automatically on a reboot, so I suspect your hardware may have spontaneously rebooted for some reason.
If you want to prevent it from starting on reboot then disable in luci or type the following:
/etc/init.d/nodogsplash disable.

I am not familiar with openvpn. However as you are not using your ar150 as a travel router it would make sense to get to grips with the config yourself. Best way is to use the GL UI to set it up then look at the config files it produces, this will probably get you going.

Finally, the AR150, although still available and a very useful travel router, it is nearing end of life (probably only available while stocks last, hence the very good price). It might be worth looking for a replacement if you are doing any serious development. (eg the GL-AR300M16 which is effectively the AR150 replacement as far as I can see with 128MB ram and a significantly faster processor).

**Comment by souravndp** [comment]
Thank you very much. As the issue is resolved, closing it.
