### ISSUE TITLE
Allow access to one domain / server IP only 

### ISSUE THREAD

**Issue by daza110** [nodogsplash/nodogsplash#220]
I am trying to capture the name and email address for internal use for people who connect to my wifi, so that when they click "Submit" it ajax's the data to a php file in the $images/ directory. But when I console.log / alert the response I am getting the WHOLE of the file data. Not what I was expecting.

I then saw that nodogsplash does not allow PHP :(.

I then tried sending the data to my external server but got the CORS header blocked orgin etc, even though I have allowed them, stumbled across the conclusion that because all traffic is blocked until NDS has approved them it wont send it to an external server.

Finally I saw on another thread that if you add `list preauthenticated_users 'allow tcp port 80 to xxx.xxx.xxx.xxx'` xxx.xxx.xxx.xxx being my external server. Logic would say that any connections to that IP would be allowed. However when I add that line in the /etc/nodogsplash/nodogsplash.conf file, it does not show the splash screen at all and allows everyone in.

I would greatly appreciate any help on this!

My aim is to add the details submitted via ajax to a DB and on success echo "success". The Ajax response would then click the button on the hidden form allowing access.

**Comment by bluewavenet** [comment]
@daza110 
Forget ajax. What you need is FAS.
https://github.com/nodogsplash/nodogsplash/tree/master/forward_authentication_service
This will make NDS redirect to your php server either local or remote.

**Comment by daza110** [comment]
@bluewavenet Thanks for this, I have tried setting this up however im just getting a permanent redirection as if the port isnt allowed even though ive added my IP address.

server is setup as:

/etc/config/nodogsplash (From link above)
/etc/nodogsplash/htdocs/ replaced with one form link above
/var/www/html/nodog/ (From link above)
 
/etc/config/nodogsplash Code (IP Address changed to 192.168.10.1 which is the IP address of Raspberry Pi
`
# The options available here are an adaptation of the settings used in nodogsplash.conf.
# See https://github.com/nodogsplash/nodogsplash/blob/master/resources/nodogsplash.conf
# 2 Example entries added to allow preauthenticated clients access to the Forwarding Authentication Service

config nodogsplash
  # Set to 1 to enable nodogsplash
  option enabled 1

  # Use plain configuration file
  #option config '/etc/nodogsplash/nodogsplash.conf'

  # The network the users are connected to
  option network 'lan'
  option gatewayname 'NodogsplashFAS'
  option maxclients '250'
  option clientidletimeout '1200'

  # Your router may have several interfaces, and you
  # probably want to keep them private from the network/gatewayinterface.
  # If so, you should block the entire subnets on those interfaces, e.g.:
  #list authenticated_users 'block to 192.168.0.0/16'
  #list authenticated_users 'block to 10.0.0.0/8'

  # Typical ports you will probably want to open up.
  #list authenticated_users 'allow tcp port 22'
  #list authenticated_users 'allow tcp port 53'
  #list authenticated_users 'allow udp port 53'
  #list authenticated_users 'allow tcp port 80'
  #list authenticated_users 'allow tcp port 443'
  list authenticated_users 'allow all'

  # For preauthenticated users to resolve IP addresses in their
  # initial request not using the router itself as a DNS server,
  #list preauthenticated_users 'allow tcp port 53'
  #list preauthenticated_users 'allow udp port 53'

  ############  FAS ############
  # Allow preauthenticated users access to the Forwarding Authentiation service
  #
  # The following line allows access to the FAS wherever it is running but must be the port and ip address of FAS
  # The example here [allow tcp port 80 to 46.32.240.37] was a live demo available at the time of writing
  # It may still be available, try it and see.
  list preauthenticated_users 'allow tcp port 80 to 192.168.10.1'

  # The following line is REQUIRED if the FAS is running ON THE SAME DEVICE as NDS
  # and is the TCP *port* of the FAS service if not listed elsewhere in the users_to_router section
  #list users_to_router 'allow tcp port 4280'
  ############  FAS ############

  # Allow ports for SSH/Telnet/DNS/DHCP/HTTP/HTTPS
  list users_to_router 'allow tcp port 22'
  list users_to_router 'allow tcp port 23'
  list users_to_router 'allow tcp port 53'
  list users_to_router 'allow udp port 53'
  list users_to_router 'allow udp port 67'
  list users_to_router 'allow tcp port 80'
  list users_to_router 'allow tcp port 443'

  
  # MAC addresses that are / are not allowed to access the splash page
  # Value is either 'allow' or 'block'. The allowedmac or blockedmac list is used.
  #option macmechanism 'allow'
  #list allowedmac '00:00:C0:01:D0:0D'
  #list allowedmac '00:00:C0:01:D0:1D'
  #list blockedmac '00:00:C0:01:D0:2D'

  #MAC addresses that do not need to authenticate
  #list trustedmac '00:00:C0:01:D0:1D'

`

I cant for the life of me figure why it keeps redirecting?? As you can see below the IP address has been changed here too!! Ive tried both "http://192.168.10.1:80" and "http://192.168.10.1" in the refresh url.

/etc/nodogsplash/htdocs/splash.html

`<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">


<meta http-equiv="refresh" content="0;URL='http://192.168.10.1:80/nodog/fas.php?authaction=$authaction&amp;gatewayname=$gatewayname&amp;tok=$tok&amp;redir=$redir&amp;mac=$clientmac&amp;ip=$clientip'" />


<link rel='shortcut icon' href='images/splash.jpg' type='image/x-icon' />
<title>Login Required On This Network</title>
<style>
body
{
background-color:lightgrey; 
color:black;
margin-left: 5%;
margin-right: 5%;
text-align: left;
}
hr
{
display: block;
margin-top: 0.5em;
margin-bottom: 0.5em;
margin-left: auto;
margin-right: auto;
border-style: inset;
border-width: 5px;
} 
</style>
</head>
<body>
<br><br>
<hr>
<b>Redirecting....</b>
<hr>
</body>
</html>
`

Id appreciate your thoughts.

**Comment by bluewavenet** [comment]
@daza110 
Have you tried this EXACTLY as in the example? The demo server is up currently. I just tried it and it is still working with an exact copy of the example.

It is impossible to see the contents if your splash.html here.
If you save it as splash.txt and attach as a file I should be able to look at it.

Is the Pi connected to the LAN of the NDS router? What is the IP of the NDS?

**Comment by bluewavenet** [comment]
@daza110 
Note: You cannot test by just browsing to the splash page, this will not work. NDS must redirect you to there so splash.html can in turn redirect you onwards.

**Comment by daza110** [comment]
I have not used the default IP of the docs no. All I have done is change the IP address in both the /etc/nodogsplash/htdocs/splash.html and /etc/config/nodogsplash to reflect the IP address of the Pi.

I have the Ethernet plugged into the Pi, hostapd and installed and configured to broadcast SSID with an ip address of 192.168.10.1 as setup in /etc/network/interfaces

When I connect it shows "Redirecting" but continually redirects doesn't actually show up the login page. (fas.php)

**Comment by daza110** [comment]
OK so I have updated the fiels once more to the default and I am just getting a constant refresh again instead of redirect.

Please see 3 attached files:
[splash.txt](https://github.com/nodogsplash/nodogsplash/files/1655243/splash.txt)
[etc-config-nodogsplash.txt](https://github.com/nodogsplash/nodogsplash/files/1655244/etc-config-nodogsplash.txt)
[etc-nodogsplash-nodogsplash.conf.txt](https://github.com/nodogsplash/nodogsplash/files/1655245/etc-nodogsplash-nodogsplash.conf.txt)

I was unsure as to where to put the /nodog/ files because the docs arent clear. So I installed apache2 and made the Pi a web server and then put the php file in the /var/www/html/ directory. If I turn off NDS I can access the php files by going to "http://192.168.10.1/nodog/xxxxx.php" so at least I know there in the correct place.

**Comment by daza110** [comment]
Please note that I found the issue!!! It was in my /etc/nodogsplash/nodogsplash.conf file!

After reading it thoroughly I noticed that there was a part that said: 
"
 # For splash page content not hosted on the router, you
 # will want to allow port 80 tcp to the remote host here.
 # Doing so circumvents the usual capture and redirect of
 # any port 80 request to this remote host.
"
So I added FirewallRule allow tcp port 80 to 46.32.240.37

and viola!! It worked.

I thyen changed this and the other files to reflect the ip of the Pi and it worked again!! Thanks for your assistance!

**Comment by bluewavenet** [comment]
Sorry, to prevent confusion if we go back to basics first. This will make a good tutorial :-D
First of all:
What version of NDS are you using and on what version of OS?
What hardware?

Then:
Is a plain basic install of NDS working? Check this first making sure a client on wifi gets the basic splash and can click and get Internet access. Once you have this proceed to the next step

Next:
Replace the basic versions of splash.html, infoskel.html, /etc/config/nodogsplash with those provided for the DEMO FAS. Do not modify any files at this stage.

Restart NDS
On LEDE using the following two commands:
service nodogsplash stop
service nodogsplash start
On older OpenWrt CC or earlier:
/etc/init.d/nodogsplash stop
/etc/init.d/nodogsplash start

Then connect a client device using your NDS router's wifi.
The splash page should then be popped up by the device's CPD.
If nothing happens, open the browser and access something like http://google.com (note the http: NOT https: You might find Chrome browser insists on changing to https after you typed it in, if so try another unencrypted port 80 web site that is available on your Internet feed).

The remote login page will appear if everything is set as above.  Try judith and heyjude1968 as credentials, read the TOS etc.

Once you have arrived here we can go to the next step of placing the /nodog folder somewhere local, eg served by uhttpd on the NDS router if it has enough RAM, or your Pi.

**Comment by daza110** [comment]
@bluewavenet 
I am using V1 as of NDS because the OS doesn't support 2.0 
The OS im using is Raspbian on Raspberry Pi Model 3

After setting up the Pi as an access point I installed NDS and it worked a treat with just the "Click here to access"

To configure the FAS I did the following:

**Pre Requisites were to stop NDS, to do this I typed 'sudo ndsctl stop'**

1: Backed up my /etc/nodogsplash/ directory and contents in case things went wrong.
sudo cp -R /etc/nodogsplash/ /directoy/of/backup/

2. Replaced all the contents of /etc/nodogsplash/ with the files from the Repo above for the FAS.

3. Added the nodogsplash file in /etc/config as per Repo instructions

TESTING - start NDS with "sudo nodogsplash"

From here you should be able to click on the WiFi from your mobile device and be forwarded to the Default NDS FAS page as per the DEMO.

If it just constantly redirects then check the NDS config file "/etc/nodogsplash/nodogsplash.conf"
Check that the following Firewall rule is added in the FirewallRuleSet preauthenticated-users {

'FirewallRule allow tcp port 80 to 46.32.240.37'
The above IP address is the IP address of the DEMO data.

Once this line has been added, Stop and Start NDS once more and try connecting. You should be successful in being forwarded and the constant refresh should have stopped.

Congratulations you now have FAS setup correctly using the DEMO data. Please note that the DEMO server might not be available forever!

To host this on your own server you must change 3 files, the one we just edited (/etc/nodogsplash/nodogsplash.conf) to include the IP address of your own server, /etc/config/nodogsplash and /etc/nodogsplash/htdocs/splash.html

In the /etc/config/nodogsplash file you must change the following line:

list preauthenticated_users 'allow tcp port 80 to xxx.xxx.xxx.xxx'
where xxx.xxx.xxx.xxx is the IP address of the server you are hosing the /nodog/fas.php files on.

In the /etc/nodogsplash/htdocs/splash.html file you must change the line that says "<meta http-equiv="refresh" content="0;URL='http://onboard-wifi.net/nodog/fas.php?authaction=$authaction&amp;gatewayname=$gatewayname&amp;tok=$tok&amp;redir=$redir&amp;mac=$clientmac&amp;ip=$clientip'" />"

to 

<meta http-equiv="refresh" content="0;URL='http://YOURWEB/nodog/fas.php?authaction=$authaction&amp;gatewayname=$gatewayname&amp;tok=$tok&amp;redir=$redir&amp;mac=$clientmac&amp;ip=$clientip'" />

Obviously replacing YOURWEB with your ACTUAL web address where you are hosting the /nodog/x.php files.

Once you have edited them 3 files stop and start NDS once more and re test. You should have FAS working.

Congratulations you now have FAS setup correctly using you own server!!

Another alternative is to host it on the device its self (Which is what I did), to do this I installed a webserver (apache2 for example) and put the contents of the /nodog/x.php files in /var/www/html/.
Then simply put the IP address of the Raspberry Pi in all of the locations I mentioned you edit. EG the IP address I setup for the WiFi AP for the Pi was 192.168.10.1 so mine looks like:

/etc/config/nodogsplash - list preauthenticated_users 'allow tcp port 80 to 192.168.10.1'
/etc/nodogsplash/nodogsplash.conf - FirewallRule allow tcp port 80 to 192.168.10.1
/etc/nodogsplash/htdocs/splash.html
<meta http-equiv="refresh" content="0;URL='http://192.168.10.1/nodog/fas.php?authaction=$authaction&amp;gatewayname=$gatewayname&amp;tok=$tok&amp;redir=$redir&amp;mac=$clientmac&amp;ip=$clientip'" />


I hope this is clear enough!! Good Luck!

**Comment by netcarenepal** [comment]
i want to run nodogsplash  to run in 4g/Wan router with Openwrt /LUCI.
my requirements:
1 . I need nodogsplash to support PHP so that i can acess media files in SD card through page.
2. For this I try to run FAS
3.now nodogsplash and luci is in same device . so i didnt find etc/config/nodogsplash since ..default installation is in etc/nodogspalsh
4.i have installed php5 and php5-cgi in my router
5.now is there any way to redirect the flash.html so that it opens the php files in luci web directory since it support php.
if anyone can help
@daza110

**Comment by bluewavenet** [comment]
@netcarenepal 
As you are using php5, you must be using a very old version of OpenWrt.
To do what you are wanting you need at least OpenWrt 18.06.1.
This will give you Nodogsplash v3.2.0, required for integrated FAS setup.
Documentation is at:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

**Comment by netcarenepal** [comment]
Is there in solution for wifi portal system integrated in openwrt router
which can access local content ( music,video etc) from the portal page.. I
have tried various portal ( cova chilli, chilli spot, wifi dog) . But
didn't get solution..will you help me on this ?

**Comment by bluewavenet** [comment]
FAS can deliver anything to its splash page.
However the issue is not the Captive Portal you use on your router, but the Captive Portal Detection (CPD) used on the client devices.
CPD varies from vendor to vendor but most are designed with the following restrictions for security reasons:
 * To immediately close the browser when the client has authenticated.
 * Prohibit the use of href links.
 * Prohibit downloading of external files (including .css and .js).
 * Prohibit the execution of javascript.

**Comment by toanphuong** [comment]
Please guide me how to use remote Fas with a domain name instead remoteip as current? Thanks in advance!

**Comment by bluewavenet** [comment]
@toanphuong 
NDS has to work at an IP packet level to do redirection.
 
A domain name is a human readable/memorable pointer to a dynamic lookup table of IP addresses and a typical Internet hosted web site addressed by a domain name may well be using the same IP address as many other web sites on the same server.

From this you can see that NDS could not reliably use just a domain name for its redirection, even if it did a DNS lookup to get an IP address.

This is not a restriction in NDS but is a result of how DNS is used in conjunction with web server software to allow a single IP address to be used to host numerous web sites (commonly called "Shared Hosting").

I should add a separate section to the documentation for this to clarify the issue!

From the current documentation:

> 

    A typical Internet hosted Apache/PHP shared server will be set up to serve multiple domain names.

    To access yours, use:

        fasremoteip = the ip address of the remote server

        and, for example,

        faspath = /domainname/pathto/myfas/fas.php

        or

        faspath = /accountname/pathto/myfas/fas.php

    If necessary, contact your hosting service provider.
