### ISSUE TITLE
Option "authenticateimmediately" broken since version 2

### ISSUE THREAD

**Issue by DissCent** [nodogsplash/nodogsplash#221]
Since the port to libmicrohttpd, the option "authenticateimmediately" which will authenticate any client immediately on sending an HTTP request is broken - it is completely missing in the code (it gets parsed but there is no action for it). Can you please re-add it?

**Comment by mwarning** [comment]
True, I see that it is only a dummy in version 2.
Somebody needs to re-add/implement it. I don't have the time/interest right now to do it myself.
@DissCent if you can code. Please feel free to submit a pull request.

**Comment by bluewavenet** [comment]
Do we need it? It has always seemed a bit pointless to me. Am I missing something?

**Comment by mwarning** [comment]
@bluewavenet I haven't thought about that. What does authenticateimmediately do that has been useful?
I do not remember that option.
If it does nothing useful, we should simply remove the option.

**Comment by bluewavenet** [comment]
@mwarning 
I'll give it a try on a v1. I seem to remember it gives the splash page without having to click to authenticate. This might have been useful before CPD for an advertising or information page, but nowadays the latest CPD automatically closes the splash as soon as you have Internet access. At best you will just see it pop up for a split second.
@DissCent 
Do you have a specific use for this?

**Comment by DissCent** [comment]
@bluewavenet In v1, the option would automatically authenticate the user upon the first HTTP request that's being sent to the router. But it caused Android users to still see the "No internet - please login" message which made it a little annoying. I was hoping to see a fix for this in v2 - but I just switched over to using a larger list of trusted MAC addresses, so I don't really need it anymore ;)

**Comment by bluewavenet** [comment]
@mwarning 
@DissCent 
I tried it out. The intention is for NDS to immediately authenticate and send the client to the originally requested url. I am struggling to see a purpose for it. I suppose allows everyone except a small list of blocked macs, rather than blocking all except a large list of allowed.
If anyone else would like to come up with a use.......

**Comment by mwarning** [comment]
@DissCent what would be the intended effect for you? It sounds like the user won't notice anything at all (apart from the please login message on android).

**Comment by DissCent** [comment]
@mwarning Well, I want to build a setup where I have multiple hotspots inside my building, but only have to accept the splash page on one of them. Once you switch access points, your MAC address should already be whitelisted. I thought about writing a hook which does basically the same as the "authenticateimmediately" option, i.e. checks whether your MAC is on some kind of "authenticated whitelist" and if so, authenticates you automatically. But since the "please login" message always appeared, I searched on now I use the "trusted MAC list" feature by adding the MAC addresses via ndsctl - it works quite well :) So as I said, I don't need that option.

**Comment by bluewavenet** [comment]
@DissCent 
The easiest way to do what you describe is to run all your access points (in bridge mode ) back to a router running NDS either by cable or WDS or Mesh. Works perfectly and no need to do anything special at all.

**Comment by mwarning** [comment]
@DissCent when the functionality is needed, then someone needs to implements it.
For now I have removed the dummy code.
