### ISSUE TITLE
Spoofing requests to FAS

### ISSUE THREAD

**Issue by xam41** [nodogsplash/nodogsplash#222]
Is there a way to make sure that the requests coming into my server for FAS (example: http://my-fas.net/nodog/fas.php?params) are from NDS? Can't anyone on the internet with the URL just call http://my-fas.net/nodog/fas.php?params with some fake parameters and cause problems?

**Comment by bluewavenet** [comment]
The example fas.php or whatever you choose to code into your own depends totally on $authaction and $tok as provided by the NDS captive portal.
For anyone to "cause problems" they must have valid values of both $authaction and $tok to have any chance of authenticating. Yes in the very simplistic demo example these could be intercepted very easily and bypass the trivial authentication of the demo example, but then this would only be of use for someone on your NDS network.
A secure implementation would for example have splash.html redirecting to a local php server, say lighttpd running on the NDS box. Here you can do whatever you like as secure as you like eg provide a radius gateway or an application to enter voucher codes or in fact anything you can think up.
The demo example is no more secure than the old sitewide authentication of NDS and is provided as a detailed HowTo more than anything else.
I hope this helps :-)

**Comment by xam41** [comment]
Thanks, I'll give lighttpd a try.

**Comment by bluewavenet** [comment]
The standard uhttpd for luci works well with php as well but can get a bit slow depending on what you want to do verses flash space and ram needs.
