### ISSUE TITLE
install Nodogsplash 2.0.1 release in LEDE ?

### ISSUE THREAD

**Issue by H1-N1** [nodogsplash/nodogsplash#223]
im new to openwrt/lede 

how i can install Nodogsplash 2.0.1 release in LEDE ?
i downloaded this .v2 here bute return Unknown package 'nodogsplash2'.
https://archive.openwrt.org/snapshots/trunk/cns3xxx/generic/packages/routing/
sorry for my bad eng!
thx

**Comment by bluewavenet** [comment]
You can download from snapshots - for example:
https://downloads.lede-project.org/snapshots/packages/mips_24kc/routing/

But obviously select the architecture for your device ;-)
