### ISSUE TITLE
wifidog-ng

### ISSUE THREAD

**Issue by zhaojh329** [nodogsplash/nodogsplash#225]
I launched a new project - wifidog-ng, which no longer uses iptables, but instead writes kernel modules.

Wifidog-ng has been merged into the official Openwrt feeds.

I am here to invite friends interested in wifidog-ng to join.

**Comment by mwarning** [comment]
Hi, nice work. Best wishes with your project.

If I may ask - what is the point of not using iptables? After the startup, there would not much left to be done in terms of iptables.

**Comment by zhaojh329** [comment]
It is more flexible to write kernel modules and more convenient to operate.

**Comment by bluewavenet** [comment]
@zhaojh329 , this will mean wifidog-ng will be kernel version dependent?

**Comment by zhaojh329** [comment]
If you encounter an incompatible kernel version, we can fix the code in time to fix it. But this is a few cases.
Here is an example: https://github.com/zhaojh329/wifidog-ng/commit/9ce158d9f1ee9d5d5ecbd73edde481f308285540

**Comment by zhaojh329** [comment]
writes kernel modules to avoid marking, because marking may conflict with other programs, such as QoS, mwan3.
