### ISSUE TITLE
How call a http get request from splash page?

### ISSUE THREAD

**Issue by camilochs** [nodogsplash/nodogsplash#226]
Hello everyone,

I'm trying to make an HTTP GET request from splash page, but not work.

I want to store the inputs from splash page to a database or plain text when the user press button "Continue". 

So, I have run an API in other port, for example:  

192.168.220.1:2050/splash.html 

and my API: 

http://192.168.220.1:5000/session?input1=123&input2=123

But from splash page not work the call API.

Thank

**Comment by camilochs** [comment]
I enable firewallrule 5000 in configuration file. Solved. :)

**Comment by bluewavenet** [comment]
@camilochs 
You might find it worthwhile looking at NDS FAS:
https://github.com/nodogsplash/nodogsplash/tree/master/forward_authentication_service
