### ISSUE TITLE
Splash page showing for direct connections to the router only 

### ISSUE THREAD

**Issue by deltabi** [nodogsplash/nodogsplash#228]
I've just configured nodogsplash (v1.0.1-2) on a GL.iNet MT300N-V2 router (running OpenWRT-LEDE 17.01) however the splash page shows up only for direct connections to router, while web sites can be reached without splash page.
As an example if the router LAN interface is at 192.168.8.1, if the browser asks for that address than the splash page shows up, but if the browser asks for (i.e.) www.google.com the splash page does not shows up.
It looks like requests going directly to internet are not routed to the nodogsplash web server.

**Comment by bluewavenet** [comment]
Are you sure the MT300N-V2 is in router mode? The chipset used powers up with the two ethernet ports in switch mode and will bridge between LAN and WAN until configured . As LEDE boots it will create separate vlans, one port for WAN and one for LAN.
Are you using the "stock" firmware or the "clean" version. Standard LEDE/OpenWrt does not support this router yet so you must use the GL-iNet proprietary version.
WAN port should be connected to your ISP router LAN.

**Comment by deltabi** [comment]
Thanks for your prompt reply.
Yes, I'm using router mode. I've configured the router in "repeater mode", i.e. I've connected the internal wifi of the device to the home wifi which is connected to internet. The wireless network on the MT300N-V2 is on a separate ip space (192.168.8.0/24) and the device is routing packet.
I'm using the "stock" firmware, the standard one GL.iNet provides with the device (latest version, 2.264).
The WAN port is not connected as I'm using "repeater" mode as per above (it's called repeater mode but actually is a wifi-to-wifi routing).

**Comment by bluewavenet** [comment]
You need Wisp mode for this to work.
However, as the WiFi chipset still needs the proprietary drivers, correctly setting up the br-lan interface for NDS can be very tricky.
I would suggest configuring in router mode with ethernet from WAN port to ISP LAN, at least to start with. If it works correctly that way, then start looking in more detail at Wisp router mode.

**Comment by deltabi** [comment]
In fact the MT300N-V2 works in WISP mode.
To me it looks like there is some problem on the firewall/iptable rules, but I'm not expert on the subject so it's only a feeling.
I'll try a new test with the WAN port connected but, as that port is in the same firewall "zone" as the WWAN port (i.e. the port which is connected to the home wifi) I think I'll get the same result.

**Comment by bluewavenet** [comment]
I am familiar with the MT300N-V2 and WiFi Repeater mode mode should create two wifi interfaces, one in sta mode and one in AP mode and bridge them together. The internal ip address will be still 192.168.8.1 and as a consequence you will only get the splash page if you access directly.
Wisp mode provides routing between the two wifi interfaces and should work with NDS but you might have to reflect the "LAN" wifi name in the NDS config file but there may be other problems. I do have one running as a simple AP on a client site that I can access remotely so could refresh my memory if needs be. Let me know how the ethernet connected test goes.

**Comment by bluewavenet** [comment]
OK I had a look at the remote MT300N-V2. The proprietary drivers present themselves as an "ethernet" device named "ra0". This means that the setup needed for wisp routing with NDS will not work without digging into the driver setup and that is not documented. It probably can be made to work but given the very low cost of the MT300N-V2 and a possible replacement by an GL-AR300M-Lite at a very similar price makes the effort not worthwhile in my opinion (the AR300M with its full open source hardware works perfectly with NDS without much effort at all and is more powerful than the MT300N-V2). The MT300N-V2 will however work well in plain router AP mode with NDS (cable on the WAN port).

**Comment by deltabi** [comment]
No joy with the WAN port connected. The only difference is that I can't reach any remote site at all. Splash page shows up again only when referring the MT300N-V2 gateway interface address directly. All others web site gives a connection timeout error.

**Comment by bluewavenet** [comment]
That sounds like it is working as designed. Just about all smart devices and desktop/laptop OS's/browsers have built in Captive Portal Detection. If you are testing with a laptop this might be disabled. Try with a smart phone or try a port 80 web site (ie non https).
There are very many CPD urls set up just for this.
Here are a few examples:
http://connectivitycheck.android.com/generate_204
http://captive.apple.com/hotspot-detect.html
http://www.msftconnecttest.com
http://www.gnome.org/
and even
http://www.google.com/
and on and on. ;-)

**Comment by deltabi** [comment]
I'm sorry but it does not work even trying with a smartphone (Android 7) and/or with non https sites (I've used even a couple of those you mentioned).

**Comment by bluewavenet** [comment]
I think you really should try the "clean" firmware. Even then it might not work due to the non standard nature of the proprietary drivers.
http://www.gl-inet.com/firmware/mt300n-v2/clean/lede-mt300n-v2-clean-2.264.bin
You really need an AR300M-lite for your requirement.

**Comment by deltabi** [comment]
Thanks, I'll try the clean firmware.
The AR300M-Lite does not have the WAN port which I need for max flexibility. Do you know if the only ethernet port can be used for WAN access too? An alternative could be the no-Lite version of the AR300M?

**Comment by bluewavenet** [comment]
The AR300M-Lite has a single ethernet connector that defaults to WAN in LEDE/OpenWrt but can be configured any way you want. The AR300M16 is identical to the Lite apart from the fact it has the second ethernet connector fitted and therefore costs a bit more.  
note: you will need to use LEDE/OpenWrt ImageBuilder to build your own image for the Lite (or download the one I built), as the radio defaults to disabled and the single ethernet defaults to WAN so you cannot login to configure it. ImageBuilder is actually a very good thing to get up to speed with as it teaches you a huge amount about the architecture of LEDE/OpenWrt. Also any packages you include in your image are in a compressed form thus saving Flash memory space. The image just needs to include a simple UCI config file to turn on the radio on first boot.

**Comment by bluewavenet** [comment]
NDS can be made to run on any router supporting LEDE/OpenWrt, but if the router depends on non open source drivers, this can prove to be an issue at times, not due to NDS its self, but in putting the router in a suitable mode for using NDS in the first place.

**Comment by deltabi** [comment]
Tested the "clean" firmware in the MT300N-V2 and NDS work as expected (WAN port connected). This afternoon I'll try the configuration with the WAN uplink done in wireless, like in my first tests with the GL.iNet "v1" firmware, just to get a full report from my tests.

**Comment by bluewavenet** [comment]
@deltabi 
re: MT300N-V2, with luck it will work with the duplicate radio configuration but as I said the proprietary drivers have undocumented methods of configuration, indicated by LUCI not being able to fully manage the radio. I am sure it can be made to work, but try without NDS just to see the wireless to wireless routing is working first. If is is then there should not be much problem.

re: AR300M, the dual flash version has both 16MB NOR and 128MB NAND. LEDE/OpenWrt does not support the 128MB NAND on this device so you will end up using the16MB NOR.
The AR300M16 is identical except the 128MB NAND is not installed. GLi did this as the NAND capacity is not needed in almost all applications so costs could be reduced. The 16MB NOR is more than enough particularly if you build your own image. A few dollars off the price makes a big difference with this kind of device.
The AR300M-Lite is identical to the AR300M16 except only a single ethernet header is installed - another cost saving. For many applications the second port goes unused and therefore this is a worthwhile saving.
All AR300M models are fully open source, have 128MB ram and the same QCA9533 SoC so can handle anything NDS can throw at them ;-)

There are many other manufacturers to choose from of course. A good place to start if looking for a device is the LEDE/OpenWrt table of hardware.
https://openwrt.org/toh/start

**Comment by deltabi** [comment]
@bluewavenet 
Thanks again for the good info.
Yes I'm reading that dual Wifi (AP+ClientMode) isn't very straightforward to configure. I've already had hints that LUCI got confused during this kind of configuration (it even throws a parameter syntax error in certain cases during wireless setup). Analyzing the requirements, maybe the dual radio isn't a real necessity especially if it brings configuration troubles, so maybe we can ditch it.

About the AR300M16 do you believe it could better support the dual radio (AP+ClientMode) setup? Or is it a common problem of the OpenWRT platform?

**Comment by bluewavenet** [comment]
The dual mode setup is very easy to do on LEDE/OpwnWrt and is fully supported by Luci - that is if you have the open scource MAC80211 drivers, or at least a fully functional shim to make it look like a MAC80211 driver. Otherwise you will need proprietary config details that will most likely be unpublished.
The AR300M series are all fully MAC80211 compatible and Luci configured AP+ClientMode works perfectly.

**Comment by deltabi** [comment]
Ok, thanks.
Do you know if, in case of absence of the wifi which provide the internet in ClientMode, the AR300M will shut off the AP wireless, too?

**Comment by bluewavenet** [comment]
An interesting point: If the router you are connecting to has a usb port capable of supporting a 4G/3G dongle, it will also be able to power your Gli mini router making it a very tidy installation.

Yes, if the client mode radio instance looses its signal the radio is disabled and this of course turns off the AP instance also.
You can prevent this by enabling WDS mode on the AP. You do not need to configure a WDS link though as in WDS-AP mode keeps the radio on at all times.

**Comment by deltabi** [comment]
Can you elaborate on the WDS mode? Is it a simple setting done via LUCI?

**Comment by bluewavenet** [comment]
Simple setting in Luci.

**Comment by deltabi** [comment]
Ok, then it looks like it would be worth testing the AR300M16, too.

Regarding the USB power, I've used it from a couple of PCs but it seems to limit the power of the wifi transmission: the second wifi network could not work until I lowered the radio transmission power.

**Comment by bluewavenet** [comment]
WDS in Luci:
Network/Wireless/wlan0/edit/Interface Configuration/Mode
and set to Access Point (WDS)

If your router can power a 4G/3G dongle it will be ok. The mini router needs a good 5 volts at maximum load and some usp ports can drop below 5 volts if the current gets to high.

**Comment by deltabi** [comment]
Ok, thanks.
I'll let you know when I'll test the AR300M16.
