### ISSUE TITLE
Existing Firewall Rules Ignored After Authentication

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#229]
As discussed at length in #197 it has been established that NDS does not pass on to the existing iptables rules.
This comes to light for example if a rule is set to redirect authenticated clients to a proxy.
This can be fixed by modifying the nat table action in ndsOUT for authenticated clients from ACCEPT to RETURN. This should also be changed for trusted clients.
After some testing by @cilix-lab and me, cilix-lab has produced a script to modify the iptables entries as follows:

#!/bin/bash

LAST=$((`iptables -t nat -L ndsOUT | wc -l`-2))
for r in 1 2 $LAST; do
        iptables -t nat -R ndsOUT $r -j RETURN
done

exit 0

@mwarning 
@jlcmoore

**Comment by bluewavenet** [comment]
I see this as a work around for existing releases and depending on feedback will do a PR with the fix.

**Comment by cilix-lab** [comment]
Sorry about that script, it does not work. Here's the one which is working:  
```
#!/bin/bash

LAST=$((`iptables -t nat -L ndsOUT | wc -l`-2))

for rule in 1 2 $LAST; do
  iptables -t nat `iptables-save | grep '^-A ndsOUT' | sed "$rule"'q;d' | \
    sed 's/-A ndsOUT/-R ndsOUT '"$rule"'/' | sed 's/-j ACCEPT/-j RETURN/'`
done

exit 0
```
