### ISSUE TITLE
.conf ERROR on pi 3b+

### ISSUE THREAD

**Issue by digitalnerve** [nodogsplash/nodogsplash#234]
Hi, 
I am VERY new to this and have been trying to get NDS working on a Raspberry Pi 3b+.
I have managed to get the vanilla version up and running and I am now looking to get FAS working.
I have followed all the instructions on this thread: https://github.com/nodogsplash/nodogsplash/issues/220
BUT can't start the nodogsplash service with the replaced nodogsplash.conf file i get:

> /etc/nodogsplash/nodogsplash.conf: line 6: Bad configuration option: config

Having trouble trying to fix it on my own.  Any ideas?

**Comment by bluewavenet** [comment]
@digitalnerve 
Did you get it working?
