### ISSUE TITLE
Customizing splash page in custom firmware image

### ISSUE THREAD

**Issue by deltabi** [nodogsplash/nodogsplash#235]
Hello,
I'm producing a custom firmware image with the OpenWRT/LEDE ImageBuilder (v17.01.4). The firmware successfully integrates a couple of extra packages (including NDS) and a custom system configuration (main reason for doing the custom firmware).
One of the parts I need to customize is the splash screen used by NDS. I've modified it on a running configuration to my liking and then included the file in the files/ folder used by the Image Builder.
However when I deploy the produced customized firmware, the splash screen is reverted to the standard, as if the personalized splash.html file was overwritten with the default one during the NDS package deployment.
What's wrong? How can I produce a custom OpenWRT firmware with a specific splash.html file using the Image Builder?
TIA for your support.

**Comment by bluewavenet** [comment]
You need to create the target directory structure in files/ as well
Eg files/etc/nodogsplash/htdocs/splash.html
And also use the files directive in your imagebuilder make command

**Comment by deltabi** [comment]
That's exactly what I did.... or at least is what I **thought** I did...
I've just discovered that I didn't create the htdocs/ folder in the tree structure... sorry.

**Comment by bluewavenet** [comment]
Very easily made mistake, I know, I have done similar myself ;-)
Glad it is working for you now.
