### ISSUE TITLE
Trigger CPD when time out. 

### ISSUE THREAD

**Issue by dsmh** [nodogsplash/nodogsplash#236]
Hi, I want to know if  is there a way to trigger the CPD when the client is timed out?

Thanks to the lack of support on https, when then time assigned through Nodogsplash runs out, all the devices act like there is no internet connection. How can Nodogsplash trigger the CPD to avoid this scenario?

**Comment by bluewavenet** [comment]
The implementation of the CPD is purely down to the individual vendors of the devices and totally outside the control of any captive portal including NDS.
No captive portal can trigger the CPD running on a client device, only the client device can do this.

The specification for CPD is for regular polling to take place, usually with a default 300 second interval.
Desktop Firefox and Chrome do this as does Network Manager in Linux and Windows 10.

Some implementations of the CPD do not poll though, notably "some" versions of iOS and Android. Instead, these versions turn off the wifi on the device when it goes to sleep to save battery but does not call CPD on waking up. The end result if NDS times the client out, is an apparent non connection. In these cases, manually turning the wifi off and back on again will invoke the CPD again.

In a typical scenario, customers come and go and connect elsewhere before coming back and this has the same effect as turning off and on, so this problem will not in fact be an issue and goes unnoticed by the vast majority of users.

**What can you do about it?**
What you should do is tune both the idle timeout and forced timeout parameters in NDS to match typical usage at the location of your NDS portal.

For example in a coffee shop where customers would stay for maybe 1 or 2 hours at maximum, an idle timeout of 2 hours will work well.
A restaurant maybe 4 hours. A museum perhaps 10 hours. In most cases a forced timeout of say 24 hours seems to work well. 

If you have people present all the time (staff perhaps), you might consider a second, secured, non-NDS managed SSID for them, or if in small numbers add the mac addresses of their devices to the NDS TrustedMacList.

I say all of this with experience of numerous live sites of different types, some very large and all based on NDS and hope it helps.

**Comment by dsmh** [comment]
Thank you so much for your answer @bluewavenet
