### ISSUE TITLE
FAS authorization users

### ISSUE THREAD

**Issue by helsyQ** [nodogsplash/nodogsplash#239]
I'm using FAS . 
My /etc/nodogsplash/htdocs/splash.html contains such stroke 
```ruby
<meta http-equiv="refresh" content="0;URL='http://mysite.com/fas.php?authaction=$authaction&amp;gatewayname=$gatewayname&amp;tok=$tok&amp;redir=$redir&amp;mac=$clientmac&amp;ip=$clientip'" />
```
So what should I write on the page to which I redirect users to let them use internet? 

For example, i have such login form on the fas page
```php
echo"<form novalidate action=\"index.php\" method=\"POST\">";
echo"<input type=\"text\" name=\"password\" required>";
```
And I want to make simple condition: if password == 123 --> let user use internet, if not --> refresh. Help me, please, about this question.

**Comment by bluewavenet** [comment]
The example fas.php does this already, but also asks for a username.
A simple way to change to password only would be to make a small change to fas.php 
If you look in fas.php, in function login()
Change the line:
`echo"<hr>Username:<br>";`
to:
`$username="nds_user";`
where nds_user is a user defined in the users.dat file
then change the line:
`echo ("<input type=\"text\" name=\"username\" value=\"" . htmlentities($username) . "\">\n<br>\n");`
to:
`echo ("<input type=\"hidden\" name=\"username\" value=\"" . $username . "\">\n<br>\n");`

This should then work as you want it to and the password can be changed in users.dat whenever needed.
