### ISSUE TITLE
Can not redirect to separate internal server

### ISSUE THREAD

**Issue by Grimmy347** [nodogsplash/nodogsplash#241]
I am running a separate server on port 8080 to run a LED matrix program but when I try to go to the server it can not connect.

I am using:
RedirectURL http://192.168.43.1:8080/Starpoint/

That ip is the ip of the RPI/rpi dhcp server.  I can access it from my computer directing to the rpi ip given to it from the router using "http://192.168.1.163:8080/Starpoint/"

how would i direct my device connecting to the NDS on the rpi?  what would the RPIs ip be relative to the device connecting to it?

I hope this makes sense.

**Comment by bluewavenet** [comment]
Sorry, does not make sense.
You have the Rpi configured as a router running NDS with its WAN(ethernet) connected to your ISP router?
The LAN(wireless) of the Rpi has a subnet of 192.168.43.0 mask 255.255.255.0 ?
The ISP router has a subnet of 192.168.1.0 mask 255.255.255.0 ?
Which OS are you running on the Rpi?
Which version of NDS are you running?
Which web server are you running for your Starpoint and is it configured to serve on both the WAN and LAN interfaces of the Rpi?
Is your computer connected to the Rpi WAN or LAN?
