### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#242]
With the upcoming release of the new OpenWrt (18.01?), should we be thinking of a new release of NDS? There are now quite a few useful fixes and enhancements since the last release.
@mwarning @lynxis @champtar @sayuan @zioproto

**Comment by mwarning** [comment]
Sounds good. But the changelog would need to be updated.

**Comment by bluewavenet** [comment]
@mwarning 
Working on it every time I get a spare few minutes.
I guess 2.0.2?
I have done some work on the docs as well. The OpenWrt install needed an update and a few other minor bits.

**Comment by mwarning** [comment]
2.0.2 sounds fine. If we have new features, we can go to 2.1.0.

**Comment by bluewavenet** [comment]
@mwarning 
The two/three new bits of functionality are -
PR #237 TCP Fastopen
PR #231 Firewall Rule Chaining
and the related https://github.com/openwrt-routing/packages/pull/369 Firewall Hook
The rest of the changes are tweaks, cleanups, fixes for changes in other packages (MWAN3 V2 and SQM), or bug fixes.

Sufficient for 2.1.0 ?

**Comment by mwarning** [comment]
2.1.0 is fine (according to https://semver.org/), we have some new features in a backwards compatible manner.

**Comment by bluewavenet** [comment]
Thanks for the semver link, useful.
2.1.0 it is then ;-)

**Comment by mwarning** [comment]
I have updated the changelog. Please have a look if I got it right or if something is missing.
Next steps:
- tagging the package and create a release on github
- building a debian package
- update openwrt package

**Comment by bluewavenet** [comment]
I have added to the changelog. Not sure of the correct way to reference PRs elsewhere.
Do we actually build a Debian package? 
I'll have another read through the docs to see if we need anything else there.

**Comment by bluewavenet** [comment]
What is the mechanism for updating https://nodogsplash.readthedocs.io ?

**Comment by mwarning** [comment]
The Debian package is a valuable addition.
I do not know how to update the docs website. I assume it is done automatically

**Comment by bluewavenet** [comment]
Agreed,the Debian package is valuable. I just can't see anywhere a package is actually built - details of how to compile are there though. Do we need to do anything specific? I was thinking of doing an OpenSuse version for a project but not had time.
Docs on readthedocs does automatically update. So we do not need to do anything there.

**Comment by bluewavenet** [comment]
@mwarning 
I've drafted the new release. I think I did it correctly, perhaps you could check it for me please :-D

**Comment by mwarning** [comment]
Looks good. Let's release.

**Comment by bluewavenet** [comment]
Do'h
Changelog has "UNRELEASED; urgency=medium" in the first line.
I can think of a few updates to https://github.com/nodogsplash/nodogsplash/blob/master/resources/nodogsplash.conf ie bringing into line with the OpenWrt version
If I fix these shall we go straight to 2.1.1?

**Comment by bluewavenet** [comment]
OK that's done.
How do we get PKG_SOURCE_VERSION and PKG_MIRROR_HASH for https://github.com/openwrt-routing/packages/blob/master/nodogsplash2/Makefile ?

**Comment by mwarning** [comment]
https://github.com/openwrt-routing/packages/pull/376
@bluewavenet PKG_SOURCE_VERSION is set to the git revision, PKG_MIRROR_HASH to the sha256 hash of the ndg file in openwrt/dl/

**Comment by bluewavenet** [comment]
Trying to follow what you are doing - out of interest, and to learn :-D
Are you building a test version?
Re my previous question, I can't find the "ndg file in openwrt/dl/dl" - I am missing something...
Git revision - found that.

**Comment by mwarning** [comment]
@bluewavenet you first have to set PKG_SOURCE_VERSION, then build nodogsplash2 (`make package/nodogsplash2/{clean,compile} V=s`). The build will likely succeed, but a warning about the hash mismatch of the dl/nodogsplash* source package file will be displayed. You need to scroll up to see the message. To get rid of the warning, PKG_MIRROR_HASH needs to be updated.

**Comment by bluewavenet** [comment]
I'm still not understanding. By source package file, do you mean the nodogsplash downloadable tar.gz?
I tried hashing an old release and get a different answer to the value in the makefile for that release.
Also, I don't see it in all packages, is it a kind of double check?

**Comment by mwarning** [comment]
Closing this ticket as the release has been done.

**Comment by bluewavenet** [comment]
@mwarning
Thanks for your efforts, patience and feedback. Much appreciated.
