### ISSUE TITLE
Change path the login

### ISSUE THREAD

**Issue by camilochs** [nodogsplash/nodogsplash#243]
Hello!
I have seen the documentation but I not found this.
How can I change the index path? 

For example: 
My current path:  /etc/nodogsplash/htdocs/splash.html  <-- login
My new path: /etc/nodogsplash/htdocs/public/index.html <-- login

Is possible this?

Thanks

**Comment by bluewavenet** [comment]
The Nodogsplash "splash" page is intended to be a simple hook into some authentication method. The "web server" part of NDS is hard coded to supply important variables specifically to splash.html
you can change splash.html to link to whatever authentication method you choose, passing these variables as required. Your authentication method must then return at least the authentication token to NDS on success.
This is Forward Authentication Service and a fully functional example can be found at:
https://github.com/nodogsplash/nodogsplash/tree/master/forward_authentication_service
If you follow the example exactly you should get it working. It will then be a simple matter to change the  example to suit your needs.

**Comment by camilochs** [comment]
Thank you!
