### ISSUE TITLE
remain authenticated after system reboot

### ISSUE THREAD

**Issue by Tengoles** [nodogsplash/nodogsplash#246]
Hello, I would like to make the users MAC addresses that at some point were authenticated to remain authenticated even after the reboot of the router. Is there any register  where I can manually add MAC addresses so that those devices don't have to go through the splash page and just connect to the network automatically?

**Comment by bluewavenet** [comment]
I'm not sure why you would want to do this for everyone, kind of makes NDS unnecessary.

You would add the mac addresses to the TrustedMACList in the config file (/etc/config/nodogsplash or /etc/nodogsplsh/nodogsplash.conf depending on operating system).

You could automate this using FAS if you really wanted to with a call to ndsctl to make it effective immediately and adding to config for after a reboot.

**Comment by Tengoles** [comment]
I want to do that because I just want users to see my splash page the first time they connect to my wifi since that is when I get what I need from them, other times the splash page has no use for me and it makes user experience worse.

Anyway, I will take a look at this tomorrow thank you for the help! 

Btw, what does FAS stand for?

**Comment by bluewavenet** [comment]
https://nodogsplash.readthedocs.io/en/latest/authentication.html#nodogsplash-all-versions-forwarding-authentication-service-fas

https://github.com/nodogsplash/nodogsplash/tree/master/forward_authentication_service
