### ISSUE TITLE
Release 2.1.1 in lede-1701 branch

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#248]
@mwarning 
Can we release 2.1.1 into the lede-1701 branch?
I just heard there is 17.01.5 about to be built so .... would be nice to be included.

**Comment by mwarning** [comment]
https://github.com/openwrt-routing/packages/pull/382

**Comment by bluewavenet** [comment]
@mwarning 
**Star!** :-D

**Comment by bluewavenet** [comment]
@mwarning 
Can we merge this? I have production firmware upgrades to roll out and it would be really great to include 2.1.1.
I know I can add it into my images anyway, but much prefer to use the stable releases.

**Comment by mwarning** [comment]
done
