### ISSUE TITLE
Not working on RPI ZERO W

### ISSUE THREAD

**Issue by tomasstranik** [nodogsplash/nodogsplash#249]
Hi,

I just want to politely ask you whether you have any information about this configuration.

I set up nodogsplash on PI 3 and it works really awesome. The splash screen is correctly displayed once a user connects to WIFI access point.

However, if the SD card is removed and placed to rpi zero w it does not work at all. All other configuration (Wifi Access Point, DNS) is right so I believe that the problem is in nodogspash, maybe in iptables rules.

Please see the log file from nodogsplash in the attachment as well as the nodogsplash configuration file. There are also iptables rules attached. The rules are same on rpi zero w as well as on rpi3. 

If you need any more information, let me know. 

Note: I'm able to get the splash screen from a browser if I connect to the wifi so libmicrohttpd works correctly.

Thank you for any information.

Regards,
Tomas  
[nodogsplash_rpi_zero_w_log.txt](https://github.com/nodogsplash/nodogsplash/files/2085094/nodogsplash_rpi_zero_w_log.txt)

[nodogsplash.conf.txt](https://github.com/nodogsplash/nodogsplash/files/2085099/nodogsplash.conf.txt)
[iptables.txt](https://github.com/nodogsplash/nodogsplash/files/2085105/iptables.txt)

**Comment by mwarning** [comment]
You could try to compare the startup logs (you can use kdiff3 or meld for this).

**Comment by bluewavenet** [comment]
What is your network configuration? What are you using for a wan connection? Without a wan connection, NDS will not work.

**Comment by tomasstranik** [comment]
@bluewavenet good point!
That is the cause. I have LAN connected to RPI 3 so NDS works correctly. R PI ZERO W has no LAN so it has no internet connection.

So is it possible to use NDS without internet connection? Is it possible to configure/modify the code so it will show the splash screen even if no internet connection is available? 

What changes in the code are needed to accomplish this task? Even if it would be a hack, please? Just give me some ideas. I could test it by myself. 

Really appreciate your quick answers. Good work.

Thanks!

Regards,
Tomas

**Comment by bluewavenet** [comment]
No code changes or hacks required ;-)

In Rpi Zero world, the terminology used in NDS might be confusing as it is intended to provide a Captive Portal for Internet access. It can be used in "offline mode" though.

WAN will be the interface providing a downstream connection to the Internet.
LAN will be the interface providing an upstream connection to client devices.

NDS must run on a device configured to be a router that provides the default gateway, DNS and dhcp for its LAN.

The splash page pops up on the client device only when a request for a port 80 web page is made.
Normally the client device does this automatically using its captive portal detection (CPD - included in just about all operating systems and browsers these days ).

When a WAN connection is not available, the DNS on your Pi will return an error so you must make it provide a real positive reply to ANY DNS request.

All you need is to add a single line to your dnsmasq config:
 address=/#/[lan_ip_address_of_NDS]
eg in my test system this would be would be:
address=/#/10.168.1.1

Add this line and reboot your Pi and it should be working.

**Comment by tomasstranik** [comment]
@bluewavenet Thanks for nice explanation 👍 
NDS works now as expected.

Closing.
Tomas

**Comment by giggioz** [comment]
@bluewavenet allow me one more question on this topic: in this configuration will the raspberry pi zero be able to connect to the internet (through the router, of course)?
Thanks

**Comment by bluewavenet** [comment]
@giggioz 
The whole point of @tomasstranik 's configuration was to make the rpi zero w work **without** an internet connection.
If you want to use a rpi zero w as a public wifi hotspot it will have to be configured with an Internet connection of course. This is most economically done by configuring a second logical wifi interface in sta mode to connect to your private Internet enabled wifi and have the rpi route between the sta interface as its WAN and the AP interface as its LAN.

**Comment by giggioz** [comment]
@bluewavenet yes, i was aware about tomas's request :)

But for my needs i needed to know something more:
I have a router (connected to internet), in its LAN i connect my rpi as AP for guests who are redirected to a web-app served by rpi. Guests never go outside the rpi net, they just need to interact with the this web-app.

Rpi needs to talk with an external server too. **that's why i was asking if it was possibile.**
And by your answer i understand that is possibile: i need to configure a logical wifi interface, correct?
And, if i correctly understood, I should not need to link the two interfaces in the rpi because my guests do not go outside the LAN.

I'm moving my first steps in networking, so sorry for not using the right words to define those concepts.

Thanks.

**Comment by bluewavenet** [comment]
The configuration detailed here will prevent the rpi from resolving DNS.
What you need is to configure your rpi as a router (WAN on STA Wifi interface, LAN on AP interface , both on the rpi single wireless device).
Run on the rpi LAN the following:
DNS, DHCP, NDS, with NAT from LAN to WAN. ie a standard router configuration and not using the special Dnsmasq config.
Then if you do NOT allow clients connecting to your rpi to authenticate into NDS, they will not have access to the Internet. The rpi will though.

**Comment by tobisey** [comment]
Sorry to ask a dumb question but how do I find out the lan_ip_address_of_NDS?

**Comment by bluewavenet** [comment]
@tobisey 
It is the LAN ipaddress of the interface NDS is bound to, ie whatever you set it to when you configured your device as a router.  The "How It Works" section of the documentation will give you some insight:
https://nodogsplashdocs.readthedocs.io/en/latest/howitworks.html
