### ISSUE TITLE
Can't get to authenticate on mobile devices.

### ISSUE THREAD

**Issue by burgonyapure** [nodogsplash/nodogsplash#250]
My nodogsplash works fine on desktop, it prompts me to log in every time I connect, and it is working fine. But when I try to use my android phone nothing happens. I'm on the network I just can't log myself in. I can't get to the captive portal. 
Any suggestions?

**Comment by bluewavenet** [comment]
@burgonyapure 
First, go to the android wifi config and "forget" the ssid of your network. Then reconnect. 

If this does not work then try opening the browser on your android and enter the url:
http://onboard-wifi.net
If this brings up the splash page then you will have some third party app that is blocking the function of the inbuilt android CPD (captive portal detection).
Apps like this are usually described as "security enhancements" and designed to prevent automated connections to captive portals amongst other things.

**Comment by burgonyapure** [comment]
Worked after forgetting the SSID, should've figured it out by myself. Thank you very much for helping!
