### ISSUE TITLE
FAS installation on nodogsplash v1

### ISSUE THREAD

**Issue by mavridis92** [nodogsplash/nodogsplash#251]
Hi, 
I would like to incorporate FAS functionality to nodogsplash v1. So I tried to copy the contents of the "forward_service_authentication" file to the nodogsplash folder, after that editιing the files as you mentioned on [documentation](http://nodogsplash.readthedocs.io/en/latest/authentication.html) but it seems that doesn't respond. I think I am confused about the FAS' installation. There is some way to understand if the FAS service operate?

PS
It is worth mentioning that I'm working on Raspberry Pi.

Best Regards,

**Comment by bluewavenet** [comment]
It works will all versions including Debian.
Read:
https://github.com/nodogsplash/nodogsplash/tree/master/forward_authentication_service/FAS-Docs
This is aimed at Openwrt/LEDE but almost the same for Debian, the only difference being the config for NDS is in /etc/nodogsplash/nodogsplash.conf.
The FAS splash.html does a meta redirect to your FAS server, wherever it is, and you have to allow access to it in the NDS config, all described in the documentation.
Follow exactly as far as you can and it should work.
Let us know haw you get on :-)

**Comment by mavridis92** [comment]
Hi Rob, thanks for quick reply!

I have checked your documentation and I have some questions as the FAS service seems that doesn't responses as I would like.

First,  in the forwarding-authentication-server folder, there is a nodog file, that you didn't mention where should be moved.  I supposed the right place is the apache folder "/var/www/html". Please, correct me if I'm false. In addition, what about "/etc/config/nodogsplash" configuration file, there are points that I don't understand how to fill. For example, 

option network 'lan'
That should be changed?  what is the right value?

option gatewayname 'NodogspalshFAS'
option maxclients '250'
option clientidletimeout '1200'
I have already identified that options in "/etc/nodogspalsh/nodogspalsh.conf", should I edit again?

Regards,

**Comment by bluewavenet** [comment]
@mavridis92 
What operating system are you using on your RPi?
The /etc/config/nodogsplash file is specifically for UCI configuration on OpenWrt/LEDE
The /etc/nodogsplash/nodogsplash.conf file is for OS that do not support UCI
Other than that, everything else is the same.
Nodog refers to a folder containing the script files for the FAS http server.

**Comment by mavridis92** [comment]
I'm working on debian. Also, in my case the nodogsplash and FAS service work on the same device.

**Comment by bluewavenet** [comment]
@mavridis92 
Debian uses the /etc/nodogsplash/nodogsplash.conf file, so you need to manually add the equivalent entries into that file.
Apache should be just fine for FAS, but any web server package supporting php will do (I use lightttpd/php7).
Best to configure Apache to serve http on a port other than 80, just to prevent any possible clash with anything else.
The structure of the nodogsplash.conf is somewhat different to the OpenWrt/LEDE UCI file but very straightforward.
The default is here:
https://github.com/nodogsplash/nodogsplash/blob/master/resources/nodogsplash.conf

For example, if the LAN interface you want to bind NDS to is wlan0 then edit the file such that it reads:
GateWayInterface wlan0

If your Apache is serving on say 10.168.1.1 port 8020, then add the following two lines -
In the FirewallRuleSet: preauthenticated-users section add:
      FirewallRule allow tcp port 8020 to 10.168.1.1
And in the FirewallRuleSet: users-to-router section add:
   FirewallRule allow tcp port 8020

All other parameters can be set depending on your use case. 

The FAS splash.html will of course need to be modified to reflect the IP and port number of your Apache server.

**Comment by mavridis92** [comment]
It works, I really appreciate your help in resolving the problem.
