### ISSUE TITLE
Any way to trace requests made by connected devices?

### ISSUE THREAD

**Issue by hatit** [nodogsplash/nodogsplash#252]
I want to know things such as:
- User-Agent used by each request.
- Url requested by each client.

I want to measure QoS such as:
- Response time.

How can i do this?

thanks

**Comment by hatit** [comment]
Great, thanks for this info.---- On Mon, 25 Jun 2018 07:23:05 -0500  Moritz Warning<notifications@github.com> wrote ----That is not implemented at this time. The URL is written as part of the debug output: https://github.com/nodogsplash/nodogsplash/blob/master/src/http_microhttpd.c#L252 The http header can be printed out with this code: static int header(void *cls, enum MHD_ValueKind kind, const char *key, const char *value)
{
 printf("key: %s, value: %s
", key, value);
 return MHD_YES;
}

// .. and in libmicrohttpd_cb() call:
MHD_get_connection_values(connection, MHD_HEADER_KIND, &header, NULL);
 Reponse time can be gathered from the client->added_time, but the details are a bit more complicated.  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bluewavenet** [comment]
@hatit 
Although what you are looking for is not directly implemented in NDS, you can use Forwarding Authentication (FAS) to run your own scripts triggered by the captive portal detection (CPD).

In this way you can use any tool or package available on the platform. 

For example in php:  "$agent=$_SERVER['HTTP_USER_AGENT'];"

Your scripts can also read the output of "ndsctl clients" to glean much information about client connections.

Dnsmasq can be configured to log all DNS requests and your scripts can use this, but be aware that your router may run out of storage or ram quite quickly as dnsmasq will generate a lot of data.

https://github.com/nodogsplash/nodogsplash/tree/master/forward_authentication_service
