### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by haniavis** [nodogsplash/nodogsplash#253]
Hi,

I would like all my users to see the splash page every time they connect to my wifi network, even if he/she is already authenticated. I can not use the clientidletimeout since it can be reduced only to 1 min. 

Moreover, for some reasons in my setup I need to restart NDS and so I would like to keep the state of the authenticated users after a restart of the nodogsplash service. Ideally, I would like to keep the connected MACs in a file (which I can do) then restart NDS and then automatically re-connect the users (MAC addresses in the file). But there is no command to re-connect a user, since NDS connects a user only when he/she performs an action in the network.

Could you help me on the above issues?

**Comment by bluewavenet** [comment]
If you want a clientidletimeout of less than one minute, then why do you want them to authenticate in the first place?
Are you trying to JUST give the splash page and nothing else?

**Comment by haniavis** [comment]
I just thought of the clientidletimeout as a solution, but it seems it doesn't help.

I need to show the splash page and then redirect to my local portal. If someone who has already seen the splash page connects again, I need to show him again the splash page.

**Comment by bluewavenet** [comment]
If I am guessing correctly, you want NDS to always redirect to a local web server (your portal) and not let anyone have access to the Internet.
You want people to have the NDS splash pop up every time they connect.

If this is true, then the answer is simple, just have splash.html do a meta redirect to your local portal. **Do not authenticate at all.**
This will have the desired effect.

If this is indeed what you want to achieve then a few other things might need setting up depending on what your portal is going to be doing and if Internet access is present or not.

**Comment by haniavis** [comment]
Thanks for your answers regarding my first issue!

Regarding my second issue:
"Moreover, for some reasons in my setup I need to restart NDS and so I would like to keep the state of the authenticated users after a restart of the nodogsplash service. Ideally, I would like to keep the connected MACs in a file (which I can do) then restart NDS and then automatically re-connect the users (MAC addresses in the file). But there is no command to re-connect a user, since NDS connects a user only when he/she performs an action in the network."

I could think of 2 solutions:
1) to have a command to automatically "add" users in NDS without requiring from them to make an action in port 80 in order NDS to detect them.
or
2) not to require to restart NDS in case I change its conf file (/etc/nodogsplash/nodogsplash.conf).

Do you have a suggestion on the above?

**Comment by bluewavenet** [comment]
I don't understand what you are trying to do.
You seem to have two contradicting requirements.
1. Everyone gets the splash page **EVERY** time they connect
2. Everyone gets the splash page **ONLY** the first time they connect.

I must be missing something here.

**Comment by haniavis** [comment]
As you can see in my first post I have two different questions/issues. The first one (get the splash page every time they connect) was my first issue which I understood how to solve, thanks to your answers.

Now, what I was describing in my last post is a totally different one. It is about keeping the exact state of NDS (connected users in "pre-auth" or "auth") after an NDS restart.

**Comment by bluewavenet** [comment]
There is no current way to restore client states after an NDS restart.
Why do you need to restart NDS? What setup parameters do you need to change?

**Comment by haniavis** [comment]
We are changing nearly every parameter of the nodogsplash.conf file.

GatewayInterface when we change the physical wifi interface of our network on the raspberry from the built-in one to the USB.
RedirectURL if our user changes the domain of the network
and most importantly we edit the rules of each group (pre-auth, auth, trusted) according to the mode of our network (offline for block Internet access to authenticated users and online for permit Internet access to authenticated users).

That's why we need to restart our NDS service.

**Comment by bluewavenet** [comment]
It seems to me that you are approaching this entirely the wrong way. The parameters you mention should not change very often, if ever, in a normal captive portal situation.
However it is very straightforward to achieve what you want without restarting NDS as follows:
1. GatewayInterface. If for example the venue could be using for example WiFi A and/or WiFi B depending on which areas of the venue are in use, then simply bridge the physical interfaces in your NDS device at the network level and set the GatewayInterface to the virtual bridge (this is the default for NDS ie br-lan).
2. If the operators of the venue want to change the URL of the web site that users are redirected to, numerous times in an operating period, then point RedirectURL to a fixed URL that is a web page that in turn redirects to the "Page of the Day". This URL could very conveniently reside on the NDS device, using lighttpd, apache for example. 
3. Changing the firewall rules as part of some transparent mode change is easily achieved by using iptables commands.
You can view the current rules with the commands:
iptables -t filter -L ndsNET  (preauthenticated users)
iptables -t filter -L ndsAUT (aurthenticated users)
iptables -t filter -L ndsRTR (users to router)

These can be changed or extended using relevant iptables commands.

**Comment by haniavis** [comment]
OK thanks for your answers! we found the way to solve this.
