### ISSUE TITLE
Can we redirect to app store after authentication to captive portal ?

### ISSUE THREAD

**Issue by alter-sachin** [nodogsplash/nodogsplash#254]
Hi 
I am using NDS for use on my local wifi network and my use case requires that I redirect to 
google playstore after authentication from the user.

Is this possible ?

**Comment by bluewavenet** [comment]
Yes you can, but depending on the vendor and Android version of the user's device, the Andriod CPD will automatically close its login screen as soon as it verifies authentication was successful. 
The NDS config "RedirectURL"  was the parameter to set but for the above reason is deprecated. In fact I think this is no longer available in NDS v2.
You can inject the redirect URL (as $redir) into the html authentication GET in splash.html but there is no guarantee the user will see the redirection.

**Comment by nomercy0** [comment]
hi @bluewavenet  redirection is not working all android CPD but works with some android devices.
Is there a way that I can Keep captive portal open in android devices after authentication of user in FAS service of nodogsplash.
This way I can provide user a link to playstore in landing.php page
I found a way to do this by blocking the captive checking sites after user has authenticated but I am not able to block the sites as your documention suggest to use only ip addresses from blocking
Here is the reference link
[](https://stackoverflow.com/questions/34933146/prevent-captive-portal-auto-close-after-authentication-android)
[](https://github.com/aruba/clearpass-cloud-service-whitelists/blob/master/onboard/onboard_android.md)

**Comment by alter-sachin** [comment]
Okay . 
I think i have found a workaround .

How do i block a particular nameserver for a particular period of time .

**Comment by bluewavenet** [comment]
Blocking a particular nameserver from a user? By default ALL external nameservers should be blocked by NDS with users only able to access the DNS service on the NDS box. The nature of DNS is that it is resilient with any nameserver being able to reply from cached values.

**Comment by alter-sachin** [comment]
Hey. Sorry.
I want to do this AFTER authentication. For a limited time period. 
I am willing to give up any security for a certain set of nameservers. Use case demands this

**Comment by bluewavenet** [comment]
This is nothing to do with NDS. Blocking just some nameservers will not have any effect, a domain will still resolve. Also your users are required to be using the DNS server specified by DHCP. They will not ever become preauthenticated if this was not the case.

**Comment by nomercy0** [comment]
hi @bluewavenet redirection is not working all android CPD but works with some android devices.
Is there a way that I can Keep captive portal open in android devices after authentication of user in FAS service of nodogsplash.
This way I can provide user a link to playstore in landing.php page
I found a way to do this by blocking the captive checking sites after user has authenticated but I am not able to block the sites as your documention suggest to use only ip addresses for blocking
Here is the reference link
[1](https://stackoverflow.com/questions/34933146/prevent-captive-portal-auto-close-after-authentication-android)

**Comment by bluewavenet** [comment]
@nomercy0 
While your users are on the fas.php page they are still not authenticated and the page will not close. So add the links to wherever you want them to go as well as an authenticate button. You will need to allow by IP address in the NDS config for Preauthenticated users.
This is "whitelisting" a known site and therefore fairly easy.
There are issues with this:
1. CPD has a refresh interval - for some implementations this is 300 seconds, for others I have seen 3600 seconds, and I am sure there are more variations.
2. CPD commonly uses a restricted browser that may not allow external links, javascript or downloads.

For your proposal, there are many more captive checking sites than you may imagine as vendors commonly set up their own. Blacklisting all of them could be quite difficult and something that needs updating to keep up with releases. Also this blacklisting will have to be at an individual user level whilst authenticated, and switched off before the CPD timeout interval takes them back to the beginning.

Finally, my statistics from many hotspot venues show around 65% iOS, 35% Android and an insignificant proportion of others. I am not sure how this effects what you are trying to do.
