### ISSUE TITLE
NDS Config Option Splashpage not served by MHD - Splash.html Served Instead.

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#255]
An alternate splash page set in the config option "splashpage" is not served by MHD, instead the default splash.html is served instead.
The command "ndsctl status" however, reports the splash page as it is configured.
My C is not that good and I may have this wrong but looking at http_microhttpd.c line 971:
	snprintf(filename, PATH_MAX, "%s/%s", config->webroot, url);

should this be:
	snprintf(filename, PATH_MAX, "%s/%s", config->webroot, config->splashpage);
?
@lynxis @mwarning

**Comment by mwarning** [comment]
line 971 is in method serve_file(). That line is correct, as it serves css, image or other files that are part of the splash site. See method show_splashpage(), it uses config->splashpage.

**Comment by mwarning** [comment]
How can this problem be reproduced? What kind of devices are involved?

**Comment by bluewavenet** [comment]
@mwarning 
Yes it is easy to reproduce.
I have NDS v2.1.1 on LEDE 17.01.4 (hardware GL-iNet AR300M 128MB ram 16MB flash)
I discovered this as follows:
1. rename splash.html to sfas.html
2. run commands:
uci set nodogsplash.@nodogsplash[0].splashpage='sfas.html'
uci commit nodogsplash
service restart nodogsplash

Then on running ndsctl status, it reports the expected "Splashpage: /etc/nodogsplash/htdocs/sfas.html"
On connecting a client, CPD is invoked in the normal way but displays error 404

Rename sfas.html back to splash.html CPD displays the normal splash.html

**Comment by bluewavenet** [comment]
My motive in trying this:
As there is quite a lot of interest in FAS, I am looking to integrate it into the NDS package. Using option splashpage and adding a new option of sfas_port plus an additional script file would enable this.

**Comment by bluewavenet** [comment]
First part of .conf file:
`#`auto-generated config file from /etc/config/nodogsplash
GatewayInterface br-lan
gatewayname NoDogSplash
maxclients 250
webroot /etc/nodogsplash/htdocs
splashpage sfas.html
.......etc

Output of ndsctl clients:
==================
NoDogSplash Status
====
Version: 2.1.1
Uptime: 0d 0h 0m 25s
Gateway Name: NoDogSplash
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: 10.168.1.1:2050
Splashpage: /etc/nodogsplash/htdocs/sfas.html
Traffic control: no
Total download: 7 kByte; avg: 2.47488 kbit/s
Total upload: 6 kByte; avg: 1.992 kbit/s
====
....etc.
Yet MHD serves a 404 error.

**Comment by mwarning** [comment]
@bluewavenet your FAS comes with some big dependencies. Better make it a separate package that depends on nodogsplash. This keeps down complexity.

**Comment by bluewavenet** [comment]
True but fixing the splashpage option and (possibly) adding another will not add complexity but will enable that separate package to be implemented, or indeed open up the possibility of yet other packages that depend on NDS.

**Comment by bluewavenet** [comment]
Adding such hooks to NDS can add tremendously to the flexibility of NDS without adding complexity.
As you say, the complexity is best placed elsewhere.

**Comment by bluewavenet** [comment]
Setting option webroot works.

**Comment by bluewavenet** [comment]
Interestingly - with splashpage set to something other than splash.html AND splash.html is still present, splash.html is served but none of the variables are passed to it (eg $redir etc)

**Comment by mwarning** [comment]
I have found the problem. See https://github.com/nodogsplash/nodogsplash/blob/master/src/http_microhttpd.c#L520
@lynxis is there a reason this is hardcoded?

**Comment by bluewavenet** [comment]
@mwarning Sorry, I don't see why this stops option splashpage from working...

**Comment by mwarning** [comment]
ah, yeah, I also had that moment of confusion when I clicked the now out of date link above. :-)
