### ISSUE TITLE
New FirewallRuleSet

### ISSUE THREAD

**Issue by mavridis92** [nodogsplash/nodogsplash#256]
Hi, 
I'm working on nodogsplash v1, and for some specific reasons on my project, I need a new  FirewallRuleSet as I have already used all available (authenticated-users, preauthenticated-users,users-to-router, trusted-users,trusted-users-to-router). My question is that. Is it possible to create a new FirewallRuleSet in config file from scratch? For example, I would like to create a FirewallRuleSet not-need-authenticated where I will edit rules for some ports.

**Comment by bluewavenet** [comment]
Creating a new FirewallRuleSet is not suported.
Do you mean you want to create rules that apply to Trusted Users? Trusted users are defined as not needing authentication and having no firewall restrictions imposed by NDS. Version 1 does not allow iptables chaining so no further restrictions can be imposed.
Version 2 does support chaining, so upgrading will allow you to create additional firewall rules in the firewall its self.
