### ISSUE TITLE
Restart command

### ISSUE THREAD

**Issue by alissonrodrigo** [nodogsplash/nodogsplash#257]
Is there any command I can restart NoDogSplash via get or some html verb. I use FAS to login.

tks

**Comment by alissonrodrigo** [comment]
It would not be basically an interface for admim, I would just run the nodogsplash reboot through a command external to the LUCI. would?

thankful

**Comment by bluewavenet** [comment]
If you are running a PHP FAS server on the same machine as NDS, something like:
`$status=exec("sudo /etc/init.d/nodogsplash restart");`
would do it.
However restarting will block every client and confuse their CPD. Some implementations of CPD require a manual disconnect/reconnect of the wifi for it to be triggered again, whereas some have a 10 minute timeout... Most users just think the network has failed.
