### ISSUE TITLE
IOS issue

### ISSUE THREAD

**Issue by flibble666** [nodogsplash/nodogsplash#259]
NDS version: latest 2.1.1 Raspbian Stretch
ISO: 11.4
Ok every think works fine on every android device ive tested it on 5+devices.
When i a friend try's to use the hotspot with his iphone when clicking on the $authtarget simple http method a pop up appears saying "cannot open authorisation page  no connection to server" and then disconnects from the wifi.

**Comment by flibble666** [comment]
Sorry bit of a noob i normally only do hardware repairs this is for a friends coffee shop.can you explain do you mean just use $authaction instead ?

**Comment by bluewavenet** [comment]
The default splash.html uses $authaction and you can see how to use it there.
Have you changed to $authtarget for any particular reason?

**Comment by flibble666** [comment]
Thank you for all the work on this project and your help. As for a particular reason i followed [`this `](https://openwrt.org/docs/guide-user/services/captive-portal/wireless.hotspot.nodogsplash) tutorial.

**Comment by bluewavenet** [comment]
That link is very old and talks about even older versions of OpenWrt even if it was last modified on 2018/05/24.
Revert to the default splash.html in v2.1.1 and it should work.

**Comment by flibble666** [comment]
Thankyou for all you help keep up the amazing woirk.
