### ISSUE TITLE
OpenWRT nodogsplash2 configuration

### ISSUE THREAD

**Issue by DanielRIOT** [nodogsplash/nodogsplash#261]
I'm building nodogsplash2 into OpenWrt from menuconfig
OpenWrt version is the current master : https://github.com/openwrt/openwrt

```
Linux OpenWrt 4.14.59 #0 SMP Tue Jul 31 12:04:45 2018 armv7l GNU/Linux
Linux version 4.14.59 (openwrt@openwrt-VirtualBox) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r7702-c72f3b5)) #0 SMP Tue Jul 31 12:04:45 2018
CPU: ARMv7 Processor revision 5 (ARMv7), 
```

and it seems that the  current build from openWRT's install scripts uses the ["old" config ](https://github.com/openwrt-routing/packages/blob/master/nodogsplash2/files/etc/config/nodogsplash) file that has the "option enabled 1" type syntax, and not the one reflected in this repo.

When I try and start nodogsplash :
```
root@OpenWrt:/# /etc/init.d/nodogsplash start
/etc/rc.common: eval: line 1: test_module: not found
Nodogsplash is missing some kernel modules.
```
When I try and run the binary I get :
```
root@OpenWrt:/# /usr/bin/nodogsplash
[3][Tue Jul 31 14:24:54 2018][2816](src/conf.c:690) FATAL: Could not open configuration file '/etc/nodogsplash/nodogsplash.conf', exiting...
```

When I replace the config file ( /etc/config/nodogsplash ) with [this ](https://github.com/nodogsplash/nodogsplash/blob/master/resources/nodogsplash.conf) one  it seems to start, but ndctl cannot connect to it and there is no captive portal behavior on the gatewayInterface either : 
```
root@OpenWrt:/# /etc/init.d/nodogsplash start
root@OpenWrt:/# /usr/bin/ndsctl status
ndsctl: nodogsplash probably not started (Error: Connection refused)

```

I get the same behavior when I install in from opkg ( opkg install nodogsplash2 )

is this an issue due to the OpenWRT install scripts or something else ?

**Comment by mwarning** [comment]
I can confirm the problem, the init script has a reference to dead code that somehow wasn't triggered in my test configuration.

**Comment by mwarning** [comment]
@DanielRIOT should be fixed now. Please reopen ticket if that is not the case.
