### ISSUE TITLE
Support luci-app-nodogsplash ?

### ISSUE THREAD

**Issue by ikokang** [nodogsplash/nodogsplash#272]
Administrators can easily change the relevant nodogsplash parameters on the background page, and also support the external FAS settings.

**Comment by bluewavenet** [comment]
NDS Version 3.1.0 will be released very soon and it supports uci configuration of both FAS and the new Binauth functionality.
A luci-app-nodogsplash would be nice but not really necessary. If you fancy writing one Pull Requests are welcome!
