### ISSUE TITLE
Nodogsplash not working on old raspberry pi 1 model A

### ISSUE THREAD

**Issue by Steveblues** [nodogsplash/nodogsplash#275]
Environment

raspberry pi
raspberry pi 1 with Stretch

What did you do?

First, i was able to set the raspberry as a wireless access point

Then I was trying to make a captive portal with my old raspberry pi, and I followed these 2 tutorials for it, step by step (I do not know too much about python, or raspberry, but this project seemed interesting)

https://pimylifeup.com/raspberry-pi-captive-portal/
https://pimylifeup.com/raspberry-pi-wireless-access-point/

so i ran the command sudo nodogsplash as the step said

What did you expect to see?

It was supposed to work everything just fine, then if I connected to the wifi from another device, a page was supposed to pop up

What did you see instead?
`iptables:No chain/target/match by that name`

And I am no longer able to connect to the wifi I just set

**Comment by mwarning** [comment]
I can confirm the error. Thanks for sharing!

**Comment by mwarning** [comment]
For the record, the problem is that the second rule does not execute:
```
iptables --wait -t nat -N ndsOUT
iptables --wait -t nat -A ndsOUT -m mark --mark 0x20000 -j RETURN
```
