### ISSUE TITLE
FAS not working

### ISSUE THREAD

**Issue by lrz0** [nodogsplash/nodogsplash#280]
Not sure if I should post this here, but it seems FAS is not working at all.

Read the documentation, uploaded the fas PHP files to a remote webserver, and modified the configuration file on my OpenWRT with nodogsplash installed as follows:

  FirewallRuleSet preauthenticated-users {
	FirewallRule allow tcp port 80 to 185.104.29.28
  }
  
  fasport 80
  fasremoteip 185.104.29.28
  faspath https://auth.portalsocial.es/fas.php
  fas_secure_enabled 0

This has been added in "/etc/config/nodogsplash", the only config file there is within OpenWRT.

These lines (FirewallRuleSet) start at line 84. When I restart the service, it says the following:

Sun Aug 26 17:19:41 2018 daemon.err uhttpd[981]: uci: Parse error (invalid command) at line 84, byte 2
Sun Aug 26 17:19:41 2018 daemon.err uhttpd[981]: sh: 1: unknown operand

How can this be an unknown command if I copied the directives from your example file?

Complete file of "/etc/config/nodogsplash" attached:

[etc-config-nodogsplash.txt](https://github.com/nodogsplash/nodogsplash/files/2321637/etc-config-nodogsplash.txt)

**Comment by lrz0** [comment]
I realized the options are declared differently in my copy of nodogsplash.

I have added the following instead:

list preauthenticated_users 'allow tcp port 53'
list preauthenticated_users 'allow udp port 53'
list preauthenticated_users 'allow tcp port 80 to 185.104.29.28'
option fasport '80'
option fasremoteip '185.104.29.28'
option faspath 'https://auth.portalsocial.es/fas.php'
option fas_secure_enabled '0'

When restarting the service, I do not get an error, but it doesn't work either. The redirect simply times out. Here are the copies of my files:

/etc/config/nodogsplash
[etc-config-nodogsplash.txt](https://github.com/nodogsplash/nodogsplash/files/2321647/etc-config-nodogsplash.txt)

/etc/nodogsplash/htdocs/splash.html
[etc-nodogsplash-htdocs-splash-html.txt](https://github.com/nodogsplash/nodogsplash/files/2321648/etc-nodogsplash-htdocs-splash-html.txt)

Please help me out, what's going wrong here? I've been tinkering with this all day and I just can't seem to get it to work!

**Comment by mwarning** [comment]
@lrz0 what version of nodogsplash do you use?

**Comment by lrz0** [comment]
I'm using version 2, not sure which one _exactly_ but I installed it
through the LuCi interface of OpenWRT, the package name was nodogsplash2
from the current opkg repository of OpenWRT. Not sure how to check the
version, doesn't mention in the config file.

Op zo 26 aug. 2018 om 18:13 schreef Moritz Warning <notifications@github.com

**Comment by mwarning** [comment]
```
option fasport '80'
option fasremoteip '185.104.29.28'
option faspath 'https://auth.portalsocial.es/fas.php'
option fas_secure_enabled '0'
```

These options are for the not yet released nodogsplash 3.1.0 and are not recognized by the init script on OpenWrt yet.

**Comment by lrz0** [comment]
Ok, but how would I go about this then?

Is there a way I can add these options in a config file and include that
with the following?

Use plain configuration file
option config '/etc/nodogsplash/nodogsplash.conf'

Op zo 26 aug. 2018 om 18:28 schreef Moritz Warning <notifications@github.com

**Comment by mwarning** [comment]
@bluewavenet it might be good to raise an error if there is an unknown option.

**Comment by mwarning** [comment]
@lrz0 you can use `option config '/etc/nodogsplash/nodogsplash.conf'`. But Nodogsplash 3.0.0 does not support these options yet anyway. That is for the upcoming 3.1.0.

**Comment by lrz0** [comment]
I don't understand, why is it not supported? It's documented as being
supported, and I can see in other threads that other users are using it?
So, how come other users are using it?

Op zo 26 aug. 2018 om 18:33 schreef Moritz Warning <notifications@github.com

**Comment by lrz0** [comment]
For example, this user got it to work:

https://github.com/nodogsplash/nodogsplash/issues/220

However, i can't get it to work and I don't understand why.

Op zo 26 aug. 2018 om 18:35 schreef Laurens Pilger <laurens.pilger@gmail.com

**Comment by mwarning** [comment]
Forward Authentication Service (FAS) was available before. But for the upcoming Nodogsplash 3.1.0, FAS support was integrated in NDS (the fas_* options were added etc.) and the documentation in the repository has already been updated.

Here is the documentation for for NDS 3.0.0:
https://github.com/nodogsplash/nodogsplash/tree/v3.0.0/forward_authentication_service
Avoid the documentation for the development version.

**Comment by lrz0** [comment]
Actually i'm running 2.1.1-1, just checked. Does this have FAS? Is there any way I can use FAS, and if not, when will a FAS-enabled version come out? I was so happy to finally find this. This is very confusing.

In the #220 issue, which is from January, it is available, so which version is that?

**Comment by mwarning** [comment]
Here you go: https://github.com/nodogsplash/nodogsplash/tree/v2.1.1/forward_authentication_service

**Comment by lrz0** [comment]
The documentation you just provided states "Fortunately, Forwarding Authentication can be done without any modification to the core NDS code and in a way that is compatible with all versions, pre v1 beta through to the current release of v2." and i am running v2, so according to that information it should work, or is this just wishful thinking?

**Comment by lrz0** [comment]
I'm afraid i don't completely understand. If I use the config file from your last link, and the splash.html also, it should work?

**Comment by mwarning** [comment]
yes, that should work.

**Comment by lrz0** [comment]
Excellent, seems to work. However, I use HTTPS, I just open up 443 right?

**Comment by mwarning** [comment]
I think so. But I have never user FAS myself.

**Comment by lrz0** [comment]
That worked. Thanks SO MUCH for the quick help!

**Comment by bluewavenet** [comment]
@lrz0 
NDS Version 3.1.0 will be available very shortly (I mean around a day to wait).
Initially you will have to download from OpenWrt snapshots but it will work on Openwrt/LEDE 17.01 and above.
It will really be better to wait just a short while for the new version, then it will be very easy for us to help you get going!
It is nice to see you so keen to get going - I will hurry up with the release :-D
I will post a link here, for the download, when it is ready.

**Comment by lrz0** [comment]
Thanks for your advice. Of course if a new version gets out, I will make the upgrade directly, but for now I can at least tinker around and make a Facebook integration on my remote AUTH/FAS script. When it updates, I probably won't have to change much anyway.

I am running OpenWRT 18.06.1 by the way, came out a week ago.

If you have 3.1.0 could you please point me to the correct location and if at all possible give me instructions how to install? Up until now, i've been tinkering on OpenWRT with opkg and the LuCI GUI so this will probably be a bit harder but i do have some Linux experience so should be doable.

**Comment by mwarning** [comment]
It will probably be in the openwrt package feed shortly after release.
But 18.06.1 has a fixed package feed version. So you might want to configure opkg or use a nightly openwrt image.
The newest documentation is available here:  https://nodogsplash.readthedocs.io/en/latest/

**Comment by bluewavenet** [comment]
@lrz0 
v3.1.0 is now available to download for OpenWrt.
Go to:
https://downloads.openwrt.org/snapshots/packages/
Select your architecture
nodogsplash v3.1.0 is in the routing folder.

Installing is very simple. 
But first you must get the package file onto your Openwrt device.
A simple beginner's method is to install openssh-sftp-server from Luci. Thin you can use any sftp client to move the file to /tmp on Openwrt.
Then ssh to OpenWrt and:
cd /tmp
opkg install <nodogsplash-packagefile>

**Comment by lrz0** [comment]
Thanks a lot. Anywhere I can see the changes between 2.1.1-1 and 3.1.0 please?

**Comment by bluewavenet** [comment]
@lrz0 
https://github.com/nodogsplash/nodogsplash/blob/master/ChangeLog

**Comment by bluewavenet** [comment]
@lrz0 
New link to the online documentation, the old one was not updating.
New link is:
https://nodogsplashdocs.rtfd.io/
