### ISSUE TITLE
The authentication page shows that the running time is not correct, and the upload byte and download byte are invalid.

### ISSUE THREAD

**Issue by ikokang** [nodogsplash/nodogsplash#286]
The authentication page shows that the running time is not correct, and the upload byte and download byte are invalid.

uptime: $uptime
uploadedbytes: $uploadedbytes
downloadedbytes: $downloadedbytes

**Comment by bluewavenet** [comment]
@ikokang 
What version are you using and on which operating system/version ?

**Comment by bluewavenet** [comment]
@ikokang 
Try $uploadbytes and $downloadbytes
I think the comment in splash.html is incorrect.

**Comment by mwarning** [comment]
uptime might be incorrect on OpenWrt, because the clock might not have been set correctly at that time.
@ikokang do you use OpenWrt?

**Comment by bluewavenet** [comment]
$uptime seems ok on OpenWrt 17.01.4 - just tried it.
Also $uploadbytes and $downloadbytes are correct on NDS v3.2.0

**Comment by ikokang** [comment]
Starting from version 3, the running time is incorrect.

**Comment by bluewavenet** [comment]
It seems to be correct on OpenWrt 17.01.4 and NDS v3.2.0
What error/result is it giving you?

**Comment by bluewavenet** [comment]
$uptime is the elapsed time since NDS started.

**Comment by ikokang** [comment]
I'm sorry to restart the router and get the correct time display.

**Comment by bluewavenet** [comment]
@ikokang 
$uptime is ok for you now?
The Available variables list in splash.html is in error, but otherwise $uploadbytes and $downloadbytes work ok?

**Comment by ikokang** [comment]
and the upload byte and download byte are invalid.

This is the custom code on my authentication page. http://103.89.137.197/20180903233439.png

**Comment by bluewavenet** [comment]
Change those two lines in your code to:
$uploadbytes
(**not** $uploadedbytes)
and
$downloadbytes
(**not** downloadedbytes)

**Comment by ikokang** [comment]
The normal upload and download parameters are now displayed as "0".

Does this function display single terminal traffic data, or do all terminals authenticated traffic data?

Is it possible to increase the number of online terminals that have been authenticated?

**Comment by bluewavenet** [comment]
It will always display "0" upon first authenticating as the client will not have uploaded or downloaded anything yet.
If their session times out and they authenticate again it will show their previous upload download.

The default number of clients is 250
in /etc/confignodogsplash
ie   option maxclients '250'

**Comment by mwarning** [comment]
@bluewavenet afaik, if the the clients session times out, the client counters will be reset.

**Comment by mwarning** [comment]
The variable is not exposed. But it would be easy to implement.

**Comment by ikokang** [comment]
My idea is to use variables to display the total number of online terminals and authorized terminals on splash. html, as well as the total download and upload traffic from the current authentication interface.

The above functions can be seen in the SSH state using the ndsctl status command. If you can display these variables to the terminal on the authentication page, the visitor experience effect will be good.

**Comment by mwarning** [comment]
Should be doable.
@bluewavenet we should also client specific variable data more apparent. Maybe clientupload, clientdownload instead of uploadbytes/downloadbytes.

**Comment by bluewavenet** [comment]
@mwarning Yes you are correct. I did an ndsctl deauth of a client, then refreshed the connection on the client to trigger CPD. splash then reports useful totals.

@ikokang  You can do what you want very easily using FAS. Once on your FAS login page you can simply enquire from ndsctl and display whatever you need.
Follow the simple guide here:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

**Comment by bluewavenet** [comment]
@mwarning 
These variables are of little use as more often than not just return zero. Removing rather than changing the names might be more sensible. After all the default splash page is supposed to be very simple.

**Comment by mwarning** [comment]
If uploadbytes/downloadbytes is 0, then so does the binauth script get this value.

**Comment by ikokang** [comment]
To enable php in uhttpd you must add the line:
list interpreter ".php=/usr/bin/php-cgi"
to the /etc/config/uhttpd file in the config uhttpd ‘main’ or first section.

OpenWrt Development Edition Select default "luci-nginx"，LuCI interface with Nginx as Webserver，
There are corresponding settings in the Nodogsplash document。

**Comment by bluewavenet** [comment]
You can use any web server you like as long as there is enough flash and ram in your router.
The default on OpenWrt is uhttpd and the Nodogsplash documentation gives an example of using this.

**Comment by bluewavenet** [comment]
@mwarning Yes, Binauth will get zero on first login, as it is valid - client cannot do anything until authed of course.

**Comment by ikokang** [comment]
Thank you for two enthusiastic answers. I will try to use Forwarding Authentication Service (FAS).
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

**Comment by bluewavenet** [comment]
@ikokang You should use nodogsplash 3.2.0 for the best results. It is available in https://downloads.openwrt.org/snapshots/packages/
or will be in a few hours as it was only released today. This is the new stable release, despite being in snapshots.

**Comment by ikokang** [comment]
By noon Beijing time yesterday, I had found an updated version of Nodogsplash 3.2.0

OpenWrt 18.06 Stable version can be used to compile firmware with this configuration file.
https://github.com/openwrt-routing/packages/tree/master/nodogsplash

**Comment by ikokang** [comment]
@bluewavenet

You can already use the FAS service. You need a username and password when you log in. I know you can get it at users. dat! Two problems are encountered at this time:

1. Can you use the specified page "index. php" to write the relevant user name and password to "users. dat" without using the SSH function?

2. FAS does not use username and password to authenticate, but clicks or touches to authenticate. How to set it?

**Comment by bluewavenet** [comment]
@ikokang 
If you are new to PHP you might find this is a good guide:
https://www.w3schools.com/php/

**Comment by ikokang** [comment]
@bluewavenet I mean: how to close the username and password to authenticate when using FAS.

**Comment by bluewavenet** [comment]
@ikokang 
Look at function acceptance () in fas.php.
This does a GET request to NDS, very similar to that in splash.html
