### ISSUE TITLE
Failed to install nodogsplash 3.2.0 because could not satisfy dependency kernel 4.14.67

### ISSUE THREAD

**Issue by Thuan2000** [nodogsplash/nodogsplash#289]
My TP-Link Wi-Fi router has kernel version 4.14.66 so I couldn't install Nodogsplash 3.2.0

**Comment by Thuan2000** [comment]
[
<img width="570" alt="issue" src="https://user-images.githubusercontent.com/15158402/45019747-491bc480-b057-11e8-8f9e-7852f9563d10.png">
](url)

**Comment by ikokang** [comment]
你会编译固件不？直接安装的话，我也出现过错误。后来我通过编译就解决这个问题。

**Comment by mwarning** [comment]
NDS does not depend on a specific kernel version. I wonder why the package requires a specific kernel..

`opkg install --force-depends <ipk_path>` should work around the problem.

**Comment by mwarning** [comment]
Ok, someone told me that the user has an older OpenWrt snapshot, so when trying to install nodogsplash it tries to install iptables-mod-ipopt, which depends on kmod-ipt-ipopt, which depends on the newer kernel.

opkg trying to install a kernel module from the repository that is not compatible with the current kernel is the problem.

**Comment by bluewavenet** [comment]
For the benefit of anyone else reading this, nodogsplash 3.2.0 is a stable release even though it is available in OpenWrt snapshots. It has been tested on OpenWrt 17.01.4, 17.01.5 and 18.06.1.

**Comment by Thuan2000** [comment]
OK, this is how I resolved it. It works now. 
Basically I just flashed the router's firmware to use OpenWrt version 18.06.1
