### ISSUE TITLE
Add template variable for currently authenticated users

### ISSUE THREAD

**Issue by mwarning** [nodogsplash/nodogsplash#290]

**Comment by bluewavenet** [comment]
Three new variables
 * number of authenticated
 * number of preauth
 * number of free connections left

**Comment by bluewavenet** [comment]
or
 * number of authenticated
 * total number of connected clients  (auth +preauth)
 * number of free connections left (max_clients - auth - preauth)

**Comment by bluewavenet** [comment]
We are only concerned with "User Experience" with these changes. In my experience users are not in the least concerned and it is not of any use from a functionality of the splash page point of view. It is just a "nice to have". I don't think we should change any core functionality just for the sake of displaying something that is only as useful as a visitor counter on a web page.
Maxclients is the maximum number in the client list so is auth plus preauth. Trusted and blacklisted don't count right now do they?

**Comment by mwarning** [comment]
Yes, your view of maxclients that is correct.
Trusted and blacklist is a different data structure.

**Comment by ikokang** [comment]
Variable counters are not mandatory Wi-Fi visitors will be able to see. Providing support for variable counters is very helpful to customize Nodogsplash and FAS services.

**Comment by bluewavenet** [comment]
https://nodogsplashdocs.readthedocs.io/en/stable/faq.html#is-https-capture-supported
Https is more than just encryption. It is specifically set up to prevent and warn against any attempts to redirect from the intended target web site.

At some stage in the future it MAY be possible to capture https by a captive portal returning server error 511 to the browser. This is not currently supported in any browsers as far as I can tell.
see:
https://tools.ietf.org/html/rfc6585#section-6
