### ISSUE TITLE
OpenWrt 18.06.1 opkg install get nodogsplash version 1.0.2-1 (Not 3.2.0)

### ISSUE THREAD

**Issue by Thuan2000** [nodogsplash/nodogsplash#291]

**Comment by Thuan2000** [comment]
Why am I getting old version not the new version (3.2.0)? .__.

**Comment by ikokang** [comment]
Only using openwrt development edition is the latest.
https://github.com/openwrt-routing/packages/tree/master/nodogsplash

**Comment by Thuan2000** [comment]
@ikokang Ah, I see. Thanks! 
When will version 3.2.0 be ready for the current OpenWrt stable release (18.06.1)?

**Comment by ikokang** [comment]
@Thuan2000 You can compile and use the latest version of nodogsplash 3.2.0 simply by deleting the old nodogsplash configuration directory file and copying the latest version of the configuration

**Comment by mwarning** [comment]
https://github.com/openwrt-routing/packages/pull/407

**Comment by mwarning** [comment]
That is a matter of time and not in our hands. :-)

**Comment by bluewavenet** [comment]
It's available for some architectures already, a few hours should see it on all.

**Comment by Thuan2000** [comment]
Thanks guys!
