### ISSUE TITLE
Error 404 - Not Found on port 2050 after authentication

### ISSUE THREAD

**Issue by ricxsar** [nodogsplash/nodogsplash#296]
Hi. I'm implementing my own FAS server with session so that the user will have the power to view its usage. I setup the splash.html to redirect to my FAS server. 

If the user is already logged in and they want to view its statistics, they will visit the router_ip:2050 and they will be redirected to the FAS server but the nodogsplash returns `Error 404 - Not Found`.

Is this error normal? I wan't the nodogsplash functions as it should be like the previous version that it is still accessible. 

Thanks.

**Comment by bluewavenet** [comment]
@ricxsar 
What versions of NDS/OS are you running and what hardware?
NDS v3.2.0 is the current release and supports integrated FAS. It does not use the splash.html file.
A user would more sensibly visit a "Status" page running on the FAS, rather than attempt to hit the NDS splash directly.

**Comment by ricxsar** [comment]
I'm using `NDS v3.2.0-0` and `OpenWrt 18.06.1 r7258-5eb055306f / LuCI openwrt-18.06 branch (git-18.228.31946-f64b152)`. 

I believe the `NDS` still use the splash.html. After I configured the `FAS` settings ie. `fasport`, `fasremoteip` and `fas_secure_enable`, it still render the default `splash.html` page not redirecting to the `FAS server`. So I modified the `splash.html` to redirect it to it.

```
A user would more sensibly visit a "Status" page running on the FAS, rather than attempt to hit the NDS splash directly.
```
Yes, I agree with that but I set the `fas_secure_enable` to `0` which is needed on my `FAS server` since the server is not on the local network. The server cannot request the auth token due to it is on the cloud.

When the user visit the `Status` page of the `FAS` and the query parameters are not set, then the `FAS` will redirect to `NDS` and then `NDS` will redirect back to the `Status` page with the query parameters set.

**Comment by ricxsar** [comment]
I have a working centralize `FAS` server at the moment using the `NDS v2.1.1-1` and it is working great.
I want to migrate to the latest version to use it's latest improvements but the current behavior prevents me to do so.

**Comment by ricxsar** [comment]
`ndsctl status`

```
==================
NoDogSplash Status
====
Version: 3.2.0
Uptime: 10s
Gateway Name: OpenWrt Nodogsplash
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: 192.168.1.1:2050
Binauth: Disabled
FAS: Secure=0 URL: http://13.55.216.237:80/
Client Check Interval: 30s
Preauth Idle Timeout: 10m
Auth Idle Timeout: 120m
Traffic control: no
Total download: 62 kByte; avg: 49.66 kbit/s
Total upload: 16 kByte; avg: 13.28 kbit/s
====
Client authentications since start: 0
Current clients: 1

Client 0
  IP: 192.168.1.175 MAC: a0:21:b7:e2:c7:9c
  Last Activity: Wed Sep 05 16:00:08 2018 (8s ago)
  Session Start: -
  Session End:   -
  Token: b2179438
  State: Preauthenticated
  Download: 0 kByte; avg: 0.00 kbit/s
  Upload:   0 kByte; avg: 0.00 kbit/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========
```
`/etc/config/nodogsplash`
```

# The options available here are an adaptation of the settings used in nodogsplash.conf.
# See https://github.com/nodogsplash/nodogsplash/blob/master/resources/nodogsplash.conf

config nodogsplash
  # Set to 0 to disable nodogsplash
  option enabled 1

  # Set to 0 to disable hook that makes nodogsplash restart when the firewall restarts.
  # This hook is needed as a restart of Firewall overwrites nodogsplash iptables entries.
  option fwhook_enabled '1'

  # Serve the file splash.html from this directory
  option webroot '/etc/nodogsplash/htdocs'

  # Use plain configuration file
  #option config '/etc/nodogsplash/nodogsplash.conf'

  # Use this option to set the device nogogsplash will bind to.
  # The value may be an interface section in /etc/config/network or a device name such as br-lan.
  option gatewayinterface 'br-lan'

  option gatewayname 'OpenWrt Nodogsplash'
  option maxclients '250'

  # Enables debug output (0-7)
  #option debuglevel '7'

  # Client timeouts in minutes
  option preauthidletimeout '10'
  option authidletimeout '120'

  # Enable BinAuth Support.
  # If set, a program is called with several parameters on authentication (request) and deauthentication.
  # Request for authentication:
  # $<BinAuth> auth_client <client_mac> '<username>' '<password>'
  #
  # The username and password values may be empty strings and are URL encoded.
  # The program is expected to output the number of seconds the client
  # is to be authenticated. Zero or negative seconds will cause the authentification request
  # to be rejected. The same goes for an exit code that is not 0.
  # The output may contain a user specific download and upload limit in KBit/s:
  # <seconds> <upload> <download>
  #
  # Called on authentication or deauthentication:
  # $<BinAuth> <*auth|*deauth> <incoming_bytes> <outgoing_bytes> <session_start> <session_end>
  #
  # "client_auth": Client authenticated via this script.
  # "client_deauth": Client deauthenticated by the client via splash page.
  # "idle_deauth": Client was deauthenticated because of inactivity.
  # "timeout_deauth": Client was deauthenticated because the session timed out.
  # "ndsctl_auth": Client was authenticated manually by the ndsctl tool.
  # "ndsctl_deauth": Client was deauthenticated by the ndsctl tool.
  # "shutdown_deauth": Client was deauthenticated by Nodogsplash terminating.
  #
  # Values session_start and session_start are in seconds since 1970 or 0 for unknown/unlimited.
  #
  #option binauth '/bin/myauth.sh'

  # Enable Forwarding Authentication Service (FAS)
  # If set redirection is changed from splash.html to a FAS (provided by the system administrator)
  # The value is the IP port number of the FAS
  option fasport '80'

  # Option: fasremoteip
  # Default: GatewayAddress (the IP of NDS)
  # If set, this is the remote ip address of the FAS.
  option fasremoteip '13.55.216.237'

  # Option: faspath
  # Default: /
  # This is the path from the FAS Web Root to the FAS login page
  # (not the file system root).
  #option faspath '/onboard-wifi.net/nodog/fas.php'

  # Option: fas_secure_enabled
  # Default: 1
  # If set to "1", authaction and the client token are not revealed and it is the responsibility
  # of the FAS to request the token from NDSCTL.
  # If set to "0", the client token is sent to the FAS in clear text in the query string of the
  # redirect along with authaction and redir.
  option fas_secure_enabled '0'

  # Your router may have several interfaces, and you
  # probably want to keep them private from the network/gatewayinterface.
  # If so, you should block the entire subnets on those interfaces, e.g.:
  #list authenticated_users 'block to 192.168.0.0/16'
  #list authenticated_users 'block to 10.0.0.0/8'

  # Typical ports you will probably want to open up.
  #list authenticated_users 'allow tcp port 22'
  #list authenticated_users 'allow tcp port 53'
  #list authenticated_users 'allow udp port 53'
  #list authenticated_users 'allow tcp port 80'
  #list authenticated_users 'allow tcp port 443'
  # Or for happy customers allow all
  list authenticated_users 'allow all'

  # For preauthenticated users to resolve IP addresses in their
  # initial request not using the router itself as a DNS server,
  # Leave commented to help prevent DNS tunnelling
  #list preauthenticated_users 'allow tcp port 53'
  #list preauthenticated_users 'allow udp port 53'

  # Allow ports for SSH/Telnet/DNS/DHCP/HTTP/HTTPS
  list users_to_router 'allow tcp port 22'
  list users_to_router 'allow tcp port 23'
  list users_to_router 'allow tcp port 53'
  list users_to_router 'allow udp port 53'
  list users_to_router 'allow udp port 67'
  list users_to_router 'allow tcp port 80'

  # MAC addresses that are / are not allowed to access the splash page
  # Value is either 'allow' or 'block'. The allowedmac or blockedmac list is used.
  #option macmechanism 'allow'
  #list allowedmac '00:00:C0:01:D0:0D'
  #list allowedmac '00:00:C0:01:D0:1D'
  #list blockedmac '00:00:C0:01:D0:2D'

  # MAC addresses that do not need to authenticate
  #list trustedmac '00:00:C0:01:D0:1D'

  # Nodogsplash uses specific HEXADECIMAL values to mark packets used by iptables as a bitwise mask.
  # This mask can conflict with the requirements of other packages such as mwan3, sqm etc
  # Any values set here are interpreted as in hex format.
  #
  # List: fw_mark_authenticated
  # Default: 30000 (0011|0000|0000|0000|0000 binary)
  #
  # List: fw_mark_trusted
  # Default: 20000 (0010|0000|0000|0000|0000 binary)
  #
  # List: fw_mark_blocked
  # Default: 10000 (0001|0000|0000|0000|0000 binary)
  #
  #list fw_mark_authenticated '30000'
  #list fw_mark_trusted '20000'
  #list fw_mark_blocked '10000'
```
Still it doesn't redirect to `FAS` server displaying the splash.html

**Comment by bluewavenet** [comment]
Without actually trying this to verify, I think NDS v2.x would in fact serve splash.html if a client tried to access 192.168.1.1:2050
If so, it was purely due to luck as it was the result of unhandled errors in that version that have been fixed in v3.x

**Comment by ricxsar** [comment]
Ahh.... I thought that behavior on NDS v2.x is normal since there's no documentation about it's behavior. So I will not rely to this behavior anymore.

If `FAS` is enabled, splash.html will not be served anymore?

`Error 404` will be served when accessing to `http://192.168.1.1:2050`?

For example, I have implemented this:
```A Secure Internet based FAS is best implemented as a two stage process, first using a local FAS, that in turn accesses an https remote FAS using tools such as curl or wget.```
How to get the access token programmatically when `option fas_secure_enabled '1'` is set?

I will redesign my `FAS` server based the inputs provided.

Thank you for the quick response and sorry for the inconvenience.

**Comment by bluewavenet** [comment]
@ricxsar 

> If FAS is enabled, splash.html will not be served anymore?

-correct.

> Error 404 will be served when accessing to http://192.168.1.1:2050?

-correct.

You can use the ndsctl command to retrieve the client information, including the token.
See:
https://nodogsplashdocs.readthedocs.io/en/stable/ndsctl.html

When fas_secure_enabled = 1, NDS sends the client IP address to FAS, so it is then easy to get the token from ndsctl.

**Comment by mwarning** [comment]
@bluewavenet it might be a good idea to include that in the documentation somewhere.

**Comment by bluewavenet** [comment]
@mwarning 
It is already but could benefit from a bit more in depth description to bring it all together.

**Comment by ricxsar** [comment]
I will now close the issue since the `NDS` functions as expected.

@bluewavenet Thank you for the heads up.

**Comment by bluewavenet** [comment]
@ricxsar
Thankyou for your feedback :-)
I will work to improve the documentation a little!

**Comment by ricxsar** [comment]
@bluewavenet One more thing, can you add client mac and gateway mac when `fas_secure_enabled = 1` and  `fas_secure_enabled = 0` . Those will be helpful when designing a centralize `FAS` since multiple routers will be using the same `FAS` and gateway mac will be used as an identification.

Thanks!

**Comment by bluewavenet** [comment]
@ricxsar 
NDS sends gatewayname to FAS for identification purposes.
It defaults to:

>   option gatewayname 'OpenWrt Nodogsplash'

Just change it to some suitable ID.
This is on my documentation update list ;-)

**Comment by ricxsar** [comment]
I'm looking forward to it. :)

**Comment by ricxsar** [comment]
I have a suggestion. Instead of setting the `fas_secure_enabled` option, I think you may specify what query parameters offered on `splash.html` you would like to passed on to `FAS`. This will make it flexible and you don't need to change the codebase when someone will request another parameters in the future.

**Comment by bluewavenet** [comment]
@ricxsar 
That would be possible, but the point of fas_secure_enabled is to keep all but source ID information hidden. (Source ID being the gatewayname and client IP).

For a secure system you will need to make a call to ndsctl anyway and when doing so you can obtain a full set of information about NDS and its clients.
