### ISSUE TITLE
[Firewall rules] Redirect url not working with plex server on raspberry pi

### ISSUE THREAD

**Issue by imbokhary** [nodogsplash/nodogsplash#300]
My Access point IP is 10.0.10.1 on raspberry pi. I used plex server with port 32400 usually and it's working well. But when I installed nodogsplash and configure it. it's working well with default image and "Continue" button showing client side when I ping 10.0.10.1. After that when I ping 10.0.10.1:32400/web/index.html?
plex not working and even I added RedirectURL 10.0.10.1:32400/web/index.html? on nodogsplash config file
it's redirected on that url but not loaded I think because of firewall rules.

Can you please help me, how can I fix it?

**Comment by imbokhary** [comment]
@bluewavenet 
thanks, it's working well.
I missed everytime by putting Firewall exception to 'authenticated-users' and 'preauthenticated-users'. It should be in 'users-to-router'.
 
Actually I want to use raspberry pi as a media server and when client will be connected with wifi the browser should be opened with media server page. 

I've one more question:
Is there anyway to open browser by nodogsplash when client connected with wifi?
or could you please give me the way or trick to solve it?

thanks in advance

**Comment by bluewavenet** [comment]
@imbokhary 
The client device will automatically open the CPD browser whenever a wifi connection is made.
There is no way any captive portal can control which browser is opened as this is purely a function of the CPD process on the client device. Pre-configuration of a (probably rooted) client would be necessary.

**Comment by imbokhary** [comment]
Is it possible whenever user connect with wifi, everytime he needs to fullfill the captive portal agreements?
In my case, captive portal coming for first time used. When I connect wifi again its not forward to captive portal for the second time. But I need client agreement everytime.

thanks.

**Comment by bluewavenet** [comment]
@imbokhary 
An authenticated client will remain authenticated whether they are connected or not for the duration of two preset time intervals.

These are set in the configuration as clientforcetimeout (or in version3 sessiontimeout), and clientidletimeout (or authidletimeout in v3)

Typically you would set a long clientforcetimeout interval so someone using your system would not have to keep logging in, and a much shorter idle timeout to deauthenticate them quickly if they stop using the system.

**Comment by imbokhary** [comment]
@bluewavenet 
thanks a lot :+1:

**Comment by imbokhary** [comment]
@bluewavenet 
The splash page opens only when I go to 192.168.4.1(wifi host iP) else it didn't work with other url. No splash page found and even no access to url.
I tested it with default configuration of nodogsplash which newly ported RASPBIAN STRETCH LITE on raspberry pi 3 model B+.
Is there any changes needed to nodogsplash config file for redirecting to splash default page whenever search to any url before accepting continue button on splash page?

**Comment by bluewavenet** [comment]
@imbokhary 
For NDS to work, the device it is running on must be configured as a NAT router with Internet access on its WAN interface, and NDS bound to its LAN interface. This router configured device must also be providing DHCP and DNS to client devices that connect to the LAN.
Once _all_ these requirements are met,  modern client devices will display the splash page on connecting. This is done by the built in CPD process of the operating system on the _client_ device.

There seems also to be an additional requirement on versions of Rasbian, ie not appearing to have a full version of iptables. Without rpi hardware we are unable to find out what is required or what versions of Raspbian are effected - the problem seems only to be present on Raspbian and not other Lunux distributions.

It would be useful if you could check to see what, if any, additional iptables and xtables packages are available for your setup and let us know.

**Comment by imbokhary** [comment]
sudo iptables -t filter --list
Chain INPUT (policy ACCEPT)
target prot opt source destination
ndsRTR   all  --  anywhere  anywhere

Chain FORWARD (policy ACCEPT)
target prot opt source destination
ndsNET all --  anywhere anywhere

Chain OUTPUT (policy ACCEPT)
target prot opt source destination

Chain ndsAUT (1 references)
target prot opt source destination
ACCEPT all  -- anywhere anywhere    ctstate RELATED,ESTABLISHED
ACCEPT all  -- anywhere anywhere
REJECT all  -- anywhere anywhere     reject-with icmp-port-unreachable

Chain ndsNET (1 references)
target prot opt source destination
DROP all  -- anywhere anywhere    mark match 0x10000/0x30000
DROP all  -- anywhere anywhere    ctstate  INVALID
TCPMSS tcp  -- anywhere anywhere  tcp flags;SYN,RST/SYN TCPMSS clamp to PMTU
ACCEPT all  -- anywhere anywhere    mark match 0x20000/0x30000
ndsAUT all  -- anywhere anywhere    mark match 0x30000/0x30000
REJECT all  -- anywhere anywhere     reject-with icmp-port-unreachable
REJECT all  -- anywhere anywhere     reject-with icmp-port-unreachable

Chain ndsRTR (1 references)
target prot opt source destination
DROP all  -- anywhere anywhere    mark match 0x10000/0x30000
DROP all  -- anywhere anywhere    ctstate  INVALID
ACCEPT all  -- anywhere anywhere    ctstate RELATED,ESTABLISHED
DROP tcp  -- anywhere anywhere    tcp option=!2 flags:SYN/SYN
ACCEPT tcp  -- anywhere anywhere    tcp dpt:2050
ACCEPT all  -- anywhere anywhere    mark match 0x20000/0x30000
ACCEPT udp  -- anywhere anywhere    udp dpt:domain
ACCEPT tcp  -- anywhere anywhere    tcp dpt:domain
ACCEPT udp  -- anywhere anywhere    udp dpt:bootps
ACCEPT tcp  -- anywhere anywhere    tcp dpt:ssh
ACCEPT tcp  -- anywhere anywhere    tcp dpt:http
ACCEPT tcp  -- anywhere anywhere    tcp dpt:https
REJECT all  -- anywhere anywhere     reject-with icmp-port-unreachable

Chain ndsTRT (0 references)
target prot opt source destination

Chain ndsTRU (0 references)
target prot opt source destination

**Comment by bluewavenet** [comment]
@imbokhary 
I will answer your questions after this, but first,  some people are having problems whereas it looks like you have a working NDS/RPi combination. If you don't mind, could we ask you some questions about the detail of your installation? @mwarning

**Comment by bluewavenet** [comment]
@imbokhary 

> if I don't press continue button and then if I open another browser and write something there, it's not redirect to splash default page.

That is correct. NDS only generates and serves an active splash page with all the variables included when a client attempts to access an external port 80 web page. The CPD (captive portal detection) on client devices does this automatically on connection to the wifi using a built in URL that depends on the operating system and vendor of the client device. If you manually open your browser and access a port 80 site, NDS will intercept this and give you the splash page.

> is it possible without LAN interface and internet connection

It is possible to make NDS work without an Internet connection, but first it is best to make sure you have it all working "Online" first. Such a configuration is not dynamic, ie it does not switch between online and offline and back depending on the state of the Internet connection. But yes it can be done.

**Comment by bluewavenet** [comment]
The DNS spoofing is a very simple configuration change if you are running Dnsmasq. It is essential though to make sure NDS is working first to prevent much confusion :-D

@mwarning 
As @imbokhary has a working RPI/NDS setup, do you have any questions for him with regard to his Raspbian configuration?
