### ISSUE TITLE
Client Upload/Download counters stop updating after session timeout and reauthentication

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#301]
@mwarning 
Happens with v3x. The values given by ndsctl for a client's upload download totals at the time of session timeout, remain the same (stuck) with no further update after the client authenticates again.
At session timeout, the client changes from authenticated to preauthenticated, with the upload counters kept.

In version 2x the behaviour was (I think) to remove the client from the client list at session timeout (aka clientforcetimeout interval). Upon reconnection in v2, all the client data was reset of course.

I will have a look at the code later when I have time, but you are probably more familiar with that part than I am, so if you can take a quick look... ;-)

**Comment by mwarning** [comment]
The error is probably at this line: https://github.com/nodogsplash/nodogsplash/blob/master/src/fw_iptables.c#L1005
