### ISSUE TITLE
Github release mechanism causing OpenWrt build failure.

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#304]
@mwarning 

Release 3.2.1 sha265sum and the tar.gz on github codeload are different for this release.
ie:
Version 3.2.1:
```
https://codeload.github.com/nodogsplash/nodogsplash/tar.gz/v3.2.1?
16da76ecf7820cd8b32081237e05b24a7d2d8a9db8a47242badc7937d6cf1ae8

https://github.com/nodogsplash/nodogsplash/archive/3.2.1.tar.gz
fdc936b1b76bcae9a0a42cd8887d4cb5037fb328449a57c2c33f03ad5013638c
```

whereas
Version 3.2.0:
```
https://codeload.github.com/nodogsplash/nodogsplash/tar.gz/v3.2.0?
c9712c21c2cc88724a8104fa63edd4f69d31af24db0fad84db6105fae2d65809

https://github.com/nodogsplash/nodogsplash/archive/3.2.0.tar.gz
c9712c21c2cc88724a8104fa63edd4f69d31af24db0fad84db6105fae2d65809
```

**Comment by mwarning** [comment]
I think the problem is that you used the wrong version tag. Instead of "v3.2.1", you used "3.2.1".

**Comment by mwarning** [comment]
We can fix that. But that needs a force push on master..

**Comment by bluewavenet** [comment]
Or release again with tag v3.2.1?

**Comment by mwarning** [comment]
The correct way would be to release 3.2.2 :-)

**Comment by bluewavenet** [comment]
v3.2.2 ;-)

**Comment by mwarning** [comment]
Maybe it's better to change the openwrt package to use https://codeload.github.com/nodogsplash/nodogsplash/tar.gz/3.2.1?

**Comment by bluewavenet** [comment]
Yes, or https://github.com/nodogsplash/nodogsplash/archive/3.2.0.tar.gz
With a comment to remind me to change it back next time!

**Comment by mwarning** [comment]
fixed: https://github.com/openwrt-routing/packages/pull/419
