### ISSUE TITLE
nodogsplash FAS https

### ISSUE THREAD

**Issue by michaeltsengpc** [nodogsplash/nodogsplash#307]
Hi,
I am sort of confused. Quoted from https://nodogsplash.readthedocs.io/en/latest/fas.html
"NOTE: USING HTTPS. Your FAS can be an https server, but self signed certificates will throw dire “Here Be Dragons” warnings on your client devices when the redirection to your FAS takes place. Also even if using a registered CA all browsers will still return a security error on returning to Nodogsplash. This can be prevented by using wget to return to Nodogsplash from your FAS script instead of an html GET."
Could you elaborate on how to make "forwarding to a remote auth-website with https" work?
I have splash.html on the router and redirect to https://domain/login.php using POST to get parameter values. How do I modify to use wget, please?

Thanks ^^

**Comment by michaeltsengpc** [comment]
Thanks I will.
If I understand you point correctly, you are saying redirecting splash.html --> http(intermediate FAS) that wget <-- https (real FAS). Is that correct?

**Comment by bluewavenet** [comment]
When FAS is enabled, NDS does not serve splash.html. Instead it redirects a connecting client directly to FAS.
So it will be:
NDS --> Intermediate FAS --> Secure Channel --> Remote FAS

Secure Channel is whatever you choose to do, wget, curl, ssh-tunnel or any other means at your disposal. The client connects only to the intermediate FAS.

**Comment by michaeltsengpc** [comment]
I am using Nodogsplash2 and redirecting splash.html to an FAS with https seemed to be working.
the flow goes like the following:
user connects-->browser opens splash.html -->redirect to the FAS with https-->login successfully on FAS--> internet access.
No tunneling/wget/curl was needed. just need to allow port 443 in the Nodogsplash.conf file. 
Any idea how this happened?
