### ISSUE TITLE
clientmac and clientip not transferred to FAS

### ISSUE THREAD

**Issue by momo7** [nodogsplash/nodogsplash#312]
I think this is an old issue that is still there in NDS, clientmac and clientip are not transferred to FAS:
below is the html source of fas.php
`
  <b>Enter Username and Password</b><form action="/auth/fas.php" method="post" >
  <input type="hidden" name="gatewayname" value="MyGateway">
  <input type="hidden" name="tok" value="050a1a45">
  <input type="hidden" name="tokchk" value="">
  <input type="hidden" name="redir" value="http://www.bing.com">
  <input type="hidden" name="orgurl" value="">
  <input type="hidden" name="authaction" value="http://192.168.1.1:2050/nodogsplash_auth/?clientip=192.168.1.207">
  <input type="hidden" name="clientip" value="">
  <input type="hidden" name="clientmac" value="">
`
I am using a comfast wifi router with OpenWrt 18.06.1 and NDS 3.2.0-1

any known solutions to this  issue?

Thanks.

**Comment by bluewavenet** [comment]
@momo7 
It looks like you are using the original, non-integrated, pre NDS v3 version of FAS.
Also, the version of NDS in OpenWrt 18.06.1 is v3.2.1-1 (it was backported a few weeks ago).
It might be worth looking at the release documentation at:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html
Do please reply here if you have any specific questions.

**Comment by momo7** [comment]
Hi Rob,

I upgraded version to 3.2.1-1 and the issue is still the same. I have also
added a dump of all GET and POST params transmitted to FAS server, and
clientip and clientmac are simply not there. so there has to be something
wrong with NDS, maybe the OpenWRT build has this limitation...

**Comment by bluewavenet** [comment]
You are trying to use a NDS v2 manual FAS configuration with NDS v3.
In v3.x, clientmac is not be transmitted to FAS. In secure mode, only gatewayname, clientip and redir are sent.
I say again, please read the documentation for using FAS at:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html
