### ISSUE TITLE
SPLASH in php on an external server

### ISSUE THREAD

**Issue by electone77** [nodogsplash/nodogsplash#314]
Hi,

I want to use nodogsplash with a splash in php on an external server.
I just want to connect my users once they have validated a check box and then clicked a SUBMIT button. Like splash.html, but I want to use a php page for that.
I have to use FAS for this ? 
I do not want to authenticate my users with login./password.

Best regards.

**Comment by bluewavenet** [comment]
Yes use FAS . Make sure you have NDS v3.2.1 and follow the instructions in the documentation at 
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html
Once you have this working it will be a simple matter to modify the login.php to suit your needs.

**Comment by bluewavenet** [comment]
This is explained in the documentation under the heading:
Post FAS processing.
