### ISSUE TITLE
PreAuth Script for Nodogsplash?

### ISSUE THREAD

**Issue by jcvilladiegoc** [nodogsplash/nodogsplash#317]
Nodogsplash allows you to define some variables in the configuration file nodegsplash/resources/nodegsplash.conf as GatewayName, Redir. You could define some names of key variables to be rendered also, such as mail, tel, address, etc.

**Comment by mwarning** [comment]
Nodogsplash does not allow to set custom template variables.
Why not put them in the `splash.html` directly?

**Comment by jcvilladiegoc** [comment]
It is only to have a template engine, to streamline development and time, having a base structure for this

**Comment by mwarning** [comment]
The only way to have dynamic content in the splash page right now is to insert javascript or to forward an external splash page (e.g. the forward authentication service (FAS)).

**Comment by mwarning** [comment]
The only way to have dynamic content in the splash page right now is to insert javascript or to forward an external splash page (e.g. the forward authentication service (FAS)).

**Comment by bluewavenet** [comment]
Unfortunately, many client CPD implementations block javascript.

FAS should only be accessed using the NDS built in configuration options and not by redirecting via the splash.html file.

@jcvilladiegoc Enable FAS and point it at your own template page written in PHP or any other language that can produce dynamic content.

For development purposes you could simply use the uhttpd server provided for the Luci interface on OpenWrt. Full details of how to set this up are in the documentation:

https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

Feel free to reply here if you need any help to get going.

**Comment by mwarning** [comment]
@bluewavenet would it make sense to allow cgi scripts to be used?
I mean, if the spash page is a script, then send the output of the script as http response...

**Comment by bluewavenet** [comment]
@mwarning Well yes, that is what FAS does. NDS redirects to the FAS splash script at:
http://fasremoteip:fasport/faspath

**Comment by mwarning** [comment]
@bluewavenet no,  I mean that NDS can executes a script that outputs the splash page. This is not about an external spalsh page.

**Comment by bluewavenet** [comment]
@mwarning Yes. Think of NDS FAS as a redirect to a script processor that outputs html response, instead of a link to splash.html
It can be anywhere, even internal to NDS if we choose. It can be any scripting language.

**Comment by mwarning** [comment]
To have the splash page to be replaceable with a script to generate a site would be nice, but I think it would only make sense if it merges with the binauth feature.
Such a step must be well-thought-out .

**Comment by bluewavenet** [comment]
@mwarning 

**Proposed new functionality:**

NDS produces a new virtual url in the same way as it does already with /nodogsplash_auth/ and /nodogsplash_deny/

Lets call it http://gatewayaddress:gatewayport/preauth/

Enable FAS, with 
fasport = gatewayport
faspath = /preauth/
(fasremoteip not set ie defaulting to NDS gateway address)

Now, when triggered by a client port 80 request, NDS redirects to
http://gatewayaddress:gatewayport/preauth/?gatewayname=[gatewayname]&clientip=[clientip]&redir=[requested-url]

NDS will then call the new script (lets call this the PreAuth script) passing the query string to it on the command line and piping the output of the script back to the client (adding standard headers and css from splash.css first). The client now sees a splash page generated by the preauth script.

Depending on what the client enters the PreAuth script can either show a "Continue" button in the normal way, or ask for more information in a back and forth dialogue between itself and the client, ending with the Continue button or "Sorry Access Denied" or somesuch.

You will have probably noticed I am describing a built in FAS, the advantage being it can be very small if using (b)ash scripting ie nothing big like PHP or Python or lighttpd needed like an external to NDS FAS does. Yet could use any scripting language an interpreter is available for (like external to NDS FAS can).

It will use FAS config in secure mode, the PreAuth script then checks that the gatewayname is correct then gets the client token from NDS using the clientip (making it impossible to bypass authentication).

BinAuth is not suitable for this as it is essentially a Post Authentication processor as /nodogsplash_auth/ must have already been called to trigger BinAuth.

I do not see this as a replacement for BinAuth either, as BinAuth is a valuable tool for use with and external (to NDS or the NDS device) FAS.

This should actually be quite simple to implement and we could provide an example script in the same way as you did for BinAuth

**Comment by mwarning** [comment]
I need some time to think about / understand the proposal and the implications. :)

**Comment by bluewavenet** [comment]
@mwarning 
I don't think it would take much coding. Pretty much just additions to conf.c and http_microhttpd.c

An extra config option or two in conf.c :
preauthdir = /preauth/
preauthscript = [path_to_preauth_script]

And a new section in  preauthenticated() in http_microhttpd.c

**Comment by bluewavenet** [comment]
@mwarning 
Pushed to Preauth branch.
Currently testing.

**Comment by bluewavenet** [comment]
@mwarning 
Lots of testing, a few fixes and tweaks. I am happy with it.
I have created a demo script that produces a dynamic splash page asking for client's name and email address and creates a log containing entries for every authentication recording date, name, email address and client mac address.
I just need to update the documentation before PR..

**Comment by bluewavenet** [comment]
Merged PR #329 
It is now possible to define custom variables and serve dynamic html pages using the NDS built in web server MHD by using a preauth script written in any language for which an interpretor is available or by using a compiled program called by NDS.

**Comment by bluewavenet** [comment]
Full details at:
https://nodogsplashdocs.readthedocs.io/en/latest/preauth.html
