### ISSUE TITLE
Splash page not working on libremesh

### ISSUE THREAD

**Issue by splucs** [nodogsplash/nodogsplash#320]
Hello.

I have LibreMesh 17.01.02 running on a TP-Link WR842N v3 router.
I have followed the instructions on https://nodogsplash.readthedocs.io/en/latest/install.html to install nodogsplash. The version that came was 1.0.1-2.
At first the file etc/nodogsplash/nodogsplash.conf wasn't created and nodogsplash didn't initiate. I created the file using this config:
```
GatewayInterface br-lan

FirewallRuleSet authenticated-users {
  FirewallRule allow all
}

FirewallRuleSet preauthenticated-users {
}

FirewallRuleSet users-to-router {
  FirewallRule allow udp port 53
  FirewallRule allow tcp port 53
  FirewallRule allow udp port 67
  FirewallRule allow tcp port 22
  FirewallRule allow tcp port 80
  FirewallRule allow tcp port 443
}

SplashPage splash.html

MaxClients 250
```

It initiates, but the splash page won't show up.
usr/bin/ndsctl status shows this:

```
==================
NoDogSplash Status
====
Version: 1.0.1
Uptime: 0d 2h 44m 52s
Gateway Name: OpenWrt Nodogsplash
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: 10.13.225.76:2050
Splashpage: /etc/nodogsplash/htdocs/splash.html
Traffic control: no
Total download: 17505 kByte; avg: 14.1572 kbit/s
Total upload: 115 kByte; avg: 0.0934153 kbit/s
====
Client authentications since start: 0
Httpd request threads created/current: 0/0
Current clients: 0
====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========

```
Internet works normally. Anyone can access without going through the splash page.

**Comment by bluewavenet** [comment]
@splucs 
First, you are using an old version of LibreMesh based on a very old and unsupported version of LEDE/OpenWrt.
Second, as a consequence of my first point, you have ended up with a very old and unsupported version of NDS. (The current version of NDS is 3.2.1).

I am not familiar with LibreMesh but do have experience with mesh networks in general. 
Are you trying to run NDS on a mesh node to provide a wireless gateway to users?
If so you will need to configure your node to provide ipv4 NAT routing between the user wireless interface and the mesh interface for NDS to work, unless you can install NDS on the root node (ie the mesh node that provides the Internet to the mesh).

Let us know more about what you are trying to achieve.

**Comment by bluewavenet** [comment]
@splucs 
You are also looking at a very outdated version of the documentation.
NDS documentation is now at:
https://nodogsplashdocs.readthedocs.io

**Comment by mwarning** [comment]
@splucs since this is a firmware for mesh routing.. If the Internet access if over the mesh, then the traffic might no leave br-lan, but will be routed over the Internet to some other place.
Check on the Internet what your public ip address is. If it is not that of your Internet provider and location, then it goes over some mesh. Nodogsplash can only intercept routed traffic (e.g. routed from br-lan to eth0).

**Comment by mwarning** [comment]
@splucs I can confirm the problem. The environment is routed - so it should work. But I don't know what is happening there. The interception is rendered useless by the lime firewall setup.

**Comment by splucs** [comment]
@bluewavenet this is the root node.
@mwarning do you know how to setup the firewall not to interfere with NDS?

**Comment by mwarning** [comment]
@splucs sorry, no. I do not know what is happening. But I can give the newest NDS version a try.

**Comment by bluewavenet** [comment]
I'll install on something later but a quick look shows it is using Batman layer 2 and ipv6 routing via Bmx, so NDS will not work in a default config. It should be possible to route ipv4 on the root node and bridge out onto the mesh on the batman interface. I have done this on OpenWrt with Batman and found no issues. No firewall issues either.
I'll try on Libremesh perhaps tonight or tomorrow.

**Comment by mwarning** [comment]
Ok, NDS 3.2.1 also does not intercept client traffic - no splash page is shown.

**Comment by bluewavenet** [comment]
@mwarning I've liberated a gl-ar300m and about to reflash. The download seems to be LEDE 17.01.2 based.

**Comment by bluewavenet** [comment]
```
uci set nodogsplash.@nodogsplash[0].gatewayinterface='anygw'
uci commit nodogsplash
service nodogsplash restart
```
Done :-D

**Comment by mwarning** [comment]
pfft :->

**Comment by bluewavenet** [comment]
HeHe ;-)

**Comment by bluewavenet** [comment]
@splucs

**Comment by bluewavenet** [comment]
This works on a route node and will bridge out onto the mesh network. Untested on a gateway node (as I only have one router available at the moment). Will only work on ipv4. If a gateway node has its own ipv4 subnet the first user to authenticate will do so for the whole subnet so a local instance of NDS would be needed. Numerous gotchas but in principle can be made to work.
