### ISSUE TITLE
Variables not replaced in splash.html

### ISSUE THREAD

**Issue by TR-SLimey** [nodogsplash/nodogsplash#321]
Hey all,
So everything seemed to work nicely until suddenly after a restart, NDS stopped replacing variables in the html file. Variables like $gatewayname show up on the page instead of their values. When clicking the login button, a 404 error appears because the URL literally says $authaction and not whatever the value is meant to be. I'm using NDS 3.2.1. BinAuth is enabled but the problem persists with it off. What could be causing this?

**Comment by mwarning** [comment]
Right Is this on OpenWrt or Debian? Either way, it would be interesting to know if there is a error message. You could start nodogsplash with a higher debug level (`-d 9`) and in foreground (`-f`) to see the debug output.

An was does `ndsctl status` output as "Gateway Name:"?

**Comment by TR-SLimey** [comment]
I'm using Raspbian which is based on Debian. When I run NDS in foreground with debug 9 like you said, there doesn't seem to be any error messages appearing. In fact, nothing gets printed when I access the splash page which seems weird but maybe it's because I added my MAC to the trusted list. `ndsctl status` outputs `Gateway Name: TRSLPI` which is correct.

**Comment by mwarning** [comment]
I think the debuglevel set on the command line is overwritten by the one set in the configuration file. Better set it there.

What Raspian version do you use? And is the behaviour consistent? Maybe you can post your configuration? That might give a glue.

**Comment by TR-SLimey** [comment]
My NDS config (/etc/nodogsplash/nodogsplash.conf): [pastebin](https://pastebin.com/Besk65ga)
Most of it is untouched except for a few options.

Also, the debian version is `9.4`

I don't think it is overwritten by the file though because it produced a **LOT** of output when I started NDS so I think it just didn't log the connection to splash.html.

**Comment by bluewavenet** [comment]
If you added your client mac to the trusted list, the only way you will ever see the splash page is to manually access it by entering its URL. If you do this you will see only the $variable names.
To see the proper splash page, you must be automatically redirected there by NDS as a result of an attempted port 80 access to some external web site.

**Comment by mwarning** [comment]
@bluewavenet ah yes, that is probably the case.

**Comment by TR-SLimey** [comment]
@bluewavenet I untrusted my MAC and Firefox correctly detected the splash page. When I clicked the button I was redirected to the splash page but the variables still weren't replaced and pressing the login button still gave a 404.

**Comment by bluewavenet** [comment]
Are you still using the default splash.html as installed or have you modified it in any way? 
I ask because this has been extensively tested - not saying you have not found an exception though :D

**Comment by bluewavenet** [comment]
When you say you clicked the button, you were redirected to the splash page?
But the continue button is ON the splash page...... so you were already on it......

**Comment by TR-SLimey** [comment]
I've changed the splash page but I've kept the whole login form the same (except for adding a login and password box). I didn't change anything (I don't think) that would affect this anyway but I can provide the contents of splash.html if you want me to. 

Also, I meant the button on the Firefox "This wifi network requires login" notification. Should've made that clearer.

**Comment by bluewavenet** [comment]
Did you find you needed to set GatewayAddress? Very unusual if you do.
Try commenting it out...

**Comment by TR-SLimey** [comment]
I commented it out and nothing changed. Everything works as before.

**Comment by bluewavenet** [comment]
Try removing/uninstalling, making sutlre the config file and /etc/nodogsplash/ folder have been deleted then reinstall from scratch so everything is default.  Then see if it works to eliminate any changes you may have made.

**Comment by bluewavenet** [comment]
sudo apt remove nodogsplash
I think.
Make sure /etc/nodogsplash gets removed.
