### ISSUE TITLE
Customize IP redirection rules and ports

### ISSUE THREAD

**Issue by jcvilladiegoc** [nodogsplash/nodogsplash#335]
it is possible to create a rule in the firewall that allows access to pre-authenticated users to a site or external data, by redirecting ports and ip in such a way that those who access via IP 192.168.8.1 on port 1030 their data in are actually going to IP 31.121.54.XX, port 8080 in lan / wan

In nodogsplash installed in a router openwrt lede with the firewall rule works, but when you install nodegsplash 1.1 it stops working, and I can not install version 2 or 3 of nodogsplash, I do not get listed in LEDE LuCI

**Comment by bluewavenet** [comment]
NDS version 3 onwards supports firewall rule chaining.
Can you explain what you mean by:

> I do not get listed in LEDE LuCI

**Comment by bluewavenet** [comment]
@jcvilladiegoc 
Ah! Yes v3 is not available in OpenWrt/LEDE 17.01.x
You should really consider upgrading to OpenWrt 18.06.1

**Comment by jcvilladiegoc** [comment]
Thanks, I will have it present for the next router that I purchased, the one I have is not 100% compatible with OpenWrt 18.06.1. is GL-AR300M.

**Comment by jcvilladiegoc** [comment]
Thanks, I will have it present for the next router that I purchased, the one I have is not 100% compatible with OpenWrt 18.06.1. is GL-AR300M.

**Comment by bluewavenet** [comment]
@jcvilladiegoc 
Actually the AR300M is fully supported in OpenWrt 18.06.1, even the old discontinued dual flash versions in NOR flash boot mode (very simple to disable NAND boot). I have used many AR300M models in numerous projects.
Let me know if you need any info.
