### ISSUE TITLE
"Error in 'nodogsplash': free(): invalid pointer: 0x76934c18"

### ISSUE THREAD

**Issue by duydeja-vu** [nodogsplash/nodogsplash#336]
i have a pi3 access point running nodogsplash. When I connected my computer to wifi, I was shown nodogsplaash splash page. At the terminal of pi3 is displayed: "Error in 'nodogsplash': free (): invalid pointer: 0xxxx". After that, I clicked on the 'Continue' button from the laptop browser, I still couldn't access the internet. But after I restarted everything and started again, everything worked normally. Then there was the same error. Sometimes successful, sometimes unsuccessful. Can someone help me?

**Comment by bluewavenet** [comment]
@duydeja-vu 
Please tell us your versions of everything. I assume you are using a version of Raspian?
Also to function properly the device needs to be configured as a router and serving dhcp to the user network (WiFi) so also let us know how your interfaces are configured.

**Comment by duydeja-vu** [comment]
I used Raspbian Stretch and I setting Raspberry Pi as an access point with this tutorial.
https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md

**Comment by bluewavenet** [comment]
What is the version of nodogsplash?

**Comment by duydeja-vu** [comment]
I use Nodogsplash version 3.3.0-4-beta.

**Comment by bluewavenet** [comment]
When it is working, do you get the splash page?
There are issues with running on an RPi, but this particular error may well be a bug in the beta.
I suspect you are the first to try it on a RPi although it has been tested on OpenWrt.
Try the stable release at:
https://github.com/nodogsplash/nodogsplash/releases/tag/3.2.1 
and let us know how you get on.

**Comment by bluewavenet** [comment]
@duydeja-vu 
This should now be fixed in master (now 3.3.0-2-beta).
We would be very interested if you are getting the splash page on the RPi as there have been issues reported by some yet others seem to have it working.

**Comment by duydeja-vu** [comment]
@bluewavenet 
Thank you for everything !! I 
I tried version 3.2.1. Everything is very good on Pi3(with Raspbian).

**Comment by bluewavenet** [comment]
Did 3.3.0-**2**-beta work without error?
