### ISSUE TITLE
Can't start nodogsplash

### ISSUE THREAD

**Issue by quadroloop** [nodogsplash/nodogsplash#339]
Hi, I've been getting this error consistently and i cant find any similar case anywhere. i just installed NDS v 3.2.1-2, but when i tried to start nds, it throws this error:

```sh
root@OpenWrt:/etc/init.d# nodogsplash start
Error relocating /usr/lib/libgnutls.so.30: explicit_bzero: symbol not found
Error relocating /usr/lib/libgnutls.so.30: getrandom: symbol not found
root@OpenWrt:/etc/init.d#
```
the same goes with using ndsctl. I included details below, hope it can help.
Any ideas on what might be the problem? Thanks in advance!

#### Router:
> TP-Link (TL-WR841N v. 13.1)

#### OpenWRT Version:
>  OpenWrt SNAPSHOT, r6880-aadca03

**Comment by mwarning** [comment]
The reason is likely that the dependency for Nodogsplash changed: https://github.com/openwrt-routing/packages/pull/445
Have you installed nodogsplash via `opkg install nodgosapsh`?

**Comment by quadroloop** [comment]
yes i did. it always worked for me before. i tried reinstalling it, but the error message persists.

**Comment by mwarning** [comment]
Please try to uninstall nodogsplash and libmicrohttpd-no-ssl. Then `opkg update` and `opkg install nodogsplash`.

**Comment by bluewavenet** [comment]
I am currently testing various routers (various targets) with current snapshot and it is working ok.... However on checking I find I have NDS 3.2.1-2 and libmicrohttpd-ssl installed. I also for other reasons have libopenssl so presumably that is why it works....
This could be an issue with the latest version bump in libmicrohttpd ie installing the ssl version regardless?

**Comment by quadroloop** [comment]
@mwarning I tried your instructions, removing libmicrohttp-no-ssl. but it seems do not have it in the first place. and opkg returns `no packages were removed.` regardless i uninstalled nodogsplash, ran `opkg update` and `opkg install nodogsplash` but the error is still present. @bluewavenet , i check my packages. after reading your response, i also have `libmicrohttpd-ssl` but not `libopenssl`, so i tried installing it. but with no improvements.

**Comment by bluewavenet** [comment]
@quadroloop @mwarning 
I have done a few tests this morning. It seems that on current snapshot, NDS installs libmicrohttpd-ssl despite the recent pr to cater for changes of naming of libmicrohttpd.
I do not know if this is NDS or MHD causing the issue (NDS = nodogsplash, MHD = libmicrohttpd).

MHD - ssl loads its dependencies (libgcrypt, libgnutls,libgpg-error) so in my case it all works fine and I am unable to replicate the error message. I did notice the other day while testing that something was using significantly more flash and more ram than in 18.06.x. Now I know the reason - the MHD -ssl dependencies.

@quadroloop The error you are getting is most likely a consequence of the nature of Snapshot, I suspect you are running an old version, as it updates sometimes twice daily and there was a major jump including a kernel update about a week ago. Try reflashing with the latest snapshot, or even stable 18.06.2 and it will work I am sure.

@mwarning This leaves us with the issue of NDS installing MHD-ssl (in OpenWrt Snapshot) for whatever reason. Also we will have to cater for the MHD change when we backport to 18.06, unless MHD gets backported as well.....

**Comment by mwarning** [comment]
@bluewavenet I can confirm the problem. I left a note here: https://github.com/openwrt/packages/pull/8075

**Comment by bluewavenet** [comment]
I found I can force uninstall libmicrohttpd-ssl and its dependencies, then install libmicrohttpd and NDS is happy. This means opkg installs it ok. It is the build system that seems to be getting it wrong.

**Comment by mwarning** [comment]
Here is a proper ticket: https://github.com/openwrt/packages/issues/8180

**Comment by bluewavenet** [comment]
PR https://github.com/openwrt/packages/pull/8569# fixes this.
