### ISSUE TITLE
Is it possible to run two nodogsplash instances?

### ISSUE THREAD

**Issue by dongha28** [nodogsplash/nodogsplash#340]
Hello, I was wondering if I could run two instances of nodogsplash.
My router has two guest networks, each with a different IP subnet and subnet mask.
I want to run two completely seperate nodogsplash instances for each of the two networks, with
different captive portal pages.

Would this be possible?

**Comment by mwarning** [comment]
Yes, it is possible. But you need to set different paths and ports. Also don't forget to set a different `ndsctlsocket` in `/etc/config/nodogsplash` as well.

**Comment by mwarning** [comment]
I will close this issue. If you run into major problems, let us know.

**Comment by bluewavenet** [comment]
@mwarning 
I had a quick look and it should indeed work but I've not tried it. It will need a named config section for each network interface in the uci config file and all the settings for each interface in each section, although there my be some problems as much has changed since this was first implemented. eg what will happen with fwhook? Multiple instances should be tested, fixed and documented I guess...
Config file something like:
```
config nodogsplash nds1
	option enabled '1'
	option fwhook_enabled '1'
	option webroot '/etc/nodogsplash/htdocs/nds1'
	option gatewayinterface 'wlan0'
	....... etc
config nodogsplash nds2
	option enabled '1'
	option fwhook_enabled '1'
	option webroot '/etc/nodogsplash/htdocs/nds2'
	option gatewayinterface 'wlan1'
	....... etc
```

**Comment by bluewavenet** [comment]
We might need a "globals" section...

**Comment by mwarning** [comment]
@bluewavenet "/etc/init.d/nodogsplash restart" would need to be extended to allow to restart a specific instance.
Further thinking about firewalls, I think the firewall instances of NDS might conflict...

**Comment by bluewavenet** [comment]
@mwarning 
A few things to think about.  I will give it a try tomorrow  :-D

**Comment by bluewavenet** [comment]
@mwarning 
A quick try this morning.
Issues:
1. The init.d script only sets up the first instance defined in the uci config and ignores any others.
2. There is no means of tellimg ndsctl which socket to use.

There may well be other issues not found yet.

Initial thoughts to get this working:
1. option fwhook_enabled and a global option enabled moved to a new globals section of the uci config
2. Keep option enabled in each instance section.
3. Fix init.d to setup and start all instances.
4. Fix ndsctl to accept instance name on the commend line.

**Comment by bluewavenet** [comment]
@dongha28 @mwarning 
PR #484 adds support for detecting the interface a client is using. It also is able to detect if a client is using an 802.11s mesh node.
The client connection information is passed to FAS when option fas_secure_enabled '2' is set, allowing the FAS captive portal login page to adapt its response depending on where the client is connected.

I think this provides most, if not all, of the functionality that multiple instances of NDS would provide.

I hope to do a new release in the next few days as I have some "holiday time" I can take advantage of :-D

@martignoni - for your information - useful for Moodlebox? Multiple groups or classrooms?

**Comment by martignoni** [comment]
Yes, could be useful. I'll test. Thank you :-)
