### ISSUE TITLE
running sudo ndsctl in php no output 

### ISSUE THREAD

**Issue by dokaga** [nodogsplash/nodogsplash#350]
hi i am having this problem with ndsctl.

1) when i execute the $result = exec("sudo /usr/bin/ndsctl status") these is no resutl;
2)when i execute $result = exec("sudo /usr/bin/ndsctl status 2>&1")
it get me error "ndsctl: nodogsplash probably not started (Error: No such file or directory)"

**Comment by dokaga** [comment]
tried this also 

echo '<pre>';
     $result = shell_exec("ndsctl json 192.168.50.203 | grep token | cut -c 10- | cut -c -8");      
//system() will echo the output of the executable, use shell_exec() instead if you don't want this
    echo '</pre>';
echo $result;

but same no result

**Comment by bluewavenet** [comment]
@dokaga 
Can you give us details of your setup and configuration please, including versions, operating system and hardware?

If you run the comment in a terminal (with and without the sudo part), does it work then?

I would recommend using exec() rather than shell_exec() as it can not only return the last line of the output but also return an array containing the entire output which is more useful/flexible. But also my choice was driven by the fact that I found that in some versions of php/webserver/operating-system combinations I have found shell_exec() to be a bit unreliable.

**Comment by dokaga** [comment]
this is my OS and hardware

raspberry pi 3 b
rasbian stretch
nodogsplash 3.3

yes when i run it in the terminal it works

**Comment by dokaga** [comment]
my php is version 7.0
and apache 2.4.25 (rasbian)

**Comment by dokaga** [comment]
i tried also this: $clientip = "192.168.50.203";
    $clientmac = exec("sudo /usr/bin/ndsctl json ". $clientip . " | grep mac | cut -c 8- | cut -c -17 2>&1", $out);
    var_dump($out);

but same so output,

**Comment by bluewavenet** [comment]
I think most likely this is an issue with your sudo configuration.
By default, sudo writes to the system log when it is used so it will be useful to look there for "access denied" or similar.
You need to allow the apache user to run ndsctl, grep, cut, awk etc etc
This is best done, at least initially, by adding to the end of sudoers, (using visudo), the line:
`apache ALL=(ALL) NOPASSWD: ALL`
substituting the name of your apache user if different.
You can tighten up sudo as much as you like once you have it working.

**Comment by dokaga** [comment]
i already paste this "apache ALL=(ALL) NOPASSWD: ALL " to my sudoer file;

this is my php code
$cmd2 = "sudo ndsctl json 192.168.50.203 | grep mac | cut -c 10- | cut -c -8";
    $clientmac = exec($cmd2);

echo "clientmac: ".$clientmac."!<br>";

but still no output

**Comment by dokaga** [comment]
when i run this

 $cmd2 = "sudo ndsctl status";
    $clientmac = exec($cmd2,$out,$vard);

echo "clientmac: ". $clientmac ."!<br>";
print_r($out);

output is Array()

but when i run this

$cmd2 = "sudo ndsctl";
    $clientmac = exec($cmd2,$out,$vard);

echo "clientmac: ". $clientmac ."!<br>";
print_r($out);

output is this,

Usage: ndsctl [options] command [arguments]

options:
  -s <path>           Path to the socket
  -h                  Print usage

commands:
  status              View the status of nodogsplash
  clients             Display machine-readable client list
  json [mac|ip|token] Display client list in json format
  stop                Stop the running nodogsplash
  auth mac|ip|token   Authenticate user with specified mac, ip or token
  deauth mac|ip|token Deauthenticate user with specified mac, ip or token
  block mac           Block the given MAC address
  unblock mac         Unblock the given MAC address
  allow mac           Allow the given MAC address
  unallow mac         Unallow the given MAC address
  trust mac           Trust the given MAC address
  untrust mac         Untrust the given MAC address
  loglevel n          Set logging level to n

**Comment by bluewavenet** [comment]
The common factor here with that reported in #315 by @FenriLupus is Apache.
It looks like the combination of Apache and PHP exec() is truncating the command at the first space for some reason.
Try creating a script file eg ndsctl-json.sh and putting in it, the line
`ndsctl json`
Then do
```
exec(sudo /path/to/ndsctl-json.sh, $output);
print_r($output);
```

**Comment by dokaga** [comment]
the output is Array()

**Comment by bluewavenet** [comment]
Did you set ndsctl-json.sh as executable?
Also, it should probably be:
`exec(sudo /path/to/./ndsctl-json.sh, $output);`
(my typo)

**Comment by bluewavenet** [comment]
Unfortunately I am running lighttpd on openwrt and cannot replicate the problem at all.
Which version of NDS are you running? 
NDS v3.3.1 was released yesterday and it can use its own built in web server in combination with any scripting language. PHP would be ideal (using php-cli instead of apache/php-cgi), but it comes pre installed with a bash script to generate dynamic html login pages that can at least be used to make sure all is working.

**Comment by dokaga** [comment]
yes still no working . .
how can i know the version of my nds?

**Comment by dokaga** [comment]
i am afraid i cannot authenticate and unauthenticate devices from php

**Comment by bluewavenet** [comment]
"Did you set ndsctl-json.sh as executable?"

**Comment by bluewavenet** [comment]
This seems to be an Apache/PHP/Sudo configuration issue and not related to NDS.
I have not been able to replicate the problem.
@dokaga 
Do let us know if you make any progress.
