### ISSUE TITLE
FAS does'nt work well. Constant forwarding

### ISSUE THREAD

**Issue by Zhenyoker** [nodogsplash/nodogsplash#354]
Greetings, it's me again. I experimented a lot. I uploaded all .php files from FAS to my hosting. Changed NDS config. Everything works fine for the first 30-40 seconds. Then the eternal forwarding begins again. I give debug files at level 7 and 5 for successful login and for unsuccessful. Help me find a problem. [My previous post ](https://github.com/nodogsplash/nodogsplash/issues/346)

OpenWrt 18.06.2 r7676-cddd7b4c77
nodogsplash 3.2.1-2

[debug7_success.txt](https://github.com/nodogsplash/nodogsplash/files/3059112/debug7_success.txt)
[debug7_unsuccess.txt](https://github.com/nodogsplash/nodogsplash/files/3059113/debug7_unsuccess.txt)
[debug5_success.txt](https://github.com/nodogsplash/nodogsplash/files/3059115/debug5_success.txt)
[debug5_unsuccess.txt](https://github.com/nodogsplash/nodogsplash/files/3059116/debug5_unsuccess.txt)

**Comment by bluewavenet** [comment]
I am away at the moment and cannot look in detail.
But the failing logs looks like you are trying to access the fas url while preauthenticated.
This would not normally happen and will, I think, have the same effect as you are seeing in the logs.
I will look in detail tomorrow.

**Comment by Zhenyoker** [comment]
Ok, thx! I will upload the config tomorrow, but I’m sure that I haven’t changed anything extra. Maybe the editor nano inserts something extra ... but this is unlikely

**Comment by bluewavenet** [comment]
Keep your hosted fas up and I will test against it from here.

**Comment by bluewavenet** [comment]
@Zhenyoker 
Your FAS hosting does not seem to be available this morning so I cannot test against it.
However, from what I can see from your logs, you have not set fasremoteip in your config. This is essential as NDS uses it to allow preauthenticated clients to access the remote FAS.

In addition, the domain name you are using in faspath looks like it is pointing to a shared service and I am not sure you have taken this into account.

An extract from the NDs documentation:

> 
> Note 1:
> 
>     A typical Internet hosted Apache/PHP shared server will be set up to serve multiple domain names.
> 
>     To access yours, use:
> 
>         fasremoteip = the ip address of the remote server
> 
>         and, for example,
> 
>         faspath = /domainname/pathto/myfas/fas.php
> 
>         or
> 
>         faspath = /accountname/pathto/myfas/fas.php
> 
>     If necessary, contact your hosting service provider.
> 

The full FAS documentation can be found at:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

**Comment by Zhenyoker** [comment]
My hosting is working. Available at: http://yrkons.000webhostapp.com/nodog/fas.php  .  I uploaded my config file NDS. And a screenshot of the successful download of FAS, but after 30 seconds there is again an endless redirect. If the FAS is raised locally to 192.168.1.1, it does not work at all and immediately it is redirected.
[nodogsplash.txt](https://github.com/nodogsplash/nodogsplash/files/3062818/nodogsplash.txt)
![Screenshot from 2019-04-10 11-23-53](https://user-images.githubusercontent.com/25462709/55864318-ea866e00-5b84-11e9-8771-bc9c6d694755.png)

**Comment by bluewavenet** [comment]
Here is another extract from the documentation:
These options are:

       1. fasport. This enables Forwarding Authentication Service (FAS). Redirection is changed from splash.html to a FAS. The value is the IP port number of the FAS.
       2. fasremoteip. If set, this is the remote ip address of the FAS, if not set it will take the value of the NDS gateway address.
       3. faspath. This is the path to the login page on the FAS.

Note here, fasremoteip is the **remote ip address** of the FAS, **not** its domain name.

Also note my previous comment:

> A typical Internet hosted Apache/PHP shared server will be set up to serve multiple domain names.
> 
> To access yours, use:
> 
>     fasremoteip = the ip address of the remote server
> 
>     and, for example,
> 
>     faspath = /domainname/pathto/myfas/fas.php
> 
>     or
> 
>     faspath = /accountname/pathto/myfas/fas.php
> 
> If necessary, contact your hosting service provider.

**Comment by Zhenyoker** [comment]
OK, why can't I run FAS locally? at 192.168.1.1

**Comment by bluewavenet** [comment]
To run locally you must have a local web server with php. It works well with uhttpd that is normally pre-installed for Luci. 
See the documentation:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#using-the-simple-example-files

**Comment by bluewavenet** [comment]
Sorry, I meant this link:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#running-fas-on-your-nodogsplash-router

**Comment by Zhenyoker** [comment]
Yes, I read this instruction 100 times already)) but the effect is the same. constant forwarding (

**Comment by bluewavenet** [comment]
I am sorry, but your configuration is clearly incorrect, so unless you correct it, you cannot expect it to work.

**Comment by bluewavenet** [comment]
You have the line:
`  option fasremoteip 'yrkons.000webhostapp.com'`

This should read:
`  option fasremoteip '145.14.144.49'`

or
`  option fasremoteip '153.92.0.100'`

depending on how your service provider has set up their hosting.

faspath will have to be a valid path on the fasremoteip address. To determine this your hosting control panel will usually tell you, but failing that you will have to contact them to find out.

**Comment by bluewavenet** [comment]
For example, if your account name is yrkrons, then

`option fasremoteip '145.14.144.49'`

and 

`option faspath '/yrcons/nodog/fas.php'`

might work. (it might be the other ip address)

**Comment by bluewavenet** [comment]
See also #356 
This applies to the case of fasport=80 and fas running on the same ipaddress as nds.
Port 80 is however valid for use when fasremoteip is set.

**Comment by Zhenyoker** [comment]
finally! thx!

**Comment by bluewavenet** [comment]
@Zhenyoker 
but your issue was running FAS remotely.......

**Comment by Zhenyoker** [comment]
> @Zhenyoker
> but your issue was running FAS remotely.......


I had the same problems with running FAS on the router
