### ISSUE TITLE
/etc/config/nodogsplash doesn't exist

### ISSUE THREAD

**Issue by DimitrisPr** [nodogsplash/nodogsplash#364]
Documentation states:
>  /etc/config/nodogsplash should be edited to reflect the ip address and port of your FAS service as described in the comments in the example file. Your FAS can reside on your Nodogsplash router, a web server on your LAN, or a web server on the internet.

Though, there is not config directory in my /etc folder (after installation of course). Am I missing something?

**Comment by mwarning** [comment]
/etc/config only exists on OpenWrt. Otherwise it is /etc/nodogsplash.conf.

**Comment by bluewavenet** [comment]
@DimitrisPr 
Make sure you are reading the up to date documentation at:
https://nodogsplashdocs.readthedocs.io/en/stable/customize.html#the-configuration-file
