### ISSUE TITLE
Nodogsplash on RPi without internet does not redirect to local site

### ISSUE THREAD

**Issue by sojastar** [nodogsplash/nodogsplash#365]
Hi,

I’m asking this here but should it be the wrong place, please ignore. That question was already asked [here](https://superuser.com/questions/1439434/nodogsplash-without-internet-connection-redirect-to-local-served-site-not-workin), but I added some details since.

I have a Raspberry Pi on Raspbian Stretch configured as an access point but not connected to the internet. The Pi is running Nginx and serving a locally stored website. Once connected to the Pi provided Wi-Fi, I can access the website without trouble at the address http://pedrasparaler.local/ (pedrasparaler is the Pi's hostname).

I wanted to add a captive portal functionality so that users connecting to the Wi-Fi would automatically be redirected to the site's main page.  Basically, I’m trying to implement the "museum example" as described by bluewavenet in this thread https://github.com/nodogsplash/nodogsplash/issues/154#event-1888947321 .

 It partially works, in that devices connecting to the Pi's Wi-Fi do pop-up the Nodogsplash splash.html page once the Wi-Fi network is selected, but the redirection to the local site after the user confirmation action always timeouts. Yet ( as visible in the following logs ), the client device gets connected, but can’t access the site at http://pedrasparaler.local/ anymore.

As the Pi is not connected to the internet, I have added the following line to dnsmasq.conf:

`address=/#/192.168.4.1 (that's the Pi static IP address)`

Here is what the ndsctl command returns after one client tried to connect:

```
==================
NoDogSplash Status
====
Version: 3.3.3-beta
Uptime: 57s
Gateway Name: pedrasparaler
Managed interface: wlan0
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.4.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Disabled
Client Check Interval: 30s
Preauth Idle Timeout: 10m
Auth Idle Timeout: 120m
Redirect URL: http://pedrasparaler.local/
Traffic control: no
Total download: 21 kByte; avg: 2.95 kbit/s
Total upload: 8 kByte; avg: 1.19 kbit/s
====
Client authentications since start: 1
Current clients: 1

Client 0
  IP: 192.168.4.29 MAC: 60:f8:1d:0c:72:c7
  Last Activity: Wed May 22 00:29:13 2019 (14s ago)
  Session Start: Wed May 22 00:28:59 2019 (28s ago)
  Session End:   -
  Token: 7fa12986
  State: Authenticated
  Download: 1 kByte; avg: 0.47 kbit/s
  Upload:   1 kByte; avg: 0.41 kbit/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========
```

Again, the client is reported as connected, but it can’t connect to the website served by the Pi.

Here is a look at the tails of the Nginx access and error logs. First acces.log:

```
…
192.168.4.29 - - [21/May/2019:23:50:37 +0200] "GET /hotspot-detect.html HTTP/1.1" 404 209 "http://192.168.4.1:2050/splash.html?redir=http%3a%2f%2fcaptive.apple.com%2fhotspot-detect.html" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60"
192.168.4.29 - - [21/May/2019:23:50:37 +0200] "GET /hotspot-detect.html HTTP/1.0" 404 233 "-" "CaptiveNetworkSupport-346.50.1 wispr"
```

And then error.log:

```
…
process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2019/05/22 00:07:39 [emerg] 568#568: bind() to 0.0.0.0:80 failed (13: Permission denied)
2019/05/22 00:07:43 [warn] 603#603: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2019/05/22 00:07:43 [emerg] 603#603: bind() to 0.0.0.0:80 failed (13: Permission denied)
```

That’s strange, because a ps aux | grep [n]ginx does indeed states that Nginx master process is running as root. This error is only triggered when Nodogsplash is activated.

```
root       458  0.0  0.4  47084  1932 ?        Ss   00:06   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
nobody     460  0.0  0.6  47236  2832 ?        S    00:06   0:00 nginx: worker process
```

Could there be a clash between Nodogsplash’s own web server and Nginx on port 80 ?

I have also found this related issue but there is no final answer : https://github.com/nodogsplash/nodogsplash/issues/338

I am at a complete loss. Any help would be greatly appreciated.

**Comment by bluewavenet** [comment]
@sojastar 
I think you need to get your Nginx server working first, the error log implies you have a config error there.
Take NDS out of the equation while testing the web server by typing:
`ndsctl stop`

You are getting the splash page popping up, so it seems NDS is running ok.

**Comment by sojastar** [comment]
@bluewavenet 

Thanks for your quick answer.

As I said somewhere in the ( admittedly very long ) message, when Nodogsplash is not running, connecting to the Pi works perfectly and Nginx doesn't reports any error at all. Hence my confusion.

Also, I've set the debug level to 7 in /etc/nodogsplash/nodogsplash.conf but can't find any log file. Where those that debug information go?

Thanks again.

**Comment by bluewavenet** [comment]
It is quite possible that RedirectURL is not working, it is rarely used as the client CPD will close its browser as soon as the client gets authenticated, so it might be that no one has noticed it no longer works! It should really be deprecated for new versions. 
FAS or FAS/PreAuth is the way to do this and avoid any CPD issues.

Try this:
1. set up your Ngnix server on port 2080 instead of port 80 (and test to make sure it is working with NDS not running).
2. Comment out the RedirectURL line in nodogsplash.conf
3. add  `fasport 2080` to nodogsplash.conf
4. restart NDS
5. Try connecting again

**Comment by sojastar** [comment]
@bluewavenet 

Thanks a lot! I'll try it tomorrow when I'm at work again and report any progress.

**Comment by bluewavenet** [comment]
By the way, the NDS logs are added to the system logs.

Also the fasport setting should already be in nodogsplash.conf but commented out.

Finally, you are using the unreleased beta version. Currently this is fine but no guarantees it will stay that way as people work on it.

It would be better to use the release version before going live.
You can find this by clicking "Releases" on the NDS github page.

At the time of writing this, the current release is at:
https://github.com/nodogsplash/nodogsplash/archive/v3.3.2.tar.gz

**Comment by sojastar** [comment]
@bluewavenet 
It works great ! Thanks ! I think the issue can be closed.

Abusing your patience, I have one last question. If I wanted to pop a new tab from the splash page using something like:

```
<form action="http://pedrasparaler.local:2080/somewhere" target="_blank">
  <input type="hidden" name="tok" value="$tok">
  <input type="hidden" name="redir" value="$redir">
  <input type="submit" value="Go to somewhere local">
</form>
```

whether the new tab would pop or not is completely dependant on the client device capabilities and not something I could setup within Nodogsplash, right? I'm asking because on the iPhone, the browser windows that appears in the WiFi selection tab is very functionally limited and this technique doesn't seem to work.

Thanks again for the great help !

**Comment by bluewavenet** [comment]
@sojastar 
Using FAS with the config I proposed, you are not using splash.html at all, as you can see, the "splash page" is your web page.
See:
https://nodogsplashdocs.readthedocs.io/en/stable/splash.html

The browser that a client CPD uses is limited. From the "Customising nodogsplash" section of the documentation, here is a list of things you might not be able to do on your splash page:

It should be noted when designing a custom splash page that for security reasons many client device CPD implementations:

* Immediately close the browser when the client has authenticated.
* Prohibit the use of href links.
* Prohibit downloading of external files (including .css and .js, even if they are allowed in NDS firewall settings).
* Prohibit the execution of javascript.

You can however use html forms to provide action buttons to navigate your web pages. You will find code examples in the FAS example files.

**Comment by sojastar** [comment]
@bluewavenet 
Sorry for answering so late. And sorry for the misunderstanding. By splash page I meant the front page of my own site.
Everything makes sense now.
Thanks again for all your detailed answers. I'll close the issue.
