### ISSUE TITLE
redirect to specific page after splash page?

### ISSUE THREAD

**Issue by jessebruffett** [nodogsplash/nodogsplash#366]
Is there a way to redirect people directly and automatically from the home page to a specific web page? A google form to be specific. Ive been at it for some time now and I can't get it to work. is it even possible?

**Comment by bluewavenet** [comment]
@jessebruffett 
Perhaps you can give us more details on what you are trying to do and what hardware/versions etc.

It is worth reading #365 

Although that is concerned with a redirect to a local page without Internet connectivity, the solution will be the same, ie use FAS to redirect to the external page.

However the redirection MUST be to a valid IPv4 address (not a URL) This is problematic when the site in question is serving multiple URLs on a single IP address.

The documentation deals with this but I have no idea whether this will work with anything on Google.
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html
