### ISSUE TITLE
NDS android problem

### ISSUE THREAD

**Issue by LauriHeiskari** [nodogsplash/nodogsplash#367]
Hi!

I installed NDS to openwrt router, and modified the splash.html to look more modern. I also made url redirect to my home page when user push continue. Everything works perfectly, but the captiveportal does not keep open with new android phones. Fos now it looks like there is no solutions for this? What i managed to do is block e.g clients3.google.com from router, but then android thinks there no internet and splashpage noes not open. Is there way to make splashpage open even in thissituation.

Bluewawenet wrote this...

1. If there is Internet => client CPD DNS query for connectivity check url gets real IP - everything as normal - splash page is triggered.
2. Internet Down (or not even available) => client CPD DNS query for connectivity check url gets gateway address - splash page is triggered.

**Comment by bluewavenet** [comment]
@LauriHeiskari 
This is how Captive Portal Detection (CPD) is designed to work.

For security reasons, as soon as the client device detects an open Internet connection it will, by default, close the CPD browser. (some older versions of client OS do not necessarily do this and some allow this to be disabled).

clients3.google.com is one of many detection urls and is often not used in vendor specific versions of Android.

If you want to keep the CPD browser open you cannot use the default NDS splash page processing, instead you must use FAS. The CPD browser will then stay open until FAS authenticates with NDS to allow the client to access the Internet - then, of course, the CPD browser will close (depending on CPD implementations as mentioned above.)

It is worth reading #366 #365 and #363 
Setting up FAS for keeping the CPD browser open is discussed there.

**Comment by LauriHeiskari** [comment]
Hi!
Thanks for a reply. I will read about FAS and see where i end up to. 
But at the moment after installing openwrt and NDS, i have only edites splash.html more modern (text in Finnish) and made redirect to my website. This works well in ios and windows. What i ment that with android my redirected website closes down. So basically CPD keeps open, but my redicted website wont.

/Lauri

**Comment by bluewavenet** [comment]
@LauriHeiskari
There are many implementations of CPD but all are converging in functionality as new versions come out. Those that stay open now might not do so after updates.

Configuring FAS to redirect clients to a web page that stays open is just a simple change the the NDS config file - detailed in one of the issues I linked earlier.
Let me know if you would like me to describe it again. On my mobile at the moment so not easy to copy to here just now.

**Comment by bluewavenet** [comment]
It's in #365
If your web server is external you will have to set fasremoteip and fasport to match the remote server.

**Comment by bluewavenet** [comment]
Do please comment here if you have any more questions.
