### ISSUE TITLE
Start up FAS. I always get "Exited"

### ISSUE THREAD

**Issue by SergioDG-YCC** [nodogsplash/nodogsplash#370]
Start up FAS. I always get "Excited"
Hi. I am new, and very new with codes. But I tried to activate FAS on a small 4G router based on OpenWrt. I could not get the version of NoDogSplash, although I suppose it's v2.0. What I want is to direct the Splash to an external one, which is https, since after trying to bring that external page, using an iframe, I understood that I was trying to put an https inside an http.
Next step, to try with FAS, I have not achieved anything but "exited process" errors. I know something is wrong, that I can not understand. I also could not update to V3.3.1 or 3.3.2, I did not understand the method. Here the code in / etc / config / nodegsplash. Excuse my bad English

`
config nodogsplash

	option enabled '1'
	option fasport '2080'
	option faspath 'https://www.iwifi.com.ar/sites/L108/2405/index.html'
	option fas_secure_enable '0'
	option gatewayinterface 'https://www.iwifi.com.ar/'
	option gatewayname 'iWiFi'
	option maxclients '50'
	list authenticated_users 'allow all'
	list preauthenticated_users 'allow tcp port 80 to 10.10.10.0/24'
	list preauthenticated_users 'allow tcp port 80 to micro.tv'
	list preauthenticated_users 'allow tcp port 80 to www.google.com'
	list preauthenticated_users 'allow tcp port 80 to www.yccgroup.com.ar'
	list preauthenticated_users 'allow tcp port 80 to www.iwifi.com.ar'
	list preauthenticated_users 'allow tcp port 80 to vod.micro.tv'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 23'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 80'
	list fw_mark_authenticated '520'
	list fw_mark_trusted '510'
	list fw_mark_blocked '500'
	option clientidletimeout '60'
	option clientforcetimeout '10'
	list allow_site 'www.google.com'
	list allow_site 'www.yccgroup.com.ar'
	list allow_site 'www.iwifi.com.ar'
`
![20190618_015259](https://user-images.githubusercontent.com/51941365/59654429-7d86ea00-916c-11e9-8320-6183dc5fe822.jpg)
![20190618_015307](https://user-images.githubusercontent.com/51941365/59654431-7e1f8080-916c-11e9-9460-5b342ea99cf1.jpg)
![20190618_015324](https://user-images.githubusercontent.com/51941365/59654432-7e1f8080-916c-11e9-8d7e-a166fd4f3034.jpg)

**Comment by bluewavenet** [comment]
What versions of OpenWrt  and NDS are you using?
I am not familiar with the hardware you are using, what is the make and model?

We will need this information to be able to help.

At the time of writing the current version of NDS is v3.3.2 and for FAS you need at least v3.1.0
This is supported for OpenWrt v18.xx and above, it may work under LEDE 17.xx, but will not for OpenWrt versions 15.xx and below.

It will be worth reading the current documentation:
https://nodogsplashdocs.readthedocs.io

Your current config file is invalid in many ways and is the cause of the "Exited" message.

**Comment by mwarning** [comment]
@SergioDG-YCC please check the log with the logread command. NDS should tell you where the problem is.
I assume it is because `allow_site` needs to be an IP address and `gatewayinterface` needs to be an network interface (like 'eth0').

**Comment by bluewavenet** [comment]
allow_site ?

**Comment by SergioDG-YCC** [comment]
Okay. I just saw the interface gateway. I think my interface is BR. The Allow Site was preset at the factory. just change the dns for mine. Anyway I have not managed to update to 3.3.x. I contacted the manufacturer in Taiwan but it knows less than me 😒

**Comment by bluewavenet** [comment]
@SergioDG-YCC
My guess is this device is running a very old customised version of OpenWrt. But it probably works very well.
It might be better to keep it untouched and add a small up to date router to it. Something like a gl-ar300m which is supported by the very latest OpenWrt and has lots of flash and ram as well as being low priced. Run NDS on this instead. You cannot redirect to an https site directly in any circumstances as this will cause security errors and make the client CPD fail. You can use a local FAS to send and receive data from it instead. How this is done will depend on the external site and not how NDS is configured.

**Comment by SergioDG-YCC** [comment]
> @ SergioDG-YCC Creo
> que este dispositivo está ejecutando una versión muy antigua de OpenWrt. Pero probablemente funcione muy bien. 
> Podría ser mejor mantenerlo intacto y agregarle un enrutador pequeño y actualizado. Algo así como un gl-ar300m que es compatible con el último OpenWrt y tiene muchos flash y ram, además de ser de bajo precio. Ejecutar NDS en este lugar. No puede redirigir a un sitio https directamente en ninguna circunstancia, ya que esto causará errores de seguridad y hará que el CPD del cliente falle. Puede utilizar un FAS local para enviar y recibir datos de él en su lugar. La forma en que se haga esto dependerá del sitio externo y no de la configuración de NDS.

Here is the dilemma. Our client wants to show an ads during or after authentication. These ads are provided by google, doubleclick.net, etc and are inserted in your website. Initially redirected to that link after authentication. Up to Android 5, including 6, everything was great. As of Android 7 the thing changed. When detecting internet, the floating browser is closed, and goodbye ads.

**Comment by SergioDG-YCC** [comment]
Initially I will try correcting the conf, for example 'gatewayinterface' which is wrong, if it does not work either I will verify the version of Openwrt and Nodogsplash, I will try to update. I have already done an update of OpenWrt and I stop working LUCI, it does not matter too much if I use the console. But my inexperience does not know the steps to update Nodogsplash to 3.3.x.
Regarding the equipment, it has 128mb of ram. When I connect it I will send capture of the Top

**Comment by bluewavenet** [comment]
@SergioDG-YCC 
Also send /etc/board.json please, then we will know what the hardware is.

**Comment by bluewavenet** [comment]
@SergioDG-YCC 
Primero, necesita llegar a un estado conocido con su firmware.
A continuación, puede ejecutar la última versión de NodogSplash.
A continuación, puede visualizar las imágenes que necesita.
He creado un ejemplo de script de inicio de sesión para Preauth que mostrará cómo mostrar imágenes remotas, una vez que tenga todas las nuevas versiones, puede probar esto.

PR #374

**Comment by SergioDG-YCC** [comment]
My board.json

`{
	"led": {
		"wifi": {
			"name": "WIFI",
			"type": "netdev",
			"sysfs": "linkall:wifi",
			"device": "ra0"
		},
		"sys": {
			"name": "SYS",
			"type": "netdev",
			"sysfs": "linkall:sys",
			"device": "eth1"
		}
	},
	"network": {
		"lan": {
			"ifname": "eth0",
			"create_vlan": true,
			"macaddr": "b0:ce:18:10:13:80"
		},
		"wan": {
			"ifname": "eth0",
			"create_vlan": true,
			"macaddr": "b0:ce:18:10:13:81"
		}
	}
}
`

**Comment by bluewavenet** [comment]
It is a very old version of OpenWrt and you will not be able to run the latest version of NDS unless you can upgrade OpenWrt.

It is too old for board.json to report the model name so I am not much further forward.

What is the manufacturer name and model name?

**Comment by SergioDG-YCC** [comment]
I will try to update OpenWrt. The manufacturing data are those that are on the label ... =D

**Comment by SergioDG-YCC** [comment]
All the different hardware that comes to me from the east, bring old soft. I hope that one day they press the 'China upgrade' button

**Comment by bluewavenet** [comment]
Is this for your bus wifi project? Have you already purchased  lots of 4g routers?
If you have and therefore stuck with them then a good way forward is to add a small modern travel router eg the Gl-iNet ar300m and put OpenWrt latest wir Nodogsplash latest and plug into the lan port of the 4g router. This will be a cheap solution and works very well ( I have done just this on numerous projects).

https://www.gl-inet.com/products/gl-ar300m/

**Comment by SergioDG-YCC** [comment]
Actually that idea is not viable. Our client already has more than 200 installed equipment, in urban buses. What, we, have installed. We will not tell our client that the equipment does not work and that he must spend money on an additional equipment = /. Free internet, in exchange for ads. The problem is that you can not reach ads. The only viable solution I see is to try to update all the soft. What comes from the East is really old-fashioned.

**Comment by SergioDG-YCC** [comment]
![20190623_154034](https://user-images.githubusercontent.com/51941365/59980543-bd672a80-95cd-11e9-8884-f2ef9833134a.jpg)
The 4g modem is a Quectel ec25-au, it really works acceptably well

**Comment by SergioDG-YCC** [comment]
![Captura](https://user-images.githubusercontent.com/51941365/59980727-31a2cd80-95d0-11e9-8c0f-8cb5d8095f17.PNG)
Capture my top. 128mb ram

**Comment by bluewavenet** [comment]
Post the outputs of "free"  and "df -h".

We know it is a ramips/mt7688 SoC.

If it has a flash of 16MB or more and 128 MB ram we are in with a chance of doing something.

Alternatively NDS version 1.x can be manually configured to run a FAS at least perhaps enough to do something.

Upgrading is really what you need to achive though - flash and ram permitting.

**Comment by bluewavenet** [comment]
Does anything in this list look like it might be it?
http://downloads.openwrt.org/snapshots/targets/ramips/mt76x8/

**Comment by SergioDG-YCC** [comment]
Fortunately, I was able to join Luci. I was in //cgi-bin/luci. Now I can see all the data. It is version 15 of openwrt. In a while I upload all the data

**Comment by bluewavenet** [comment]
Output of "df -h" ?

**Comment by SergioDG-YCC** [comment]
![Captura2](https://user-images.githubusercontent.com/51941365/59981476-2c4a8080-95da-11e9-9fb4-8a9937696a8e.PNG)

**Comment by SergioDG-YCC** [comment]
Data of LUCI
Hostname | OpenWrt
Model | 76x8linkall
Firmware Version | OpenWrt Chaos Calmer 15.05.1 r49389 / LuCI for-15.05 branch (git-18.097.75958-5537d68)
Kernel Version | 3.18.45

**Comment by bluewavenet** [comment]
Output of "ndsctl status"

**Comment by SergioDG-YCC** [comment]
I have managed to update to openwrt 18, NDS is not installed, it is the next step. I got a seemingly compatible firmware from your link. Thank you. Luci was not included, I have already installed it manually by ssh

**Comment by SergioDG-YCC** [comment]
=D
==================
NoDogSplash Status
====
Version: 3.3.2
Uptime: 40s
Gateway Name: OpenWrt Nodogsplash
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.11.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Disabled
Client Check Interval: 600s
Preauth Idle Timeout: 30m
Auth Idle Timeout: 120m
Traffic control: no
Total download: 6 kByte; avg: 1.32 kbit/s
Total upload: 6 kByte; avg: 1.20 kbit/s
====
Client authentications since start: 0
Current clients: 0
====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========
admin@OpenWrt:/root#

**Comment by SergioDG-YCC** [comment]
I can not get to the fas.php because my ip, also that of my client, hosts several domains (DNS). How can I tell you a DNS instead of an IP?


NoDogSplash Status
====
Version: 3.3.2
Uptime: 1s
Gateway Name: OpenWrt Nodogsplash
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.11.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Secure=1 URL: http://190.2.45.49:80/htdocs/fas.php
Client Check Interval: 600s
Preauth Idle Timeout: 30m
Auth Idle Timeout: 120m
Traffic control: no
Total download: 0 kByte; avg: 1.92 kbit/s
Total upload: 0 kByte; avg: 1.98 kbit/s
====
Client authentications since start: 0
Current clients: 0
====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none

**Comment by SergioDG-YCC** [comment]
I got "FAS" to work. I still have to solve a problem: I need to see an external web page during authentication, and I can not get it. Add all these firewall rules and none allow me to pass those webs:

`
# auto-generated config file from /etc/config/nodogsplash
GatewayInterface br-lan
fasport 80
fasremoteip 190.2.45.49
faspath /htdocs/fas.php
fas_secure_enabled 0
maxclients 250
gatewayname iWiFi
gatewayinterface br-lan
webroot /etc/nodogsplash/htdocs
sessiontimeout 1200
preauthidletimeout 30
authidletimeout 120
checkinterval 600
TrustedMACList 98:E7:F4:5f:20:A8
FirewallRuleSet authenticated-users {
  FirewallRule allow all
}
FirewallRuleSet preauthenticated-users {
  FirewallRule allow tcp port 80 to google.com
  FirewallRule allow tcp port 80 to yccgroup.com.ar
  FirewallRule allow tcp port 80 to iwifi.com.ar
  FirewallRule allow tcp port 80 to vod.micro.tv
  FirewallRule allow tcp port 443 to google.com
  FirewallRule allow tcp port 443 to yccgroup.com.ar
  FirewallRule allow tcp port 443 to iwifi.com.ar
  FirewallRule allow tcp port 443 to vod.micro.tv
  FirewallRule allow tcp port 53
  FirewallRule allow udp port 53
}
FirewallRuleSet users-to-router {
  FirewallRule allow tcp port 22
  FirewallRule allow tcp port 23
  FirewallRule allow tcp port 53
  FirewallRule allow udp port 53
  FirewallRule allow udp port 67
  FirewallRule allow tcp port 80
  FirewallRule allow tcp port 80 to google.com
  FirewallRule allow tcp port 80 to googletagmanager.com
  FirewallRule allow tcp port 80 to yccgroup.com.ar
  FirewallRule allow tcp port 80 to iwifi.com.ar
  FirewallRule allow tcp port 80 to vod.micro.tv
  FirewallRule allow tcp port 443
  FirewallRule allow tcp port 443 to google.com
  FirewallRule allow tcp port 443 to googletagmanager.com
  FirewallRule allow tcp port 443 to yccgroup.com.ar
  FirewallRule allow tcp port 443 to iwifi.com.ar
  FirewallRule allow tcp port 443 to vod.micro.tv
}
FirewallRuleSet trusted-users {
}
FirewallRuleSet trusted-users-to-router {
}
`

**Comment by bluewavenet** [comment]
@SergioDG-YCC 
Which firmware did you choose from the list?

**Comment by SergioDG-YCC** [comment]
hilink_hlk-7628n-squashfs-sysupgrade.bin 

I adapt quite well. I just did not have LUCY. I installed it by ssh, and then from LUCY I installed NDS

**Comment by bluewavenet** [comment]
Now you have FAS working there are a few important things to know.
Firstly though, NDS config for all firewall rules must be ip addresses.

But also adding access to other web sites in firewall rules is not really going to work very well if at all mainly due to restrictions on the client device, so this is not the way to do it.
I will, for your information, post a list of rules for what the client will allow.

To solve this issue you will need your FAS to pull in remote web site information and relay it to the client. I will give some pointers for this also.

**Comment by bluewavenet** [comment]
To get your Internet hosted FAS working you have set fas_secure_enabled = 0.
This means a knowledgeable user could bypass FAS, but if you are not intending to do a credential check in FAS, but just display information/advertising, then this will probably not matter. You will have to decide if this method is acceptable.

**Comment by bluewavenet** [comment]
Client devices all have captive portal detection (CPD). This is what opens the screen on the device when it connects to the Wifi.

Different vendors implement CPD in different ways.

It should be noted when designing a custom splash page that for security reasons many client device CPD implementations:

- Immediately close the browser when the client has authenticated.
- Prohibit the use of href links.
- Prohibit downloading of external files (including .css and .js, even if they are allowed in NDS firewall settings).
- Prohibit the execution of javascript.

How the Client CPD reacts is entirely up to how that client based CPD code is implemented and is outside the control of any captive portal.

**Comment by bluewavenet** [comment]
So from this you can see, embedding Googleads into the splash page is going to be quite difficult even if you could add all the relevant ip addresses to the firewall rules.

**Comment by SergioDG-YCC** [comment]
I do not know almost anything about iptables, but I tried to create some rules input_wan_rule in firewall.user, they did not work:
`
iptables -A input_wan_rule -p tcp -s googletagmanager.com --dport 80 -j ACCEPT
iptables -A input_wan_rule -p tcp -s iwifi.com.ar --dport 80 -j ACCEPT
iptables -A input_wan_rule -p tcp -s googletagmanager.com --dport 443 -j ACCEPT
iptables -A input_wan_rule -p tcp -s iwifi.com.ar --dport 443 -j ACCEPT
`

**Comment by SergioDG-YCC** [comment]
> So from this you can see, embedding Googleads into the splash page is going to be quite difficult even if you could add all the relevant ip addresses to the firewall rules.
> 
> This is not a deficiency in NDS, it is a deliberate restriction built into client devices.

Yes. Its a big problem. But I think if I have access to googletagmanager.com it's enough

**Comment by SergioDG-YCC** [comment]
> So from this you can see, embedding Googleads into the splash page is going to be quite difficult even if you could add all the relevant ip addresses to the firewall rules.
> 
> This is not a deficiency in NDS, it is a deliberate restriction built into client devices.

I think I have the right dns, dodging google:

https://ad.doubleclick.net/
https://pubads.g.doubleclick.net/
https://www.googletagmanager.com/
https://www.iwifi.com.ar/

**Comment by bluewavenet** [comment]
Your iptables entries must have an ip address not a domain name. This is why NDS must also have ip addresses.

**Comment by bluewavenet** [comment]
Googleads requires a download of javascript to the user's browser. Most implementations of CPD on clients block such downloads.

**Comment by SergioDG-YCC** [comment]
I already did the splash test with flowplayer, which requires jquery

**Comment by bluewavenet** [comment]
I thought Flowplayer was a video player?

**Comment by SergioDG-YCC** [comment]
![Screenshot_2019-06-12-22-12-52](https://user-images.githubusercontent.com/51941365/60019350-0a95db80-9664-11e9-99c0-9cff2da2e574.png)
Yes. Flowplayer uses 2 js and 1 css. This is a hotspot in a mikrotik. same as NDS

**Comment by bluewavenet** [comment]
The issue is how the client displays the splash page using its CPD.
As I mentioned earlier, the CPD on most up to date mobile devices will not download or run a remote javascript file. Some older CPD implementations MAY download and run, but this cannot be relied upon.
There are ways to get round this problem but the solution will depend on the details of each remote site.

**Comment by SergioDG-YCC** [comment]
It will be a matter of trying. I've already had several problems with Android 9, in various devices, not exactly hotspots

**Comment by SergioDG-YCC** [comment]
I need at this moment, a Walled Garden towards an IP range, I do not find in the docs how to configure it

**Comment by bluewavenet** [comment]
I think this issue is now resoved by upgrading the firmware in your device to allow later versions of NDS to be run.

It will be more useful to open a new issue for Walled Garden.
