### ISSUE TITLE
error when adding new key to config file

### ISSUE THREAD

**Issue by khoailangdo** [nodogsplash/nodogsplash#371]
I added a key called 'fas_key' to the config file. when i reboot by command

> /etc/init.d/nodogsplash restart

The error is as follows.

> Tue Jun 18 09:57:58 2019 kern.notice nodogsplash[1783]: Warning - Forwarding Authentication - Security is DISABLED.
Tue Jun 18 09:57:59 2019 daemon.err odhcp6c[1273]: Failed to send DHCPV6 message to ff02::1:2 (Operation not permitted)
Tue Jun 18 09:57:59 2019 kern.notice nodogsplash[1783]: Initializing firewall rules
Tue Jun 18 09:57:59 2019 kern.err nodogsplash[1783]: FW_MARK_BLOCKED, FW_MARK_TRUSTED, FW_MARK_AUTHENTICATED not all nonzero.
Tue Jun 18 09:57:59 2019 kern.info kernel: [   59.797956] do_page_fault(): sending SIGSEGV to nodogsplash for invalid read access from 52454a45
Tue Jun 18 09:57:59 2019 kern.info kernel: [   59.807129] epc = 77f0400c in libc.so[77e92000+95000]
Tue Jun 18 09:57:59 2019 kern.info kernel: [   59.812483] ra  = 77f05f2c in libc.so[77e92000+95000]
Tue Jun 18 09:57:59 2019 daemon.info procd: Instance nodogsplash::cfg015847 s in a crash loop 6 crashes, 1 seconds since last crash

The commands that call 'fas_key' I execute in file conf.c and conf.h

what happened ?. Please help me fix the error

Thanks

**Comment by bluewavenet** [comment]
What is fas_key supposed to do?

Your c code obviously breaks things.
Care to share it?

**Comment by khoailangdo** [comment]
This is conf.h and conf.c


[conf.zip](https://github.com/nodogsplash/nodogsplash/files/3301361/conf.zip)

**Comment by bluewavenet** [comment]
Do you have your fork on Github? It will be much easier to see the changes then.

Also can you explain what you are trying to achieve?

**Comment by khoailangdo** [comment]
I just added 1 key to the config for later setup. .
But when I add the full information to the config file and soure the code, the error is as above

**Comment by mwarning** [comment]
The source code looks fine to me. The problem seems to be "FW_MARK_BLOCKED, FW_MARK_TRUSTED, FW_MARK_AUTHENTICATED not all nonzero."

**Comment by khoailangdo** [comment]
`
/** @internal
 * A flag.  If set to 1, there are missing or empty mandatory parameters in the config
 */
static int missing_parms;

/** @internal
 The different configuration options */
typedef enum {
	oBadOption,
	oSessionTimeout,
	oDaemon,
	oDebugLevel,
	oMaxClients,
	oGatewayName,
	oGatewayInterface,
	oGatewayIPRange,
	oGatewayIP,
	/* TODO: deprecate oGatewayAddress option */
	oGatewayAddress,
	oGatewayPort,
	oFasPort,
	oFasPath,
	oFasRemoteIP,
	oFasSecureEnabled,
	oFasAesKey,
	oHTTPDMaxConn,
	oWebRoot,
	oSplashPage,
	oStatusPage,
	oImagesDir,
	oPagesDir,
	oRedirectURL,
	oPreauthIdleTimeout,
	oAuthIdleTimeout,
	oCheckInterval,
	oSetMSS,
	oMSSValue,
	oTrafficControl,
	oDownloadLimit,
	oUploadLimit,
	oUploadIFB,
	oNdsctlSocket,
	oSyslogFacility,
	oFirewallRule,
	oFirewallRuleSet,
	oEmptyRuleSetPolicy,
	oMACmechanism,
	oTrustedMACList,
	oBlockedMACList,
	oAllowedMACList,
	oFWMarkAuthenticated,
	oFWMarkTrusted,
	oFWMarkBlocked,
	oBinAuth,
	oPreAuth
} OpCodes;

/** @internal
 The config file keywords for the different configuration options */
static const struct {
	const char *name;
	OpCodes opcode;
	int required;
} keywords[] = {
	{ "sessiontimeout", oSessionTimeout },
	{ "daemon", oDaemon },
	{ "debuglevel", oDebugLevel },
	{ "maxclients", oMaxClients },
	{ "gatewayname", oGatewayName },
	{ "gatewayinterface", oGatewayInterface },
	{ "gatewayiprange", oGatewayIPRange },
	{ "gatewayip", oGatewayIP },
	/* TODO: remove/deprecate gatewayaddress keyword */
	{ "gatewayaddress", oGatewayAddress },
	{ "gatewayport", oGatewayPort },
	{ "fasport", oFasPort },
	{ "fasremoteip", oFasRemoteIP },
	{ "fas_secure_enabled", oFasSecureEnabled },
	{ "faspath", oFasPath },
	{ "fas_aes_key", oFasAesKey },
	{ "webroot", oWebRoot },
	{ "splashpage", oSplashPage },
	{ "statuspage", oStatusPage },
	{ "imagesdir", oImagesDir },
	{ "pagesdir", oPagesDir },
	{ "redirectURL", oRedirectURL },
	{ "preauthidletimeout", oPreauthIdleTimeout },
	{ "authidletimeout", oAuthIdleTimeout },
	{ "checkinterval", oCheckInterval },
	{ "setmss", oSetMSS },
	{ "mssvalue", oMSSValue },
	{ "trafficcontrol",	oTrafficControl },
	{ "downloadlimit", oDownloadLimit },
	{ "uploadlimit", oUploadLimit },
	{ "ifb", oUploadIFB },
	{ "syslogfacility", oSyslogFacility },
	{ "ndsctlsocket", oNdsctlSocket },
	{ "firewallruleset", oFirewallRuleSet },
	{ "firewallrule", oFirewallRule },
	{ "emptyrulesetpolicy", oEmptyRuleSetPolicy },
	{ "trustedmaclist", oTrustedMACList },
	{ "blockedmaclist", oBlockedMACList },
	{ "allowedmaclist", oAllowedMACList },
	{ "MACmechanism", oMACmechanism },
	{ "fw_mark_authenticated", oFWMarkAuthenticated },
	{ "fw_mark_trusted", oFWMarkTrusted },
	{ "fw_mark_blocked", oFWMarkBlocked },
	{ "binauth", oBinAuth },
	{ "preauth", oPreAuth },
	{ NULL, oBadOption },
};

static void config_notnull(const void *parm, const char *parmname);
static int parse_boolean(const char *);
static int _parse_firewall_rule(t_firewall_ruleset *ruleset, char *leftover);
static void parse_firewall_ruleset(const char *, FILE *, const char *, int *);

static OpCodes config_parse_opcode(const char *cp, const char *filename, int linenum);

/** @internal
Strip comments and leading and trailing whitespace from a string.
Return a pointer to the first nonspace char in the string.
*/
static char* _strip_whitespace(char* p1);

/** Accessor for the current gateway configuration
@return:  A pointer to the current config.  The pointer isn't opaque, but should be treated as READ-ONLY
 */
s_config *
config_get_config(void)
{
	return &config;
}

/** Sets the default config parameters and initialises the configuration system */
void
config_init(void)
{
	t_firewall_ruleset *rs;

	debug(LOG_DEBUG, "Setting default config parameters");
	strncpy(config.configfile, DEFAULT_CONFIGFILE, sizeof(config.configfile)-1);
	config.session_timeout = DEFAULT_SESSION_TIMEOUT;
	config.debuglevel = DEFAULT_DEBUGLEVEL;
	config.maxclients = DEFAULT_MAXCLIENTS;
	config.gw_name = safe_strdup(DEFAULT_GATEWAYNAME);
	config.gw_interface = NULL;
	config.gw_iprange = safe_strdup(DEFAULT_GATEWAY_IPRANGE);
	config.gw_address = NULL;
	config.gw_ip = NULL;
	config.gw_port = DEFAULT_GATEWAYPORT;
	config.fas_port = DEFAULT_FASPORT;
	config.fas_secure_enabled = DEFAULT_FAS_SECURE_ENABLED;
	config.fas_remoteip = NULL;
	config.fas_path = DEFAULT_FASPATH;
	config.webroot = safe_strdup(DEFAULT_WEBROOT);
	config.splashpage = safe_strdup(DEFAULT_SPLASHPAGE);
	config.statuspage = safe_strdup(DEFAULT_STATUSPAGE);
	config.imagesdir = safe_strdup(DEFAULT_IMAGESDIR);
	config.pagesdir = safe_strdup(DEFAULT_PAGESDIR);
	config.authdir = safe_strdup(DEFAULT_AUTHDIR);
	config.denydir = safe_strdup(DEFAULT_DENYDIR);
	config.preauthdir = safe_strdup(DEFAULT_PREAUTHDIR);
	config.redirectURL = NULL;
	config.preauth_idle_timeout = DEFAULT_PREAUTH_IDLE_TIMEOUT,
	config.auth_idle_timeout = DEFAULT_AUTH_IDLE_TIMEOUT,
	config.checkinterval = DEFAULT_CHECKINTERVAL;
	config.daemon = -1;
	config.set_mss = DEFAULT_SET_MSS;
	config.mss_value = DEFAULT_MSS_VALUE;
	config.traffic_control = DEFAULT_TRAFFIC_CONTROL;
	config.upload_limit =  DEFAULT_UPLOAD_LIMIT;
	config.download_limit = DEFAULT_DOWNLOAD_LIMIT;
	config.upload_ifb =  DEFAULT_UPLOAD_IFB;
	config.syslog_facility = DEFAULT_SYSLOG_FACILITY;
	config.log_syslog = DEFAULT_LOG_SYSLOG;
	config.ndsctl_sock = safe_strdup(DEFAULT_NDSCTL_SOCK);
	config.internal_sock = safe_strdup(DEFAULT_INTERNAL_SOCK);
	config.rulesets = NULL;
	config.trustedmaclist = NULL;
	config.blockedmaclist = NULL;
	config.allowedmaclist = NULL;
	config.macmechanism = DEFAULT_MACMECHANISM;
	config.fw_mark_authenticated = DEFAULT_FW_MARK_AUTHENTICATED;
	config.fw_mark_trusted = DEFAULT_FW_MARK_TRUSTED;
	config.fw_mark_blocked = DEFAULT_FW_MARK_BLOCKED;
	config.ip6 = DEFAULT_IP6;
	config.binauth = NULL;
	config.preauth = NULL;

	/* Set up default FirewallRuleSets, and their empty ruleset policies */
	rs = add_ruleset("trusted-users");
	rs->emptyrulesetpolicy = safe_strdup(DEFAULT_EMPTY_TRUSTED_USERS_POLICY);
	rs = add_ruleset("trusted-users-to-router");
	rs->emptyrulesetpolicy = safe_strdup(DEFAULT_EMPTY_TRUSTED_USERS_TO_ROUTER_POLICY);
	rs = add_ruleset("users-to-router");
	rs->emptyrulesetpolicy = safe_strdup(DEFAULT_EMPTY_USERS_TO_ROUTER_POLICY);
	rs = add_ruleset("authenticated-users");
	rs->emptyrulesetpolicy = safe_strdup(DEFAULT_EMPTY_AUTHENTICATED_USERS_POLICY);
	rs = add_ruleset("preauthenticated-users");
	rs->emptyrulesetpolicy = safe_strdup(DEFAULT_EMPTY_PREAUTHENTICATED_USERS_POLICY);
}

/**
 * If the command-line didn't specify a config, use the default.
 */
void
config_init_override(void)
{
	if (config.daemon == -1) {
		config.daemon = DEFAULT_DAEMON;
	}
}

/** @internal
Attempts to parse an opcode from the config file
*/
static OpCodes
config_parse_opcode(const char *cp, const char *filename, int linenum)
{
	int i;

	for (i = 0; keywords[i].name; i++) {
		if (strcasecmp(cp, keywords[i].name) == 0) {
			return keywords[i].opcode;
		}
	}

	debug(LOG_ERR, "%s: line %d: Bad configuration option: %s", filename, linenum, cp);
	return oBadOption;
}

/**
Advance to the next word
@param s string to parse, this is the next_word pointer, the value of s
	 when the macro is called is the current word, after the macro
	 completes, s contains the beginning of the NEXT word, so you
	 need to save s to something else before doing TO_NEXT_WORD
@param e should be 0 when calling TO_NEXT_WORD(), it'll be changed to 1
	 if the end of the string is reached.
*/
#define TO_NEXT_WORD(s, e) do { \
	while (*s != '\0' && !isblank(*s)) { \
		s++; \
	} \
	if (*s != '\0') { \
		*s = '\0'; \
		s++; \
		while (isblank(*s)) \
			s++; \
	} else { \
		e = 1; \
	} \
} while (0)

/**
@param filename Full path of the configuration file to be read
*/
void
config_read(const char *filename)
{
	FILE *fd;
	char line[MAX_BUF], *s, *p1, *p2;
	int linenum = 0, opcode, value;
	struct stat sb;

	debug(LOG_INFO, "Reading configuration file '%s'", filename);

	if (!(fd = fopen(filename, "r"))) {
		debug(LOG_ERR, "FATAL: Could not open configuration file '%s', "
			  "exiting...", filename);
		exit(1);
	}

	while (fgets(line, MAX_BUF, fd)) {
		linenum++;
		s = _strip_whitespace(line);

		/* if nothing left, get next line */
		if (s[0] == '\0') continue;

		/* now we require the line must have form: <option><whitespace><arg>
		 * even if <arg> is just a left brace, for example
		 */

		/* find first word (i.e. option) end boundary */
		p1 = s;
		while ((*p1 != '\0') && (!isspace(*p1))) p1++;
		/* if this is end of line, it's a problem */
		if (p1[0] == '\0') {
			debug(LOG_ERR, "Option %s requires argument on line %d in %s", s, linenum, filename);
			debug(LOG_ERR, "Exiting...");
			exit(-1);
		}

		/* terminate option, point past it */
		*p1 = '\0';
		p1++;

		/* skip any additional leading whitespace, make p1 point at start of arg */
		while (isblank(*p1)) p1++;

		debug(LOG_DEBUG, "Parsing option: %s, arg: %s", s, p1);
		opcode = config_parse_opcode(s, filename, linenum);

		switch(opcode) {
		case oSessionTimeout:
			if (sscanf(p1, "%d", &config.session_timeout) < 1 || config.session_timeout < 0) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oDaemon:
			if (config.daemon == -1 && ((value = parse_boolean(p1)) != -1)) {
				config.daemon = value;
			}
			break;
		case oDebugLevel:
			if (sscanf(p1, "%d", &config.debuglevel) < 1 || config.debuglevel < LOG_EMERG || config.debuglevel > LOG_DEBUG) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s. Valid debuglevel %d..%d",
					p1, s, linenum, filename, LOG_EMERG, LOG_DEBUG);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oMaxClients:
			if (sscanf(p1, "%d", &config.maxclients) < 1 || config.maxclients < 1) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oGatewayName:
			config.gw_name = safe_strdup(p1);
			break;
		case oGatewayInterface:
			config.gw_interface = safe_strdup(p1);
			break;
		case oGatewayIPRange:
			config.gw_iprange = safe_strdup(p1);
			break;
		/* TODO: deprecate oGatewayAddress option */
		case oGatewayAddress:
		case oGatewayIP:
			config.gw_ip = safe_strdup(p1);
			break;
		case oGatewayPort:
			if (sscanf(p1, "%u", &config.gw_port) < 1) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oFasPort:
			if (sscanf(p1, "%u", &config.fas_port) < 1) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oFasSecureEnabled:
			if (sscanf(p1, "%d", &config.fas_secure_enabled) < 1) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oFasPath:
			config.fas_path = safe_strdup(p1);
			break;
		case oFasRemoteIP:
			config.fas_remoteip = safe_strdup(p1);
			break;
		case oFasAesKey:
			config.fas_aes_key = safe_strdup(p1);
			break;
		case oBinAuth:
			config.binauth = safe_strdup(p1);
			if (!((stat(p1, &sb) == 0) && S_ISREG(sb.st_mode) && (sb.st_mode & S_IXUSR))) {
				debug(LOG_ERR, "binauth program does not exist or is not executeable: %s", p1);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oPreAuth:
			config.preauth = safe_strdup(p1);
			if (!((stat(p1, &sb) == 0) && S_ISREG(sb.st_mode) && (sb.st_mode & S_IXUSR))) {
				debug(LOG_ERR, "preauth program does not exist or is not executeable: %s", p1);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oFirewallRuleSet:
			parse_firewall_ruleset(p1, fd, filename, &linenum);
			break;
		case oEmptyRuleSetPolicy:
			parse_empty_ruleset_policy(p1, filename, linenum);
			break;
		case oTrustedMACList:
			parse_trusted_mac_list(p1);
			break;
		case oBlockedMACList:
			parse_blocked_mac_list(p1);
			break;
		case oAllowedMACList:
			parse_allowed_mac_list(p1);
			break;
		case oMACmechanism:
			if (!strcasecmp("allow",p1)) config.macmechanism = MAC_ALLOW;
			else if (!strcasecmp("block",p1)) config.macmechanism = MAC_BLOCK;
			else {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oWebRoot:
			/* remove any trailing slashes from webroot path */
			while((p2 = strrchr(p1,'/')) == (p1 + strlen(p1) - 1)) *p2 = '\0';
			config.webroot = safe_strdup(p1);
			break;
		case oSplashPage:
			config.splashpage = safe_strdup(p1);
			break;
		case oStatusPage:
			config.statuspage = safe_strdup(p1);
			break;
		case oImagesDir:
			config.imagesdir = safe_strdup(p1);
			break;
		case oPagesDir:
			config.pagesdir = safe_strdup(p1);
			break;
		case oRedirectURL:
			config.redirectURL = safe_strdup(p1);
			break;
		case oAuthIdleTimeout:
			if (sscanf(p1, "%d", &config.auth_idle_timeout) < 1 || config.auth_idle_timeout < 0) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oPreauthIdleTimeout:
			if (sscanf(p1, "%d", &config.preauth_idle_timeout) < 1 || config.preauth_idle_timeout < 0) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oNdsctlSocket:
			free(config.ndsctl_sock);
			config.ndsctl_sock = safe_strdup(p1);
			break;
		case oSetMSS:
			if ((value = parse_boolean(p1)) != -1) {
				config.set_mss = value;
			} else {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oMSSValue:
			if (sscanf(p1, "%d", &config.mss_value) < 1) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oTrafficControl:
			if ((value = parse_boolean(p1)) != -1) {
				config.traffic_control = value;
			} else {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oDownloadLimit:
			if (sscanf(p1, "%d", &config.download_limit) < 1 || config.download_limit < 0) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oUploadLimit:
			if (sscanf(p1, "%d", &config.upload_limit) < 1 || config.upload_limit < 0) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oUploadIFB:
			if(sscanf(p1, "%d", &config.upload_ifb) < 1 || config.upload_ifb < 0) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oFWMarkAuthenticated:
			if (sscanf(p1, "%x", &config.fw_mark_authenticated) < 1 ||
					config.fw_mark_authenticated == 0 ||
					config.fw_mark_authenticated == config.fw_mark_blocked ||
					config.fw_mark_authenticated == config.fw_mark_trusted) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oFWMarkBlocked:
			if (sscanf(p1, "%x", &config.fw_mark_blocked) < 1 ||
					config.fw_mark_blocked == 0 ||
					config.fw_mark_blocked == config.fw_mark_authenticated ||
					config.fw_mark_blocked == config.fw_mark_trusted) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oFWMarkTrusted:
			if (sscanf(p1, "%x", &config.fw_mark_trusted) < 1 ||
					config.fw_mark_trusted == 0 ||
					config.fw_mark_trusted == config.fw_mark_authenticated ||
					config.fw_mark_trusted == config.fw_mark_blocked) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oCheckInterval:
			if (sscanf(p1, "%i", &config.checkinterval) < 1 || config.checkinterval < 1) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oSyslogFacility:
			if (sscanf(p1, "%d", &config.syslog_facility) < 1) {
				debug(LOG_ERR, "Bad arg %s to option %s on line %d in %s", p1, s, linenum, filename);
				debug(LOG_ERR, "Exiting...");
				exit(-1);
			}
			break;
		case oBadOption:
			debug(LOG_ERR, "Bad option %s on line %d in %s", s, linenum, filename);
			debug(LOG_ERR, "Exiting...");
			exit(-1);
			break;
		}
	}

	fclose(fd);

	if (config.fas_remoteip) {
		 if (validateIP4Dotted(config.fas_remoteip) == 1) {
		 	debug(LOG_INFO, "fasremoteip - %s - is a valid IPv4 address...", config.fas_remoteip);
		 } else {
		 	debug(LOG_ERR, "fasremoteip - %s - is NOT a valid IPv4 address format...", config.fas_remoteip);
		 	debug(LOG_ERR, "Exiting...");
		 	exit(-1);
		 }
	} else {
		if (config.fas_port == 80) {
			debug(LOG_ERR, "Invalid fasport - port 80 is reserved and cannot be used for local FAS...");
			debug(LOG_ERR, "Exiting...");
			exit(-1);
		}
	}

	debug(LOG_INFO, "Done reading configuration file '%s'", filename);
}
`

**Comment by khoailangdo** [comment]
> The source code looks fine to me. The problem seems to be "FW_MARK_BLOCKED, FW_MARK_TRUSTED, FW_MARK_AUTHENTICATED not all nonzero."

When I remove the key reading from the config file, the system works well, no errors at all

**Comment by bluewavenet** [comment]
@khoailangdo 
You are not setting a default value for fas _key.

**Comment by khoailangdo** [comment]
yes
That doesn't matter, because I haven't called that key yet. I just put the key to see how it works

**Comment by bluewavenet** [comment]
But it is read anyway:
```
case oFasKey:
		config.fas_key = safe_strdup(p1);
		break;
```

**Comment by khoailangdo** [comment]
I have added the default key. but still the same error

**Comment by bluewavenet** [comment]
@khoailangdo 
Please share your config file.
Perhaps the actual crash may be caused by errors in the config that are not trapped correctly....

**Comment by khoailangdo** [comment]
This is my config file (extract zip pls)
[nodogsplash.zip](https://github.com/nodogsplash/nodogsplash/files/3305003/nodogsplash.zip)

**Comment by bluewavenet** [comment]
@khoailangdo 
Which version of OpenWrt are you running?

**Comment by khoailangdo** [comment]
I downloaded the latest version from Github
Command:
`git clone https://github.com/nodogsplash/nodogsplash.git`

**Comment by bluewavenet** [comment]
@khoailangdo 
No - Which version of **OpenWrt Operating system** are you using?

**Comment by khoailangdo** [comment]
Kernel Version: 4.14.121
Lastest version from GIthub
Command:
`git clone https://git.openwrt.org/openwrt/openwrt.git/`

**Comment by bluewavenet** [comment]
Have you modified the init.d script for fas_key?

**Comment by khoailangdo** [comment]
I just edit here:

` for option in preauth binauth fasport fasremoteip faspath fas_secure_enabled fas_key \
    daemon debuglevel maxclients gatewayname gatewayinterface gatewayiprange \
    gatewayaddress gatewayport webroot splashpage statuspage imagesdir pagesdir \
    redirecturl sessiontimeout preauthidletimeout authidletimeout checkinterval \
    setmss mssvalue trafficcontrol downloadlimit uploadlimit \
    syslogfacility ndsctlsocket fw_mark_authenticated \
    fw_mark_blocked fw_mark_trusted
  do
    config_get val "$cfg" "$option"

    if [ -n "$val" ]; then
      addline "$option $val"
    fi
  done
`

**Comment by mwarning** [comment]
@khoailangdo I gave your changes to `conf.c`, `conf.h` and your `/etc/config/nodogsplash` a try. I started without problems.

I saw that you did not use `fas_aes_key`, so I added it to `/etc/nodogsplash.conf` and changed `/etc/config/nodogsplash` to use `option config '/etc/nodogsplash.conf'`.

Now NDS did not start but reported via syslog (use command `logread`) that `fas_aes_key` was expecting an argument. After I added an argument NDS was starting fine.

What device do you use? (device model)

**Comment by khoailangdo** [comment]
I am using a ComFast 320N v2 device

**Comment by mwarning** [comment]
Ok, I don't have such a device. Probably some memory error in NDS that is only exposed on that CPU.

**Comment by bluewavenet** [comment]
@mwarning 
The ComFast 320N v2 is a fairly old device based on the mips_24kc platform. It is a 64/16 device so will be edging towards end of life due to lack of RAM.
There is now a new ath79 target for it in snapshots. ie a very common SoC and one I use myself for many projects, so I doubt it is exposing anything....

**Comment by khoailangdo** [comment]
@mwarning ok thanks.
but I still don't satisfy the reason the device's CPU does not support
Are there any friends who only help me with the exact reason?

**Comment by bluewavenet** [comment]
@khoailangdo @mwarning 
I have created a fas_key branch. I added the new fas_key from scratch and I have compiled in OpenWrt SDK for mips_24kc and it works fine.

For example - Add:
`option faskey '123abcABC'`
to /etc/config/nodogsplash and restart

Then logread will report:
FAS key is: 123abcABC

**Comment by khoailangdo** [comment]
I downloaded your sourcecode version from the github link you sent. But when installing the package to the device, the error is still as follows:

> Thu Jun 20 10:20:36 2019 daemon.err nodogsplash[28340]: fasremoteip - dattest.matmagoc.com - is NOT a valid IPv4 address format...
Thu Jun 20 10:20:36 2019 daemon.err nodogsplash[28340]: Exiting...
Thu Jun 20 10:20:36 2019 daemon.info procd: Instance nodogsplash::cfg015847 s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by mwarning** [comment]
@khoailangdo afaik, fasremoteip has to be an IP address.

**Comment by bluewavenet** [comment]
> Thu Jun 20 10:20:36 2019 daemon.err nodogsplash[28340]: fasremoteip - dattest.matmagoc.com - is NOT a valid IPv4 address format...
> Thu Jun 20 10:20:36 2019 daemon.err nodogsplash[28340]: Exiting...

This is correct - fasremoteip MUST be an ip address (hint: the key is in the name).

> Thu Jun 20 10:20:36 2019 daemon.info procd: Instance nodogsplash::cfg015847 s in a crash loop 6 crashes, 0 seconds since last crash

This is procd trying to respawn NDS as it terminated itself - normal result.

@khoailangdo 
fasremoteip must be a valid IPv4 address in dotted notation

@mwarning 
Yes, we could resolve the ip address from the domain name, but is this really worth the effort?
It can get very complicated on shared servers when faspath must also contain the domain name. Also NDS must not redirect to an https authentication service directly (results in dire security errors and CPD failure) so is hard wired to http. (If an https authentication service is required you must use FAS as an intermediary that proxies the client CPD input/output)

**Comment by khoailangdo** [comment]
I tried using the domain instead of IP and it still works fine. Do I have a problem with using the domain?

**Comment by bluewavenet** [comment]
@khoailangdo
As I said before, fasremoteip must be a valid IPv4 address in dotted notation.
For example 100.123.10.12

**Comment by khoailangdo** [comment]
@bluewavenet 
I find using IP very inconvenient, when the IP of the server contains the captive portal system changes. We will have to go to each device location to edit the config file.

**Comment by bluewavenet** [comment]
@khoailangdo
I understand that but it implies you are going about it the wrong way.
Give me an outline of what you are trying to achieve.
A local FAS perhaps written in PHP is a better means of talking to a remote system, rather than trying to add custom functionality into NDS.
This way NDS can do what it is  good at without being loaded down with many different types of functionality.

**Comment by mwarning** [comment]
Using domains etc. can be solved (using ipsets). But we do not have the time to implement it.

**Comment by bluewavenet** [comment]
@khoailangdo 
NDS v4.0.0 is now released and should fix your problems with its enhanced FAS.
https://nodogsplashdocs.readthedocs.io/en/latest/fas.html#overview
