### ISSUE TITLE
Is it possible to allow in the config file to access some domain before FAS authentication?

### ISSUE THREAD

**Issue by khoailangdo** [nodogsplash/nodogsplash#373]
I have turned on FAS and successfully authenticated. But on the FAS splash page, I want to show some images from the internet before authenticating.
Is it possible to allow in the config file to access some domain before FAS authentication?
Thanks

**Comment by bluewavenet** [comment]
It is possible to show images  from elsewhere on tour FAS. How you do this depends on the location of your FAS as well as the location of the images.

You either need to allow the client access to the ip address of the image source using a fiewall rule or have your FAS pull in the image on behalf of the client using some means eg open a stream, use curl or use wget.

There are some defacto rules regarding CPD to follow also.

I currently have some documentation updates to do on this topic so can elaborate somewhat in advance of the updates if you wish.

**Comment by bluewavenet** [comment]
Defacto rules for CPD:

It should be noted when designing a custom splash page that for security reasons many client device CPD implementations:

- Immediately close the browser when the client has authenticated.
- Prohibit the use of href links.
- Prohibit downloading of external files (including .css and .js, even if they are allowed in NDS firewall settings).
- Prohibit the execution of javascript.

How the Client CPD reacts is entirely up to how that client based CPD code is implemented and is outside the control of any captive portal.

**Comment by bluewavenet** [comment]
FAS can write to / read from a remote server and pipe to the client in many ways.
For example in PHP, you might use:
```
stream_context_create()
stream_socket_client()
```
to open a "channel",
then use

```
fputs()
fgets()
```
to send and receive.

**Comment by bluewavenet** [comment]
@khoailangdo @mwarning 
I have added a PreAuth login script example that pulls in a remote image and displays it on the CPD browser login screen. The remote server can be https and the remote ip address is not needed.
see PR #374 
Let me know if you need a hand with the config if you want to try it out.
