### ISSUE TITLE
Running NDS on rpi zero w as standalone network Captive Portal

### ISSUE THREAD

**Issue by SerialIterator** [nodogsplash/nodogsplash#375]
I have seen some "issues" about running NDS in "offline" mode and I have tried all different configurations suggested to make it work and I can't seem to. I am trying to get 2 rpi zero w's to function as separate captive portals that redirect to a flask program controlling connected lora modules where the users will be prompted with a captive portal asking what message they want to send. I have been trying to get just the NDS splash screen to show up when connecting to the rpi (not worried about flask or the lora modules at this point) and I haven't been successful. I started using the tutorial [pimylifup wap](https://pimylifeup.com/raspberry-pi-wireless-access-point/) where I ignored steps 16 and on that concerned ip tables as I don't have an outbound internet connection. In step 15 it says to modify the `/etc/dnsmasq.conf` file to say: 

```
interface=wlan0       # Use interface wlan0  
server=1.1.1.1       # Use Cloudflare DNS  
dhcp-range=192.168.220.50,192.168.220.150,12h # IP range and lease time
``` 

In [issue #249](https://github.com/nodogsplash/nodogsplash/issues/249#issuecomment-395948950) I saw a comment about inserting `address=/#/[lan_ip_address_of_NDS]` which for me is `192.168.220.1` based on the pimylifeup setup. I saw a comment on reddit where the person said they changed `server=1.1.1.1` to `server=/#/192.168.220.1`. I have tried `server=` and `address=` to no avail. I have ran a flask server on port `5000` and I am able to connect through wifi to the rpi and GET a flask served page using multiple different devices so I know that dnsmasq and hostapd are functioning.

`/etc/dnsmasq.conf` file:

```
interface=wlan0         #use interface wlan0
server=192.168.220.1
address=/#/192.168.220.1
dhcp-range=192.168.220.50,192.168.220.150,12h #ip range and lease time
```

`/etc/nodogsplash/nodogsplash.conf` file:

```
GatewayInterface wlan0
FirewallRuleSet authenticated-users {
  FirewallRule allow all
}
FirewallRuleSet preauthenticated-users {
  FirewallRule allow udp port 53
  FirewallRule allow tcp port 53
  FirewallRule allow udp port 67
  FirewallRule allow tcp port 22
  FirewallRule allow tcp port 80
  FirewallRule allow tcp port 443
}
FirewallRuleSet users-to-router {
  FirewallRule allow udp port 53
  FirewallRule allow tcp port 53
  FirewallRule allow udp port 67
  FirewallRule allow tcp port 22
  FirewallRule allow tcp port 80
  FirewallRule allow tcp port 443
}
GatewayAddress 192.168.220.1
GatewayPort 2050
MaxClients 250
SessionTimeout 0
PreAuthIdleTimeout 10
AuthIdleTimeout 120
CheckInterval 30
MACMechanism block
BlockedMACList none
AllowedMACList none
TrustedMACList none
TrafficControl no
DownloadLimit 0
UploadLimit 0
GatewayIPRange 0.0.0.0/0
DebugLevel 9
#fasport 5000
#faspath /
#fas_secure_enabled 0
```

`/etc/resolv.conf` file:

```
# Generated by resolvconf
nameserver 127.0.0.1
```

added to the end of `/etc/dhcpcd.conf` file:

```
interface wlan0
static ip_address=192.168.220.1/24
#static routers=192.168.220.1
#static domain_name_servers=192.168.220.1
nohook wpa_supplicant
``` 

I should also mention I used `https://github.com/nodogsplash/nodogsplash.git` to retrieve the latest repo and used:

```
make
sudo make install
```
according to [pimylifeup raspberry pi captive portal](https://pimylifeup.com/raspberry-pi-captive-portal/) to install NDS. I am also running Raspbian stretch on the rpi. any help would be greatly appreciated

**Comment by bluewavenet** [comment]
Remove this entire section:

```
FirewallRuleSet preauthenticated-users {
  FirewallRule allow udp port 53
  FirewallRule allow tcp port 53
  FirewallRule allow udp port 67
  FirewallRule allow tcp port 22
  FirewallRule allow tcp port 80
  FirewallRule allow tcp port 443
}
```
It is intended for creating a "Walled garden". The settings you have are preventing NDS from functioning.
