### ISSUE TITLE
How to allow facebook page before auth?

### ISSUE THREAD

**Issue by worlak2** [nodogsplash/nodogsplash#379]
I want to allow users to log in via facebook. I created a page with a script, how can I allow unauthorized users to access the Facebook domain?

**Comment by bluewavenet** [comment]
You will have to allow preauthenticated access to all the Facebook IPv4 addresses that the FB API could use. In addition, client device CPD will, for security reasons, often prohibit download and running javascript, particularly with up to date operating systems, thus making the standard FB API problematic.

**Comment by bawantha** [comment]
Think scenario where I have different captive portals over city. If one customer log in to my portal from coffee shop and if this is his/her **first ever** login to my WIFI , I want to get phone number and authenticate it ( via OTP) now if same person go to another shop ( eg-: burger shop) he don't need to give phone number he/she can directly connect to internet and browse it. what mechanism should I follow? is it feasible to get   user's MAC address to do this.?

**Comment by bluewavenet** [comment]
@bawantha 
This is a different question to the one asked originally.
Please create a new issue so it can be found later :-)

PS the mechanism is to use a centralised FAS.

**Comment by OmarNsiri** [comment]
I'm also having problems trying to get a facebook login page to be served as a captive portal. should I use FAS in order to serve the login page as a splash?

**Comment by bluewavenet** [comment]
@OmarNsiri 
As the Facebook API is heavily dependent on javascript and the client CPD standard prohibits javascript, you have a problem.
To get a FB login on a Captive Portal you must used a server based javascript interpretor.
This is possible with NDS if you use something like node.js to implement your FAS.
