### ISSUE TITLE
Captive portal not showing for some devices

### ISSUE THREAD

**Issue by bawantha** [nodogsplash/nodogsplash#380]
Hi
I installed NDS for OpenWrt I tested  on 4 devices

- Apple Iphone v12.3 **worked**

- Huawei Nova 3i  Android 9.0  **worked**

- Laptop windows 10 **worked**

- Samsung Tab 7 Android 4.4.4 **not worked**

**not worked** mean I couldn't access the internet but didn't load the splash page , what might be the case ?. Is NDS depend on OS?. or is it depend ot Device ? . or any other reason?

Thank you...

**Comment by bluewavenet** [comment]
@bawantha 
The automatic appearance of the splash page on the client device is triggered by a function on the client device itself. This is CPD (Captive Portal Detection) and has become a defacto standard and should work well on all new operating systems.

However Android 4.4.4 is very old and will most likely not have a functioning CPD. This is a problem with the device and not an issue with NDS.

You can force the splash page to appear by opening the browser and accessing an http port 80 web page (simulating what CPD does).

Desktop Firefox CPD uses http://detectportal.firefox.com/success.txt
and Linux Networkmanager CPD often uses  http://www.gnome.org/

Either of these should work.

**Comment by bawantha** [comment]
> @bawantha
> The automatic appearance of the splash page on the client device is triggered by a function on the client device itself. This is CPD (Captive Portal Detection) and has become a defacto standard and should work well on all new operating systems.
> 
> However Android 4.4.4 is very old and will most likely not have a functioning CPD. This is a problem with the device and not an issue with NDS.
> 
> You can force the splash page to appear by opening the browser and accessing an http port 80 web page (simulating what CPD does).
> 
> Desktop Firefox's built in CPD uses http://detectportal.firefox.com/success.txt
> and Linux Networkmanager CPD often uses http://www.gnome.org/
> 
> Either of these should work.

Thanks I got the idea

**Comment by bluewavenet** [comment]
@bawantha 
I had a problem at a school where they had a fairly large number of old but otherwise useful tablets that also did not have CPD. I got them to add a Firefox shortcut to http://detectportal.firefox.com/success.txt
Then to log in, the students just had to tap the shortcut. Might be useful for you....

**Comment by quanticsolutions** [comment]
@bluewavenet I have the same trouble, with huawei phones but I have been detected that these phones are requesting for the CPD addres like "http://connectivitycheck.gstatic.com" but it doesn't redirecting to captive portal, any suggestions? Would be customising some http responses? Regards

**Comment by bluewavenet** [comment]
Do these phones work on the very first connection? If so try "forgetting" the SSID then reconnecting.

Huawei phones use the standard Android CPD and I have not seen a problem with them on any installation that I look after.

Is this a batch of phones eg issued to employees? Apps similar to https everywhere can break CPD and prevent access to ANY captive portals.

**Comment by quanticsolutions** [comment]
Is a specific model "Huawei P10" that have opened the captive portal at once. But after this connection doesn't open the portal. Have any idea what could be wrong?

**Comment by bluewavenet** [comment]
Try switching wifi off and on then reconnect. That usually triggers the client CPD again.

CPD is primarily designed for mobile use where the mobile devices are taken away from the signal area after a period of use, eg a coffee shop.

If a client device stays connected past the session timeout interval you will most likely see this behaviour. It varies depending on client OS version and vendor specific tweaks. 
Generally, setting the sessiontimeout duration to a value at the maximum likely time the client will be at the venue is best.
The default of 20 hours works reasonably well at most venues but obviously this is venue dependent.

To simplify: Assuming the client device does not have an app that inhibits the CPD then this is an issue with the client CPD itself. We can mitigate by tuning the session timeout.

**Comment by mimtechorg** [comment]
I have this problem with plenty of devices such as iPhone 6s iOS 13, Huawei, etc.
I've set `SessionTimeout 1200` and `AuthIdleTimeout 480`, however, the problem doesn't solve.
How can I add some new URLs for the CPD?
