### ISSUE TITLE
How to execute ndsctl commands in Openwrt console. (Node+ Express)

### ISSUE THREAD

**Issue by bawantha** [nodogsplash/nodogsplash#385]
Hi
My NDS is installed on Openwrt I executed the command to get _clientmac_ 

> app.get('/', function (req, res) {
    var _clienstip = req.query.clientip;
    exec("/usr/bin/ndsctl json  " + _clienstip + "| grep mac | cut -c 8- | cut -c -17", function (error, stdout, stderr) {
        console.log(error || stdout || stderr);
    });
});

as expect it was execute in my windows shell, so I got 

> The system cannot find the path specified.

but How can execute this in OpenWrt ( My OpenWrt is installed on Raspberry Pi )  shell?

**Comment by bluewavenet** [comment]
I am not familiar with node but I suspect the node user does not have execute permission for ndsctl.
Try:
`sudo /usr/bin/ndsctl json " + _clienstip + "| grep mac | cut -c 8- | cut -c -17`

**Comment by bawantha** [comment]
@bluewavenet 
 same as without sudo

**Comment by bluewavenet** [comment]
@bawantha I am assuming you are running node on the same machine as nds.

**Comment by bluewavenet** [comment]
Does ndsctl run on a console?
Typical output:

```
root@BlueWave:~# /usr/bin/ndsctl json
{
"client_length": 4,
"clients":{
"74:de:2b:b1:70:33":{
"id":789,
"ip":"10.168.1.68",
"mac":"74:de:2b:b1:70:33",
"added":1563171760,
"active":1563175422,
"duration":3662,
"token":"5cf19806",
"state":"Authenticated",
"downloaded":34470,
"avg_down_speed":75.30,
"uploaded":2580,
"avg_up_speed":5.64
},
"04:15:52:5a:e1:ed":{
"id":792,
"ip":"10.168.1.63",
"mac":"04:15:52:5a:e1:ed",
"added":1563095322,
"active":1563175422,
"duration":80100,
"token":"0481c71b",
"state":"Authenticated",
"downloaded":641718,
"avg_down_speed":64.09,
"uploaded":82074,
"avg_up_speed":8.20
},
"84:38:38:98:38:1a":{
"id":793,
"ip":"10.168.1.89",
"mac":"84:38:38:98:38:1a",
"added":1563132057,
"active":1563175422,
"duration":43365,
"token":"a461948f",
"state":"Authenticated",
"downloaded":86010,
"avg_down_speed":15.87,
"uploaded":7562,
"avg_up_speed":1.40
},
"b4:74:43:37:20:3d":{
"id":795,
"ip":"10.168.1.118",
"mac":"b4:74:43:37:20:3d",
"added":0,
"active":1563174818,
"duration":0,
"token":"f2d6dec8",
"state":"Preauthenticated",
"downloaded":0,
"avg_down_speed":0.00,
"uploaded":0,
"avg_up_speed":0.00
}
}
}

```

**Comment by bawantha** [comment]
@bluewavenet  
NO that is the problem my NDS is running on raspberry PI  ( on Top of OpenWrt)  node server is running on  Windows( localhost) I should execute command on Pi instead of windows but command is executing on windows

**Comment by bluewavenet** [comment]
@bawantha 
So in summary, your setup is:
 * OpenWrt as OS on your  Pi (Openwrt version? NDS version?)
 * FAS is a Node app running on a windows machine on the NDS LAN

The best ways forward for you are:

 * Install node on your pi 

or

 * upgrade your NDS to version 4.0.0 and use `fas_secure_enabled = 2`

**Comment by bawantha** [comment]
Im wonder what will be like this _return URL_  as mentioned in doc

> It is the responsibility of FAS to obtain the unique client token allocated by NDS as well asconstructing the return URL to NDS.The return url will be constructed by FAS from predetermined knowledge of the configurationof NDS using gatewayname as an identifier

**Comment by bluewavenet** [comment]
> Im wonder what will be like this return URL as mentioned in doc

https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#post-fas-processing

**Comment by bawantha** [comment]
How to find v4 .ipkg?

**Comment by bluewavenet** [comment]
For now you will have to compile yourself but it will be available soon for download.
What versions of OpenWrt and NDS are you using?

**Comment by bluewavenet** [comment]
@bawantha Which model pi are you using?

**Comment by bawantha** [comment]
this one [https://downloads.openwrt.org/snapshots/targets/brcm2708/bcm2710/](url)

**Comment by bawantha** [comment]
pi b+ (  BCM 2837B0) 
NDS version  3.3.2-1 ( available one for Openwrt )

**Comment by bluewavenet** [comment]
The version 4.0.0 binaries will hopefully be available in a few days.
Node package is available now though.

**Comment by bluewavenet** [comment]
https://github.com/openwrt-routing/packages/pull/484

**Comment by bawantha** [comment]
> Node package is available now though.
could you please guild me to there, I couldn't find it out

**Comment by bluewavenet** [comment]
NDS 4.0.0 is being compiled by the OpenWrt build system now. It takes a while to work around all the different architectures so keep checking. 
Here I think:
https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/

Node is currently failing to compile in snapshot - that is the nature of snapshot. It will no doubt be fixed pretty soon.
https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a53/packages/node/

**Comment by bawantha** [comment]
H=

> Does ndsctl run on a console?
> Typical output:
> 
> ```
> root@BlueWave:~# /usr/bin/ndsctl json
> {
> "client_length": 4,
> "clients":{
> "74:de:2b:b1:70:33":{
> "id":789,
> "ip":"10.168.1.68",
> "mac":"74:de:2b:b1:70:33",
> "added":1563171760,
> "active":1563175422,
> "duration":3662,
> "token":"5cf19806",
> "state":"Authenticated",
> "downloaded":34470,
> "avg_down_speed":75.30,
> "uploaded":2580,
> "avg_up_speed":5.64
> },
> "04:15:52:5a:e1:ed":{
> "id":792,
> "ip":"10.168.1.63",
> "mac":"04:15:52:5a:e1:ed",
> "added":1563095322,
> "active":1563175422,
> "duration":80100,
> "token":"0481c71b",
> "state":"Authenticated",
> "downloaded":641718,
> "avg_down_speed":64.09,
> "uploaded":82074,
> "avg_up_speed":8.20
> },
> "84:38:38:98:38:1a":{
> "id":793,
> "ip":"10.168.1.89",
> "mac":"84:38:38:98:38:1a",
> "added":1563132057,
> "active":1563175422,
> "duration":43365,
> "token":"a461948f",
> "state":"Authenticated",
> "downloaded":86010,
> "avg_down_speed":15.87,
> "uploaded":7562,
> "avg_up_speed":1.40
> },
> "b4:74:43:37:20:3d":{
> "id":795,
> "ip":"10.168.1.118",
> "mac":"b4:74:43:37:20:3d",
> "added":0,
> "active":1563174818,
> "duration":0,
> "token":"f2d6dec8",
> "state":"Preauthenticated",
> "downloaded":0,
> "avg_down_speed":0.00,
> "uploaded":0,
> "avg_up_speed":0.00
> }
> }
> }
> ```

Are you asking ,   NDS must install on my server ? , isn't it ?

**Comment by bluewavenet** [comment]
ndsctl is an executable that is part of nodogsplash and runs on the same machine as nodogsplash.
