### ISSUE TITLE
if I have remote server how to use ndsctl commands?

### ISSUE THREAD

**Issue by bawantha** [nodogsplash/nodogsplash#388]
Hi I have a server on cloud , NDS is installed in OpenWrt router I want to execute  ndsctl commands to my router , How can I do that 
[network diagram](https://imgur.com/UwWc7ck)

**Comment by sqrt-1764** [comment]
Of course your has to be reachable from your server.
Then the easiest method would be to execute those commands via ssh.

**Comment by bluewavenet** [comment]
Yes it is possible to communicate with NDS from outside on the Internet as in your diagram.
But this cannot be built in to NDS in a sensible way, it is up to developers like yourself to use available tools to set something up.

**A hint:**

> 
> Set up a web page on your NDS router and allow access to it from the Internet through your firewalls using port forwarding.
> Your external server can then call this page using wget or curl, requesting whatever information you need (eg client token, client mac) by providing the client ip address that is sent in the query string.
> 
> NDS v4 makes all this redundant however, by adding faskey, fasremotefqdn and fas_secure_enable=2, enabling NDS to send the required information in an encrypted form even to a shared hosting service without having to know specific details of the hosting type.

**Comment by bawantha** [comment]
> Of course your router has to be reachable from your server.
> Then the easiest method would be to execute those commands via ssh.

but my router is connected to DHCP server , DHCP server is connected to internet How can I get router's IP to do SSH

**Comment by bluewavenet** [comment]
@bawantha 
You will have to do port forwarding in your Internet router.

The whole issue is made irrelevant by NDS v4.0.0.

I realise you currently cannot run this on your rpi with OpenWrt snapshot, but have you tried OpenWrt 18.06.4? NDS v4.0.0 will run on this.
