### ISSUE TITLE
End session on WiFi Connection disconnect

### ISSUE THREAD

**Issue by amenk** [nodogsplash/nodogsplash#389]
Is it possible to end the session as soon as the WiFi connection is disconnected?

There are the time out variables, but I would like to end the session on WiFi disconnect.

**Comment by amenk** [comment]
I am running nodogsplash on OpenWrt ... 

logread shows:

Tue Jul  9 21:31:16 2019 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 7c:d9:xx:xx:xx:xx

So I have to monitor that log and call

"ndsctl deauth $MAC"

**Comment by amenk** [comment]
Putting the following in /etc/rc.local is working:

    ( logread -f | awk '/AP-STA-DISCONNECTED/{ system("ndsctl deauth " $10) }' ) &
    exit 0

Unless there is a better solution, this can be closed.

**Comment by bluewavenet** [comment]
@amenk May I ask why?
My guess is this will take up around ~5% of the cpu on a typical low cost router.
Any client that leaves the area or turns off its WiFi for battery savings when idle will not formally disconnect but timeout some time later. For this reason "checkinterval" is set to 600 seconds by default. In addition "maxclients" defaults to 250, so running out of possible client connections is very unlikely. You would have to have 250 clients connecting then leaving the area/going to sleep all within 600 seconds for it to be an issue.

**Comment by amenk** [comment]
It's probably pretty niche & hacky what I am doing. I show some information on the captive portal and did not want to get this missed when somebody signs in again. Also I try to simulate an Internet connection where is none - which is working well on some devices, but on some it isn't anyways... I will not follow this further and just close it :-)
