### ISSUE TITLE
faspath: was not found on this server.

### ISSUE THREAD

**Issue by ikokang** [nodogsplash/nodogsplash#391]
Not Found
The requested URL /home/www/fas-aes.php?fas=aWVHM1VtZ291aXV0TGtBa0haaHBpakxzOFVXYWphR3Y5ZHdac1N1VUxrVnBDQnliVjhobXpSWmxjcUFYM09ZaTJEaXlJWWFNR1pET25pT0RXamIvbE5XcjF5emJBdVZIdUZXZ2hSaUduTm05WEdVWWRyWHRuYmhOY0hya0hYcko2SjRhMnRVQllVVUlBa1NIN2FUYXpwWTNpM0JkditHTmg1R25nSFVjMGYyZTNZbHZqbWtwMkZOS1U0S3lkeXlsZHZ6ZVpOMllZN1VNbFhVVDM1dUpxaTZPaTRJSjBScFZQWVNQZUtCTlU4b0Q3RWI3b2FGQXZsSk9yd1p0N1c4SWs0akRRaWY3MjhVQU9RLysxTmsvNWE4MElVQmtlU3AzQzFSNElqbjJsTi8yL2F4M0hobEp0VjZ2cE9xY2d4VkR4RitjdTJuZnVQQ21Jam9ybW4zVFdBPT0=&iv=8ab7dcbf3094dcf1 was not found on this server.

I compiled nodogsplash 4.0.0 using openwrt x64 18.06.4
Php7-cli and php7-mod-openssl were selected at compile time

**Comment by ikokang** [comment]
/etc/config/nodogsplash
config nodogsplash
	option enabled '0'
	option fwhook_enabled '1'
	option gatewayinterface 'br-lan'
	option gatewayname 'OpenWrt Nodogsplash'
	option maxclients '250'
	option preauthidletimeout '30'
	option authidletimeout '120'
	option sessiontimeout '1200'
	option checkinterval '600'
	list authenticated_users 'allow all'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 23'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'
	list users_to_router 'allow tcp port 8090'
	option fasport '2080'
	option faspath '/home/www/fas-aes.php'
	option fas_secure_enabled '2'
	option faskey '1234567890'
	list trustedmac '00:00:CA:FE:BA:BE'

/etc/config/uhttpd
config uhttpd 'main'
	list listen_https '0.0.0.0:443'
	list listen_https '[::]:443'
	option redirect_https '1'
	option home '/www'
	option rfc1918_filter '1'
	option max_requests '3'
	option max_connections '100'
	option cert '/etc/uhttpd.crt'
	option key '/etc/uhttpd.key'
	option cgi_prefix '/cgi-bin'
	list lua_prefix '/cgi-bin/luci=/usr/lib/lua/luci/sgi/uhttpd.lua'
	option script_timeout '60'
	option network_timeout '30'
	option http_keepalive '20'
	option tcp_keepalive '1'
	option listen_http '8090'

config cert 'defaults'
	option days '730'
	option bits '2048'
	option country 'ZZ'
	option state 'Somewhere'
	option location 'Unknown'
	option commonname 'OpenWrt'

config uhttpd 'web'
	option listen_http '0.0.0.0:80'
	option home '/home/www'
	option index_page 'index.php'
	option interpreter '.php=/usr/bin/php-cgi'

config uhttpd 'wifi'
	option listen_http '0.0.0.0:2080'
	option home '/home/www'
	option index_page 'fas-aes.php'
	option interpreter '.php=/usr/bin/php-cgi'

**Comment by bluewavenet** [comment]
I think you have faspath incorrect.
From the documentation:

> faspath. This is the path from the FAS Web Root (not the file system root) to the FAS login page.

See also:
https://nodogsplashdocs.readthedocs.io/en/latest/fas.html#using-the-fas-example-script

From your uhttpd config:
```
config uhttpd 'wifi'
option listen_http '0.0.0.0:2080'
option home '/home/www'
option index_page 'fas-aes.php'config uhttpd 'wifi'
option listen_http '0.0.0.0:2080'
option home '/home/www'
option index_page 'fas-aes.php'
```

The web root (or "home") for port 2080 is "/home/www" and index_page is "fas-aes.php"
So in this case you would have:

`option faspath '/'`

or

`option faspath '/fas-aes.php'`

**Comment by ikokang** [comment]
Thank you for reminding me! Now the problem has been solved.
