### ISSUE TITLE
Error 404 - Not Found

### ISSUE THREAD

**Issue by ikokang** [nodogsplash/nodogsplash#395]
I set relevant parameters according to the document to achieve remote authentication page!  https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

When I enter the username and email, click "Continue" to enter the welcome page, and click "Continue" again, return to the local terminal to display the error message!

**Error 404 - Not Found**
http://192.168.9.1:2050/?originurl=http%253a%252f%252fwww.hao123.com%252fmid%253ffrom%253dshoubai%2526key%253d8722382419560789585%2526type%253drec

**Comment by ikokang** [comment]
/etc/config/uhttpd
config uhttpd 'main'
	list listen_https '0.0.0.0:443'
	list listen_https '[::]:443'
	option redirect_https '1'
	option home '/www'
	option rfc1918_filter '1'
	option max_requests '3'
	option max_connections '100'
	option cert '/etc/uhttpd.crt'
	option key '/etc/uhttpd.key'
	option cgi_prefix '/cgi-bin'
	list lua_prefix '/cgi-bin/luci=/usr/lib/lua/luci/sgi/uhttpd.lua'
	option script_timeout '60'
	option network_timeout '30'
	option http_keepalive '20'
	option tcp_keepalive '1'
	option listen_http '8090'
	option listen_http '0.0.0.0:2080'
	option interpreter '.php=/usr/bin/php-cgi'

/etc/config/nodogsplash
config nodogsplash
	option enabled '1'
	option fwhook_enabled '1'
	option gatewayinterface 'br-lan'
	option maxclients '250'
	option preauthidletimeout '30'
	option authidletimeout '120'
	option sessiontimeout '1200'
	option checkinterval '600'
	list authenticated_users 'allow all'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 23'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'
	option gatewayname 'Free-WiFi'
	option fasremoteip '154.48.246.104'
	option fasremotefqdn 'www.cs510.com'
	option fasport '80'
	option faspath '/fas-aes.php'
	option fas_secure_enabled '2'
	option faskey '1234567890'

**Comment by bluewavenet** [comment]
@ikokang 
Coincidentally I encountered this yesterday - I am investigating - it is some combination of versions.
Which version of OpenWrt are you using and which version of NDS (4.0.0 or 4.0.1beta)?

**Comment by ikokang** [comment]
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=nodogsplash
PKG_FIXUP:=autoreconf
PKG_VERSION:=4.0.0
PKG_RELEASE:=1

PKG_SOURCE_URL:=https://codeload.github.com/nodogsplash/nodogsplash/tar.gz/v$(PKG_VERSION)?
PKG_SOURCE:=nodogsplash-$(PKG_VERSION).tar.gz
PKG_HASH:=4cc3a9200380f03c8c3a71afc1fda0006b8e7bf70129f2419768a767b734da21
PKG_BUILD_DIR:=$(BUILD_DIR)/nodogsplash-$(PKG_VERSION)

**Comment by bluewavenet** [comment]
@ikokang 
Try changing line 110 in fas-aes.php
from:
`	$redir=$_SERVER["SCRIPT_URI"]."/?originurl=".urlencode($originurl);`
to:
`	$redir=$_SERVER["SCRIPT_URI"]."/?originurl=".$originurl;`

NDS url encodes before sending, so it is not necessary to encode here. It seems some versions of php do not encode if the string is already encoded, but others will encode again. I will investigate further but this should fix the problem......

**Comment by ikokang** [comment]
After replacing the above code, the problem still exists.

**Comment by ikokang** [comment]
When the domain name cannot be accessed, will it automatically be converted to the IP address to continue providing authentication services? Can you set the main domain name or the main IP address, the standby IP address or the standby domain name as the remote line fault, automatically select the available line?

**Comment by bluewavenet** [comment]
@ikokang 
Here is the fixed fas-aes.php. It was a coding error (by me!). I will be doing a PR so it will be in the next release.
[fas-aes.php.txt](https://github.com/nodogsplash/nodogsplash/files/3438345/fas-aes.php.txt)

The settings for uhttpd are only given as an example and yes you are correct, they are not needed if you are not using uhttpd.

**Comment by bluewavenet** [comment]
@ikokang 

> When the domain name cannot be accessed, will it automatically be converted to the IP address to continue providing authentication services? 

Do you mean if the Internet is unavailable? There is no automatic offline detection yet.

> Can you set the main domain name or the main IP address, the standby IP address or the standby domain name as the remote line fault, automatically select the available line?

Are you asking if NDS can support multiple Internet feeds for resilience?
NDS is compatible with mwan3 on OpenWrt. mwan3 can loadshare between multiple feeds and automatically fail-over if a feed fails.

**Comment by ikokang** [comment]
Are you asking if NDS can support multiple Internet feeds for resilience?

Support multiple domain name remote host authentication services to prevent remote servers from crashing, resulting in the unavailability of authentication services.
	option fasremoteip '154.48.246.104' #main
	option fasremoteip '116.89.248.130' #secondary
	option fasremotefqdn 'www.hkfqdn.com' #main
	option fasremotefqdn 'www.spfqdn.com' #secondary
	option fasport '80'
	option faspath '/fas-aes.php'
	option fas_secure_enabled '2'
	option faskey '1234567890'

**Comment by ikokang** [comment]
I just used the update file you provided and uploaded it to replace the remote server's namesake file, then restarted the local router. Unfortunately, the message "Error 404 - Not Found" is still displayed on mobile phones and computers after remote authentication. I checked the remote server and logged the authentication terminal.

When the error message is displayed, the mobile phone and computer terminals can access the Internet at this time!
Tomorrow I will recompile the firmware and test other routers.

**Comment by bluewavenet** [comment]
@ikokang 

> I just used the update file you provided and uploaded it 

Did you remember to rename it from fas-aes.php.txt, to fas-aes.php?

> When the error message is displayed, the mobile phone and computer terminals can access the Internet at this time!

That is correct. The problem was fas-aes.php malforming the $redir variable.

Test the new fas-aes.php with uhttpd on the router. I have seen some web hosting systems that buffer ftp uploads for an hour or so before updates are reflected on the live web site.

**Comment by bluewavenet** [comment]
@ikokang 
I just configured my test system to use your FAS settings and it works perfectly.
If you have permissions set for the logging in fas-aes.php you will see my login.
Your problem with the updated fas-aes.php must have been caching somewhere.

**Comment by ikokang** [comment]
![U({FQ$XPLCQ9EKJ@LQ8J_35](https://user-images.githubusercontent.com/33259900/62002628-4d9f0f00-b13a-11e9-95c0-e1f1d13d8116.png)

I do see your login information. I have the right to manage the network. I try to restart the host server and change other domain names, and I also recompile the firmware, unfortunately! It still hasn't solved the problem. Preliminary suspicions are about router configuration.

**Comment by bluewavenet** [comment]
I think this is your browser caching the previous 404.

The redirect is working and you get Internet access. The final step of redirecting to the originally requested url is what is giving the 404.

Try clearing the browser cache...

This final step is actually somewhat redundant, as the operating system on mobile client devices has CPD (captive portal detection), the defacto standard is for the CPD to immediately close the login screen as soon as the captive portal authentication is detected as successful. This is what happens for up to date CPD implementations anyway (iOS, Android, Microsoft, Linux), older versions perhaps not but will do as they get upgraded.

**Comment by bluewavenet** [comment]
@ikokang 
Here is an extract of the only parts of the config I have changed to connect to your FAS:
```
	option fasremoteip '154.48.246.104'
	option fasremotefqdn 'www.cs510.com'
	option fasport '80'
	option faskey '1234567890'
	option faspath '/fas-aes.php'
```

It is working perfectly.

**Comment by bluewavenet** [comment]
You say you are compiling your self.
What does `ndsctl status` report as the version?

**Comment by ikokang** [comment]
/$ ndsctl status
==================
NoDogSplash Status
====
Version: 4.0.0
Uptime: 5m 3s
Gateway Name: OpenWrt Nodogsplash
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.123.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Secure Level 2, URL: http://www.cs510.com:80/fas-aes.php
Client Check Interval: 600s
Preauth Idle Timeout: 30m
Auth Idle Timeout: 120m
Traffic control: no
Total download: 500 kByte; avg: 13.21 kbit/s
Total upload: 274 kByte; avg: 7.25 kbit/s
====
Client authentications since start: 1
Current clients: 1

Client 0
  IP: 192.168.123.181 MAC: e0:d5:5e:25:49:0d
  Last Activity: Sun Jul 28 19:34:10 2019 (0s ago)
  Session Start: Sun Jul 28 19:33:23 2019 (47s ago)
  Session End:   Mon Jul 29 15:33:23 2019 (19h 59m 13s left)
  Token: 80bb9fbf
  State: Authenticated
  Download: 325 kByte; avg: 55.36 kbit/s
  Upload:   124 kByte; avg: 21.23 kbit/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========

**Comment by ikokang** [comment]
**Try clearing the browser cache...**

I've cleaned up Google Chrome's online records many times.
![001](https://user-images.githubusercontent.com/33259900/62006255-d042c100-b170-11e9-9bfd-7a9ad2ab30dc.png)
![002](https://user-images.githubusercontent.com/33259900/62006260-d8026580-b170-11e9-965d-d4ac78d72469.png)
![003](https://user-images.githubusercontent.com/33259900/62006263-e0f33700-b170-11e9-84bc-278836c922dd.png)
![QQ图片20190728193127](https://user-images.githubusercontent.com/33259900/62006267-eea8bc80-b170-11e9-99d2-3a106cbd8ebd.png)

**Comment by ikokang** [comment]
Thank you so much for your time! I'll try SQM Scripts next. My WiFi is free and open, usually connected to a larger number of users. Most of the visitor terminals are mainly used to watch video games download APP and so on.
