### ISSUE TITLE
How do I use QoS or TrafficControl on OpenWrt?

### ISSUE THREAD

**Issue by ikokang** [nodogsplash/nodogsplash#396]
Can Traffic Control be supported by adding IMQ patches?

Related IMQ patch links:
https://github.com/imq/linuximq/tree/master/kernel/v4.x
https://github.com/ericpaulbishop/gargoyle/tree/master/patches-generic

**Comment by bluewavenet** [comment]
@ikokang 

> Can Traffic Control be supported by adding IMQ patches?

It might be possible - no one has time to do the coding that would be required as it is quite a low priority because NDS is compatible with SQM Scripts.
https://nodogsplashdocs.readthedocs.io/en/stable/faq.html#how-do-i-use-qos-or-trafficcontrol-on-openwrt

**Comment by ikokang** [comment]
Thank you for your suggestion. I'll try the SQM plug-in.
