### ISSUE TITLE
Stuck on NDS 1.0.2

### ISSUE THREAD

**Issue by akrantz01** [nodogsplash/nodogsplash#398]
I am using the GL.iNet AR750s with OpenWrt 18.06.1 r7258-5eb055306f and am trying to setup FAS. It would seem as though I can only install NDS 1.0.2-1, even though the current version is 4.0.0.

```bash
# opkg list nodogsplash
nodogsplash - 1.0.2-1 - Nodogsplash offers a simple way to open a free hotspot providing
 restricted access to an internet connection.
```

Even if I download NDS v4.0.0 from OpenWRT ([https://downloads.openwrt.org/snapshots/packages/mipsel_74kc/routing/](https://downloads.openwrt.org/snapshots/packages/mipsel_74kc/routing/)), it ends up pulling v1.0.2-1 from the OpenWRT repositories. What should I do?

**Comment by ikokang** [comment]
It is recommended to download the nodogsplash file package for compilation, which is fast and new! Support for friendliness
Download address:
https://github.com/openwrt-routing/packages.git

**Comment by bluewavenet** [comment]
@ikokang 
Sorry, that is not recommended or required.
@akrantz01 
The latest package binary you have downloaded already.

Are you running the GL.iNet custom version of OpenWrt? It does look like you are as you are getting NDS v1, and that was removed from the official OpenWrt 18.06 packages.

To install it, do the following:
 * opkg update
 * delete /etc/config/nodogsplash and /etc/init.d/nodogsplash if they exist.
 * copy to /tmp on your router then run:
 * opkg remove nodogsplash
 * opkg install /tmp/nodogsplash_4.0.0-1_mips_24kc.ipk

This should also download and install the libmicrohttpd-no-ssl package.

Finally you can run ndsctl status to verify the NDS version.

**Comment by akrantz01** [comment]
That worked. Thanks
