### ISSUE TITLE
How to enable Oauth2.0 authentication from NDS

### ISSUE THREAD

**Issue by bawantha** [nodogsplash/nodogsplash#402]
How can I let to Oauth authentication from NDS like google OpenId, how  can I enable to access those sites?

**Comment by bawantha** [comment]
> How can I let to Oauth authentication from NDS like google OpenId, how can I enable to access those sites?

as set this not sure right or wrong

list preauthenticated_users 'allow tcp port 80 to 172.217.7.173'

where 172.217.7.173 is ip address of accounts.google.com

**Comment by bawantha** [comment]
> How can I let to Oauth authentication from NDS like google OpenId, how can I enable to access those sites?

I found this from config
 # Allow preauthenticated users to access an external IP address
  # This is commonly referred to as a Walled Garden.
  # Only IPv4 addresses can be used (not domain names) 
  #list preauthenticated_users 'allow tcp port 80 to 172.217.7.173'
  #list preauthenticated_users 'allow udp port 8020 to 112.122.123.124'
 is this is the solution but why I can't use domain names

**Comment by bluewavenet** [comment]
@bawantha 
This will not work directly - one of the major reasons is that the client CPD will in most cases refuse to download/run javascript for reasons of security. The Google, Facebook, etc authentication APIs rely heavily on javascript running on the client.
What you need to do is have NDS redirect to your own external FAS (as you already know how to do) and have that FAS use something like Node.js to talk to Google etc.

We could develop NDS to do DNS lookups for us so we could use domain names but it would be a mostly useless exercise as you could still not use the Google API directly from the client CPD, you need FAS as an intermediary that serves pure html to the client CPD.

**Comment by bawantha** [comment]
I have FAS in cloud but normally when we use Google atuh it's redirect to **accounts.google.com/[params]** but it didn't load in client device. it's may be CPD refusing it.

**Comment by bluewavenet** [comment]
From memory, the first thing the Google api does is try to download some fairly large javascript files to the client.
The client CPD blocks this.
Your FAS could download and run as an intermediary as I mentioned earlier.

**Comment by bawantha** [comment]
Hi I did research about already implemented WIFI marketing solutions like https://beambox.com/ for there CP facebook , twitter auth work. I'm thinking about  how do they do it?

**Comment by bluewavenet** [comment]
Similar in  principle to how I suggested.

**Comment by klinutzu** [comment]
hello, tried to send an email to you, but no luck, so i decided to write here. i need for a project UE-based to use domains in wall garden as they need to use a javascript. how can be this done as i tried with ip, but no success.

**Comment by bluewavenet** [comment]
@klinutzu 
You can create an ipset, then populate it using the --ipset configuration option in Dnsmasq.
Finally, you add the ipset to the preauth ruleset in the NDS config.
Search the NDS config file for "Walled Garden".
This is currently not well documented unfortunately.
