### ISSUE TITLE
Keep authenticated clients on reboot

### ISSUE THREAD

**Issue by javifperez** [nodogsplash/nodogsplash#408]
I have a router with openwrt running a hotspot using nodogsplash. The matter is that the users connect to an open wifi network and they log in the network for a week and in that time they no longer log in within a week (the authidle timeout is a week) and once past that week they have to login again with a different user and password because I have put in the PHP Page a command that erases the username and password once introduced from the users.dat list, so after that week they have to use a different user and password. Well, the problem comes when the router reboots due to some cause and the client list appears empty, so if it hasn't been a week, the client doesnt have an usermane to log in. Then at this point I have the following question: Is there any possibility to keep the client list and their auth idle time when the system reboots?

**Comment by ikokang** [comment]
How to verify the username and password online?
I am currently using a remote authentication server fas-aes.php

**Comment by bluewavenet** [comment]
@javifperez 
From your description, I do not fully understand what you are trying to do, but here is a scenario, and a possible solution that might help.

**Scenario:**
You have a FAS that allows users to log in and pay for 7 days of Internet access. A paid up client can then freely access the Internet for 7 days without any interaction with NDS.
After 7 days have expired, the client has to log in and pay again for another 7 days.

**Solution:**
On first connecting to the WiFi, NDS redirects the client to FAS. There the client fills in a self registration form and pays using Paypal. (FAS could use node.js and the Paypal api for payment).
FAS then returns to NDS for final authentication. NDS has BinAuth enabled as well as FAS, so the BinAuth script is called.
The BinAuth script will then in turn call -
 *  `ndsctl trust [client_mac]`
 * `uci add_list nodogsplash.@nodogsplash[0].trustedmac='[client_mac]'`
 * `uci commit nodogsplash`

The first call of BinAuth tells NDS to allow the client free access.
The second and third tell NDS to remember the client after a reboot.

Finally a process needs to run in the background to remove the client after a week. This can be a shell script started at boot. This will loop indefinitely and at a suitable interval, say every 10 minutes, will ask FAS for a list of expired clients (using wget or curl to a special FAS page written for the purpose). The clients on the list are then deauthed by calling for each client:
 * `ndsctl deauth [client_mac]`
 * `uci del_list nodogsplash.@nodogsplash[0].trustedmac='[client_mac]'`
Then once all clients on the list have been dealt with:
 * `uci commit nodogsplash`
The script then sleeps for its polling interval (10 mins in this example).

**Comment by bluewavenet** [comment]
@ikokang 
Did you mean to start a new issue or is your question related to this issue?

**Comment by bawantha** [comment]
> I have a router with openwrt running a hotspot using nodogsplash. The matter is that the users connect to an open wifi network and they log in the network for a week and in that time they no longer log in within a week (the authidle timeout is a week) and once past that week they have to login again with a different user and password because I have put in the PHP Page a command that erases the username and password once introduced from the users.dat list, so after that week they have to use a different user and password. Well, the problem comes when the router reboots due to some cause and the client list appears empty, so if it hasn't been a week, the client doesnt have an usermane to log in. Then at this point I have the following question: Is there any possibility to keep the client list and their auth idle time when the system reboots?

you should use remote FAS to avoid data lost

**Comment by bluewavenet** [comment]
@bawantha Yes that is pretty much the point of having a remote FAS.
However it is worth noting that BinAuth can be enabled along with FAS and in the case of wanting to "Keep authenticated clients on reboot", a Binauth script is ideal, ie an authenticated client stays authenticated even through a reboot of NDS.
