### ISSUE TITLE
FAS not working when fas_secure 0

### ISSUE THREAD

**Issue by bawantha** [nodogsplash/nodogsplash#413]
Hi when I set fas_secure level to 0 , popup URL's  domain name set to it's IP address and not loading FAS but whem fas_secure level set to 1 it's working fine 

my NDS configs [https://pastebin.com/X4K3cPch](url)

**Comment by bluewavenet** [comment]
You seem to be pointing at the web root of example.com for your fas script....

By the way, last time I looked, OpenWrt Snapshot for RPi was working again so you should be able to go back to level 3 now.

**Comment by bluewavenet** [comment]
It looks like fas_remotefqdn is not supported with option fas_secure_enabled '0'
This is a bug - easy fix - will be in release 4.0.2

**Comment by bluewavenet** [comment]
Done. Expect v4.0.2 soon.

**Comment by bluewavenet** [comment]
@bawantha 
v4.0.2 is available in OpenWrt Snapshot
