### ISSUE TITLE
deauth after specific time using ndsctl commands

### ISSUE THREAD

**Issue by bawantha** [nodogsplash/nodogsplash#423]
Hi 
I used ndsctl commands to auth client mac
`ndctl auth $mac`
is there any way to deauth particular mac in time base so far I found this
`ndsctl deauth $mac`
but is there any way to automate it like when auth happens it should deauth after some time 
Thank you

**Comment by bluewavenet** [comment]
If you are doing a manual auth then instead you could run a shell script you have written for the purpose that auths, then after a set time deauths again.

**Comment by bawantha** [comment]
> If you are doing a manual auth then instead you could run a shell script you have written for the purpose that auths, then after a set time deauths again.

I created mobile app it's SSH connect to NDS and execute `ndsctl` as you say I can create timer for that but If user close my app It won't run

**Comment by bluewavenet** [comment]
No, run a script on the NDS router that runs ndsctl auth, then loops until the required time interval has expired then runs ndsctl deauth. You can start this remotely.

**Comment by bawantha** [comment]
yeah remote execution may be the answer
