### ISSUE TITLE
How do i redirect cpd to a website ?

### ISSUE THREAD

**Issue by uplsaurabhA** [nodogsplash/nodogsplash#424]
My understanding was- if set fasremotefqdn to the url of the website it would take portal to the website. But fasremotefqdn doesn't accept https , so i put in the public  ip of the website in fasremoteip (while keeping fasport as 80, and gateway address as wlan ip address of raspberry pi i am trying to get it work on ). Am i doing something wrong?
Apologies if this isn't the correct place for asking implementation advice.
Also how do i find out the version of nodogsplash i am using?

**Comment by bluewavenet** [comment]
@uplsaurabhA
FAS is designed to make NDS redirect to a web page where users will log in. Using the parameters set in config, NDS will set up firewall rules to allow access to that web page then redirect client CPD browsers there.

The minimum FAS parameters for an external FAS web page are:

- fasremoteip
- fasport
- faspath

These three parameters tell the CPD the address of the remote FAS, the IP port to use, and the path to the login page. They also allow NDS to automatically set up the required firewall rules so clients have access to the remote FAS.


Optional parameters are:

- fasremotefqdn
- fas_secure_enable
- faskey

FQDN means "Fully Qualified Domain Name". This is not the web address of the FAS server, but the DNS entry which allows browsers to look up the IP address of the server by name. The FQDN is then used by the web server to determine which web site is to be served when the web server is hosting multiple web sites using a single ip address (this is the most common setup for web hosting services).

You can find the documentation for setting up NDS with FAS at:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html
