### ISSUE TITLE
Allow external resources to be loaded on CPD splash page

### ISSUE THREAD

**Issue by schoren** [nodogsplash/nodogsplash#429]
Im trying to load some external resources on the HTML Splash page. Specifically, some given JS scripts in the form of:
```
<head>
...
  <script src="https://somedomain.com/somescript.js"></script>
</head>
```

If the src is HTTP (unsecure), it redirects to the splash. If it's HTTPS, it returns with "Connection Refused".

How can I tell NDS to allow certain urls (or IPs?) to go through?

**Comment by mwarning** [comment]
I think that will do it:
```
option authenticated-users 'allow tcp port 443 to <ip_of_somedomain.com>'
```

**Comment by bluewavenet** [comment]
@schoren @mwarning

`option authenticated-users 'allow tcp port 443 to <ip_of_somedomain.com>'`

This will  indeed give the client access to https://[ip_of_somedomain.com] but this presents two major problems. There is no guarantee the splash page will work as intended on all, or even any devices.
The problems:
 * Many client CPD implementations disallow download and execution of javascript (for security reasons).
 * On a   typical shared hosting service the server ip address does not give access directly to any particular hosted web site, in general a very specific url is required.

In addition, accessing an https component will very probably generate CPD browser security warnings.

If javascript is absolutely required (eg Facebook api login), then the best way to do this is to use a FAS that is implemented using node.js. This FAS can then run the required remote javascript at the same time as interacting with the client user.
