### ISSUE TITLE
ByPass redirection

### ISSUE THREAD

**Issue by jeetu28** [nodogsplash/nodogsplash#436]
Can we run the NoDogSplash  without redirecting to web page? And quota metering etc should work as it is.

**Comment by bluewavenet** [comment]
@jeetu28 
The "as installed" default configuration does indeed redirect to the originally requested URL.
Using the NDS api you can choose the behaviour you need for your use case using combinations of FAS, PreAuth and Binauth.

NDS keeps track of client usage times, upload data and download data. This data can be utilised along with the api to implement your own "quota metering" system.

If you could you give a bit more detail about what you are trying to do then I can give you some pointers on how to go about it.

**Comment by jeetu28** [comment]
Thanks you for your quick response!!
Well... i want the nodogsplash to work as it is, But there should not be any authentication on it. Even not to accept the terms and click on continue.
So User will latch and when router( running with nodogsplash) will intercept the first http request it will create the session( by allocating the quota) right away without redirecting on any splash and user would be able to do the internet.

**Comment by bluewavenet** [comment]
@jeetu28 
Well, NDS is a Captive Portal. The whole technical process, involving the client CPD is to show the client user some sort of Portal web page.

CPD is designed, not only to facilitate login, but also to inform client users that they have been "captured".

Hiding this from users is not what is intended in the development of CPD and Captive Portals, and in fact this may not be legal in some jurisdictions (eg Europe).

**Comment by jeetu28** [comment]
Well I understand you concern. 
But we are authenticating user on EAP based. But we want to control the user session with NDS like upload/download limit etc. Thats why we want to avoid splash.

**Comment by bluewavenet** [comment]
I don't think NDS is the right tool for this.

The reason is in the name:
NoDog**_Splash_**

**Comment by jeetu28** [comment]
Thanks @bluewavenet  for the explanation...
I will then try to achieve this the other way :)
