### ISSUE TITLE
External Splash/CaptivePortal

### ISSUE THREAD

**Issue by jeetu28** [nodogsplash/nodogsplash#437]
I want to redirect the user to an external captive portal using the NDS. How can i do this?
Also , how will it call the $authaction if the html page is getting host on another node at remote location.

Please let me know if you need further info about the query!!!

Thanks in advance!!

**Comment by bluewavenet** [comment]
The ability to do just this is built into NDS and is known as Forwarding authentication Service (FAS).
An example php script is supplied with simple config options to enable this.
I would suggest you get this example working first, then look at how you will modify it for your own uses.
Full documentation can be seen at:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#

I would suggest that you download and install NDS v4.2.0 or above, binaries are available at:
https://downloads.openwrt.org/snapshots/packages/
You will find the package in the routing part of the selected architecture.

Feel free to ask any questions.

**Comment by jeetu28** [comment]
FAS , we can use to serve splash from another host and to authenticate users . That is OK
But FAS is not any external captiveportal. It should be made in a way to do the communication from NDS i.e. token, gatewayaddress .
My point is to have an captiveportal which is a sort of form written in 'lets say' javascript+html and after doing registraion/acceptTerms on this NDS can allow user to go on internet - both CaptivePortal and NDS are on different node.

**Comment by bluewavenet** [comment]
@jeetu28 
A captive portal will have two components:

 * Something that does the capturing
 * Something that displays a splash page for credential validation

By definition, the thing that does the capturing must be on the router that serves as ip gateway for the local network.

The thing that does the splash page can be anywhere.

NDS has both of these components. The second one, for anything other than the very simplest configuration, will be a FAS such as the example fas-aes.php.

The capturing part of NDS (when at level 2) sends the following information in encrypted form to the FAS:
 * client ip address
 * client mac address
 * client token
 * gatewayname
 * gatewayaddress
 * authdir
 * originurl

You can write your FAS to use this information in any way you please, conduct a dialog with the client (asking for credentials for example), before finally returning to the "capturing" part of NDS using authaction constructed from the information sent to it.

Details of the flow of communication between the client and the FAS can be seen in the fas-aes example.

You should also note:
https://nodogsplashdocs.readthedocs.io/en/stable/customize.html#rules-for-customised-splash-pages

**Comment by jeetu28** [comment]
So you mean we need to design the FAS to be compliant to talk with NDS. We can not use the already available external captiveportal/Splash

**Comment by bluewavenet** [comment]
@jeetu28 

> So you mean we need to design the FAS to be compliant to talk with NDS. We can not use the already available external captiveportal/Splash

No, I am not saying that at all. FAS is a **component** of the NodogSplash captive portal "engine".

As I stated previously, a captive portal will have two components:
 * Something that does the capturing
 * Something that displays a splash page for credential validation

> We can not use the already available external captiveportal/Splash

You have not mentioned this before.
I assume, perhaps incorrectly, that it is one of the proprietary systems that are available.

In this case you would use FAS as an intermediary software shim between the client capture done by NDS and the proprietary system (presumably to avoid having to purchase proprietary hardware to work with the proprietary software).
To do this you will need knowledge of the interface of that system, either via a published API or by some reverse engineering.

NoDogSplash has been designed to be used as a core system with great flexibility for customisation. The default installation of NDS provides some fully functional, simple examples that might be all many people need. But it also provides the tools for development of very sophisticated, dedicated solutions.
If you have enough knowledge of your existing "splash page system", FAS can be used to interface with it.

**Comment by jeetu28** [comment]
thank you @bluewavenet  for this Clarification. I got the understanding about the external CaptivePortal with NDS now.

Thanks Again !!!

**Comment by bluewavenet** [comment]
@jeetu28 
If you need any further help, please just ask.
