### ISSUE TITLE
NDS v4.3.0 fails to create deb package on RPi 4B

### ISSUE THREAD

**Issue by martignoni** [nodogsplash/nodogsplash#447]
## Steps to reproduce

```bash
git clone https://github.com/nodogsplash/nodogsplash.git
cd nodogsplash/
git checkout v4.3.0
make deb
```

## Error occurring

```
cp: cannot create regular file '/home/xxx/nodogsplash/dist/nodogsplash-4.3.0/debian/nodogsplash/usr/lib/nodogsplash/login.sh': No such file or directory
make[2]: *** [Makefile:45: install] Error 1
```

## Note

On the same hardware, NDS v4.2.0 creates deb package flawlessly (just typing `git checkout v4.2.0` instead of `git checkout v4.3.0`.

**Comment by bluewavenet** [comment]
@martignoni
Thanks for reporting this. 
I see the problem - a missing line in the Debian makefile, it does not make the library directory.
Fix on its way...

**Comment by bluewavenet** [comment]
@martignoni 
see commit https://github.com/nodogsplash/nodogsplash/commit/3c4013133353f43ff8bb14c4ea33e0a63b412ff0

Could you please test by add the missing mkdir line to your Makefile?
If this works I'll tag a new release.

**Comment by martignoni** [comment]
Yes, the deb package creation works with the fix indicated. 👍

**Comment by bluewavenet** [comment]
@martignoni 
Thanks ;-)
https://github.com/nodogsplash/nodogsplash/releases/tag/v4.3.1

**Comment by martignoni** [comment]
Thank **you**!

**Comment by martignoni** [comment]
Ooops:
```
dpkg-source: error: can't build with source format '3.0 (quilt)': non-native package version does not contain a revision
```

**Comment by bluewavenet** [comment]
@martignoni 
The source for libmicrohttpd has been intermittently offline today. I think that is the problem.
The Travis checks were failing for the same reason. Keep trying, will probably return to normal very soon.

**Comment by bluewavenet** [comment]
The primary mirror https://mirrors.ocf.berkeley.edu/gnu/ is offline or extremely slow at the moment (Wed Oct 9 18:35 UTC). 
There will be some poor server engineer wishing he had taken the day off I suspect ;-)

**Comment by martignoni** [comment]
Indeed. Thanks for the info, I'll try tomorrow.

**Comment by martignoni** [comment]
Cause was a wrong version number. Just created a PR to fix it.

**Comment by martignoni** [comment]
(Sorry, I should have raised another issue for this.)

**Comment by bluewavenet** [comment]
Thankyou. It was my mistake so it is me making apologies!
