### ISSUE TITLE
Automatic Redirection (Raspberry Pi 3B)

### ISSUE THREAD

**Issue by LeonPro12** [nodogsplash/nodogsplash#463]
Hello,
I installed NoDogSplash on OpenWrt.
But when I connect to the OpenWrt WiFi the login page does not appear. I have to type in the IP adress. Also I can surf the internet without clicking on Continue in the NoDogSplash page.

How can I solve this?
Thanks

**Comment by bluewavenet** [comment]
@LeonPro12 
To give you any help, it would be a great help if you could state the versions of OpenWrt and NoDogSplash you are using.
You should also read the documentation, a good starting place would be:
https://nodogsplashdocs.readthedocs.io/en/stable/install.html

Note, NDS requires to be installed on a ROUTER with WAN and LAN interfaces. The LAN interface must be the IPv4 gateway for the subnet. 

You can check the status of NDS by running, in an SSH terminal, the command:
`ndsctl status`

**Comment by bluewavenet** [comment]
@LeonPro12 
Please post the output of the command:
`ifconfig`
also run from an ssh terminal.

**Comment by bluewavenet** [comment]
No response so closing.
