### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by hanis94** [nodogsplash/nodogsplash#466]
Hi,
Please why javascript is not working with nodogsplash but with other captive portal is working I tested tanaza portal is working also can integrate google analytics with javascript and when I test it is working but with NDS is not working.

thanks

**Comment by bluewavenet** [comment]
This is **not** a problem with NoDogSplash, it is a security feature of the CPD (captive portal detection) that is built into all phones, tablets, desktops etc. 

**It is the device CPD that blocks javascript.**

If CPD did not block javascript, all sorts of nasty things would be possible, automatically, in the background, without the user knowing, just by connecting to a wifi network.

All captive portals (including NoDogSplash) must interpret any javascript used on third party web pages, by implementing a remote authentication server portal page to relay html to the CPD browser.

This is commonly done using something like node.js on the remote portal and is fully supported by NDS-FAS.

**Comment by hanis94** [comment]
Thanks I will contact node js developer for implementing this
