### ISSUE TITLE
Title tag not taking effect

### ISSUE THREAD

**Issue by Warniz** [nodogsplash/nodogsplash#468]
I've made a captive portal on my Raspberry Pi 3+ and every thing run smoothly, but I can't get a custom title to show.
I've changed in the html tag but still is shows the name of the network and the IP.
I've only tested on IOS since it's all I have at hand.

Is there some parameters I'm missing to change the captive portal name?

**Comment by bluewavenet** [comment]
@Warniz 
It is not clear what you are trying to do.
Please give some more detail eg:
 * Operating system on your RPi
 * Version of NDS
 * Mode you have set NDS to use (Templated html, Preauth or FAS?)
 * What you have edited

For reference, the NDS documentation can be found at:
https://nodogsplashdocs.readthedocs.io
