### ISSUE TITLE
Is there anyway to bypass nodogsplash using JavaScripts?

### ISSUE THREAD

**Issue by nntoan** [nodogsplash/nodogsplash#47]
Hello,

I am afraid about there is some user can bypass our wifi access, so is there anyway to bypass nodogsplash via Js? Around my area is students and they have a tons of tricks....

Thanks.

**Comment by mwarning** [comment]
I do not really know how the iptable rules are set up (aka Firewall). But normally there should be no way. A way to access Internet is of course to try to transfer data over DNS. As for approaches using Javascript, I do not think there are. It might be easier to spoof the MAC address of somebody who is authenticated. Anyway, let us know if you come to know any security issues with Nodogsplash.

**Comment by mwarning** [comment]
Oh, and there is a Mailing list (http://ml.ninux.org/mailman/listinfo/nodogsplash) which might be better suited.

**Comment by nntoan** [comment]
Well, when splash page shown up. I don't set password for it. User must click to continue button to access Internet again. But can the user write an automatic javascript (userscripts.org) to bypass it?

**Comment by mwarning** [comment]
Yes, that would be pussible. The only way around this would be to add a so called captcha to the splash page.
