### ISSUE TITLE
After passing the authentication, you cannot return to the website page!

### ISSUE THREAD

**Issue by openwrt-diy** [nodogsplash/nodogsplash#470]
After you set up the tutorial page,**https://nodogsplashdocs.readthedocs.io/en/stable/fas.html**
After the local computer has passed the authentication, when clicking "**Continue**", it is unable to return to the web address page just entered

**http://192.168.100.1:2050/nodogsplash_auth/http%3a%2f%2fwww.ifeng.com%2f
Error 404 - Not Found**

/$ uci show uhttpd
uhttpd.main=uhttpd
uhttpd.main.listen_https='0.0.0.0:443' '[::]:443'
uhttpd.main.redirect_https='1'
uhttpd.main.home='/www'
uhttpd.main.rfc1918_filter='1'
uhttpd.main.max_requests='3'
uhttpd.main.max_connections='100'
uhttpd.main.cert='/etc/uhttpd.crt'
uhttpd.main.key='/etc/uhttpd.key'
uhttpd.main.cgi_prefix='/cgi-bin'
uhttpd.main.lua_prefix='/cgi-bin/luci=/usr/lib/lua/luci/sgi/uhttpd.lua'
uhttpd.main.script_timeout='60'
uhttpd.main.network_timeout='30'
uhttpd.main.http_keepalive='20'
uhttpd.main.tcp_keepalive='1'
uhttpd.main.listen_http='0.0.0.0:2080'
uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
uhttpd.defaults=cert
uhttpd.defaults.days='730'
uhttpd.defaults.bits='2048'
uhttpd.defaults.country='ZZ'
uhttpd.defaults.state='Somewhere'
uhttpd.defaults.location='Unknown'
uhttpd.defaults.commonname='OpenWrt'

/$ uci show nodogsplash
nodogsplash.@nodogsplash[0]=nodogsplash
nodogsplash.@nodogsplash[0].enabled='1'
nodogsplash.@nodogsplash[0].fwhook_enabled='1'
nodogsplash.@nodogsplash[0].gatewayinterface='br-lan'
nodogsplash.@nodogsplash[0].gatewayname='OpenWrt Nodogsplash'
nodogsplash.@nodogsplash[0].maxclients='250'
nodogsplash.@nodogsplash[0].preauthidletimeout='30'
nodogsplash.@nodogsplash[0].authidletimeout='120'
nodogsplash.@nodogsplash[0].sessiontimeout='1200'
nodogsplash.@nodogsplash[0].checkinterval='600'
nodogsplash.@nodogsplash[0].authenticated_users='allow all'
nodogsplash.@nodogsplash[0].users_to_router='allow tcp port 22' 'allow tcp port 23' 'allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 80' 'allow tcp port 443'
nodogsplash.@nodogsplash[0].fasport='2080'
nodogsplash.@nodogsplash[0].faspath='/nds/fas-aes.php'
nodogsplash.@nodogsplash[0].fas_secure_enabled='2'
nodogsplash.@nodogsplash[0].faskey='1234567890'
nodogsplash.@nodogsplash[0].debuglevel='1'
nodogsplash.@nodogsplash[0].trustedmac='00:00:CA:FE:BA:BE'
nodogsplash.@nodogsplash[0].fw_mark_authenticated='30000'
nodogsplash.@nodogsplash[0].fw_mark_trusted='20000'
nodogsplash.@nodogsplash[0].fw_mark_blocked='10000'

**Comment by bluewavenet** [comment]
@openwrt-diy 
This seems to be a bug introduced in the last release (by me! :-D)
I have fixed the file and attached here for you to try. Download and remove the .txt from the end of the file name.
I'll do a PR shortly.
[fas-aes.php.txt](https://github.com/nodogsplash/nodogsplash/files/3833316/fas-aes.php.txt)

**Comment by bluewavenet** [comment]
Accidentally closed so reopening until you have confirmed it is working.

**Comment by openwrt-diy** [comment]
I've downloaded it. I'll test it tomorrow at work.

**Comment by bluewavenet** [comment]
Let me know how it goes.

**Comment by openwrt-diy** [comment]
After passing the authentication, you can return to the current website you are visiting! Another problem was found. Using Fas authentication, the lower right corner of the desktop will not remind you that you need to log in for authentication. The response speed of authentication is not as fast as HTML.

**Comment by bluewavenet** [comment]
> the lower right corner of the desktop will not remind you that you need to log in for authentication.

I'm not sure what is in the lower right of your workstation - is this windows? I haven't used windows for years ;-)

> The response speed of authentication is not as fast as HTML.

You are using uhttpd and it can be slow with php. What hardware are you using and how much free ram is there (use free command)? uhttpd can be exceptionally slow if free ram is low.

uhttpd is fine for testing, but you should use something like lighttpd, ngnix or apache for serious development. I prefer lighttpd as its resource utilisation is indeed "light" and very good for IoT type devices.
