### ISSUE TITLE
facebook login button 

### ISSUE THREAD

**Issue by richyxi** [nodogsplash/nodogsplash#474]
hi, im trying to implement a captive portal with NDS with a facebook login and google login button like in common places, when i was checking through the html file, it says that javascript wil not work due the CPD of the devices.

so, if the login button needs to work with the sdk of js, what can i do to get it work?

thanks so much in advance! awsome proyect!!!

**Comment by bluewavenet** [comment]
@richyxi 
You will have to implement a FAS that can interact remotely with the relevant SDKs.
The most obvious way is to use node.js as the platform for your FAS.

Conceptually, think of NoDogSplash as the "captive portal engine" that calls your custom application as a forwarding authentication service (FAS).

**Comment by richyxi** [comment]
can i run my FAS on the flask-python server?

**Comment by bluewavenet** [comment]
You can write your custom FAS on any platform that can serve interactive html!
So the answer is yes :-D

**Comment by richyxi** [comment]
Good! Thank you so much!!
