### ISSUE TITLE
Authentication points to an external radius server?

### ISSUE THREAD

**Issue by monelgordillo** [nodogsplash/nodogsplash#475]
Howdy,

Is it possible for nodogsplash to reference an external radius server for authentication?

**Comment by bluewavenet** [comment]
@monelgordillo 
The short answer is yes!
The long answer is you will have to write a FAS that interfaces between NDS and your Radius. Should be fairly straightforward assuming you have the API details.

Very much depending on what you are trying to achieve, an external radius may be overkill (a feeling I get from my own experience).

Can you share an outline of the requirements?

**Comment by monelgordillo** [comment]
@bluewavenet , thank you for the confirmation.  I'm working on this as a personal project; I want to see if I can get it to work.  

This is what I'm working with so far:
-1 raspberry pi model 3 (1 physical ethernet connection, 1 onboard wireless)
-hostapd is installed
-basic installation of nodogsplash is installed
-freeradius server in aws

hostapd is unsecured (no password/username); the nodogsplash basic splash page comes up when a user connects to the wifi access point presented by hostapd.  I would like an authentication page to be presented instead of the basic splash page, and I would like to use the external radius server that hosts those credentials.  Are there any examples of a FAS that I could look at maybe?

**Comment by bluewavenet** [comment]
@monelgordillo
The Rpi, although great for general development, does not make a very good router as the interfaces, particularly the wireless are somewhat of an io bottleneck and optimised for "end node" usage, eg workstation or IoT type of device. Nevertheless it can be used successfully in the case of a small number of users.
I assume you are using Rasbian or Debian variant. This is fine also, but it might be worth considering using OpenWrt as the operating system as it is optimised for router functionality and can mitigate some of the hardware limitations, at least to some degree. Also, I am much more familiar with OpenWrt and therefore would be better placed to help ;-)

https://downloads.openwrt.org/snapshots/targets/brcm2708/bcm2710/

There are ext4 and squashfs images you can use in the normal Rpi way, the ones labelled factory (sysupgrade is for in place upgrading from a previous version of OpenWrt).

If you go this route, the latest version of nodogsplash binary package (v4.3.3) will be available ready to install.
 You would then use NDS/FAS to communicate with the remote radius. An example FAS is included, if you first got this working, either locally or remotely then you will be at the point to begin talking to the radius with only small changes.
Documentation for NDS:
https://nodogsplashdocs.readthedocs.io/en/stable/

All this can of course be done using Rasbian but unless you have a specific need for it, I would recommend OpenWrt.

**Comment by monelgordillo** [comment]
@bluewavenet ,

This would be for a small # of users, and for my personal learning.  Thanks for the tip about the io bottleneck and openwrt.

I'm using the Rasbian flavor.  I have Nodogsplash version 4.3.4.beta installed.  I'm looking at the example fas-aes.php.  I've updated nodogsplash.conf to use the fas options.  However, I'm getting "ERR_INVALID_REDIRECT" when I try connecting to the access point.

My conf file:
root@raspberrypi:~# cat /etc/nodogsplash/nodogsplash.conf | egrep -v "^$|^#"
GatewayInterface wlan0
FirewallRuleSet authenticated-users {
  FirewallRule allow all
}
FirewallRuleSet preauthenticated-users {
FirewallRule allow tcp port 53	
FirewallRule allow udp port 53
FirewallRule allow tcp port 80 to RemoteIPHERE
FirewallRule allow tcp port 443 to RemoteIPHERE
}
FirewallRuleSet users-to-router {
   FirewallRule allow udp port 53	
   FirewallRule allow tcp port 53	
   FirewallRule allow udp port 67
  FirewallRule allow tcp port 22
  FirewallRule allow tcp port 80
  FirewallRule allow tcp port 443
}
GatewayAddress 10.3.141.1
MaxClients 250
AuthIdleTimeout 60 
fasport 80
fasremotefqdn RemoteFQDNHERE
fasremoteip RemoteIPHERE
faspath '/authweb/fas-aes.php'
faskey PasswordHERE1234
fas_secure_enabled 2

**Comment by monelgordillo** [comment]
@bluewavenet , I figured out the "ERR_INVALID_REDIRECT" issue.  I had to get rid of the single quotes in nodogsplash.conf: faspath /authweb/fas-aes.php

**Comment by monelgordillo** [comment]
@bluewavenet , you mention "you will be at the point to begin talking to the radius with only small changes."  Is there an example of this somewhere?  :)

**Comment by bluewavenet** [comment]
@monelgordillo 
Do you have fas-aes working now?
The login form asks for name and email address, but this could just as well be username and password. It currently just logs and displays a landing page. You would add the code to pass the credentials to the radius server for verification as soon as the client submits the login form, rather than just logging and continuing. Obviously if the verification fails you would get FAS to serve an error page instead.

Going back to your config, you do not need to add anything to the preauthenticated users section, in fact it is best left completely empty. NDS adds required iptables entries automatically.

A "proper" working config will have the device that NDS is running on set up to be the default ip gateway for the subnet in addition to providing DHCP and DNS for all clients - hence my comment about the preauthenticated users section.
All this is default on OpenWrt of course :-D

**Comment by bluewavenet** [comment]
Make sure you are reading the up to date documentation:
https://nodogsplashdocs.readthedocs.io/en/stable/

Most of the Rpi tutorials are very outdated from an NDS point of view.

**Comment by monelgordillo** [comment]
@bluewavenet ,

The sample fas-eas.php is working for me.  Looks like I need to learn a bit of php. :)

I'll try it without the preauthenticated lines.

Thanks for your help thus far.

**Comment by bluewavenet** [comment]
@monelgordillo 
Snippet from fas-aes.php:
```
	# Output the "Thankyou page" with a continue button
	# You could include information or advertising on this page
	# Be aware that many devices will close the login browser as soon as
	# the client taps continue, so now is the time to deliver your message.
	$authaction="http://".$gatewayaddress."/".$authdir."/";

	echo "<big-red>Thankyou!</big-red>\n".
	"<br><b>Welcome $fullname</b>\n".
	"<br><italic-black> Your News or Advertising could be here, contact the owners of this Hotspot to find out how!</italic-black>\n".
	"<form action=\"".$authaction."\" method=\"get\">\n".
	"<input type=\"hidden\" name=\"tok\" value=\"".$tok."\">\n".
	"<input type=\"hidden\" name=\"redir\" value=\"".urldecode($originurl)."\"><br>\n".
	"<input type=\"submit\" value=\"Continue\" >\n".
	"</form><hr>\n";
	read_terms($me,$gatewayname);
```
At the beginning of this snippet, we have the values of fullname and emailaddress so you would insert your code here to submit these to the radius server for verification, and if successful then continue to the Thankyou Page, if verification fails then tell the client with an error page.

**Comment by monelgordillo** [comment]
Alright. I got the radius authentication piece in place.  I was able to add this https://github.com/dapphp/radius at the beginning of the snippet you mentioned.  Thank you, @bluewavenet !
