### ISSUE TITLE
Question about RadiusDesk 

### ISSUE THREAD

**Issue by richyxi** [nodogsplash/nodogsplash#477]
Hi.

im trying to implement a captive portal on my house for learning purposes. I already read all of the documentation, in fact, the radius concept came across, which seems a very good management and data collector tool. 
I saw this raduisdesk option that provides a clear frontend for a quick and easy set up and it comes with a dynamic login page editor.
since FAS its a set of dynamic web pages, it will be a great deal to work with.

does nds can be used with raduisdesk?

my set up is:

-raspberry 3b+
-RaspAP with nodogsplash
-RadiusDesk from an external computer(Virtual Machine) on my local network

thanks in advance and have a great day!!!

**Comment by bluewavenet** [comment]
@richyxi 
I'm afraid I know nothing about RadiusDesk.
You might like to see issue #475 for some pointers.

**Comment by richyxi** [comment]
thanks for answer, i will do some research on how to implement it on raduis, thank u very much
