### ISSUE TITLE
Not repeated splash page

### ISSUE THREAD

**Issue by mrostamii** [nodogsplash/nodogsplash#478]
**I've run the nodogsplash 4.0.3 on OpenWrt. The device is Raspberry Pi 3 B v1.2.**  
When I connect to the Raspberry Pi SSID, it shows me the splash page and everything is ok. After that, I disconnect and connect again but the client has authorized and the splash page doesn't appear.  
How can I configure to make it repeated? I mean, every time that clients connect,  authorized or unauthorized, the splash page will become visible.

**Comment by bluewavenet** [comment]
@mrostamii 

> I disconnect and connect again but the client has authorized and the splash page doesn't appear.

That is how it is supposed to work. If disconnecting and reconnecting was to trigger a deauthentication, the system would be pretty much unusable as most mobile devices regularly disconnect from WiFi to save power often after a very short interval of inactivity.

You can set the config option "authidletimeout". This defaults to 120 minutes (shortest 1 minute). This forces a deauthentication after the set period of inactivity. Be aware though that users find this very annoying if set to a very short interval.

**Comment by mrostamii** [comment]
Thanks. I agree with you. It will bother users, however, I didn't config FAS and any login system and they just need to tap the `Continue` button.  
How can I unauthorize a user or a mac address? Is it possible to do that?

**Comment by mrostamii** [comment]
Weird news. I've set the "authidletimeout" value to "1" but nodogsplash didn't start after startup. Also, the same thing with "2".  
I changed it to "120" and it works fine.

**Comment by bluewavenet** [comment]
@mrostamii 
Ah! Sorry, yes, I forgot, checkinterval (set in in seconds) must be smaller than half of auth_idle_timeout (set in minutes).
So for authidletimeout of 1 minute, then you would need checkinterval set to 29 seconds or less.
There would have been an entry in the system log saying just this I think ;-)

**Comment by bluewavenet** [comment]
@mrostamii 
You can deauth a client by mac or ip using ndsctl eg:
`ndsctl deauth [client ip or mac address]`

**Comment by bluewavenet** [comment]
An issue you may well encounter if you just deauthenticate a client is with the client device CPD polling interval. This is often quite long for an authenticated client eg 300 or 600 seconds. This means the splash page will not appear for a period of up to the polling interval. This is set by the client device and nothing to do with NDS.

**Comment by mrostamii** [comment]
Thank you. It's worked. I disconnect the client, check the status by `ndsctl status`, after that the status and the **States** has changed to "Preauthenticated" and **Last Activity** has told (-1s ago).  

Is there a way to configure "checkinterval" == 1 sec and "authidletimeout" == 2 sec?  
My objective is that reduce it to 2 or 1 sec.

**Comment by mrostamii** [comment]
> `ndsctl deauth [client ip or mac address]`

I wanna write a script to block a MAC that the downloaded traffic is 100 megabytes.  

The thing I've thought is, find this MAC according to the `ndsctl status`, then block that by `ndsctl block [client mac address]`.

Any ideas?

**Comment by mrostamii** [comment]
> An issue you may well encounter if you just deauthenticate a client is with the client device CPD polling interval. This is often quite long for an authenticated client eg 300 or 600 seconds. This means the splash page will not appear for a period of up to the polling interval. This is set by the client device and nothing to do with NDS.

The splash page appears on any device so fast except a Huawei Android 8 device! You mean, because of the "CPD polling interval" of this device the problem happen?

**Comment by bluewavenet** [comment]
> Is there a way to configure "checkinterval" == 1 sec and "authidletimeout" == 2 sec?

The smallest value for authidletimout is 1 minute.

**Comment by bluewavenet** [comment]
The client captive portal detection (CPD) works by attempting access to a specific port 80 url.

On first connection the CPD attempts this a few times in quick succession, checking for the expected response from the remote server. If a response is received but not as expected, the CPD assumes it is behind a captive portal and opens a restricted functionality browser and displays the response ie the captive portal splash page.

At this point, many vendor's CPD implementations will either not test again while the wifi is connected, or at best wait a CPD polling interval of 300 to 600 seconds. So if you deauth an authenticated client, they will loose their connection and the splash page will not pop up again until the client user tries to access a port 80 web site or the CPD polling interval expires (if there is one).

If the client user disconnects from the wifi, then reconnects, the whole CPD process starts again and the splash will pop up immediately - but this requires a client user action of course.

**Comment by bluewavenet** [comment]
> I wanna write a script to block a MAC that the downloaded traffic is 100 megabytes.

Yes, ndsctl gives you the upload and download amounts for each client so you can use this information in a script to deauth and block a client.

**Comment by mrostamii** [comment]
> If the client user disconnects from the wifi, then reconnects, the whole CPD process starts again and the splash will pop up immediately - but this requires a client user action of course.

Therefore, the problem with Huawei Android 8 device has recognized. :D
Thank you.

**Comment by mrostamii** [comment]
> > I wanna write a script to block a MAC that the downloaded traffic is 100 megabytes.
> 
> Yes, ndsctl gives you the upload and download amounts for each client so you can use this information in a script to deauth and block a client.

Is there any command to get me a list of authorized MAC addresses?

**Comment by mrostamii** [comment]
> > > I wanna write a script to block a MAC that the downloaded traffic is 100 megabytes.
> > 
> > 
> > Yes, ndsctl gives you the upload and download amounts for each client so you can use this information in a script to deauth and block a client.
> 
> Is there any command to get me a list of authorized MAC addresses?

**Comment by bluewavenet** [comment]
There is not a single command but:
`ndsctl status`
`ndsctl clients`
or
`ndsctl json`
all give the authenticated mac addresses. A script could then filter to make a list quite easily.

**Comment by bluewavenet** [comment]
Fun 2 line script :-D
```
maclist=$(ndsctl json | grep -B 5 Authenticated | grep mac | awk -F '"' '{printf " " $4}')
echo $maclist
```

**Comment by mrostamii** [comment]
> ```
> maclist=$(ndsctl json | grep -B 5 Authenticated | grep mac | awk -F '"' '{printf " " $4}')
> echo $maclist
> ```

Thank you. 😅
Although, I'm new in scripting hence how can I get the mac address in which downloaded more than 20 megabytes?

**Comment by mrostamii** [comment]
Thank you. 
Although, I'm new in scripting.  
  
This command block all mac addresses in which the downloaded traffic is more than 100 megabytes.

`ndsctl json | jq -r '.clients[] | select(.downloaded > 102400).mac' | xargs -n 1 ndsctl unblock`

**Comment by bluewavenet** [comment]
Nice :)
That will just deauth the client though, they could just reconnect and log back in with an empty counter. There is a challenge for you! 

Which package are you using to give the select command?

**Comment by mrostamii** [comment]
You are right. After deauth the mac, we can block that, though.  
  
`select` is a subcommand of `jq` package.

**Comment by mrostamii** [comment]
If we deauth a mac, the "downloaded" counter would be "0". Therefore: 

First: `ndsctl json | jq -r '.clients[] | select(.downloaded > 102400).mac' | xargs -n 1 ndsctl block`
Then: `ndsctl json | jq -r '.clients[] | select(.downloaded > 102400).mac' | xargs -n 1 ndsctl deauth`

I've just tested and it's worked.

**Comment by bluewavenet** [comment]
But then they will be blocked until NDS is restarted :-D

Wait, I tried it here and it blocks everyone regardless of downloaded amount......
Downloaded is a string, not a number.... is that the problem?

**Comment by mrostamii** [comment]
> But then they will be blocked until NDS is restarted :-D

Yes, exactly. I intended to write a quota limitation script and it's the first step. 
I'll tell you the result.

**Comment by mrostamii** [comment]
> Wait, I tried it here and it blocks everyone regardless of downloaded amount......
> Downloaded is a string, not a number.... is that the problem?

Run `ndsctl json | jq -r '.clients[] | select(.downloaded > 10240).mac'` and it would tell you the mac addresses which downloaded more than 10 megabytes. Check it out to works well. Next, block the mac addresses one by one. This is what that command has worked for you.

**Comment by mrostamii** [comment]
> First: `ndsctl json | jq -r '.clients[] | select(.downloaded > 102400).mac' | xargs -n 1 ndsctl block`
> Then: `ndsctl json | jq -r '.clients[] | select(.downloaded > 102400).mac' | xargs -n 1 ndsctl deauth`

You can try it out: 
First: `ndsctl json | jq -r '.clients[] | select(.downloaded + .uploaded > 102400).mac' | xargs -n 1 ndsctl block`
Then: `ndsctl json | jq -r '.clients[] | select(.downloaded + .uploaded > 102400).mac' | xargs -n 1 ndsctl deauth` 

To ban the downloaded **and** uploaded traffic.

**Comment by bluewavenet** [comment]
The select requires the value returned to be long integer, but downloaded (and uploaded) are both strings, not long-integer, so your test does not work. It blocks ALL clients regardless of the amount of traffic. Lots of ways to fix it though.

**Comment by mrostamii** [comment]
No, it's ok. I just tested by two devices and it worked well.
  
`/etc/init.d/example`:
```
#!/bin/sh /etc/rc.common

while :
    sleep 15
    do
        ndsctl json | jq -r '.clients[] | select(.downloaded > 20480).mac' | xargs -n 1 ndsctl block
        ndsctl json | jq -r '.clients[] | select(.downloaded > 20480).mac' | xargs -n 1 ndsctl deauth
done
```
`/etc/crontan/root`: 
```
1 * * * * /etc/init.d/example start
30 5 * * * sleep 70 && reboot
```

It has been running the script each minute and also would restart the device each day at 05:30 am. 
It's what I need.

**Comment by mrostamii** [comment]
No, it's ok. I just tested by two devices and it worked well.
  
`/etc/init.d/example`:
```
#!/bin/sh /etc/rc.common

while :
    do
        ndsctl json | jq -r '.clients[] | select(.downloaded + .uploaded > 20480).mac' | xargs -n 1 ndsctl block
        ndsctl json | jq -r '.clients[] | select(.downloaded + .uploaded > 20480).mac' | xargs -n 1 ndsctl deauth
done
```
`/etc/crontab/root`: 
```
*/1 * * * * /etc/init.d/example start
30 5 * * * sleep 70 && reboot
```

It has been running the script each minute and also would restart the device each day at 05:30 am. 
It's what I need.

**Comment by bluewavenet** [comment]
It is good if it is working for you.
I have tested on OpenWrt and it does not work for me. I suspect it is a difference in the version of jq you are using compared to the one I have.
For me, your script just blocks everyone regardless as my jq correctly returns the string value that ndsctl json returns.
I have done very similar some time ago using awk filtering with success.

The danger is you will as some stage load an upgrade and it will stop working for you.

**Comment by mrostamii** [comment]
> The danger is you will at some stage load an upgrade and it will stop working for you.  
I agreed, but I need to config my device in a limited time. Thank you for the support and response. 

I'll post the exact version of the `jq` package.
