### ISSUE TITLE
FAS changes needed for new splash.html page in my web server

### ISSUE THREAD

**Issue by GabrielStoica** [nodogsplash/nodogsplash#479]
Hello everyone!
I followed this issue: https://github.com/nodogsplash/nodogsplash/issues/220 and modified all the configurations file, more exactly:
/etc/nodogsplash/nodogsplash.conf - FirewallRule allow tcp port 80 to 192.168.4.1 - which is my Raspberry Pi ip 
/etc/nodogsplash/htdocs/splash.html
< meta http-equiv="refresh" content="0;URL='http://192.168.4.1/nodog/fas.html?authaction=$authaction&amp;gatewayname=$gatewayname&amp;tok=$tok&amp;redir=$redir&amp;mac=$clientmac&amp;ip=$clientip'" / >

Everything it's ok till here. My splash page redirects to my fas.html page in /var/www/html/nodog, but now i have a question.
How can i gen internet connection? I mean if i'm trying to put in my fas.html page:

```
<form method='GET' action='$authaction'>
  <input type='hidden' name='tok' value='$tok'>
  <input type='hidden' name='redir' value='$redir'>
  <input type='submit' value='Click Here to Enter'>
</form>

```
And click on submit when my new splash page is prompted.. i get "not found reuqested URL..." 
Hope you understand my problem. Thanks in advance!

**Comment by bluewavenet** [comment]
@GabrielStoica 
It seems that everything you are doing is VERY outdated. 
Please read the up to date documentation here:
https://nodogsplashdocs.readthedocs.io

And the section on FAS:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

Once you have read this you will need to ensure you are using Nodogsplash v4.3.3 or later.
You will see there are some fully functional example FAS and PreAuth scripts provided. Get these working before you start making any of your own changes and make sure you understand how it is working.
Feel free to ask any questions but please read the documentation first ;-)

**Comment by GabrielStoica** [comment]
Thanks!
I'm a little bit confused about the FAS. So after I edit my **/etc/nodogsplash/nodogsplash.conf** file and put **FirewallRule allow tcp port 80 to 192.168.4.1**, I need to edit my original(put that meta http-equiv) splash.html page in /nodogsplash/htdocs, right?

After that i'm going to my web server source folder /var/www/html and create folder called nodog(name doesn't matter), which contain my new splash page  (fas.html).  So now, i have a redirection from original splash.html to my new fas.html page. 

My question is how can i put in this (fas.html) page, that button(submit from splash.html) which allow me to gain acces to internet from any device connected to wifi?
Thanks!

**Comment by bluewavenet** [comment]
@GabrielStoica 

> So after I edit my /etc/nodogsplash/nodogsplash.conf file and put FirewallRule allow tcp port 80 to 192.168.4.1, I need to edit my original(put that meta http-equiv) splash.html page in /nodogsplash/htdocs, right?

**No! - none of that is correct - that is VERY outdated.**
Please READ the documentation, particularly:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

Example code is pre-installed in NDS 4.3.3
FAS example:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#using-the-fas-example-script

PreAuth is a special case of FAS and the pre-installed PreAuth script can be enabled by adding a SINGLE line to the config file.
See:
https://nodogsplashdocs.readthedocs.io/en/stable/preauth.html

**In addition, ensure you are using Nodogsplash v4.3.3 or later.**

You do not say which operating system you are using on your Rpi.
NDS will run fine on Debian variants, or in fact most Linux distributions, however as it MUST run on a device configured as a router, it will be much more efficient to use OpenWrt as this is optimised for routing and at least from my point of view is much easier to provide advice as I do not have access to any Rpi hardware.
You can download a bootable image at:
https://downloads.openwrt.org/snapshots/targets/brcm2708/
and selecting the "factory" image for whichever model of Rpi you have.
The factory image is copied onto your boot/storage media using the Linux DD utility or equivalent.

**Comment by bluewavenet** [comment]
I think the issue here is people using very old and outdated RPi tutorials.
@GabrielStoica Don't worry, you have done the right thing asking :-D
Continue to post here if you are still having difficulties.
