### ISSUE TITLE
Setup fas on port 80 on the same device

### ISSUE THREAD

**Issue by ClydeAmazing** [nodogsplash/nodogsplash#485]
Hello, I would like to setup fas to port 80 on the same device where NDS is installed. I am using NDS 4.3.3beta on orange pi running armbian configured to act as router and webserver(for FAS) at the same time. How do I actually do this? I already tried setting up NDS with fasport 80 but resulted to too many redirect error. Maybe i may have missed some settings here. Any help will be greatly appreciated.

**Comment by bluewavenet** [comment]
@ClydeAmazing 
You should not use 4.3.3beta as it is only a daily snapshot and you will only have what was available on the day you downloaded it and it has not been available for 2 months or so.
Before you do anything else you should upgrade to the current **release** 4.3.3.
https://github.com/nodogsplash/nodogsplash/releases/tag/v4.3.3

Regardless of version, local port 80 is reserved for the client CPD so CANNOT be used if FAS is local to NDS. You can use any ports except 80 and 2050.
This is not an issue as any web server can be set up to serve on any port. This will be transparent to the user as they will be redirected to the FAS server automatically.

Please make sure you are reading the up to date documentation at:
https://nodogsplashdocs.readthedocs.io/en/stable/

Also, be aware that most, if not all, Rpi tutorials to be found online are very outdated and will probably not work.

**Comment by ClydeAmazing** [comment]
@bluewavenet 
Thank you for a very prompt response. That clears things up a bit.
