### ISSUE TITLE
Help with whitelisting domains on splash page/including external websites

### ISSUE THREAD

**Issue by catsdgs** [nodogsplash/nodogsplash#488]
I am attempting to have my Wi-Fi users fill out a simple html form that they can submit. After they submit it, the Access Internet button will be enabled. All of this works on my server, but doesn't work on the splash page. I'm attempting to whitelist the domain _usebasin.com_ (138.197.131.106 so that my form can be properly submitted to this form hosting service. I've tried getting the IP address and adding it to a `FirewallRule allow tcp port 80 to 138.197.131.106.` But this doesn't seem to work. I also tried `FirewallRule allow ipset 138.197.131.106` I have put these in the `FirewallRuleSet preauthenticated-users` section. The form is sent through a post method and looks something like this: `<form action="https://usebasin.com/f/myendpoint" method="POST" id='myform'>`, and again works fine on my local computer. I need to use a form endpoint like this so its easy for many users to modify things about it, because system is for a family member.

**Comment by bluewavenet** [comment]
@catsdgs 
I am afraid that what you are describing shows some misunderstanding of how the NDS captive portal redirect works.
I suspect you are trying to use NDS in its very basic "simple splash page" mode, perhaps even using a very old version as well as old documentation.

For me to help, you will have to let me know:
 1. your operating system and its version
 2. your hardware and its configuration
 3. the version of NDS you are using

Once I have this information, I can hopefully give you some pointers in the right direction.

While you are at it, you should also read the current documentation ;-)
You can find it at at:
https://nodogsplashdocs.readthedocs.io

**Comment by catsdgs** [comment]
I am using Raspbian Buster Lite September 2019 on a raspberry pi 3 b. I use Ethernet to connect and the built-in Wi-Fi as a hotspot through raspap. I am using the latest version of NDS for debian which I downloaded through git a few days ago. The documentation hasn't helped me at all.

**Comment by catsdgs** [comment]
Also, I see that doing `FirewallRule allow tcp port 443 to 138.197.131.106` should work fine, right? I have seen something similar to this in this referenced thread. I also am able to submit by using http and the ip instead of https and the domain on my computer, so there should be no issue for the form to submit.
#429

**Comment by bluewavenet** [comment]
@catsdgs 

> FirewallRule allow tcp port 443 to 138.197.131.106 should work fine, right?

Unfortunately no, at best it will result in dire security errors, at worst, a blank screen with security errors.

> I am using the latest version of NDS for debian

There is no such thing as a "version for Debian". All versions support compiling for Debian. Most if not all Rpi tutorials are VERY outdated and usually point to NDS master. Master is a momentary "snapshot" with no guarantee that the snapshot you get at any particular time will work. What you should do is download the current RELEASE for compiling - sorry if you have already done this but it is a recurring issue.
Latest release at time of writing is v4.3.3, with another new release imminent.
Download:
https://github.com/nodogsplash/nodogsplash/releases/tag/v4.3.3

I will make further replies here and try to guide you through the documentation, so you get a better understanding.

I do not know RaspAP, but I have had a quick look at their github and web page.

**Comment by bluewavenet** [comment]
@catsdgs 
Documentation. Apologies if you are aware of the following. The typical Rpi user is a hobbyist and trying to use NDS will be their first attempt at "networking". Unfortunately, most of the online Rpi tutorials are at best very outdated, at worst, very imprecise , leading to much confusion.

The best place to start with NDS is:
https://nodogsplashdocs.readthedocs.io/en/stable/howitworks.html

The first important point of note is that NDS **must** be installed on a router.

> A router, by definition, will have two or more interfaces, at least one to connect to the wide area network (WAN) or Internet feed, and at least one connecting to the local area network (LAN).
> 
> Each LAN interface must also act as the Default IP Gateway for its LAN, ideally with the interface serving IP addresses to client devices using DHCP.

It is worth noting the terminology used in the RPi world is not necessarily the same as that used in the data networking world. This very often causes considerable confusion.
An Access Point (AP) is usually considered as a bridge device between a local area network feed and a wireless radio. Typically an AP will have its (often single) ethernet port connected to a lan port of a router. The AP ethernet is bridged at layer 2 to the wireless radio making the wireless interface an extension of the local area network.
NDS cannot work on an AP as it requires layer 3 routing, specifically IPv4 routing with NAT, on the device it is running on.

**Comment by bluewavenet** [comment]
@catsdgs 
The client CPD is probably the most important aspect of how a Captive Portal (CP) works.
CPD is a de-facto standard, supported by just about all vendors, operating systems and browsers. It is what triggers the "pop up" login page of a CP. It enforces aspects of security that help to prevent "spoofing" and "capture" attacks in a public WiFi environment. The most important aspects to note are:
 * File downloads are prohibited
 * Execution of javascript is prohibited

https://nodogsplashdocs.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

**Comment by bluewavenet** [comment]
@catsdgs 
NDS has the built in ability to forward requests to a third party authentication service.
No whitelisting is required, NDS automatically handles all aspects of the local firewall configuration.

https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

**Comment by catsdgs** [comment]
_Nodogsplash is working great for me on my raspberry pi as an access point already..._ I have worked with this stuff before. I just thought that getting out my old raspberry pi and try to do this would be fun. I have already had my raspberry pi as a hotspot with nodogsplash working fine for a while, with just a simple "agree to these terms, click to continue" page. _All I ask_ is how can I allow the existing splash page hosted on the pi to access an external website just to post a nice form, so I can gather data about my Wi-Fi users. All it would do would allow a user to enter other details and then click the continue button. There wouldn't be any authentication. Like I have said, I have got everything working except for this form on the pi, but on my local server, everything works fine. I also do need something portable and simple (not "overkill") so I will stick with a raspberry pi. Also, why would I need the current release? I would think that this would be an easy thing to be done. Also, every device that I have tried this portal on allows JavaScript fine. Most captive portals today use it. Aeroplane captive portals, like GoGoInFlight have to connect to many external websites to access information and use many different forms for payment, but are locally stored on the plane because aeroplane internet is very slow. All I'm saying is that allowing an external website should be pretty easy to do, and I will go with other portal options if I have to.

**Comment by catsdgs** [comment]
```
FirewallRuleSet preauthenticated-users {
# For preauthenticated users to resolve IP addresses in their
# initial request not using the router itself as a DNS server.
# Leave commented to help prevent DNS tunnelling
# FirewallRule allow tcp port 53  
# FirewallRule allow udp port 53
#
# For splash page content not hosted on the router, you
# will want to allow port 80 tcp to the remote host here.
# Doing so circumvents the usual capture and redirect of
# any port 80 request to this remote host.
# Note that the remote host's numerical IP address must be known
# and used here.  
   FirewallRule allow tcp port 443 to 138.197.131.106
   FirewallRule allow tcp port 80 to 138.197.131.106
}
# end FirewallRuleSet `preauthenticated-users
```
This is my code on nodogsplash.conf to try to allow ips

**Comment by catsdgs** [comment]
And my ndsctl status says I am using version 4.3.4beta

**Comment by bluewavenet** [comment]
@catsdgs
It is not NDS that blocks javascript but the client CPD.
Most up to date mobile CPD implementations use a specially cut down browser. Any script element with a src attribute will be ignored along with many script elements containing code.
This is done for security reasons. It is not yet universal but is slowly being rolled out with upgrades. 

**Getting NDS to redirect to a web page on a remote server is very simple.**

It is done by setting the following options in nodogsplash.conf:

> fasport [port] (the port number of the remote FAS server)
> faspath [path] (the path from the FAS Web Root to the FAS login page)
> fasremoteip [ip address] (the ip address of the remote FAS server)

and optionally:

> fasremotefqdn [fqdn] (optional, the fqdn of the remote FAS server)
> fas_secure_enabled [level] (optional,the security level, 0,1 or 2, default 1)
> faskey [pre-shared key] (optional, not required for fas_secure_enabled 1 or 2)
> 

**No whitelisting is required.**

An example FAS is included (fas-aes.php), written in php but can be any language.
This is a very simple example, requiring client users to enter a name and email address.
The entered data is stored in a log file.
Full details can be found in the documentation.

Javascript can be supported in captive portals by ensuring script execution is done server side, usually with something like node.js

Version 4.3.4beta is Github master snapshot and will change with every commit, so use at your own discretion. The current release at time of writing is v4.3.3

**Comment by catsdgs** [comment]
But I don't need to redirect to a remote website. I'm sorry, but please read over all of my responses as you don't seem to understand what I am trying to do.

>  _All I ask_ is how can I allow the **existing** splash page **hosted on the pi** to access an external website **just to post a nice form**, so I can gather data about my Wi-Fi users. All it would do would allow a user to enter other details and then click the continue button. There wouldn't be any authentication.

Right now, when I use a web console to view errors about the splash page, I get a 403 error that the request to 138.197.131.106 couldn't go through, which would be expected on a captive portal system. I want to allow this HTTP POST request to go through. I just want to allow this IP for preauthenticated users, so my form could submit. I don't need FAS, as I am not going to a remote website. The form is a simple html form on the existing splash.html. I am really sorry that I might've not explained this well enough.

>  The form is sent through a post method and looks something like this: `<form action="https://usebasin.com/f/myendpoint" method="POST" id='myform'>`,

**Comment by catsdgs** [comment]
```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="shortcut icon" href="/images/splash.jpg" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="/splash.css">

<title>$gatewayname Captive Portal.</title>

<!--
Content:
	Nodogsplash (NDS), by default, serves this splash page (splash.html)
	when a client device Captive Portal Detection (CPD) process
	attempts to send a port 80 request to the Internet.
	You may either embed css in this file or use a separate .css file
	in the same directory as this file, as demonstrated here.
	It should be noted when designing a custom splash page
	that for security reasons many CPD implementations:
		Immediately close the browser when the client has authenticated.
		Prohibit the use of href links.
		Prohibit downloading of external files
			(including .css and .js).
		Prohibit the execution of javascript.
Authentication:
	A client is authenticated on submitting an HTTP form, method=get,
	passing $authaction, $tok and $redir.
	It is also possible to authenticate using an href link to
	$authtarget but be aware that many device Captive Portal Detection
	processes prohibit href links, so this method may not work with
	all client devices.
Available variables:
	error_msg: $error_msg
	gatewayname: $gatewayname
	tok: $tok
	redir: $redir
	authaction: $authaction
	denyaction: $denyaction
	authtarget: $authtarget
	clientip: $clientip
	clientmac: $clientmac
	clientupload: $clientupload
	clientdownload: $clientdownload
	gatewaymac: $gatewaymac
	nclients: $nclients
	maxclients: $maxclients
	uptime: $uptime
Additional Variables that can be passed back via the HTTP get,
or appended to the query string of the authtarget link:
	username
	password
-->

</head>

<body>
<div class="offset">
<med-blue>$gatewayname Captive Portal.</med-blue>
<div class="insert">
<img style="height:60px; width:60px; float:left;" src="/images/splash.jpg" alt="Splash Page: For access to the Internet.">
<big-red>Welcome! Please fill out this form so we can get to know you!</big-red>
<form action="http://138.197.131.106/f/myendpoint" method="POST">

<label for="name">Name</label>

<input type="text" id="name" name="name" required>

<label for="email-address">Email Address</label>

<input type="email" id="email" name="email" required>

<button type="submit">Submit</button>

</form>
<hr>
<br>
<italic-black>For access to the Internet, please tap or click Continue.</italic-black>
<br><br>
<hr>

<form method="get" action="$authaction">
<input type="hidden" name="tok" value="$tok">
<input type="hidden" name="redir" value="$redir">
<input type="submit" value="Continue">
</form>

<hr>
<copy-right>Copyright &copy; The Nodogsplash Contributors 2004-2019.<br>This software is released under the GNU GPL license.</copy-right>

</div></div>
</body>
</html>
This is a very simple "simulation" of what my splash.html page looks like.
```

**Comment by bluewavenet** [comment]
`http://138.197.131.106` does an immediate 301 redirect to:
`https://138.197.131.106` but that has an invalid security certificate

**Comment by catsdgs** [comment]
Yes I am aware of that. The form works fine through a usual website. The regular URL would be
`<form action="http://usebasin.com/f/myendpoint" method="POST">`
But I thought I couldn't use that because it would require DNS.

**Comment by bluewavenet** [comment]
What happens when you put in the second one? ie:
<form action="https://usebasin.com/f/myendpoint" method="POST">

**Comment by catsdgs** [comment]
The form doesn't submit. I get no submissions. Unable to connect.

**Comment by bluewavenet** [comment]
Edit a couple of lines in fas-aes, upload somewhere, job done. ;-)

**Comment by catsdgs** [comment]
Can you help me with this? What do I have to edit?

**Comment by bluewavenet** [comment]
**Back to your original questions for the moment:**
Your firewall rule set entries should work. I use OpenWrt and don't have an issue, perhaps your OS version is showing an problem with iptables?
Once your client has connected and the splash page has appeared, can you browse to https://usebasin.com  ?
I don't have time to look at this right now and anyway do not have a non-OpenWrt setup to test on. I will have to come back to this later.

**You can however very easily test with FAS**
FAS uses iptables in its setup, so trying will **at least test basic functionality of the firewall** settings.
You can very simply test your installation/os combo by enabling login option in the config file.

But first I would suggest that if possible you **re-download v4.3.4beta source and recompile** as there have been almost daily commits over the last few days.

**NDS has a fully functional login page built in and pre-configured.** It is a special case of FAS. It asks client users to enter their name and email address, then logs the details before presenting the "Continue" button.
This is not exactly what you have been trying to do and runs 100% locally, but if it works on your OS it is a step in the right direction. If local logs are not an issue, changing the form is a simple task.
The advantage of using this would be that you would not have any usebasin hosting fees :-D
If you require centralised Internet based storage of form data **AND** already have Internet web hosting for other purposes, fas-aes would be almost as simple to set up as the built in login option.

To enable the login option, edit nodogsplash.conf login option line to read:
`login_option_enabled 1 `
Save and restart NDS.
If all is well it will create its log file in /tmp

**Comment by catsdgs** [comment]
I get redirected to the splash page when I attempt to load https://usebasin.com. I will try other things.

**Comment by bluewavenet** [comment]
@catsdgs 
In case there is an issue with NDS on your operating system, you should try the login option as this, if it works, will eliminate any interaction issues between the OS and NDS.

As I mentioned above, this is very simple.

> To enable the login option, edit nodogsplash.conf login option line to read:
> login_option_enabled 1
> Save and restart NDS.
> If all is well it will create its log file in /tmp
