### ISSUE TITLE
[QUESTION] Allow one domain before user go through auth

### ISSUE THREAD

**Issue by famousky** [nodogsplash/nodogsplash#49]
So I want to be able to use an API from one domain to perform some tasks before user click the button on my gateway page. To do so, I need to enable this domain so nodogsplash by default doesn't block it.

Where in config file I can do it?

**Comment by mwarning** [comment]
You cannot really allow a domain by name (unless you use advanced trickery..), maybe unblocking a specific IP does help?

    FirewallRuleSet: preauthenticated-users {
      FirewallRule allow to 1.2.3.4
    }

**Comment by famousky** [comment]
@mwarning yeah I know this one, will give it a try :)

**Comment by famousky** [comment]
@mwarning I tried this, but it doesn't work (I am sure I put correct IP of the site).

Also - is possible to set FirewallRule allow *from* 1.2.3.4 to for example allow callback back from the server?
