### ISSUE TITLE
using nodogsplash with various APs

### ISSUE THREAD

**Issue by schweini** [nodogsplash/nodogsplash#495]
As far as I could see, the docs (and Google) don't really indicate if it is possible to have various APs (with the same SSID) running OpenWRT with NoDogSplash, using a centralized authentication server.

Or would I have to route the AP's traffic to a central host, and tun NoDogSplash there?

**Comment by bluewavenet** [comment]
@schweini 
Your question is somewhat ambiguous.
First, for clarity and to prevent any confusion, here are some definitions:

 * Access Point (AP) - a device that provides a layer 2 bridge between a wireless network to a local area network.
 * Router - a device that forwards data packets at layer 3 between two or more independent networks
 * Wireless Router - a Router and AP combined into one device

Captive portals run at layer 3 on a router device and interact with the client captive portal detection (CPD) that runs on the connecting client device.

From these definitions, you can see that:
 1. You can have an unlimited number of APs on a single LAN managed by NDS, with NDS running on the default gateway router of the LAN.

 2. You could also have an unlimited number of LANs, each with its own router in turn running its own copy of NDS.

To tie this all together, NDS fully supports a "centralised login" using its built in FAS functionality.

Can you describe more about what you are trying to achieve?

**Comment by schweini** [comment]
Thanks for your answer!

I am basically looking for a captive portal solution for a small shopping
center which would require multiple wireless access points in order to
cover the whole premises.

I would like to use sheepish wireless APs/Routers for that, and add
APs/Routers as necessary.

If I understood correctly, the usual approach is to have NDS running on the
(OpenWRT) router and do it's iptables magic there on the spot - which I
figure can't be coordinated between differente APs/Routers.

So I am guessing that I would have to run my Wifi equipment in AP mode, and
have NDS running on some centralized (Raspberry Pi like?) default gateway.
The APs would have to have dedicated cabling to the controller, or at the
very least be in one VLAN (in order to separate the NDS DHCP traffic from
the regular network, I guess).
That controller would have to have to be able to 'see' the MAC addresses of
the Wifi clients.

It's just from what I can see, there's precious little documentation on
this configuration available.

Also, I think it should be possible to have the AP/Router link up the
controller via OpenVPN and bridge the Wifi connection in a manner that
forwards ARP/MAC traffic to the controller. This would allow me to use
shared, non VLAN-ed cabling to the APs, I guess?

**Comment by bluewavenet** [comment]
@schweini 
You are over thinking this and making it very complicated.
It might be useful to read the up to date documentation at:
https://nodogsplashdocs.readthedocs.io

Also take note of the comments I made:
 1.  You can have an unlimited number of APs on a single LAN managed by NDS, with NDS running on the default gateway router of the LAN.

 2.  You could also have an unlimited number of LANs, each with its own router in turn running its own copy of NDS.

To tie this all together, NDS fully supports a "centralised login" using its built in FAS functionality.

Questions, not in any particular order:
Does each shop have an Internet feed?
Does each shop want a customised login?
What is the existing infrastructure if any?
What is the "regular" network?
What is a "sheepish" AP/router?

**Comment by schweini** [comment]
> Does each shop have an Internet feed?
Not really. I was planning on using one big internet connection for the public spaces - although using multiple ones might be advantageous, but I am guessing this would complicate things a lot.

> What is the existing infrastructure if any?
That's my main issue - there is chaotic unordered ethernet cabling without VLAN tagging. The current network is running multiple IP networks, separated just by statically assigned IPs. So having NDS's DHCP server on there might be an issue. Hence encapsulating the traffic between the APs/Routers and the NDS control box in a rudimentary VPN might be a solution which would also definitely prohibit access to the business network from the public one.

> What is a "sheepish" AP/router?
Not defined yet, but I was hoping on being able to use the the cheapest available COTS routers/APs in AP mode, or - if a VPN backhaul is necessary - some basic OpenWRT capable WIFI routers. An awesome solution, if possible, would be to have the AP/Routers running in extender mode, and using wireless backhaul - but the performance impact might be too much.

**Comment by bluewavenet** [comment]
@schweini 
If it is for the public areas with no customisation for each shop then it is very easy.
Forget the problematic existing infrastructure and use a simple 802.11s mesh to provide your own wireless infrastructure.
Performance is fine for this sort of venue. People want to use social media, get emails and browse. An average of ~100Mb/s throughput is readily achievable.
I have implemented pretty much the same on numerous occasions using gl-inet ar300m-ext mini routers, one configured as a wireless router running NDS and mesh, the others configured as wireless access points/mesh node (ie a mesh gateway)
The number of mesh gateways needed depends on the coverage required.

**Comment by bluewavenet** [comment]
@schweini 
This is more of a network infrastructure design issue so closing this issue.
Feel free to ask any questions on the subject though!
