### ISSUE TITLE
CPB asking for password even with NoDogSplash Running

### ISSUE THREAD

**Issue by sojastar** [nodogsplash/nodogsplash#496]
I have just compiled and installed NoDogSplash on a Raspberry PI 4 (Raspbian Buster 09/19) configured as an access point. My only modification to the nodogsplash.conf file was to change the `GatewayInterface `to `wlan0`. When trying to connect to the PI with my iPhone, I get the regular iOS password request modal window.

Here is the output of `ndsctl status`:

```
==================
NoDogSplash Status
====
Version: 4.4.0
Uptime: 5m 56s
Gateway Name: NoDogSplash
Managed interface: wlan0
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.4.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Disabled
Client Check Interval: 30s
Preauth Idle Timeout: 10m
Auth Idle Timeout: 120m
Traffic control: no
Total download: 18 kByte; avg: 0.41 kbit/s
Total upload: 64 kByte; avg: 1.45 kbit/s
====
Client authentications since start: 0
Current clients: 1

Client 0
  IP: 192.168.4.2 MAC: 5c:f9:38:a2:07:4a
  Last Activity: Sun Jan 12 20:16:13 2020 (26s ago)
  Session Start: -
  Session End:   -
  Token: a4fea82f
  State: Preauthenticated
  Download: 0 kByte; avg: 0.00 kbit/s
  Upload:   0 kByte; avg: 0.00 kbit/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========
```

And the output of `systemctl status nodosplash`:
```
● nodogsplash.service - NoDogSplash Captive Portal
   Loaded: loaded (/lib/systemd/system/nodogsplash.service; disabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-01-12 20:10:43 GMT; 8min ago
  Process: 5496 ExecStart=/usr/bin/nodogsplash $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 5497 (nodogsplash)
    Tasks: 4 (limit: 4915)
   Memory: 2.0M
   CGroup: /system.slice/nodogsplash.service
           └─5497 /usr/bin/nodogsplash

Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 22: [: -url: unexpected operator
Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 17: [: -url: unexpected operator
Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 22: [: -url: unexpected operator
Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 22: [: -url: unexpected operator
Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 17: [: -url: unexpected operator
Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 22: [: -url: unexpected operator
Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 22: [: -url: unexpected operator
Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 17: [: -url: unexpected operator
Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 22: [: -url: unexpected operator
Jan 12 20:17:13 weavers nodogsplash[5496]: /usr/lib/nodogsplash/./unescape.sh: 22: [: -url: unexpected operator
```

I have no clue as how to investigate this `unexpected operator` error. Any help would be greatly appreciated.

**Comment by bluewavenet** [comment]
@sojastar 
You must configure your rpi as a wireless router, not an access point, and you must have a live Internet feed for NDS to work.
What do you mean by "regular iOS password request"? Have you set up secure wifi?

**Comment by bluewavenet** [comment]
@sojastar 
the `unexpected operator` error might be an incompatibility between the default shell on OpenWrt and that on Rasbian.
I can get you to do a few tests, and if it is the problem we can fix it ;-)

**Comment by sojastar** [comment]
@bluewavenet 

Thank you for the ever super fast answers.

As you have noticed, the main reason for this issue is very certainly my own ignorance. I'll try and configure my PI as a router rather than an access point and come back to you. I'll then be most happy to run any test you ask me too.

Thanks again !

**Comment by bluewavenet** [comment]
Not so much ignorance, more a desire for knowledge. Keep going!

**Comment by bluewavenet** [comment]
@sojastar 
Try the following command:
`sudo /usr/lib/nodogsplash/./unescape.sh -url %24%25%26%0a`
This should return `$%&`

If you get the "unexpected operator error, run the following command:
`sudo sed -i 's/#!\/bin\/sh/#!\/bin\/bash/' /usr/lib/nodogsplash/unescape.sh`

followed by
`sudo /usr/lib/nodogsplash/./unescape.sh -url %24%25%26%0a` again.
Now do you get `$%&` ?

**Comment by bluewavenet** [comment]
@sojastar 
This is a bug on Debian based OSs
#500 describes the problem. Appears to be fixed by the above sed commands.
Apply also to: 

- get_client_interface.sh
- login.sh
- get_client_token
