### ISSUE TITLE
No such file or directory, unless running with -d2 or -d3

### ISSUE THREAD

**Issue by frnhr** [nodogsplash/nodogsplash#498]
I have installed nodogsplash on a brand new Raspbian Buster (`git clone`, `make` and `sudo make install`). With all the default setting, this does not work:

```
$ sudo nodogsplash
[5][...date...](src/main.c:267) Detected gateway blah blah...
[3][...date...](src/main.c:278) Could not create web server: No such file or directory
```

Running with `sudo nodogsplash -d2` or `sudo nodogsplash -d3` works fine.

Options I have tried that didn't make any difference:
 *  `-c /etc/nodogsplash/nodogsplash.conf`
 * `-s`
 * `-f`

I have also tried to manually create a log file at `/tmp/ndslog.log`, but that didn't have an effect either.

Strange that verbosity level can cause a crash 😕 or am I doing something wrong?

**Comment by bluewavenet** [comment]
Caused by unescape.sh not being posix compliant see #500

**Comment by frnhr** [comment]
@bluewavenet I have checked `debian-testing` on Raspberry Pi and still getting the same behaviour. 

Looks like this issue is not related to, or at least not resolved by, the changes to shebang line.

**Comment by frnhr** [comment]
@bluewavenet After your comment in PR https://github.com/nodogsplash/nodogsplash/pull/500#issuecomment-575936787 and after testing again on Raspbian using `debian-testing` branch, this issue remains unresolved.

I believe this issue is unrelated to `unescape.sh` because when I run nodogsplash with `-d2` option, I see logs that come from this script and those look ok, AFAICT:

<img width="1506" alt="fran_—_pi_maxnet____—_ssh_pi_192_168_0_108_—_201×54" src="https://user-images.githubusercontent.com/1173748/72685000-e9a44480-3ae5-11ea-9cd5-6d2990af44db.png">

**Comment by bluewavenet** [comment]
@frnhr 
The proper way to start NDS is:
`systemctl start nodogsplash.service`

What happens if you try this?

**Comment by frnhr** [comment]
Huh! 🤔 

I have installed it with `sudo make install`, as mentioned in the docs: https://nodogsplashdocs.readthedocs.io/en/stable/compile.html#linux-unix 
so I don't have it installed as a service:
```
$ sudo systemctl status nodogsplash
Unit nodogsplash.service could not be found.
$ sudo systemctl list-units | grep nodogsplash
$ # nothing
```

If I make a deb package and install that, then I do get a service, and it runs ok.

I actually don't need it running as a service, it is a very niche usage for a CP... Any downsides to running it from `/usr/bin` directly? Other then needing to set `-d2`, seems to work just fine in both cases.

**Comment by bluewavenet** [comment]
@frnhr 
The Debian support was set up a few years ago and there have been huge changes since and it has hardly been looked at. There must be something wrong with the command line code. It must only be used rarely, if ever (until now!). The debug level code was rehashed last year around about the time of the release of v4.0.0, but this has gone unnoticed until now.... I'll take a look.

**Comment by bluewavenet** [comment]
@frnhr 
Have you tried -d 1 (note the space - not -d1)?

**Comment by bluewavenet** [comment]
@frnhr 
What is the full command line you are using?

**Comment by bluewavenet** [comment]
@frnhr 
What is the full command line you are using?

**Comment by frnhr** [comment]
Looks like the space makes no difference: 

<img width="1137" alt="IMG_1321_JPG" src="https://user-images.githubusercontent.com/1173748/72751119-f8125f00-3bbe-11ea-9c1f-f209cbeb4d0f.png">

The exact command is simply `sudo nodogsplash -f`. Or, to make it work now, I'm using `sudo nodogsplash -f -d2`.
I have tried many variations of available options (see issue description above) with no effect.

An additional thing to note is that the output is shown in the terminal even without `-f`, which is not ideal, but probably a separate issue.

**Comment by bluewavenet** [comment]
@frnhr 
After the last couple of commits, the error:

> (src/main.c:278) Could not create web server: No such file or directory

should only be generated by NDS if the file unescape.sh is missing.

Can you check if it is there in /usr/lib/nodogsplash and that it is executable?

Have you recompiled based on the latest in master?

Having to set the debuglevel to make it work does not make sense.
But it works just fine if you make a deb package and install that....

**Comment by frnhr** [comment]
@bluewavenet if you have 6.5 mins I made a screencast showing the entire process, from burning the SD card up to running `nodogsplash` and hitting this issue. Some parts are sped up but every single command typed into the Pi is visible (except for enabling SSH).

Also showing the `unescape.sh` working fine.

https://youtu.be/97XT15Jj4VM

**Comment by bluewavenet** [comment]
@frnhr 
That is excellent thankyou.
Could you write some instructions for setting the locale, this can then go in the documentation.

It is very odd that none of these problems occur if you make the .deb package and install that.

I don't understand why you do not want to run NDS as a service, it is intended to be run in that way and I only see disadvantages in not doing so. I was just wondering why.... ;-)

**Comment by frnhr** [comment]
Note: Setting the locale didn't seem to have any effect.

I used `raspi-config` tool to set the locale. There are other ways too, but again, that didn't seem to change anything.

**Comment by frnhr** [comment]
Re why not a service, I have a niche application where NDS will only run about once a year for a few minutes. So I don't want it running all the time taking up resources, and also it is a bit simpler to start and stop a process from other code then is it a service. Marginally, thought. I _could_ have it as a disabled service and enable it when needed, but running with `-d2` also works just fine for me.

I opened this issue because that looked like a bug to me. I read the code quickly and I have no idea what could be the cause, but it's definitely happening. Plus, it is currently a documented way of running NDS.

**Comment by bluewavenet** [comment]
@frnhr 
I agree, it must be a bug somewhere but I can't see anything in the code either. It is something very subtle and only shows if installed with make install. I can't see how the debug level setting comes into it!
Perhaps this way of running should be removed from the documentation until the problem is identified and fixed.

**Comment by bluewavenet** [comment]
@frnhr 
I think @skra72 has found the problem ;-)
See #510

**Comment by bluewavenet** [comment]
@frnhr 
PR #511 implements the fix, I hope!

**Comment by frnhr** [comment]
It does! 🎉 

Now it works both on Raspbian Buster and Raspbian Stretch (on Stretch my little workaround of adding `-d2` wasn't working).

**Comment by bluewavenet** [comment]
@frnhr 
Excellent. Thanks for testing :-D
