### ISSUE TITLE
Forwarding wlan0 traffic to apache server ip (iptables)

### ISSUE THREAD

**Issue by sm88sm88** [nodogsplash/nodogsplash#501]
I want to forward all traffic from the interface wlan0 (which some devices are connected to hotsapd access point) to my apache server index.html so that it will be like a captive portal. What are the rules that I should add to iptables to do that?

**Comment by bluewavenet** [comment]
@sm88sm88 
The way to do this is built into NDS, no adding of rules is required.
You can read full details in the documentation:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

Executive summary :-D
This is achieved by adding just a few simple options to the configuration file.

If you would like help (after you have read the docs!), let me know the details of your hardware, operating system and if the apache server is on the same hardware, on the local network or on the Internet.

**Comment by sm88sm88** [comment]
thanks for your replay
I am using raspberry pi 4 and I have shared a hotsapd access point and also I have apache server on raspberry my /etc/nodogsplash/nodogsplash.conf has the following construction:
```
GatewayInterface wlan0
GatewayAddress 192.168.220.1
MaxClients 250
AuthIdleTimeout 480
```
and when I am running the  nodogsplash ( sudo ./nodogsplash) and connect to the access point it is not forwarding any track it is showing that there is no internet connection

**Comment by bluewavenet** [comment]
@sm88sm88 

You do not say which operating system you are using. This is important.

From the documentation:

> NoDogSplash MUST run on a device configured as an IPv4 router.
> 
> A wireless router will typically be running OpenWrt or some other Linux distribution.
> 
> A router, by definition, will have two or more interfaces, at least one to connect to the wide area network (WAN) or Internet feed, and at least one connecting to the local area network (LAN).
> 
> Each LAN interface must also act as the Default IP Gateway for its LAN, ideally with the interface serving IP addresses to client devices using DHCP.

Can you confirm your Rpi is configured in this way and if so, 
 1. what is the IPv4 subnet and DHCP address range for the Rpi LAN, and 
 2. what is the IPv4 address your WAN interface receives from the Rpi's WAN network?

**Comment by sm88sm88** [comment]
my operating system is the raspberry linux OS I have downloaded from the official RP website.
IPv4 address is :
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.178.26/24 brd 192.168.178.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 192.168.220.1/24 brd 192.168.220.255 scope global noprefixroute wlan0
       valid_lft forever preferred_lft forever
`
and DHCP config file is empty.



I am trying to forward the client whos connecting to the hotsapd Access Point to the apache server ip .

**Comment by bluewavenet** [comment]
@sm88sm88 
What version of NDS are you running?

A quick test to see if your Rpi is working as a router - with NDS not started, can a client connect to the wifi and get an ip from dhcp in the 192.168.220.x range, then access the Internet via the 192.168.178.x network (presumably your ISP's router's local network)?
