### ISSUE TITLE
Making splash_sitewide.html more dynamic when using BinAuth

### ISSUE THREAD

**Issue by nairobiny** [nodogsplash/nodogsplash#507]
I've successfully set up nodogsplash to use a modified version of the splash_sitewide.html file along with my own BinAuth script. My modified splash_sitewide.html asks only for a password, not a username. If the password is entered correctly, nds gives access. However, if the password is entered incorrectly, the user is re-presented with a brand new splash_sitewide.html. This isn't great from a user perspective, as it doesn't tell them they entered the wrong password or, for example, tell them how many times they've got it wrong.

Of course, this sort of thing would be trivial with javascript, but we're warned that js might not work with captive portal detection.

So is there a way to make splash_sitewide.html more dynamic without js? 

[As a matter of fact, on all the devices I have tested javascript **does** work, so we can use the referring page to deduce whether we're being served splash_sitewide.html for the first time]

**Comment by bluewavenet** [comment]
@nairobiny 
BinAuth is intended as a post-authentication-request process and has no control over the static html served.

If you want a dynamic splash page you should use FAS in one form or another.

A quick way to see how this works is to enable the pre-installed login script.
https://nodogsplashdocs.readthedocs.io/en/stable/preauth.html#selecting-pre-installed-username-email-login-script-v4-3-0-onwards

This is a PreAuth script and is a special case of FAS that uses the NDS built in web server library. You should disable your current Binauth when enabling this as BinAuth can be enabled at the same time.

This PreAuth script asks for username and email address and does not do any verification, but it is a trivial task to edit the file for username/password or indeed just password with verification.
It is very simple to set up a back and fourth dialogue between the script and the client before locking out or allowing access.

**Comment by bluewavenet** [comment]
@nairobiny 
**_With respect to javascript, it is the safest strategy to not use any at all._** Many device CPDs have javascript disabled, others will run limited js scripts but it varies from vendor to vendor. Some laptop/desktop operating systems/versions run the system default browser, so you get whatever is allowed by that browser. Some older OSs do not have a CPD at all and you have to manually browse to an http:// web site to get the splash page.

**Comment by nairobiny** [comment]
> 
> 
> @nairobiny
> BinAuth is intended as a post-authentication-request process and has no control over the static html served.
> 
> If you want a dynamic splash page you should use FAS in one form or another.
> 
> A quick way to see how this works is to enable the pre-installed login script.
> https://nodogsplashdocs.readthedocs.io/en/stable/preauth.html#selecting-pre-installed-username-email-login-script-v4-3-0-onwards
> 
> This is a PreAuth script and is a special case of FAS that uses the NDS built in web server library. You should disable your current Binauth when enabling this as BinAuth can be enabled at the same time.

That's exactly what I was looking for. Thank you.
