### ISSUE TITLE
Ubiquiti ERX .deb package

### ISSUE THREAD

**Issue by klinutzu** [nodogsplash/nodogsplash#508]
hello, i want to use nodogsplash on ubiquiti edgerouter x. found on net 1.3.deb package, but seems not working. can you help me with a newer package or with instructions how to cook it? regards.

**Comment by bluewavenet** [comment]
@klinutzu 
Unless you have an overriding requirement for Debian, I would suggest you use OpenWrt instead as the Ubiquiti ERX is very well supported there.
https://openwrt.org/toh/ubiquiti/ubiquiti_edgerouter_x_er-x_ka
https://downloads.openwrt.org/releases/19.07.0/targets/ramips/mt7621/

and the latest stable release of NDS:
https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/routing/nodogsplash_4.4.0-1_mipsel_24kc.ipk

If you absolutely do require a .deb package you will need a cross compiler for mipsel_24kc. I do not have any experience with this so cannot help.

**Comment by klinutzu** [comment]
thx a lot, i will try it to compile the package. till then i already installed the openwrt package from the package list as the one that you provided give me install errors about the installed dependencies.

**Comment by bluewavenet** [comment]
@klinutzu 
First, you will have to install the OpenWrt Operating system.

Then install the NDS package for OpenWrt.
 1. Copy the downloaded NDS package to /tmp
 2. run the command `opkg update` (so dependencies can be found)
 3. run the command `opkg install /tmp/nodogsplash_4.4.0-1_mipsel_24kc.ipk`

**Comment by klinutzu** [comment]
root@OpenWrt:~# opkg install nodogsplash_4.4.0-1_mips_24kc.ipk
Unknown package 'nodogsplash'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for nodogsplash found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package nodogsplash.

**Comment by klinutzu** [comment]
openwrt 19.06

**Comment by bluewavenet** [comment]
@klinutzu 
I guess you realised already as you have asked another question in a new issue, but you have the wrong .ipk
You had:

    nodogsplash_4.4.0-1_mips_24kc.ipk

but it should be:

    nodogsplash_4.4.0-1_mipsel_24kc.ipk
