### ISSUE TITLE
Setting up FAS - Could not create web server: Invalid argument

### ISSUE THREAD

**Issue by klinutzu** [nodogsplash/nodogsplash#509]
hi all,

finally i got a nodogsplash captive portal on my edgerouter x with https. it works great with internal splash page. tried to make a captive portal with an external FAS without user/pass or something else, just an accept tos button. NDS send to external server info, the mobile device receive landing page (it works as desired), but i don't know how to serve back to NDS the string from FAS. tried to use https://mydomain.com/nodogsplash_auth in the action form, but received an unknown page. what should i put there to make the user as authenticated?

i mention that tried wan-ip:2050, lan-ip:2050, hostname:2050.

on wan-ip or lan-ip i get a new unsecured page which told me if i want to use this wifi network i need to connect to it. if i press connect the landing page appear again and again.

on hostname i get "The requested URL /nodogsplash_auth/?tok=3eeebabe&redir=http%3A%2F%2Fwww.msftconnecttest.com%2Fredirect was not found on this server."

**Comment by klinutzu** [comment]
great... :( 

upgraded to 4.4 and now can't start the server:

 daemon.err nodogsplash[1827]: Could not create web server: Invalid argument

**Comment by bluewavenet** [comment]
@klinutzu 
Not a stupid question, you are trying to learn how it works!

It is probably worth reading the full NDS documentation:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html
It is not perfect and I intend to do some updates shortly but it will give you a good basis.

For your specific question read:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#post-fas-processing

You will find a fully functional example FAS script on the device at:
/etc/nodogsplash/fas-aes.php

The first thing you should do is get this example working then you will get a feel for how it works.
 1. Copy the file fas-aes.php to your remote server.
 2. Add `option fasport '80'` to the config file (note https is NOT supported)
 3. Add `option fasremotefqdn 'mydomain.com'` to the config file (replacing mydomain.com with the actual fqdn)
 4. Add `option fasremoteip '46.32.240.41'` to the config file (replacing 46.32.240.41 with the actual ip address of the remote server)
 5. Add `option faspath '/nodog/fas-aes.php'` to the config file (replacing /nodog/fas-aes.php with the actual path to fas-aes.php). Note this is the path from the FAS Web Root to the FAS login page (not the file system root).
 6. Add `option faskey '1234567890'` to the config file (you can change this later but must match the value in the fas script).
 7. Add option fas_secure_enabled '2' to the config file.
 8. Make sure the Internet connection is up
 9. Run the command `opkg update` 
 10. Run the command `opkg install php7-cli`
 11. Run the command `opkg install php7-mod-openssl`
 12. Run the command `service nodogsplash restart`

Check the configuration by running `logread | grep nodogsplash`
The last few lines of the output of this should echo the config with no errors.

Finally: Try connecting a client and testing it out :D

Once you get to this stage, look at fas-aes.php and see how you would like to modify it for your own purposes.

**Comment by klinutzu** [comment]
thanks, that is exactly what i intend to do. i've tried to use an existing php file, developed by myself, but no luck.  one more thing: is somehow connected with the fact that i need to have an https portal?

**Comment by klinutzu** [comment]
factory reset, setup network, installed 4.4, changed options to met my scenario and ERROR...

daemon.err nodogsplash[4124]: Could not create web server: Invalid argument

don't understand...

**Comment by bluewavenet** [comment]
@klinutzu 
 Note: The above changes to the config file are the only changes required for it to work. Revert any changes you may have previously made.

The portal must be http. If it was https, then when a client did their final "click to continue" they would immediately be presented with a dire security error. There are nasty hacks to prevent the errors but these can be used to compromise https security. For this reason NDS blocks access to https FAS.
The correct way to do this is to have NDS poll FAS for authentication requests and I am planning to implement this in the near future... paid job free time permitting :-D

**Comment by bluewavenet** [comment]
@klinutzu 

> daemon.err nodogsplash[4124]: Could not create web server: Invalid argument

Try running:
`/usr/lib/nodogsplash/unescape.sh -url  %22%23%24`

You should get:
`"#$`

**Comment by bluewavenet** [comment]
@klinutzu 
You have NDS version 4.4.0, is that correct? (not 4.3.3 or 4.4.1beta)

**Comment by klinutzu** [comment]
strange, but with nodog from packages it works and start without errors.

https it's a must unfortunately...

**Comment by klinutzu** [comment]
version it's 4.4.0 for sure as i downloaded from your link in other post

**Comment by bluewavenet** [comment]
I have 4.4.0 running here on an ar300m, mt300N and b1300 (all gl-inet devices). I don't have an ERX any more.
What version of OpenWrt are you on?

**Comment by klinutzu** [comment]
19.07.

**Comment by bluewavenet** [comment]
@klinutzu 
As I said before, try running:
`/usr/lib/nodogsplash/unescape.sh -url %22%23%24`

You should get:
`"#$`

**Comment by bluewavenet** [comment]
@klinutzu 

> The correct way to do this [https FAS] is to have NDS poll FAS for authentication requests and I am planning to implement this in the near future... paid job free time permitting :-D

**Comment by klinutzu** [comment]
strange behavior: as i already told you, just factory reset, installed nodog 4.0.1 from the sources, install dependencies. the server where is the fas in already https and therefore your php fas-aes.php doesn't connect; can't change the server from https to http as it's a must to be like that. if i put on walled garden my ip with both 80 and 443 it connect, as the landing page appear on the mobile device. i'll try now to see if it comes something back

**Comment by klinutzu** [comment]
btw, which are user/email?

**Comment by klinutzu** [comment]
got it! entered whatever user/email aaaaaaaaand....... it works! even fas is on https AND also nodog is on a router with letsencrypt certificates!.... great job! now i have to modify fas-aes.php script to met my requirements. keep in touch!

**Comment by klinutzu** [comment]
question: if i put security level on 0 is normal to receive a "ERROR! Incomplete data passed from NDS"?

**Comment by bluewavenet** [comment]
@klinutzu 
It turned out there was a bug in NDS 4.4.0 that only sows itself on OpenWrt 19.07.0 and Raspbian and then only on some hardware. A very subtle memory corruption.
Fixed by PR #511 I'll do a new release shortly as time permits.

**Comment by bluewavenet** [comment]
@klinutzu 

> and one more EXCEPTIONAL IMPORTANT: I NEED TO USE JAVASCRIPT!!!!! also it's a must... :( how can be done this?

NDS is triggered when a client device connects. This is achieved automatically on modern devices using CPD (Captive Portal Detection). CPD is a function of the client device operating system. It has evolved over a number of years and is now an unofficial **_De-facto_** standard implemented by all vendors following loosely a set of rules. The aim is to provide automatic detection of the captive portal, yet be as secure as possible against inscrutable "operators" who might want to gain control of the client device.
These de-facto rules are as follows:

Rules for Customised Splash Pages

 * Immediately close the browser when the client has authenticated.
 * Prohibit the use of href links.
 * Prohibit downloading of external files (including .css and .js, even if they are allowed in NDS firewall settings).
 * Prohibit the execution of javascript.

Not all vendor's of CPD follow all of the rules and some allow some exceptions to the rules, but all vendors are active in evolving CPD over time with incremental changes slowly being rolled out.
If you find you can break one or more of the rules in specific cases, there is no guarantee it will continue to work.

If you find yourself needing https and javascript, for example when using the Facebook api to do authentication, then you must run that javascript on the remote FAS server using something like node.js
To describe what you must do simplistically, consider using the client CPD pop up browser to remote control a virtual browser running in FAS.
