### ISSUE TITLE
NDS cannot start web server using latest stable 4.4.0 branch

### ISSUE THREAD

**Issue by skra72** [nodogsplash/nodogsplash#510]
Using the latest stable 4.4.0 branch, I'm not able to start NDS on my Raspberry Pi anymore.

When the service starts, it exists with error

`(src/main.c:278) Could not create web server: No such file or directory`

Digging through the latest changed, I think the new MHD_OPTION_UNESCAPE_CALLBACK option added to the service start call expects two parameters instead of a single callback pointer. The libmicrohttpd documentation mentions that besides the call back pointer this option expects a "cls" pointer which will be the first parameter to the unescape callback.

Thus, if I change line 276 in main.c to:

`MHD_OPTION_UNESCAPE_CALLBACK, unescape, NULL,`

NDS starts again as expected and runs perfectly.

I would appreciate if this can be fixed. Thanks!

**Comment by capakt** [comment]
> Thus, if I change line 276 in main.c to:
> 
> `MHD_OPTION_UNESCAPE_CALLBACK, unescape, NULL,`
> 
> NDS starts again as expected and runs perfectly.

Hey there! I had the same problem and ive spent the last two hours trying to solve it.
Thank you for your comment, that seems to fix the problem.

**Comment by bluewavenet** [comment]
@skra72 
Excellent, well spotted thanks!
This was not happening on OpenWrt, at least on the hardware types I've tested it on. But that might just be luck as the missing NULL was probably causing some subtle memory corruption that only rears its head if the circumstances permit.
I have tried your change on the OpenWrt hardware with no problems. I will PR a commit.

**Comment by bluewavenet** [comment]
PR  #511 implements this. Thanks @skra72
