### ISSUE TITLE
Redirect-Error after authentication - Error 404 Not Found

### ISSUE THREAD

**Issue by Lorenz512** [nodogsplash/nodogsplash#513]
Hey guys,

I've encountered an issue when upgrading Nodogsplash from version 4.3.3 to 4.4.0.

I'm using a simple splash page with some text and a button, which users have to click to get access to the network. There is no login or any other authentication.

Until version 4.3.3 clicking the button and submitting the form worked as expected, the user was given access to the network and was redirected to the requested page.

Now on version 4.4.0, the user is not correctly redirected anymore. Instead, a 404 error appears. However, the user seems to be authenticated and can access other webpages.

I did not make any changes to my configuration.

![Screenshot from 2020-01-30 12-33-04](https://user-images.githubusercontent.com/57999645/73446407-f97d1d80-435c-11ea-8074-4e5312c15e56.png)
![Screenshot from 2020-01-30 12-29-06](https://user-images.githubusercontent.com/57999645/73446413-fc780e00-435c-11ea-8a42-a495cd8db26c.png)

Nodogsplash config: https://paste.ubuntu.com/p/QKDrH4236R/
The index.html I use: https://paste.ubuntu.com/p/7BJffjSMTj/

I'm manually starting Nodogsplash with `nodogsplash -c /somepath/nodogsplash/nodogsplash_eth1.conf -f` on Ubuntu Core 18, which basically is Ubuntu 18.04 server.

Side note: This problem still exists when building the current master.

Could someone help me figure out what's going on here? I think it's either the $authaction variable value or an internal error with .../nodogsplash_auth/ - I didn't look at the URL Nodogsplash previously redirected to after submitting the form.

Thanks, and keep up the great work you're doing here! :smiley:

**Comment by bluewavenet** [comment]
@Lorenz512 
My guess is you have probably followed an old and outdated Raspberry Pi tutorial?
Your config does not look anything like the current release config.

The up to date documentation can be found here:
http://nodogsplashdocs.readthedocs.io/

Some pointers:
 * The device NDS is running on must be configured as a NAT router
 * A router is a device that has at least two interfaces
 * One interface is dedicated to providing an internet feed and would be wan from the device firewall point of view
 * The other will be configured to provide dhcp on a private IPv4 network (a different one to the wan). This will be lan from the point of view of the device (other interfaces, such as wireless, can be bridged to this one)
 * The device firewall will provide NAT (masquerading) from lan to wan

A server grade device can of course be configured in this way, but as dedicated routers supporting OpenWrt (the primary target for NDS), can be purchased at very low cost even for high quality devices, it makes little sense to run NDS on a server.
For example, depending on requirements:
https://www.amazon.co.uk/GL-iNet-GL-MT300N-V2-Converter-Pre-installed-Performance/dp/B073TSK26W
Reflash with the latest OpenWrt, install NDS and the default Captive Portal will be running with the basic splash page.

For continuing on your Debian server, I would suggest initially trying the default config file, changing only the GatewayInterface setting and nothing else and see if that works.
v4.4.0 is known to have issues on Raspbian, so may well have issues here.
**_Debian testers welcome!_** :-D

**Comment by Lorenz512** [comment]
Thank you for your detailed and quick answer, Rob.

The configuration I'm using is my modification of the provided configuration at /etc/nodogsplash/nodogsplash.conf - it is not from any tutorial.

When manually building and installing Nodogsplash on a Debian based system, the config at /etc/nodogsplash/nodogsplash.conf is created by copying https://github.com/nodogsplash/nodogsplash/blob/master/resources/nodogsplash.conf

`make install`

> strip nodogsplash
> strip ndsctl
> mkdir -p /usr/bin/
> cp ndsctl /usr/bin/
> cp nodogsplash /usr/bin/
> mkdir -p /etc/nodogsplash/htdocs/images
> cp resources/nodogsplash.conf /etc/nodogsplash/
> cp resources/splash.html /etc/nodogsplash/htdocs/
> cp resources/splash.css /etc/nodogsplash/htdocs/
> cp resources/status.html /etc/nodogsplash/htdocs/
> cp resources/splash.jpg /etc/nodogsplash/htdocs/images/
> mkdir -p /usr/lib/nodogsplash
> cp forward_authentication_service/PreAuth/demo-preauth.sh /usr/lib/nodogsplash/login.sh
> sed -i 's/#!\/bin\/sh/#!\/bin\/bash/' /usr/lib/nodogsplash/login.sh
> cp forward_authentication_service/libs/get_client_interface.sh /usr/lib/nodogsplash/
> sed -i 's/#!\/bin\/sh/#!\/bin\/bash/' /usr/lib/nodogsplash/get_client_interface.sh
> cp forward_authentication_service/libs/get_client_token.sh /usr/lib/nodogsplash/
> sed -i 's/#!\/bin\/sh/#!\/bin\/bash/' /usr/lib/nodogsplash/get_client_token.sh
> cp forward_authentication_service/libs/unescape.sh /usr/lib/nodogsplash/
> sed -i 's/#!\/bin\/sh/#!\/bin\/bash/' /usr/lib/nodogsplash/unescape.sh
> cp forward_authentication_service/fas-aes/fas-aes.php /etc/nodogsplash/

I'm sorry if I'm getting things wrong, but if the configuration file which is created on installation is outdated, is there any other sample config, for systems which are not supporting UCI?

**Comment by bluewavenet** [comment]
@Lorenz512 
I did not mean to say you are getting things wrong, it is just a recurring theme where people do refer to old tutorials, and I was probably having a bad day when I wrote it ;-)

The latest version of nodogsplash.conf is here (but what you have actually looks ok):
https://github.com/nodogsplash/nodogsplash/blob/master/resources/nodogsplash.conf
The only line you will actually need to use for test purposes anyway, is GatewayInterface.

In firefox, on the splash page, press crtl/u to view the html.
You should see the line:
`<input type="hidden" name="redir" value="http://detectportal.firefox.com/success.txt">`

If you do see this then it should all be working.....
If not, what do you see?
It is working in this mode here on OpenWrt so not sure what is happening.

**Comment by bluewavenet** [comment]
@Lorenz512 
Closing for now, but you can still post updates here.

**Comment by Lorenz512** [comment]
Sorry for the delay, but until now, I did not find the time to get back to this issue.
I'm not quite sure what went wrong, but building the current master resolves the issue :)

**Comment by dennisroczek** [comment]
Comming back o this. I have a reason for running NoDogSplash on my local server - using Ubunutu.

I guess I found the original problem (ignore that this maschines is named timemaschine. That just another project and the unused virtual server is used for testing at the moment):


`
dennis@s-timemaschine:~/git/nodogsplash-5.0.1$ sudo make
cc  -O2 -g -Wall -Isrc -c src/auth.c -o src/auth.o
cc  -O2 -g -Wall -Isrc -c src/client_list.c -o src/client_list.o
cc  -O2 -g -Wall -Isrc -c src/commandline.c -o src/commandline.o
cc  -O2 -g -Wall -Isrc -c src/conf.c -o src/conf.o
cc  -O2 -g -Wall -Isrc -c src/debug.c -o src/debug.o
cc  -O2 -g -Wall -Isrc -c src/fw_iptables.c -o src/fw_iptables.o
cc  -O2 -g -Wall -Isrc -c src/path.c -o src/path.o
cc  -O2 -g -Wall -Isrc -c src/main.c -o src/main.o
src/main.c: In function ‘main_loop’:
src/main.c:280:49: warning: passing argument 5 of ‘MHD_start_daemon’ from incompatible pointer type [-Wincompatible-pointer-types]
  280 |                                                 libmicrohttpd_cb, NULL,
      |                                                 ^~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **) {aka int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, long unsigned int *, void **)}
In file included from src/main.c:65:
/usr/include/microhttpd.h:2701:45: note: expected ‘MHD_AccessHandlerCallback’ {aka ‘enum MHD_Result (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, long unsigned int *, void **)’} but argument is of type ‘int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)’ {aka ‘int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, long unsigned int *, void **)’}
 2701 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
cc  -O2 -g -Wall -Isrc -c src/http_microhttpd.c -o src/http_microhttpd.o
src/http_microhttpd.c: In function ‘authenticated’:
src/http_microhttpd.c:500:64: warning: passing argument 3 of ‘MHD_get_connection_values’ from incompatible pointer type [-Wincompatible-pointer-types]
  500 |         MHD_get_connection_values(connection, MHD_HEADER_KIND, get_host_value_callback, &host);
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                |
      |                                                                int (*)(void *, enum MHD_ValueKind,  const char *, const char *)
In file included from src/http_microhttpd.c:20:
/usr/include/microhttpd.h:3048:49: note: expected ‘MHD_KeyValueIterator’ {aka ‘enum MHD_Result (*)(void *, enum MHD_ValueKind,  const char *, const char *)’} but argument is of type ‘int (*)(void *, enum MHD_ValueKind,  const char *, const char *)’
 3048 |                            MHD_KeyValueIterator iterator,
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
src/http_microhttpd.c: In function ‘preauthenticated’:
src/http_microhttpd.c:602:64: warning: passing argument 3 of ‘MHD_get_connection_values’ from incompatible pointer type [-Wincompatible-pointer-types]
  602 |         MHD_get_connection_values(connection, MHD_HEADER_KIND, get_host_value_callback, &host);
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                |
      |                                                                int (*)(void *, enum MHD_ValueKind,  const char *, const char *)
In file included from src/http_microhttpd.c:20:
/usr/include/microhttpd.h:3048:49: note: expected ‘MHD_KeyValueIterator’ {aka ‘enum MHD_Result (*)(void *, enum MHD_ValueKind,  const char *, const char *)’} but argument is of type ‘int (*)(void *, enum MHD_ValueKind,  const char *, const char *)’
 3048 |                            MHD_KeyValueIterator iterator,
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
src/http_microhttpd.c: In function ‘get_query’:
src/http_microhttpd.c:783:88: warning: passing argument 3 of ‘MHD_get_connection_values’ from incompatible pointer type [-Wincompatible-pointer-types]
  783 |         element_counter = MHD_get_connection_values(connection, MHD_GET_ARGUMENT_KIND, counter_iterator, NULL);
      |                                                                                        ^~~~~~~~~~~~~~~~
      |                                                                                        |
      |                                                                                        int (*)(void *, enum MHD_ValueKind,  const char *, const char *)
In file included from src/http_microhttpd.c:20:
/usr/include/microhttpd.h:3048:49: note: expected ‘MHD_KeyValueIterator’ {aka ‘enum MHD_Result (*)(void *, enum MHD_ValueKind,  const char *, const char *)’} but argument is of type ‘int (*)(void *, enum MHD_ValueKind,  const char *, const char *)’
 3048 |                            MHD_KeyValueIterator iterator,
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
src/http_microhttpd.c:796:70: warning: passing argument 3 of ‘MHD_get_connection_values’ from incompatible pointer type [-Wincompatible-pointer-types]
  796 |         MHD_get_connection_values(connection, MHD_GET_ARGUMENT_KIND, collect_query_string, &collect_query);
      |                                                                      ^~~~~~~~~~~~~~~~~~~~
      |                                                                      |
      |                                                                      int (*)(void *, enum MHD_ValueKind,  const char *, const char *)
In file included from src/http_microhttpd.c:20:
/usr/include/microhttpd.h:3048:49: note: expected ‘MHD_KeyValueIterator’ {aka ‘enum MHD_Result (*)(void *, enum MHD_ValueKind,  const char *, const char *)’} but argument is of type ‘int (*)(void *, enum MHD_ValueKind,  const char *, const char *)’
 3048 |                            MHD_KeyValueIterator iterator,
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
cc  -O2 -g -Wall -Isrc -c src/http_microhttpd_utils.c -o src/http_microhttpd_utils.o
cc  -O2 -g -Wall -Isrc -c src/ndsctl_thread.c -o src/ndsctl_thread.o
cc  -O2 -g -Wall -Isrc -c src/safe.c -o src/safe.o
cc  -O2 -g -Wall -Isrc -c src/tc.c -o src/tc.o
cc  -O2 -g -Wall -Isrc -c src/util.c -o src/util.o
cc  -O2 -g -Wall -Isrc -c src/template.c -o src/template.o
cc -pthread -o nodogsplash src/auth.o src/client_list.o src/commandline.o src/conf.o src/debug.o src/fw_iptables.o src/path.o src/main.o src/http_microhttpd.o src/http_microhttpd_utils.o src/ndsctl_thread.o src/safe.o src/tc.o src/util.o src/template.o -lmicrohttpd
cc  -O2 -g -Wall -Isrc -c src/ndsctl.c -o src/ndsctl.o
cc -pthread -o ndsctl src/ndsctl.o -lmicrohttpd
`

Resulting in that bad html code:
<img width="717" alt="grafik" src="https://github.com/nodogsplash/nodogsplash/assets/3443013/57c0be4e-a86b-4cf7-8b47-b669cea72a97">

As you can see, I'm using the release version.

Any ideas?

**Comment by bluewavenet** [comment]
@dennisroczek 
Development of Nodogsplash stopped over 3 years ago. The compiler warnings you are getting are due to the fact that libmicrohttpd has moved forward several versions and Nodogsplash has not changed.
As far as I am aware Nodogsplash still works with the latest libmicrohttpd but can throw errors, lock up or crash.

I don't follow what you are saying about "bad html code". The html is not dynamically generated but is served from a fixed file, splash.html.

Also, the redirect after authentication will be to a CPD "canary test" url that is often a blank page of response code "204 No content". Most implementations of CPD will immediately close on authentication anyway, so do not expect to see much.

**Comment by dennisroczek** [comment]
oh, I see. That the complete development stopped wasn't clear for me. Then I will do try opennds as nodogsplash does not work for me for whatever reason. Original I really wanted some very light and small and fast system without any big req except clicking on "accept". Thanks for the really fast response.

**Comment by mwarning** [comment]
I have fixed the compiler warnings. But even so the warnings will not change the behavior of the program.

@dennisroczek  Maybe I have time to check your use case of Nodogsplash at some point. But I cannot make any promise.

**Comment by bluewavenet** [comment]
@dennisroczek 

> Original I really wanted some very light and small and fast system without any big req except clicking on "accept".

FYI: The openNDS default is "Click to Continue" and does not have any additional requirements or dependencies.
