### ISSUE TITLE
Serving clients on multiple interfaces

### ISSUE THREAD

**Issue by Lorenz512** [nodogsplash/nodogsplash#514]
Hey there!

My goal is to run Nodogsplash on a device with three network interfaces:

- eth0 internet connection
- eth1 LAN
- wlan0 LAN

The operating system is Ubuntu Core 18, which is basically Ubuntu 18.04 server.

Nodogsplash should listen for requests on eth1 and wlan0. End-Devices on both subnets should be served with the same splash page. But as far as I know, one Nodogsplash instance can only listen on one interface.

Therefore, I tried to start multiple instances, each with its own configuration file:

eth1:
configuration file: https://paste.ubuntu.com/p/TqkJVr4RMn/
starting the instance with `nodogsplash -c /somepath/nodogsplash/nodogsplash_eth1.conf -f`

wlan0:
configuration file: https://paste.ubuntu.com/p/SNrGmbKGb5/
starting the instance with `nodogsplash -c /somepath/nodogsplash/nodogsplash_wlan0.conf -f`

However, starting two Nodogsplash instances leads to the second one overwriting the first one's firewall rules.

Is there something I'm missing?

In https://github.com/nodogsplash/nodogsplash/issues/340 @mwarning refers to a configuration option called ndsctlsocket. But I could not find any documentation or other information about this option.

I really don't want to stress you, and I appreciate your work very much. Unfortunately, this problem is of great urgency and significance to me. I, therefore, highly appreciate you taking the time! :smiley: 

Should you need any further information, please let me know.

**Comment by bluewavenet** [comment]
@Lorenz512 
If you read ALL of issue #340 you will see that NDS does **_NOT_** support multiple instances.

The default configuration of NDS is to bind itself to the standard bridge interface found on routers ie br-lan
br-lan typically bridges eth0 (wired lan) and wlan0 (wireless lan).
If you wanted a different response for clients on each interface (eth0 and wlan0 in this case), you can differentiate between them in  FAS (or PreAuth).

If you need any further help, please supply:
 * Your hardware type and model
 * Your operating system and version
 * The version of NDS you are using. ( `ndsctl status` will show you )

**Comment by Lorenz512** [comment]
Ok, thank you very much for your answer!

Based on the conversation, as an outsider, I could not immediately understand that running multiple instances does not work. Your response, in combination with the release note of version 4.4.0 now makes sense. I'm sorry for the trouble I caused.

> This allows FAS response to be dynamically tailored for each client depending on their connection to the network, mitigating the problems arising due to multiple instances of NDS not being supported on a single router.

I didn't even think about bridging the interfaces and running one Nodogsplash instance listening to the bridge. Simply using a bridge fixed my issue.

Thanks again, and sorry for your troubles :)
