### ISSUE TITLE
Lots of pre-authenticated clients

### ISSUE THREAD

**Issue by 01010000101001100** [nodogsplash/nodogsplash#52]
I am looking at stats (command **ndsctl clients**) and I can clearly see that most of the people who stumble upon my hotspot, are in preauth state. Why is that?

Are they considered as "preauth" if their devices connected but did not go through the gate?
Is there a way to kick them out (command **ndsctl deauth**) if lets say they won't go through authorisation in 5min or so?

**Comment by NS-K** [comment]
You can add this to firewall.c

else if (added_time +  (config->checkinterval * 5 <= now && cp1->fw_connection_state == FW_MARK_PREAUTHENTICATED ) {
				client_list_delete(cp1);
			}

**Comment by famousky** [comment]
@NS-K where is file **firewall.c**? I use uhttpd.

**Comment by NS-K** [comment]
That's what i have in my custom version.
i have added a preauthtimeout on the config file and i set it always to the half of my DHCP-LEASE-TIMEOUT via the init file.

**Comment by lynxis** [comment]
it would be nice if you could share your feature and create a pull-request :)

**Comment by bluewavenet** [comment]
Clients are only added to preauth if:
1. A new device to the network is manually connected and its CPD triggers the splash page.
2. A previously visiting device comes into range and its CPD triggers the splash page.
The current v2 default of maxclients=250 does not seem to result in a problem even at large busy venues with a class C subnet.
Closing this issue for now.
