### ISSUE TITLE
Nodogsplash LAN interfaces

### ISSUE THREAD

**Issue by netcarenepal** [nodogsplash/nodogsplash#528]
I want nodogsplash to allow access to internet for WLAN users while LAN interface have internet connections anyways .i.e Bypass nodogsplash for LAN interfaces. is it possible to do? i am using ZBT device.currently each LAN interface acts as separate client but i have connected LAN port for CCTV DVR .

**Comment by bluewavenet** [comment]
@netcarenepal 
If you just want the DVR to have access and everything else restricted, then make it a trusted device.
If you want just the wireless lan to be controlled by NDS and anything on the ethernet LAN to have free access, then bind just the wireless interface to NDS instead of the LAN bridge interface

**Comment by netcarenepal** [comment]
i wanted  just the wireless lan to be controlled by NDS ..  

the part of nodogsplash.conf looks like

# GatewayInterface is not autodetected, has no default, and must be set here.
# Set GatewayInterface to the interface on your router
# that is to be managed by Nodogsplash.
# Typically br0 for the wired and wireless lan on OpenWrt White Russian.
# May be br-lan on OpenWrt Kamikaze.
#
GatewayInterface br-lan

# FirewallRuleSet: authenticated-users

and my device interfaces are
config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd7c:1321:9968::/48'

config interface 'lan'
	option ifname 'eth0.1'
	option force_link '1'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option macaddr '78:a3:51:2b:c9:b6'

config interface 'wan'
	option ifname 'eth0.2'
	option proto 'dhcp'
	option macaddr '78:a3:51:2b:c9:b7'

config interface 'wan6'
	option ifname '@wan'
	option proto 'dhcpv6'

config interface '4g'
	option ifname '3g'
	option proto '3g'
	option device '/dev/ttyUSB2'

config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '1'

config switch_vlan
	option device 'switch0'
	option vlan '1'
	option ports '0 1 2 3 5 6t'

config switch_vlan
	option device 'switch0'
	option vlan '2'
	option ports '4 6t'

Just didnt know what to use instead of br-lan

**Comment by netcarenepal** [comment]
or is it possible to use Nodogsplash is such a way the it only provides flash page as an advertisement but didnt block internet at all.

**Comment by bluewavenet** [comment]
@netcarenepal 
Which versions of OpenWrt and NoDogSplash are you using?

Can you post the contents of your wireless config as well please?

Also the output from the command:
`ip link`
not as a screenshot, but copy and paste into here, as seeing the images on a mobile is very difficult.

This will tell us what interface to use (probably wlan0).

**Comment by netcarenepal** [comment]
sorry for late response. i as doing some changes and found the solution. I created separate interface wth different network for LAN interfaces and it worked.

the output  is : in this i created another LAN interface Cr-lan and i got internet working bypassing nodogsplash. while for wifi it will use nodogsplash.
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 78:a3:51:2b:c2:ec brd ff:ff:ff:ff:ff:ff
3: ifb0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 32
    link/ether d6:f2:2b:b9:ac:fc brd ff:ff:ff:ff:ff:ff
4: ifb1: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 32
    link/ether 3a:6e:e3:d0:c3:89 brd ff:ff:ff:ff:ff:ff
5: gre0: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT group default
    link/gre 0.0.0.0 brd 0.0.0.0
6: gretap0: <BROADCAST,MULTICAST> mtu 1476 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
14: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 78:a3:51:2b:c2:ee brd ff:ff:ff:ff:ff:ff
15: eth0.1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-lan state UP mode DEFAULT group default
    link/ether 78:a3:51:2b:c2:ec brd ff:ff:ff:ff:ff:ff
16: eth0.2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 78:a3:51:2b:c2:ef brd ff:ff:ff:ff:ff:ff
17: 3g-4g: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 3
    link/ppp
18: ra0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br-lan state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 78:a3:51:2b:c2:ec brd ff:ff:ff:ff:ff:ff
19: wds0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 78:a3:51:2b:c2:ec brd ff:ff:ff:ff:ff:ff
20: wds1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 78:a3:51:2b:c2:ec brd ff:ff:ff:ff:ff:ff
21: wds2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 78:a3:51:2b:c2:ec brd ff:ff:ff:ff:ff:ff
22: wds3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 78:a3:51:2b:c2:ec brd ff:ff:ff:ff:ff:ff
23: apcli0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 78:a3:51:2b:c2:ed brd ff:ff:ff:ff:ff:ff
