### ISSUE TITLE
Rpi 4 compile gives HASH error and can't download v4.4.1beta source file

### ISSUE THREAD

**Issue by BaltasarParreira** [nodogsplash/nodogsplash#530]
The latest openWRT package for Raspberry pi 4 is not working with the error that server could not start.

So I decide to compile using the instructions here with the late GIT source and I got an old error reported here https://github.com/nodogsplash/nodogsplash/issues/355 that you have to put the hash value on the Makefile file.

Anyway even doing that, the link suppose to use to download the source file:
https://codeload.github.com/nodogsplash/nodogsplash/tar.gz/v4.4.1beta
is not working and gives always " 404: Not Found " so could not put that file on the openwrt/dl folder as mensioned.
Workaround I download the zip here with the green button " Clone or download " and convert it to the correct name and compression (nodogsplash-4.4.1beta.tar.gz) changing also inside the folder nodogsplash-master to nodogsplash-4.4.1beta.

So I generate the hash from that file and put the value in the Makefile file. 
Run make and it worked.
Now I can install the compiled nodogsplash_4.4.1beta-1_aarch64_cortex-a72.ipk package and everything is working.

Here it is just if anyone else with a Raspberry pi 4 is stuck with the same problem.
Hope this will be solved soon on next releases.
[nodogsplash_4.4.1beta-1_aarch64_cortex-a72.zip](https://github.com/nodogsplash/nodogsplash/files/4251058/nodogsplash_4.4.1beta-1_aarch64_cortex-a72.zip)

**Comment by bluewavenet** [comment]
@BaltasarParreira 
This is happening because 4.4.1beta is not a release.
You figured out a way to do it ;-)
The plan is for a new release soon!

**Comment by BaltasarParreira** [comment]
I understand what you are saying, but since the last snapshot from OpenWRT for Rpi 4 was not working and I getting the start failure I mentioned I decided to compile from here to see if it solves by any chance. So, following just the build commands from here:
https://github.com/nodogsplash/nodogsplash/tree/master/openwrt 
without changing anything it goes for the 4.4.1beta so not compiling as I said.
 ;)

**Comment by bluewavenet** [comment]
@BaltasarParreira 
Yes indeed, v4.4.0 does fail on some devices. The current 4.4.1beta with a few more commits will soon be evolving into version 4.5.0 with some significant new functionality.
The more people we can find to test the better ;-)

**Comment by BaltasarParreira** [comment]
Ok, count with me for anything related to Raspberry pi 4 you might need.

**Comment by bluewavenet** [comment]
@BaltasarParreira 
Excellent ;-)
