### ISSUE TITLE
Restart nodogsplash after power shutdown

### ISSUE THREAD

**Issue by doxendine** [nodogsplash/nodogsplash#533]
Hi. 
This may not be an issue, just how it works. Not sure. I'm running nodogsplash on raspberry pi 4 with moodlebox on it. After running 'sudo systemctl start nodogsplash' at the command line, nodogsplash starts & runs as expected. However, if power is shut down to the pi & rebooted, I need to retype the same line at the command line to get it to restart. Is this normal? Is there a way to keep nodogsplash on after a power reboot?
Thanks

**Comment by bluewavenet** [comment]
@doxendine 
To make it start on boot I think you need to do the following once:
`sudo systemctl enable nodogsplash`

**Comment by doxendine** [comment]
Thanks. I've tried that also. After a power reboot, I have to do 'sudo systemctl restart nodogsplash'. Wasn't sure if this is normal or there is a get around for this.

**Comment by bluewavenet** [comment]
@doxendine 

> After a power reboot, I have to do 'sudo systemctl restart nodogsplash'

No, this is not normal.

Can you tell us what operating system/version and what version of NDS you are currently using please.
Your system log should show if NDS is being started when booting. It is possible that for some reason it is failing, for example if the interface NDS is configured to bind to is not up at the time.
This could be dependent on what interfaces you are starting and how you are doing it.

**Comment by doxendine** [comment]
Hi. 
Running MoodleBox version 3.5.1 on Pi 4. Not sure how to check the version of nodogsplash.
However, when I type:  'sudo systemctl status nodogsplash' I get the following. Looks like it's running, but for some reason need to restart it to get it to work. 
![nodogsplash status](https://user-images.githubusercontent.com/31901422/75751932-e4413900-5ce4-11ea-956a-7ac30453d9e3.jpg)

**Comment by bluewavenet** [comment]
@doxendine 
For some reason NDS is getting 0.0.0.0 as an ip address. This is invalid. The OS must be reporting all zeros my guess because the wireless interface is not completely up when NDS gets started....

Run the command:
`ndsctl status`
To get the NDS version.

**Comment by doxendine** [comment]
I get this error when I run that command:
ndsctl: nodogsplash probably not started (Error: Permission denied)
Here's the same pic after I restart it:
![nodogsplash status 1](https://user-images.githubusercontent.com/31901422/75754279-aeeb1a00-5ce9-11ea-949f-fc4fd108d19b.jpg)

**Comment by bluewavenet** [comment]
@doxendine 
`sudo ndsctl status`

**Comment by doxendine** [comment]
I should have been able to figure that out. 
Version: 4.3.3.

**Comment by bluewavenet** [comment]
@doxendine 
You could try adding an extra line into nodogsplash.service (in /etc/systemd somewhere I think).
Add the line:
`ExecStartPre=sleep 5` in the [Service] section.

The nodogsplash.service file will then be:
```
[Unit]
Description=NoDogSplash Captive Portal
After=network.target

[Service]
Type=forking
ExecStartPre=sleep 5
ExecStart=/usr/bin/nodogsplash $OPTIONS
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
This is only a possible workaround....

**Comment by doxendine** [comment]
Hi.
Found nodogsplash.service under:  /lib/systemd/system/
ExecStartPre=sleep 5  didn't seem to work. 
However, 'ExecStartPre=sleep 10' worked perfectly. 
You are awesome. 
Thanks for your help.

**Comment by bluewavenet** [comment]
@doxendine 
Excellent :-D

**Comment by bluewavenet** [comment]
@doxendine 
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560 

This issue should be fixed there - if you are up for it, some testing would be very useful ;-)
https://github.com/openNDS/openNDS/releases/tag/v5.0.0

**Comment by andy-yeung** [comment]
> @doxendine
> You could try adding an extra line into nodogsplash.service (in /etc/systemd somewhere I think).
> Add the line:
> `ExecStartPre=sleep 5` in the [Service] section.
> 
> The nodogsplash.service file will then be:
> 
> ```
> [Unit]
> Description=NoDogSplash Captive Portal
> After=network.target
> 
> [Service]
> Type=forking
> ExecStartPre=sleep 5
> ExecStart=/usr/bin/nodogsplash $OPTIONS
> Restart=on-failure
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> This is only a possible workaround....
> You will have to do a systemctl disable nodogsplash and a systemctl enable nodogsplash for it to take effect I think.

hi, I also would like to automatically activate NDS service after reboot,and I had followed your guideline but I have an error:
![image](https://user-images.githubusercontent.com/62322681/104868886-8ca0d000-597f-11eb-9a01-ffaa80c96617.png)
![image](https://user-images.githubusercontent.com/62322681/104869092-10f35300-5980-11eb-8636-57d8f3292ee2.png)
How can I solve it?

**Comment by bluewavenet** [comment]
@andy-yeung 
This is solved by upgrading to openNDS.
You can download the latest version here:
[https://github.com/openNDS/openNDS/releases/](url)

First you must uninstall NoDogsplash and libmicrohttpd, then follow the simple installation instructions here:
[https://opennds.readthedocs.io/en/stable/compile.html#linux-unix-compile-in-place-on-target-hardware](url)

If you have any problems please open an issue here:
[https://github.com/openNDS/openNDS/issues](url)

**Comment by andy-yeung** [comment]
> @andy-yeung
> This is solved by upgrading to openNDS.
> You can download the latest version here:
> https://github.com/openNDS/openNDS/releases/
> 
> First you must uninstall NoDogsplash and libmicrohttpd, then follow the simple installation instructions here:
> https://opennds.readthedocs.io/en/stable/compile.html#linux-unix-compile-in-place-on-target-hardware
> 
> If you have any problems please open an issue using this link:
> https://github.com/openNDS/openNDS/issues

![image](https://user-images.githubusercontent.com/62322681/104902048-289afd80-59b9-11eb-85ba-7297322b7415.png)
libmicrohttpd is out of date but i had tried "apt-get install libmicrohttpd" and it doesn't work.

**Comment by bluewavenet** [comment]
@andy-yeung 
Please:
1. Read https://opennds.readthedocs.io/en/stable/compile.html#linux-unix-compile-in-place-on-target-hardware
2. Close this issue and open a new one at https://github.com/openNDS/openNDS/issues

**Comment by bluewavenet** [comment]
@andy-yeung 
Note also the latest release of openNDS is v8.0.0
https://github.com/openNDS/openNDS/releases/tag/v8.0.0
