### ISSUE TITLE
Fas redirection problem due CPD

### ISSUE THREAD

**Issue by richyxi** [nodogsplash/nodogsplash#534]
I'm facing an issue about redirection with my FAS, but only(yet) on an haweii device, when I'm trying to access it does open a splash page but in chrome and it's redir is the same as my FAS which is hosted in remote server.

This is the link that I get when I'm trying to access: 
http://innerout.pythonanywhere.com/?authaction=http://10.3.141.1:2050/nodogsplash_auth/?clientip=10.3.141.240&gatewayname=zitla-cumbres-1&tok=e74f018e&redir=http%3a%2f%2finnerout.pythonanywhere.comhttp%3a%2f%2finnerout.pythonanywhere.com%2f%3fauthaction%3dhttp%3a%2f%2f10.3.141.1%3a2050%2fnodogsplash_auth%2f%3fclientip%3d10.3.141.240%26gatewayname%3dzitla-cumbres-1%26tok%3de74f018e%26redir%3dhttp%3a%2f%2finnerout.pythonanywhere.comhttp%3a%2f%2finnerout.pythonanywhere.com%2f%3fauthaction%3dhttp%3a%2f%2f10.3.141.1%3a2050%2fnodogsplash_auth%2f%3fclientip%3d10.3.141.240%26gatewayname%3dzitla-cumbres-1%26tok%3de74f018e%26redir%3dhttp%3a%2f%2finnerout.pythonanywhere.comhttp%3a%2f%2finnerout.pythonanywhere.com%2f%3fauthaction%3dhttp%3a%2f%2f10.3.141.1%3a2050%2fnodog

My FAS InnerOut.pythonanywhere.com

Thanks in advance!

**Comment by bluewavenet** [comment]
@richyxi 
You have not given any details of your OS and NDS versions, but this looks like either a coding error in your FAS or a configuration error in your NDS (maybe even both).
The link you are getting is clearly incorrect and has looped around at least 3 times by the look of it.
Have you tried the supplied examples: fas-hid.php or fas-aes.php?
I know they are not in Python, but they do give examples of the process.

**Comment by richyxi** [comment]
my actual set is
os: raspian
nds: 4.3.4

this is my actual config

```fasremoteip 35.173.69.207
fasport 80
fasremotefqdn innerout.pythonanywhere.com
fas_secure_enabled 0
GatewayName zitla-cumbres-1
```
the logs when i got the problem
```
[5][Sun Mar 01 18:08:07 2020][3747](src/client_list.c:139) Adding 10.3.141.240 a4:93:3f:b4:c4:24 token 7ba5f232 to client list
[4][Sun Mar 01 18:08:10 2020][3747](src/http_microhttpd.c:1063)  Query string exceeds the maximum of 4096 bytes so has been truncated.
[4][Sun Mar 01 18:08:10 2020][3747](src/http_microhttpd.c:1063)  Query string exceeds the maximum of 4096 bytes so has been truncated.
[4][Sun Mar 01 18:08:10 2020][3747](src/http_microhttpd.c:1063)  Query string exceeds the maximum of 4096 bytes so has been truncated.
[4][Sun Mar 01 18:08:10 2020][3747](src/http_microhttpd.c:1063)  Query string exceeds the maximum of 4096 bytes so has been truncated.
[4][Sun Mar 01 18:08:10 2020][3747](src/http_microhttpd.c:1063)  Query string exceeds the maximum of 4096 bytes so has been truncated.
[4][Sun Mar 01 18:08:10 2020][3747](src/http_microhttpd.c:1063)  Query string exceeds the maximum of 4096 bytes so has been truncated.
[4][Sun Mar 01 18:08:10 2020][3747](src/http_microhttpd.c:1063)  Query string exceeds the maximum of 4096 bytes so has been truncated.
[4][Sun Mar 01 18:08:10 2020][3747](src/http_microhttpd.c:1063)  Query string exceeds the maximum of 4096 bytes so has been truncated.
``
i think that my config is normal, and my code actually works with many devices, for what i can expect(correct me if am wrong), the value of redir is what is causing the issue and redir is set by nds which depends on the cpd, so if a specify a redirected page, maybe this can solve this issue?

**Comment by bluewavenet** [comment]
@richyxi 
There never was a release 4.3.4 so I think you have a pretty old snapshot of master.
The current release is 4.4.0, but there are some other issues with that on devices with larger amounts of ram eg Rpi.
A new release 4.5.0 is imminent, from current master, so before we dig deeper, I would suggest you recompile using current master (it declares itself v4.4.1beta right now - but that will change). The problem you are having may well be fixed and if not we will be at a good starting point to find the cause!

**Comment by richyxi** [comment]
I will do the recompile soon.
I fixed this issue by setting a RedirectURL value.
Another quick question, is nds able to run on 4/16 modem devices?

**Comment by bluewavenet** [comment]
@richyxi 

> I fixed this issue by setting a RedirectURL value.

RedirectURL is deprecated. It possibly still works.... but don't rely on it.

> is nds able to run on 4/16 modem devices?

The problem with a 4/16 device is actually finding an OS that will fit on it.
A modern bottom of the range device will have 16/128 these days....

**Comment by richyxi** [comment]
Is there a replace of the RedirectUrl?

**Comment by bluewavenet** [comment]
@richyxi 
RedirectURL is deprecated because most implementations of client CPD will eventually close immediately an Internet connection is detected, many do already.
FAS already has this functionality, even if it might not be effective.

**Comment by richyxi** [comment]
Okay thanks for the info, also, what devices you recommend for running nds?

**Comment by bluewavenet** [comment]
@richyxi 

> what devices you recommend for running nds?

I would go for something with at least 16MB flash and 128MB ram. Just about all up to date models meet or exceed this specification.
A good budget starter is the GL-iNET MT300M-V2 at ~$20 USD with OpenWrt is ideal. It all depends on your use case.

**Comment by richyxi** [comment]
Such a good info here, thanks for the input
