### ISSUE TITLE
Splash page redirect to a website

### ISSUE THREAD

**Issue by mrostamii** [nodogsplash/nodogsplash#536]
Hello. I'm backed.  

We want to change the splash page like this:

- When devices connect to the AP, the splash page appears. (It's ok. Same as usual)
- The page has a button that captioned "Open our website". The website is over the internet hence I must at first connect the internet (Like the "Continue" button) then open up a web page by the Browser installed.  

Is it possible?

All we have done is that change the button like it:  
```
    <ul class="cta-container">
        <li><form method="get" action="$authaction">
            <input type="hidden" name="tok" value="$tok">
            <input type="hidden" name="redir" value="http://www.mimtech.ir">
            <input type="submit" value="Continue">
            </form></li>
        <li><a class="btn btn-cta btn-secondary" href="http://www.mimtech.ir/">Not at this time</a> 
        </li>
    </ul>
```

**Comment by bluewavenet** [comment]
It is not "reliably" possible.
It depends upon the client device and not NDS.
The CPD process on the client device will, on most implementations, close as soon as an Internet connection is detected.

**Comment by mrostamii** [comment]
Thank you for the response. 

And another question, can I somehow open the google chrome browser? or any application which is possible?
Something like system-call.

**Comment by bluewavenet** [comment]
The client CPD is specifically designed to prevent any outside influence from starting any app or installing anything for security reasons.
``can I somehow open the google chrome browser? or any application ``
The simple answer is no.
