### ISSUE TITLE
Login option not logging properly

### ISSUE THREAD

**Issue by Kosa103** [nodogsplash/nodogsplash#542]
In the nodogsplash.conf I have login option enabled: 
`login_option_enabled 1`

The login-type captive portal shows up normally, asking for login name and e-mail address.
However after entering data and pressing 'continue' the data isn't recorded, only the time of the login.

The log file is located at:
`/tmp/ndslog.log`

Content of the log file after a successful login: (system language is not english)
`2020. márc.  4., szerda, 06:13:40 CET, New log file created`

And that's it. No login name, no e-mail address, nothing.
Where should I look for the solution?

**Comment by bluewavenet** [comment]
@Kosa103 
This is a known issue when running on Raspbian and is fixed in release 4.5.0
https://github.com/nodogsplash/nodogsplash/releases/tag/v4.5.0
The /usr/lib/nodogsplash/login.sh file is now easily customisable with working suggestion for Raspian in the file itself.
I am making the assumption you are running Raspbian ;-)

I suggest you upgrade to v4.5.0 anyway as there are many fixes and enhancments.
Extract from the beginning of the v4.5.0 login.sh :
```
# Customise the Logfile location:
#
# mountpoint is the mount point for the storage the log is to be kept on
#
# /tmp on OpenWrt is tmpfs (ram disk) and does not survive a reboot.
#
# /run on Raspbian is also tmpfs and also does not survive a reboot.
#
# These choices for OpenWrt and Raspbian are a good default for testing purposes
# as long term use on internal flash could cause memory wear
# In a production system, use the mount point of a usb drive for example
#
#
# logdir is the directory path for the log file
#
#
# logname is the name of the log file
#

#For Openwrt:
mountpoint="/tmp"
logdir="/tmp/ndslog/"
logname="ndslog.log"

#For Raspbian:
#mountpoint="/run"
#logdir="/run/ndslog/"
#logname="ndslog.log"

```

**Comment by Kosa103** [comment]
@bluewavenet Thanks a lot!
Yes, I'm using Raspbian. You are reading my mind ;-)

Is there a simple way of upgrading my NDS to v4.5.0 or I have to purge the old version and start from scratch?

Also, what memory wear should I expect over long term use?

**Comment by bluewavenet** [comment]
@Kosa103 
I think if you recompile and install it will overwrite the old.
You might be set back to default - I'm not sure on Raspian. ...

**Comment by Kosa103** [comment]
It all works, thanks for the help!
The git page (https://github.com/nodogsplash/nodogsplash.git) is also updated I see.
Recompiling and installing also worked - simple. The config file (nodogsplash.conf) was reset to default but it's very easy to understand and re-config. Great job! :)

**Comment by bluewavenet** [comment]
@Kosa103 

>  The git page (https://github.com/nodogsplash/nodogsplash.git) is also updated I see.

That is "master"and will have the very latest commits. If you use it, bare in mind that it should be regarded as a "development snapshot" and that what you get at any instant in time may not be the same as what you will get a bit later. Also it probably will not be fully tested and indeed it may not work at all.
Official releases however are fixed and will be tested in a real environment as far as possible.

> what memory wear should I expect over long term use?

NDS does not do any continual writing so will not cause memory wear. However, any scripts that for example, write logs for every access could. If you are using the built in flash memory of a router class hardware, you might well eventually see memory failures. It very much depends on the type of memory used. An SSD is designed to minimise the problem and be as long lived or better then a spinning hard disk. A dedicated "logging" USB stick or a micro sd card will be pretty good, but if the worst happens these are cheap and quick to replace. In answer to your question - I don't know - it depends on so many factors. So go for something quick and cheap to replace. I find one of those nano style usb "buttons" is perfect as they have nothing sticking out or easy to knock loose/steal.
There are many to choose from but here is an example:
https://www.amazon.co.uk/dp/B00RORBNR6
