### ISSUE TITLE
How can i file indexing in splash page.

### ISSUE THREAD

**Issue by ByambaKh** [nodogsplash/nodogsplash#543]
I want to file can be download from folder index in splash page. is it possible? for example created html iframe and loading folder index (./images)

**Comment by bluewavenet** [comment]
@ByambaKh 
Generally, the client CPD blocks iframes and downloads for security reasons, so no, it is not possible. This is not an issue with NDS, but precautions implemented by operating systems to protect clients from badly behaved captive portals.

**Comment by lynxis** [comment]
@ByambaKh nodogsplash doesn't support folder index (as nginx/apache) supports it. However extra files can be offered as static files.

**Comment by bluewavenet** [comment]
@lynxis 
This issue can be closed.
