### ISSUE TITLE
how to use php on splash.html page

### ISSUE THREAD

**Issue by klinutzu** [nodogsplash/nodogsplash#544]
hi all,

it's possible to use php code in splash.html default page? i need only to send in a mysql database some info's. or even to have all connections not in a txt file as default, but in mysql?

if i open php use in uhttpd it's enough?

thanks and regards

**Comment by bluewavenet** [comment]
@klinutzu 
For this you must use a dynamic splash page using the built in FAS support.
splash.html is a static html page so you cannot use php code within it.

The best way to get started is to read the documentation at:
https://nodogsplashdocs.readthedocs.io/en/stable/customize.html#dynamic-splash-pages

**Comment by klinutzu** [comment]
ok, i know that, but i need only a 'click to go' page and to have a list with the authenticated and active clients.  it's somewhere a file like this, as i don't found it? i want also to insert these users in a database... :)

**Comment by bluewavenet** [comment]
@klinutzu 
The example scripts eg fas-aes.php, fas-hid.php and login.sh can trivially be modified for "click and go" and will have access to anything available where they are running as well as having the client details such as ip address, mac address and user-agent string. The examples write all this to a log file already. This could just as easily be a write to an sql database.

**Comment by klinutzu** [comment]
thx, where is the log file? is this file even with splash page?

**Comment by bluewavenet** [comment]
@klinutzu 
If you are using splash.html, there is no log file.
The example FAS scripts do create a log file, the location depends upon where the script is run.
For example, the preinstalled login script (login.sh) saves its logs in /tmp (or /run on Raspbian).
https://nodogsplashdocs.readthedocs.io/en/stable/preauth.html#enabling-the-preinstalled-login-script-v4-0-2-onwards

**Comment by bluewavenet** [comment]
@klinutzu 
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560

**Comment by lynxis** [comment]
@klinutzu we're moving out the FAS out of nodogsplash into it's own project (opennds). Nodogsplash will support simple splash pages. You could try adding a redirect it in the splashpage.html body. http header redirect aren't support atm.
