### ISSUE TITLE
NDS NEW VERSION RELEASE IS NOW INCOMPATIBLE TO MY ROUTER

### ISSUE THREAD

**Issue by gameplandigital** [nodogsplash/nodogsplash#546]
Hi Guys! I'm using NDS version 3.2.1 on my TP-Link MR3420 v5 in my store and now when I want to config and add more routers with the same model to my other stores, I can't install NDS with architecture error. I'm using "opkg update" then "opkg install nodogsplash" and I notice that version installing is the latest 4.5.0 which means the latest won't work on my current routers. How can I install nodogsplash 3.2.1 instead of 4.5.0???

PLEASE HELP ME!

**Comment by bluewavenet** [comment]
@gameplandigital 
v4.5.0 is released as source code but the version available on OpenWrt  is v4.0.1-1, so you cannot actually be seeing v4.5.0 being installed. Not even OpenWrt snapshot has v4.5.0 yet.
If you are getting an architecture error, it means you are trying to install a binary for different hardware.
What is the version of OpenWrt you are running?

**Comment by gameplandigital** [comment]
lede ramips mt7628 squashfs tftp recovery bin

Hostname | LEDE
-- | --
Model | TP-Link TL-MR3420 v5
Firmware Version | LEDE Reboot SNAPSHOT r5442+6-b0b289e / LuCI Master (git-17.328.04231-802d5b6)
Kernel Version | 4.9.65

**Comment by bluewavenet** [comment]
@gameplandigital 
That is a very ancient "snapshot" version of OpenWrt that has not been valid for a number of years. opkg update probably downloads something very wrong if it does not actually fail.
I suggest you download OpenWrt 19.07.2 and try again.
Download from here:
https://downloads.openwrt.org/releases/19.07.2/targets/ramips/mt76x8/

**Comment by gameplandigital** [comment]
I'll try. Thank you so much <3

**Comment by gameplandigital** [comment]
One more thing. What if, I want to install NDS v.3.2.1 instead of v.4.0.1. How can I do that? Thanks

**Comment by bluewavenet** [comment]
@gameplandigital 
I think you would have to download the v3.2.1 source code and compile it yourself.

**Comment by gameplandigital** [comment]
Could you give me a tutorial or step-how-step on how to compile it? Sorry, I don't have any idea or experience with this. Thank you so much

**Comment by bluewavenet** [comment]
@gameplandigital 
It will be much simpler to just download and reflash with 19.07.2. v4.0.1 is fully compatible with v3.2.1 but has a considerable number of enhancements.

If you want to go through the learning exercise take a look at:
https://openwrt.org/docs/guide-developer/using_the_sdk

**Comment by gameplandigital** [comment]
Problem resolved. Thank youuuuuuuu

**Comment by gameplandigital** [comment]
Problem solved. Thank youuuuuuuu

**Comment by bluewavenet** [comment]
@gameplandigital 
Excellent.

v4.0.1 on OpenWrt 19.07.2 I presume?

**Comment by gameplandigital** [comment]
Yes. Thank you!

**Comment by bluewavenet** [comment]
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560
