### ISSUE TITLE
server side session

### ISSUE THREAD

**Issue by richyxi** [nodogsplash/nodogsplash#547]
hi!
i would like to know the return rate of my clients, since i think that asking for email is not a good way to make a reliable indicator, i was thinking about working with some kind of cookies that can refeer with the specific client but i know that the cpd has very strict rules due security, i saw this #403 post and it was mention the server side session, does this function can be applied to the refeer cookie principle?

**Comment by bluewavenet** [comment]
@richyxi 
You have the client mac address and user agent string already. If these are logged (they are in the example scripts), then it is a simple matter to parse the log to get the return rate.

**Comment by richyxi** [comment]
Can I access to the nds from remote server to run the ndsctl?

**Comment by bluewavenet** [comment]
@richyxi 
What informarion are you trying to retrieve by running ndsctl?
NDS sends everything it knows about a client if you choose the right configuration.

**Comment by richyxi** [comment]
The session start and session end interval

**Comment by bluewavenet** [comment]
@richyxi 
Session start is the time the client is authenticated by FAS and session end is session start plus session duration set in config so easy :-D

**Comment by richyxi** [comment]
That works perfectly! but lets say, I need to know how long my clients stay
in my local, if I put a restriction like 30 minutes of internet, it will
always show that my clients just stay 30 minutes in the local, and that's
not necessarily very accurate. That's why I need to know the output of
ndsctl that shows the exact time of session end.

I was thinking of writing a bash script that sends every x time the json
that ndsctl provides to a database or maybe accessing to the router from
outside and running that manually.

Sorry if don't give the specific detail from the beginning.
Thanks in advance!

**Comment by bluewavenet** [comment]
@richyxi 
There are two timeout intervals, sessiontimeout and authidletimeout.
Once a client is timed out, it is deleted from the auth table so NDS will have no knowledge of it thereafter.
Clients do not "log out" they just leave the venue and eventually time out. The exact time the client stops using the connection is not known. Ndsctl will not help as it does not know. The operating system does not know either. You could continuously monitor wireless connections, traffic download/upload per client, and timeout time per client and make a guess, but this would be very complicated and not at all accurate.

**Comment by richyxi** [comment]
Thanks for the input, just a few question that i got reading this and the docs and look if that the implement that i have in mind is posible.

I will write a binauth script that will be called when the idle timeout reach its end, and in every call it will send to a db the time but i also need the token, and the mac address.

- How can those variables can be passed to the script from the respective client? 

- does the mac adress can be passed to may FAS in the query string?

Thanks in advance!

**Comment by bluewavenet** [comment]
@richyxi 
sessiontimeout and authidletimeout do not change dynamically as they are set in the config.

FAS will not know which of these de-authenticates the client so yes you are correct that binauth can be used to collect the session start and session end values.

You will find these values passed to the binauth script as method client_deauth and method idle_deauth

You can see how to do this by looking at the binauth_log.sh script included in the source code and listed in the documentation:
https://nodogsplashdocs.readthedocs.io/en/stable/binauth.html#installing-example-2

You will see the client is identified by its mac address. The token is irrelevant at this time so is not passed.
Your binauth script could wget the information to your FAS instead of/as well as logging locally.


> does the mac address get passed to my FAS in the query string?

If you use fas_secure_enable levels 2 or 3, everything you could need is passed to FAS including the mac address and token.
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#example-fas-query-strings
Note level 3 is only available in v4.5.0 onwards

**Comment by richyxi** [comment]
Great thanks! Also does ndsctl can run on the binauth script? I saw that in
latest release now it can't be run from that script.

**Comment by bluewavenet** [comment]
@richyxi 

> does ndsctl run in a binauth script?

Unfortunately not. When the binauth script is called, NDS has the client list locked, so ndsctl causes a deadlock.
Prior to NDS v4.5.0, using ndsctl in a binauth script would cause NDS to either lock up or crash. In v4.5.0 ndsctl just exits if it finds itself called by binauth. It should be possible to allow this in a later version, but is it needed? Preauth or a custom daemon running in the background can get all the information that is available.

**Comment by richyxi** [comment]
nice.
just to check last things

- Is this the proper way to set the binauth in for the call in a idle timeout?
`BinAuth /bin/myauth.sh <idle_deauth> <client_mac>`

- Does fas secure 2 (in 4.3.3 nds version) needs php-cli and php-openssl when fas is located in a remote server?

**Comment by bluewavenet** [comment]
@richyxi 

> Is this the proper way to set the binauth in for the call in a idle timeout?

I think you mean "How is binauth called for an idle timeout?".
The binauth script is called by NDS with up to 7 arguments. (see the example script binauth_log.sh)
if $1 => idle_deauth, then:
$2 => clientmac
$3 => bytes_incoming
$4 => bytes_outgoing
$5 => session_start
$6 => session_end
$7 not set

> Does fas secure 2 (in 4.3.3 nds version) need php-cli and php-openssl when fas is located in a remote server?

Yes. If these are not installed, NDS will exit, logging the requirement.

**Comment by richyxi** [comment]
> Yes. If these are not installed, NDS will exit, logging the requirement.

in 4.5.0 is still necessary?

**Comment by bluewavenet** [comment]
@richyxi 
Yes, prerequisite for levels 2  and 3

**Comment by richyxi** [comment]
Big thanks!
