### ISSUE TITLE
Customise .php for login mode

### ISSUE THREAD

**Issue by Kosa103** [nodogsplash/nodogsplash#549]
Hey there!

My system: Raspberry Pi 3b v1.2 running Raspbian Stretch

My question is which .php to modify (I assume it's a .php) to customise the Captive portal page if I set 'login mode'? I know I can easily modify the basic looks of the splash.html and status.html but that's without login mode. Since I'd only like to give it a different looks with some extra text I wouldn't want to make a fresh new page for it since the original is working perfect. I'd be simpler to do tweaks to the existing one.

Can you help please? :)

**Comment by bluewavenet** [comment]
@Kosa103 
This is actually a bash script, located in the /usr/lib/nodogsplash folder. Its filename is login.sh

It is identical to the demo-preauth.sh script and uses the same splash.css that is used by splash.html.
The script is fairly well documented in its own inline comments so is quite easy to modify.
Let me know if you need any help.

**Comment by bomboem** [comment]
I can't wrap my head around how to modify this login.sh script. Say I want to ask for a room number and a "Internet key" they received at the bar of my hotel, and I want to design the appearence so it looks like the website of my hotel. How would I edit this bash script? And what is the function of authmon.sh and post-request.php? I can't seem to understand how this login.sh works and how i'd design my own login page... Help would be appreciated

**Comment by Kosa103** [comment]
@bomboem 

Hi there! I'm just another fella experimenting with NDS and I'll try to help you.
The login.sh basically splits the login page to 3 parts:
- a header (beginning: line 222)
- a footer (beginning: line 244)
- a login form (beginning: line 258)
The code you see in between "  " is your html for the captive portal. Modify them here as they'll be used several times later in the script.

They are used in the lines you see `echo -e $header` for example. Every time you see echo it means that the .sh script is writing out text. Sometimes the script is informing the user that he's already connected or failed to connect. You probably want to modify those lines as well to fit into your webpage. As you probably know not all html content is displayed but that's part of a longer story.

WARNING!
You must escape the` " `characters to make them work: `\"`
Otherwise they mess up your .sh as well as your .html code. Example:
Won't work: `<meta charset="utf-8">`
Will work: `<meta charset=\"utf-8\">`


If you want to get extra login data from your guests (like room number) you should modify the login form (beginning at line 258). There is a line beginning like: `input type=\"text\" name=\"username\"`
This is the line asking for the client's name. Add more of these lines and modify them according to your needs. Starting at line 100 the script prepares user data for logging. You will also need to add your additional data there.

Final notes: 
The .css file is located at `/etc/nodogsplash/htdocs/splash.css`
You should make a copy of the original files before you play around with them.

I hope this is not too hard to understand and will help you. As for the other two files (authmon.sh, post-request.php) you better wait for @bluewavenet 's response as I didn't yet dig into them.
Good luck! :)

**Comment by bluewavenet** [comment]
@Kosa103 
Thanks, you have it exactly!

@Kosa103 and @bomboem and everyone reading

**Note 1:** The login.sh file is copied at install time from the file demo-preauth.sh (see forward_authentication_service/preauth/ folder in the source code).

**Note 2:** Make sure you are using a proper release version. At the time of writing, this is version 4.5.0. Many Rpi tutorials are very outdated and point you at master on Github. This will give you a beta version that is only a development snapshot at the moment you download it and as such it will most likely not be tested and there is no guarantee it will even work.

**Note 3:** Make sure you are reading the current release documentation, not an old version. This can be found at https://nodogsplashdocs.readthedocs.io/en/stable/

This default login.sh is a built in implementation of a PreAuth script. PreAuth is a special case use of the FAS functionality built into NDS that does not require the overhead of a separate web/php server thus minimising storage and ram requirements, an important consideration when for example, using OpenWrt on older, dedicated, router hardware that might have as little as 4MB of flash and 16MB of ram. I will go into more detail about FAS and PreAuth in reply to #553 

**NDS v4.5.0 has a library of utilities installed in /usr/lib/nodogsplash:**

**_authmon.sh_** is one of these and is the authorisation monitor daemon. It is started automatically by NDS if configured for a remote https FAS and is only used in that mode.

**_post-request.php_** is called by authmon to communicate with the remote https FAS server.

**_get_client_token.sh_** is a utility to get the client token

**_get_client_interface_** is a utility to get the interface the client is connected to (eg wlan0, wlan1, mesh1, eth0 etc etc). This allows a login script to have a different response according to the interface a client is using. For example staff using ssid "staff" on wlan0, and guests using ssdi "guest" on wlan0-1

**_unescape.sh_** is a utility that can be used by NDS, if enabled, that allows custom unescaping of data sent to NDS by client CPD browsers. This is normally disabled. The default unescape.sh is a simple unescaper, more or less used as a placeholder. This would normally only be used for advanced applications where custom unescaping is required to modify user entered data.

**Comment by bomboem** [comment]
@bluewavenet how do I get the user's ip when they get served my php script? What order are the parameters passed to login.php? `php login.php arg1 arg2 arg3`

What are these arguments and in what order?

**Comment by bluewavenet** [comment]
@bomboem 
login.sh is a BASH script.

You can **NOT** just replace login.sh with a login.php. If you want a PreAuth script in php, you need php-cli to be installed and configure a custom PreAuth.

It might be better to run an independent http/php FAS server. Apache, Ngnix, Lighttpd are good choices, The FAS server can be on the NDS device, on another machine on the lan, or on commercial hosting services on the Internet.

As I mentioned earlier, I will reply to #553 in more detail.

However I suggest you read the up to date documentation at:
https://nodogsplashdocs.readthedocs.io/en/stable/preauth.html
and
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

**Comment by bluewavenet** [comment]
@Kosa103 
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560

**Comment by lynxis** [comment]
@Kosa103 the php/FAS part has been moved to OpenNDS. nodogsplash will no longer support it.
