### ISSUE TITLE
Openssl

### ISSUE THREAD

**Issue by richyxi** [nodogsplash/nodogsplash#550]
Can I use openssl command in shell to decrypt the FAS in fas secure 2?
Just for curious, does nds use the same command to encrypt the data?

**Comment by bluewavenet** [comment]
@richyxi 

> Can I use openssl command in shell to decrypt the FAS in fas secure 2?

Yes you can. The example FAS script fas-aes.php uses the php7-mod-openssl module and the code that actually does the decryption is just a single line of php. ie:
`	$decrypted=openssl_decrypt( base64_decode( $string ), $cipher, $key, 0, $iv );`

This is php of course but any scripting language with access to ssl libraries could be used.

The fas-aes.php script goes on to populate variables with all the values passed in the encripted string. :
```
if (isset($_GET['fas']) and isset($_GET['iv']))  {
	$string=$_GET['fas'];
	$iv=$_GET['iv'];
	$decrypted=openssl_decrypt( base64_decode( $string ), $cipher, $key, 0, $iv );
	$dec_r=explode(", ",$decrypted);

	foreach ($dec_r as $dec) {
		list($name,$value)=explode("=",$dec);
		if ($name == "clientip") {$clientip=$value;}
		if ($name == "clientmac") {$clientmac=$value;}
		if ($name == "gatewayname") {$gatewayname=$value;}
		if ($name == "tok") {$tok=$value;}
		if ($name == "gatewayaddress") {$gatewayaddress=$value;}
		if ($name == "authdir") {$authdir=$value;}
		if ($name == "originurl") {$originurl=$value;}
		if ($name == "clientif") {$clientif=$value;}
	}
	$client_zone_r=explode(" ",trim($clientif));

	if ( ! isset($client_zone_r[1])) {
		$client_zone="LocalZone:".$client_zone_r[0];
	} else {
		$client_zone="MeshZone:".str_replace(":","",$client_zone_r[1]);
	}

}

```


>  Just for curious, does nds use the same command to encrypt the data?

Yes. NDS uses the same php7-mod-openssl module, accessed via a call to the php7-cli package.

OpenSSL C libraries could have been used but this would have made OpenSSL a dependency of NDS. As we will often have php installed anyway (for a local FAS), making OpenSSL only a pre-requisite for levels 2 and 3 is much more efficient from a flash storage point of view (very important on most router hardware).
 
NDS has to first generate a random initialisation vector before encrypting the data.
For interest, here is the C code in NDS (http_microhttpd.c):
```
if (config->fas_secure_enabled == 2 || config->fas_secure_enabled == 3) {
	safe_asprintf(&phpcmd,
		"echo '<?php \n"
		"$key=\"%s\";\n"
		"$string=\"%s\";\n"
		"$cipher=\"aes-256-cbc\";\n"

		"if (in_array($cipher, openssl_get_cipher_methods())) {\n"
			"$secret_iv = base64_encode(openssl_random_pseudo_bytes(\"8\"));\n"
			"$iv = substr(openssl_digest($secret_iv, \"sha256\"), 0, 16 );\n"
			"$string = base64_encode( openssl_encrypt( $string, $cipher, $key, 0, $iv ) );\n"
			"echo \"?fas=\".$string.\"&iv=\".$iv;\n"
		"}\n"
		" ?>' "
		" | %s\n",
		config->fas_key, querystr, config->fas_ssl);

	debug(LOG_DEBUG, "phpcmd: %s", phpcmd);

	if (execute_ret_url_encoded(msg, sizeof(msg) - 1, phpcmd) == 0) {
		safe_asprintf(&splashpageurl, "%s%s",
			config->fas_url, msg);
		debug(LOG_DEBUG, "Encrypted query string=%s\n", msg);
	} else {
		safe_asprintf(&splashpageurl, "%s?redir=%s",
			config->fas_url, originurl);
		debug(LOG_ERR, "Error encrypting query string. %s", msg);
	}
	free(phpcmd);
}
```

**Comment by richyxi** [comment]
it does not come with padding right?

**Comment by bluewavenet** [comment]
@richyxi 
Padding?

**Comment by richyxi** [comment]
sorry i was a little confused at the time, i get errors in my code that were saying that encrypted string($string) wasnt multiple of 16 so it needed to be pad it, but my problem were that the string is sent to me being encode two times(one from the openssl_encrypt() and the last from base64_encode()) so thats why a get those problems

2 more questions:

when does the the fas key is hashed, is on the function itself?

why does faskey is limited to 16 characters?

thanks a lot!

**Comment by bluewavenet** [comment]
@richyxi 
It is working for you now?
The raw encrypted string would be in binary format. To transport it in an html query string we have to base64 encode it.

> when is the the fas key hashed for the encryption, is it in the function itself?

Yes

> why is faskey limited to 16 characters?

Technically it is not limited. Practically, there is little benefit having it longer than 16 characters as the initialisation vector is random for every encryption. The described limit is mostly for documentation purposes. Try a longer one ;-)

**Comment by bluewavenet** [comment]
@richyxi 
For your information, the devs are in discussion about splitting nodogsplash into two packages:
 1. a very small stripped down "tiny" version with only templated splash.html mode, optimised for IoT devices with very limited resources.
 2. A full FAS integrated version that can continue to be enhanced without compromising use on the afore mentioned IoT devices.

There will be an announcement here in due course. The initial "full" version will at least be the same as the current release.

**Comment by richyxi** [comment]
> Technically it is not limited. Practically, there is little benefit having it longer than 16 characters as the initialisation vector is random for every encryption. The described limit is mostly for documentation purposes. Try a longer one ;-)

I already did it, but the IV is not sended

**Comment by bluewavenet** [comment]
@richyxi 

> I already did it, but the IV is not sent

I use a 78 character key on a large project and it works fine.
What version of nodogsplash are you running?

**Comment by richyxi** [comment]
im using: Version: 4.3.4beta

**Comment by bluewavenet** [comment]
@richyxi 
On Raspbian?
Beta versions are at worst just daily snapshots.
The current release is 4.5.0. It will be best to upgrade to 4.5.0 as a starting point..
https://github.com/nodogsplash/nodogsplash/releases/tag/v4.5.0

**Comment by richyxi** [comment]
Sweet, works like a charm

Also the branch of version light and full of nds got me wonder, what kind
of iot devices are using the places in which nds is part of?

It's very interesting that there's like a demand for doing a light version,
focus just in iot.

Is there any open forum where this ideas are discuss?

Thank you for your time!

**Comment by bluewavenet** [comment]
@richyxi 
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560

**Comment by lynxis** [comment]
@richyxi the FAS will be moved out of nodogsplash. It will live in it's own project https://github.com/opennds/opennds
If you have further questions regarding FAS please open an issue there.
