### ISSUE TITLE
offline modus issue

### ISSUE THREAD

**Issue by sh1va73** [nodogsplash/nodogsplash#551]
I have set up a portal on my Pi4 and it works fine on my phone. When I open internet on my phone then the captive portal appears.

But when I open internet on my laptop then it does not work. This is because I need internet to make it working.

I have added address=/#/192.168.158.10 to dnsmasq.conf , pointing to what I have set up as router. But this does not help, it still not works on my laptop.

latest version on latest Raspbian on a Raspberry Pi 4.

**Comment by bluewavenet** [comment]
@sh1va73 
Resolving all DNS to a private ip address can have this effect on many recent CPD implementations.

Try it with your DNS set to respond with 121.122.123.124

This is discussed in issues #531 and #328

**Comment by sh1va73** [comment]
Thanks for the advice.
I added :
address=/#/121.122.123.124 to my dnsmasq.conf.

Still I don't get the captive portal page on my laptop (only I get it on my iPhone)

**Comment by bluewavenet** [comment]
@sh1va73 
Try disabling IPv6 support on your laptop.

**Comment by bluewavenet** [comment]
@sh1va73 
I am of course assuming you do not have CPD disabled on the laptop.

**Comment by sh1va73** [comment]
@bluewavenet Thanks for the suggestions. I have been testing a lot with multiple devices. For now the captive portal still only appears on multiple mobiles phones. But on desktops and laptops it does not popup. I tried disabling IPv6 . Also CPD is not disabled on those devices. I think I must have missed something in here.

**Comment by bluewavenet** [comment]
@sh1va73 
If it works on mobiles then this shows your configuration is good. The problem will most likely be a problem with the other devices.

Do the laptops/desktops use dhcp?  - This is essential.

Do the laptops/desktops have a local override for DNS servers? If they do, then this is the problem.

**Comment by sh1va73** [comment]
Yes they use DHCP and have no override. My guess is I am doing something wrong with address=/#/121.122.123.124 to my dnsmasq.conf. I tried other addresses but with no luck.

**Comment by bluewavenet** [comment]
@sh1va73 

> My guess is I am doing something wrong with address=/#/121.122.123.124 to my dnsmasq.conf.

But you said it works on mobiles, so dnsmasq config cannot be the problem.

**Comment by sh1va73** [comment]
Yes it works on mobiles, but then I don't add that line of code. Its because it didnt work on laptops that I added that line of code. But with that line of code it doesn't work, neither on laptop or mobile. Only without that line of code it works on mobile.

**Comment by bluewavenet** [comment]
@sh1va73 

> Its because it didn't work on laptops that I added that line of code.

I'm confused. That line is to FORCE offline mode. Offline mode is for situations where an Internet connection **_is not available_**. If one is available then this will prevent normal access as DNS will not resolve the correct addresses.

In your case then it seems you have two problems:
 1. There is something wrong with the network or CPD configuration (network manager) on your laptops. This could be dhcp override, preferential use of IPv6, CPD disabled or broken, etc....

 2. When forcing offline mode you have something wrong with your dnsmasq configuration - are you sure you do not have another dhcp server running somewhere?

**Comment by sh1va73** [comment]
Thank for getting back at me. Point 1 is not the case, I havent changed anything in those devices.
Yes i have DHCP running on the router. Is that the issue?
My guess its something wrong in the config files. To be complete I will post them here:
dnsmasq.conf
interface=wlan1       # Use interface wlan1
server=1.1.1.1       # Use Cloudflare DNS
dhcp-range=192.168.220.50,192.168.220.150,12h # IP range and lease time


hostapd.conf
interface=wlan1
driver=nl80211
ssid=MyAccessPoint
hw_mode=g
channel=6
#macaddr_acl=0
#ignore_broadcast_ssid=0
auth_algs=1
wmm_enabled=0

Then I followed these steps exactly:
https://pimylifeup.com/raspberry-pi-wireless-access-point/
https://pimylifeup.com/raspberry-pi-captive-portal/

**Comment by bluewavenet** [comment]
@sh1va73 
Are you saying this issue has nothing to do with offline mode? 
You tried offline mode because your laptop CPD was not working?

**Comment by sh1va73** [comment]
Exactly. Someone told me that i had to add that dnsmasq extra line for my laptop because it didnt open the captive portal. But this is wrong?

**Comment by bluewavenet** [comment]
That extra line is to allow client CPD to work when there is no Internet connection ie **Offline Mode**

Can you confirm that without that extra line in dnsmasq.conf:
 1. Mobiles successfully pop up the captive portal
 2. Your laptop does not pop up the captive portal

**Comment by sh1va73** [comment]
Thanks so much for your time and patience. 
1. yes it pop pop on all mobile devices
2. no it does not pop up on any laptop/desktop

**Comment by bluewavenet** [comment]
@sh1va73 
Assuming you have windows on your laptop, there is  a registry setting that is on by default but gets set to off by over enthusiastic security software. Worth checking it.
Registry setting to enable CPD:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\HotspotAuthentication
DWord: Enabled = 1

**Comment by sh1va73** [comment]
All devices are Mac devices, no Windows devices.

**Comment by bluewavenet** [comment]
@sh1va73 
There is similar for macOS.
In macOS, CPD is called "Captive Network Assistant". By default this is enabled but gets disabled by some security software.
I don't recall exactly how you check but is something like:
finder: go to folder >/System/Library/CoreServices
look for "Captive Network Assistant" and make sure it is enabled.

**Comment by sh1va73** [comment]
Yes that file is there and is enabled. When I go to captive.apple.com I get a text result: Success

**Comment by sh1va73** [comment]
I finally found the solution! All laptop/desktop had DNS server redirected to 1.1.1.1 and 1.0.0.1
After removing this it works fine.
I want to thank you @bluewavenet for all your advice and support. Much appreciated.

**Comment by bluewavenet** [comment]
@sh1va73 
Excellent!

**Comment by bluewavenet** [comment]
@sh1va73 
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560
