### ISSUE TITLE
Social Login - Facebook e Gmail - Firebase

### ISSUE THREAD

**Issue by ciborgcarom** [nodogsplash/nodogsplash#552]
Hello, has anyone managed to implement social login (for example, Facebook and Gmail) with Nodogsplash? I'm trying through FAS with NodeJS and I'm having a hard time.

Do I need to allow Facebook, Gmail and Firebase IPs for pre-authenticated users?

Is there any other way to do this, without releasing IP addresses?

Thanks in advance!

**Comment by bluewavenet** [comment]
@ciborgcarom 
Yes. there are none-open-source proprietary FAS implementations that do this, so it is indeed possible.

**It is your FAS server needs access to all the remote ip addresses, not the clients.**

The concept for how to make this work can be difficult to grasp, so here are some (rather simplistic) conceptual hints that should help:

1. Imagine you connect your desktop to the Internet. You can freely log in to Facebook and do whatever you like. Lets call this the first machine.

2. Now enable a remote control system on the desktop.

3. Connect another machine behind a firewall that allows only access to the first machine. lets call this the second machine.

4. On the second machine, open a remote session to the first machine. 

5. Login to Facebook.

6. An "operator" you left monitoring the first machine sees you have logged in to Facebook.

7. The operator then configures the firewall you are behind, to give you access to the Internet on the second machine.

In a real system:
 1. The firewall is NDS

 2. The first machine is the FAS server, the second machine is the client device

 3. The remote control system is a combination of CPD, NDS and FAS.

 4. The remote control client software on the second machine is the client CPD

 5. The remote control service software on the first machine is FAS

 6. The "operator" is FAS and on successful login it tells NDS to open the firewall for the client.

Hopefully this will clarify the concept and be useful for others also.

**Comment by bluewavenet** [comment]
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560

**Comment by lynxis** [comment]
@ciborgcarom we're splitting the FAS out of nodogsplash. It will live in it's own project opennds. Please ask there is you still have FAS questions.
