### ISSUE TITLE
Login.sh setup and modification

### ISSUE THREAD

**Issue by bomboem** [nodogsplash/nodogsplash#553]
Hi,
I am running nodogsplash on raspbian buster and it works like a charm. I have enabled the login form in nodogsplash.conf and when a client connects he is served the default portal requesting the e-mail and name of the user. Now, I'd love to write this page completely new and in php. I have no clue how to get started on thus so I'll ask questions and I hope somebody helps me.

I'd love to remove login.sh and make a login.php script.

Now:
1) How do I Tell NoDogSplash to look for login.php instead of login.sh

2) What variables are available to the script and how are they available to the script? Like requested_url and user_agent, how would I call these variables in my php script

3) How do I implement the authentication on the end of my php file when the user is done? How do I tell NoDogSplash this user is now allowed to surf the web?

I'm sorry for these stupid questions, I've read the documentation on NoDogSplash but I just can't figure out how to make a login script in php and how to correctly communicate with Nodogsplash and with ndsctl. Help would be very much appreciated

**Comment by bomboem** [comment]
Can someone help me to setup a php script work with php? I have php7.3 fully installed on my system, including php-cli. How do I use login.php instead of login.sh? It is very confusing to me.

**Comment by bluewavenet** [comment]
@bomboem 
Your questions are not stupid at all ;-)
Before doing anything else you should do the following:
 1. Compile and install NDS v4.5.0 if you do not have it already. (https://github.com/nodogsplash/nodogsplash/releases/tag/v4.5.0)
 2. Read the up to date documentation, particularly the PreAuth and FAS sections

You then need to decide if you want to run a separate http/php server or not and if you do whether you want it to be local or remote. Once you have done 1 and 2 above I am quite happy to give you some pointers.

**Comment by bomboem** [comment]
@bluewavenet I've read the preauth and the FAS documentation. Is it possible to **NOT** run a php server, and still use php as an interpreter for the preauth? Currently with the login.sh, ?clientip and all are attached to the url. I would like to all jeep it this way, but use a login.php script instead login.sh how would I do this (preferrably without a running php server and just php-cli)

**Comment by bluewavenet** [comment]
@bomboem 
Yes! A PreAuth script can be written in any language you have an installed interpretor for. It could even be a compiled binary if you wish.
You need to turn off the login.sh support in the config, and then set up a custom PreAuth as described in the documentation.

But first make sure you are running the release version (v4.5.0 at time of writing).

**Comment by bomboem** [comment]
@bluewavenet Do I just turn of the login option, or what line do I change in order to disable login.sh
And how do I tell NoDogSplash to use login.php? I know I'm asking the same things but I just can't figure it out reading the docs.

**Comment by bomboem** [comment]
Do I write "faspath usr/lib/nodogsplash/login.php", and how do I pass the `?clientip=xxx` to this script. And how do I tell nds to use php-cli?

**Comment by bluewavenet** [comment]
@bomboem 
You enabled login.sh by setting:
`login_option_enabled 1`
in the nodogsplash.conf file.
Change it back to the default (disabled):
`login_option_enabled 0`

Then upload your login.php to somewhere, /usr/lib/nodogsplash/ is fine.
Flag your login.php to be executable.
Add a shebang to the beginning of the login.php:
Here is an example trivial file with a suitable shebang - assuming the command on your system is php-cli, and its location is in /usr/bin/ 
You must adjust this to suit (this is correct in OpenWrt but may be different for you in Rasp):
```
#!/usr/bin/php-cli
<?php
print_r($argv);
echo "Hello World\n";
?> 
```

Test this by running `sudo /usr/lib/nodogsplash/login.php arg1 arg2 arg3`

The output should be:
```
Array
(
    [0] => /usr/lib/nodogsplash/login.php
    [1] => arg1
    [2] => arg2
    [3] => arg3
)
hello World
```


Finally set up your custom PreAuth config in nodogsplash.conf by adding the line:
`preauth /usr/lib/nodogsplash/login.php`

Reboot or restart nodogsplash and test.

**Comment by bomboem** [comment]
Thank you. Thank you for helping me so far, now I understand how it works. I have one more question, if I want to auth the user, how do I do this?
Is this the right way?:

`<?php
...Some php code
//If the user gets here in the script, they're allowed to use the internet
//I sanitzed the user ip to avoid remote execution 
exec(sudo ndsctl auth $clientip);
die();
?>`

Or should I do this another way?
I'm sure it's in the bash script, but I don't understand bash and I can't wrap.my head around it, that's why I ask it here.

Thanks a lot for the quick and clear replies! You're an amazing dev coping with someone like me 😁

**Comment by bluewavenet** [comment]
@bomboem 
No, don't do this.
You should use an html form to authenticate.
The code in login.sh (bash) is almost identical to the php version.

From login.sh:
```

	echo "<big-red>Thankyou!</big-red>"
	echo "<br><b>Welcome $usernamehtml</b>"

	# Add your message here:
	# You could retrieve text or images from a remote server using wget or curl
	# as this router has Internet access whilst the client device does not (yet).
	echo "<br><italic-black> Your News or Advertising could be here, contact the owners of this Hotspot to find out how!</italic-black>"

	echo "<form action=\"/nodogsplash_auth/\" method=\"get\">"
	echo "<input type=\"hidden\" name=\"tok\" value=\"$tok\">"
	echo "<input type=\"hidden\" name=\"redir\" value=\"$requested\"><br>"
	echo "<input type=\"submit\" value=\"Continue\" >"
	echo "</form><hr>"
```
	
To change this to php you just need semi colons at the end of each line!

**Comment by bomboem** [comment]
Thank you, this solved my issue.
