### ISSUE TITLE
Query string changes when user is authenticated

### ISSUE THREAD

**Issue by bomboem** [nodogsplash/nodogsplash#554]
Hi,

I'm running Nodogsplash in raspbian buster, and am using my own preauth script written in php.
I have discovered something weird when trying to write my php script. My login.php (preauth script) is very short:

```
<?php
$query_string=$argv[1];
$query=urldecode($query_string);
print_r($query);
?>
```

This displays the decoded query string in the user's browser when they visit the Nodogdplash page. When a user **IS NOT** authenticated, this is returned:
```
?clientip=192.168.220.96, gatewayname=NoDogSplash, redir=http://google.com/
```

The query parameters are split with a **comma space** ```, ```

**But**, when a user **IS** authenticated and visits the Nodogdplash page, this is returned:
```
clientip=192.168.220.96&gatewayname=NoDogSplash&gatewayaddress=192.168.220.1:2050&status=authenticated
```
The query parameters are now split with an **ampersand** ```&```.

This makes the programming rather difficult in order to check wether a user is authenticated or not. Is this an error? Or is this done on purpose? Or did I configure something the wrong way?

**Comment by bluewavenet** [comment]
@bomboem 
When a client deliberately attempts to directly access /nodogsplash_preauth/ when authenticated (ie without the CPD redirect), it should return an error page "403 Direct Access Forbidden".

This is a bug and will be fixed in the next release. Thanks for pointing it out!

**Comment by bomboem** [comment]
@bluewavenet 
I'm trying to make a user login system using my custom php preauth script and MySQL. I'm wondering now, as I'm adding multiple stages to my php script, can I just make a ```type->get``` form that targets ```/nodogsplash_auth/```, and am I able to acces those ```$_GET["somevar"]``` values in my script, or how does nds pass these form values to my script?

**Comment by bluewavenet** [comment]
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560

**Comment by lynxis** [comment]
@bomboem the FAS will be moved into it's own project. It will be removed from the next release.
If you've further questions towards the FAS, please open an issue in https://github.com/opennds/opennds
