### ISSUE TITLE
How can i download image from splash page. Click image then lost connection.

### ISSUE THREAD

**Issue by ByambaKh** [nodogsplash/nodogsplash#555]
I created hotspot, and login page with nodogsplash. I want to login page with image download page. when password  put into login page then can be download image files from image.html page. I already created but click image it's lost connection. Anyone can help, appreciate.

**Comment by bluewavenet** [comment]
@ByambaKh 
Perhaps you can explain in more detail what you are trying to achieve.

All captive portals, NodogSplash included, are triggered by the client CPD and the CPD browser will in most cases, close immediately the client authenticates.

You can read more about this in the documentation, particularly in the following sections:
https://nodogsplashdocs.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd
and
https://nodogsplashdocs.readthedocs.io/en/stable/faq.html#what-is-cpd-captive-portal-detection

**Comment by bluewavenet** [comment]
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560
