### ISSUE TITLE
Writing a PreAuth Script (moved from #554)

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#556]
Moved from #554 as it is a new question:
Posted by @bomboem

> I'm trying to make a user login system using my custom php preauth script and MySQL. I'm wondering now, as I'm adding multiple stages to my php script, can I just make a type->get form that targets /nodogsplash_auth/, and am I able to acces those $_GET["somevar"] values in my script, or how does nds pass these form values to my script? Are they accessible using $_GET[...] or are they sent as a command line paramater to my script and should I access them with $argv[...]?
> The login system would multiple pages (a signup dialogue) and in each step the script would be loaded again.

PreAuth is a special use case of FAS that is specifically designed to use the NodogSplash built in webserver libraries, thus eliminating the need for an independent webserver. This is particularly useful for legacy devices with limited flash and ram capacity, but can be used in any type of device.

Writing your own PreAuth script is discussed in detail in the documentation:
https://nodogsplashdocs.readthedocs.io/en/stable/preauth.html#defining-and-using-variables

It is very simple to set up a multi page signup dialogue and this is demonstrated in the default login.sh bash script.
It is a quite simple matter to convert this bash to php, or indeed any scripting language you have an interpretor for. You could even compile a binary from suitable C code for example.

Once you have digested the documentation, do please ask here if you need any help.

**Comment by bomboem** [comment]
@bluewavenet 
I am including the HTML in my php script for layout and form usage, but I can't seem to get the images to show up. Maybe you could help me?

For example, I have this in my html:
```
<img src="/images/mypng.png" alt="my png file" />
```
And I have mypng.png inside of the folder ```/etc/nodogsplash/htdocs/images/```, but when the "Login to network" pop up opens, I get the alt text ```my png file``` instead of my picture. Am I doing something wrong? If there's no way to do this I'm sure I could include my images as base64 encoded strings, but that would be quite messy.

**Comment by bomboem** [comment]
Found it! I was running a seperate webserver that apparently interfered with nds, making the png files return 404 when requested. Works fine now.

**Comment by bomboem** [comment]
I made a fully custom PreAuth script in php, if I find some time tomorrow or next week I'll make some sort of a how-to for php as I came across some difficulties.

Thank you @bluewavenet for helping me get here, and sorry for all the questions.

**Comment by bluewavenet** [comment]
@bomboem 

> Works fine now.

Excellent ;-)

> I'll make some sort of a how-to for php

Great thanks! We can incorporate it into the documentation.

**Comment by bluewavenet** [comment]
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560
