### ISSUE TITLE
Setting Firewall Rules

### ISSUE THREAD

**Issue by npateman** [nodogsplash/nodogsplash#56]
Hi there,

I'm trying to configure 2 firewall rules on nodogsplash but I don't seem to be able to locate the config file.  The only one I can find is located at

/etc/config/nodogsplash

This has firewall rules in it but it doesn't look like the ones in the documentation, for example, I want to add the following rules,

FirewallRuleSet: preauthenticated-users {
  FirewallRule allow to 54.231.132.144
  FirewallRule allow to 54.174.186.63
}

but in the config file all I can find is,

list preauthenticated_users 'allow tcp port 53'

If I have to set it here, what's the correct syntax for my 2 rules as above?

**Comment by npateman** [comment]
I tried changing the one in the source code prior to compiling it, but the changes don't get migrated across, oddly enough a search for nodogsplash.conf returns nothing.

**Comment by mwarning** [comment]
This should do the job:

    list preauthenticated_users 'allow to 54.231.132.144'
    list preauthenticated_users 'allow to 54.174.186.63'

**Comment by npateman** [comment]
awesome thanks! I'll give it a shot now
