### ISSUE TITLE
FAS API Moved to OpenNDS

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#560]
**OpenNDS v5.0.0 release**

The developers of NoDogSplash have decided to split further development into two separate packages. The next release of NoDogSplash will have all components of FAS removed and be optimised for running on devices with low storage and RAM, whereas OpenNDS will continue with the full suite of FAS options.

https://github.com/openNDS/openNDS

OpenNDS v5.0.0 is the first release of OpenNDS.
Binaries are available now on OpenWrt Snapshot and compatible with OpenWrt 18.x and 19.x

Testers for Debian variants would be very welcome!

OpenNDS is derived from the v4.5.0 release of Nodogsplash. As development of Forwarding Authentication Service (FAS) continues, it has become more and more difficult to not compromise optimisation of NoDogSplash for use on devices with very limited resources.

Initially, with this release, both OpenNDS and NoDogSplash are, apart from the FAS api, synchronised with the same basic code. As divergence is inevitable and developer time is at a premium, no attempts will be made to keep to the same common code.

**Comment by lynxis** [comment]
@bluewavenet I've created a branch v4 in nodogsplash. I would like to add a notice in the v4 branch, that further development with FAS will be splitted to opennds, while the minimized version will go to towards the master. I also plan to add a version notice in the doc explaining the history of the different versions.
