### ISSUE TITLE
Connection refused with FAS level 2 on remote server

### ISSUE THREAD

**Issue by carlitossuper1** [nodogsplash/nodogsplash#561]
I tried nodogsplash with my TL-WDR4300 on OpenWRT 18.06.7 (also 19.07.2 but couldn't install php7-cli and php7-mod-openssl together).

Set it up correctly with a remote shared hosting (with correct domain, ipaddress and path, even the key.).

But when entering the Captive Portal I get a ERR_CONNECTION_REFUSED.

What could it be?

On the logs it says that it was enabled successfully and I see the correct URL but there's no way to make it work.

PS: I'm aware of OpenNDS but I couldn't find the package on opkg install.

**Comment by bluewavenet** [comment]
@carlitossuper1 
FAs support is now at:
https://github.com/openNDS/openNDS
Please open a new issue there, including the details of your config file.
:-)

**Comment by lynxis** [comment]
FAS has been moved into an own project -> opennds. The FAS in nodogsplash will be removed with the next release.
