### ISSUE TITLE
Does faspath have to be a php page?

### ISSUE THREAD

**Issue by monelgordillo** [nodogsplash/nodogsplash#562]
Does faspath have to be a PHP page?

fas-aes.php

I'm hoping I can do this with python instead.

**Comment by bluewavenet** [comment]
@monelgordillo 
Please note NoDogSplash has now been split into two separate projects, NoDogsplash "lite"  which will be here and openNDS, the full FAS version at:
https://github.com/openNDS/openNDS

The next release of NoDogSplash will only support simple templated splash pages.
OpenNDS supports the full FAS API.

OpenNDS will work with any interpreted language your chosen web hosting server supports and can also use compiled binaries, running either local or remote.

If you would like any further information or to discuss in detail, please open an issue in OpenNDS
