### ISSUE TITLE
NoDogSplash and Forwarding Accounting Service?

### ISSUE THREAD

**Issue by monelgordillo** [nodogsplash/nodogsplash#563]
I have a remote RADIUS server setup.  I have a remote fas-aes.php working.  I am able to use a username & password on the captive portal successfully.

The next goal for me is accounting.  I would like to see how much data has been downloaded/uploaded by an authenticated user.  To do this, I need to send accounting attributes/information to the RADIUS server.  Is there a Forwarding Accounting Service yet?  I'm guessing not? crossing-fingers and toes.  

I did notice some utilities.  /usr/bin/ndsctl clients is promising.  It shows downloaded/uploaded information by client IP address & mac address.  

Any thoughts/recommendations would be greatly appreciated.  

Just in case others are interested: I used boo/radius (https://github.com/jyggen/radius) for the authentication piece in fas-aes.php.

**Comment by bluewavenet** [comment]
@monelgordillo
Please note NoDogSplash has now been split into two separate projects, NoDogsplash "lite" which will be here and openNDS, the full FAS version at:
https://github.com/openNDS/openNDS

The next release of NoDogSplash will only support simple templated splash pages.
OpenNDS supports the full FAS API.

If you would like to discuss more about "Forwarding Accounting", please open an issue in OpenNDS
