### ISSUE TITLE
session start issue

### ISSUE THREAD

**Issue by richyxi** [nodogsplash/nodogsplash#564]
hi, hope you all doing well!
im facing a wierd issue using NDS on GL-MT300N-V2

binauth is enable, the script is getting the parameters but those are really out of sight 

eg.
`Sun May 10 00:03:09 2020 daemon.debug nodogsplash[2453]: Executing command: /root/run.sh idle_deauth 48:4b:aa:92:fb:af 499504 62102 6825301027524656607 18613409008320512`

as you may notice, session start and session end are not correct, the correct input will something like "1588731573" or some similar values.
FYI, in my rpi i have the same set up and it works normal.

actual set up:
modem: GL-MT300N-V2
version: 4.5.1beta (it was tested on 4.3.3 with same results)
config: 

```
  config nodogsplash
  # Set to 0 to disable nodogsplash
  option enabled 1

  # This hook is needed as a restart of Firewall overwrites nodogsplash iptables entries.
  option fwhook_enabled '1'
 
  option gatewayinterface 'br-lan'
  option maxclients '250'

  option fasremoteip xx.xx.xx.xx.xx
  option fasport 80
  option fasremotefqdn fqdn.com
  option fas_secure_enabled 2
  option gatewayname xxx-xxxx-x
  option RedirectUrl google.com
  option faskey 1234567890
  option binauth '/root/run.sh'
  option redirecturl 'https://www.google.com/'
  option authidletimeout '22'
  option use_outdated_mhd '1'

  option preauthidletimeout '30'
  option sessiontimeout '1200'
  option checkinterval '600'
```
i just put the relevant things

thanks in advance!

**Comment by bluewavenet** [comment]
@richyxi 
NodogSplash has now been split into a lightweight version supporting only the templated splash page (NodogSplash) and a version with the full FAS/BinAuth API (openNDS).

The version you require is openNDS and the current release is v5.0.1.

**_For support please open a new issue at:_**
https://github.com/openNDS/openNDS
remembering to state the OpenWrt version you are using.

The installable .ipk for the 5.0.1-1 stable release  of openNDS (Openwrt on MT300N-V2) can be downloaded here:
https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/routing/opennds_5.0.1-1_mipsel_24kc.ipk

**Comment by richyxi** [comment]
thanks!
