### ISSUE TITLE
Android TV connection problems.

### ISSUE THREAD

**Issue by saul-avikar** [nodogsplash/nodogsplash#565]
I have got nodogsplash working as intended with PreAuth however when I connect a Android TV device ([smartVU](smartvu.co.nz)) with it added as a trusted mac, it will connect but be unable to access the internet (it will not state this like it would if something was blocking internet access). 

Running `ndsctl` shows that it is not getting picked out by the splash page and `logread` is not showing any apparent errors or warnings. Tested adding an android phone to the trusted macs and it works fine so I think perhaps there is something specific that nodogsplash is blocking that Android TV needs.

NDS: v4.5 beta
Device: Raspberry Pi 4B

**Comment by bluewavenet** [comment]
@saul-avikar 
NodogSplash has now been split into a lightweight version supporting only the templated splash page (NodogSplash) and a version with the full FAS/BinAuth API (openNDS).

The version you require is openNDS and the current release is v5.0.1.

For support please open a new issue at:
https://github.com/openNDS/openNDS
remembering to state the versions of everything including your operating system and sharing your openNDS config.

**Comment by bluewavenet** [comment]
@lynxis 
This issue can be closed.
