### ISSUE TITLE
make install 

### ISSUE THREAD

**Issue by tinwinaung** [nodogsplash/nodogsplash#566]
I am having error on RaspberryPi for make install beause of the following line in Makefile

cp forward_authentication_service/PreAuth/demo-preauth.sh $(DESTDIR)/etc/nodogsplash/login.sh

Should I remove it?

**Comment by bluewavenet** [comment]
@tinwinaung 
What error are you getting?

**Comment by tinwinaung** [comment]
strip nodogsplash
strip ndsctl
mkdir -p /usr/bin/
cp ndsctl /usr/bin/
cp nodogsplash /usr/bin/
mkdir -p /etc/nodogsplash/htdocs/images
cp resources/nodogsplash.conf /etc/nodogsplash/
cp resources/splash.html /etc/nodogsplash/htdocs/
cp resources/splash.css /etc/nodogsplash/htdocs/
cp resources/status.html /etc/nodogsplash/htdocs/
cp resources/splash.jpg /etc/nodogsplash/htdocs/images/
cp forward_authentication_service/PreAuth/demo-preauth.sh /etc/nodogsplash/login.sh
cp: cannot stat 'forward_authentication_service/PreAuth/demo-preauth.sh': No such file or directory
make: *** [Makefile:45: install] Error 1

**Comment by tinwinaung** [comment]
This issue is reported in #568

**Comment by bluewavenet** [comment]
@tinwinaung 
As you are not constrained by resources and as the new stripped down version of NoDogSplash is so far incomplete, you might be better off using OpenNDS instead.
The current release of OpenNDS is stable and can be downloaded here:
https://github.com/openNDS/openNDS/releases/tag/v5.0.1

**Comment by tinwinaung** [comment]
Hi @bluewavenet ,

Thanks for suggestion. Yes, I did as I am using RPi 4 with latest Buster lite version.
However, I got dependency issue where I need latest version of libmicrohttpd. I try to compile it from source but I still need to find out how to make it work (as i still got complain after make install). It will be good if someone update readme with how to compile dependencies for someone like me (If they are too new).  I just wish. You already did a very good job

**Comment by bluewavenet** [comment]
@tinwinaung 
To use the older versions of libmicrohttpd you can set, in your opennds.conf, the option:
`use_outdated_mhd 1`
This will work fine in most circumstances. The older versions have an issue with the built in unescape function so strings, for example usernames and passwords might be corrupted if some non-alphanumeric characters are used.

**Comment by tinwinaung** [comment]
Thanks, I will close the issue as the reason and work around are already discussed here
