### ISSUE TITLE
nodogsplash vs OpenNDS

### ISSUE THREAD

**Issue by tinwinaung** [nodogsplash/nodogsplash#567]
May I know what are different use cases between this two project?

**Comment by bluewavenet** [comment]
@tinwinaung 
NoDogSplash will support only templated splash pages and be optimised for minimal resource requirements.
OpenNDS will support the full FAS/PreAuth/BinAuth API in addition to templated splash pages.

**Comment by tinwinaung** [comment]
Thanks
