### ISSUE TITLE
Redirect & internet error

### ISSUE THREAD

**Issue by pole28** [nodogsplash/nodogsplash#570]
I have a RASP PI 3 B+, image-iso is OpenWrt.
Router (not the rasp) of network: 10.0.10.1.
Rasp (connected with ethernet cable and then also in wifi of .1): 10.0.10.95.
I tried two solutions: dumb and “normal” access point.
One error for solution.

DUMB ACCESS POINT

Network->interfaces->br-lan (default br-lan=eth0+wlan0):
        Ip addr: 10.0.10.95
        Gateway: 10.0.10.1 (tried also .95 -> connection works the same)
        Broadcast: 10.0.10.1 (tried also .255 like default)
        Dns: 10.0.10.1
        Dhcp (in Network->interfaces): disable
Go on System-Service:
        Dnsmasq: disable
        Odhcpcd: disable
        Firewall: enable (default) (but i try also disable before iptables-try)
Now (disable dns-dhcp) this is a DUMB access point (it works as a dumb).
Then install nodogsplash (default configuration: interface br-lan which is 10.0.10.95 with default other settings like authenticated allow all, fwhook enabled 1...).
Now I want that every first access to wifi-RaspberryPi goes on 10.0.10.95 to the nodogsplash-splashpage.
I try some iptables like the classic
        (#iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT  --to-destination 10.0.10.95:2050
#iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination 10.0.10.95:2050
#iptables -t nat -A POSTROUTING -j MASQUERADE)
        and also with -i br-lan, and other similar iptables (ex: like https://openwrt.org/docs/guide-user/firewall/fw3_configurations/fw3_nat).
But it does not work. I want that, when you click on wifi, the nodogsplash-splashpage starts (like in my other solution, namely like default nodogsplash function).
I did not try much on internet..
With this configuration, phone connected can go to the internet (also before they are authenticated..), and if you digit 10.0.10.95 in URL you can click "continue" and nodogsplash works (user preauthenticated begins authenticated and go to internet through 10.0.10.1).
Question: With this "dumb mode" there is some way to redirect the first page to 10.0.10.95 (iptables of rasp firewall or maybe firewall of .1 or other..)?

NOT DUMB ("OPENWRT DEFAULT") ACCESS POINT

Instead, if I use Raspberry not as a dump but as a  “normal“ ap (with dnsmasq, odhcpc…, and the same configuration of network-interfaces-br-lan (I can also use .95 as gateway.. look like works same as .1)):
Network->interfaces->br-lan (default br-lan=eth0+wlan0):
        Ip addr: 10.0.10.95
        Gateway: 10.0.10.1 (tried also .95 and works the same)
        Broadcast: 10.0.10.255
        Dns: 10.0.10.1 (tried also 8.8.8.8)
        Dhcp (in Network->interfaces): enable
Go on System-Service:
        Dnsmasq: enable
        Odhcpcd: enable
        Firewall: enable
When I click on wifi the first thing is “login” of nodogsplash (thing that I want in the other solution). But ap works (also with gateway 10.0.10.95 (that is watchable by app Iptools from phone) -> then the waterfall-effect that route from .95 to .1 works -> then I think Proxy does not resolve (I also tried Squid-proxy but nothing)) only without nodogsplash.
Then when nodogsplash runs, this waterfall-effect crash and phone connected cannot go to internet (they have a IP assigned by DHCP but N/A by Iptools-info) (I try tcpdump but its results are not "user-friendly" for me..
I send a line that repeats itself more than the others:
17:17:41.474615 IP Pulpstone-OpenWrt.lan.2050 > GalaxyPhone.lan.42318: Flags [F.], seq 277, ack 689, win 254, options [nop,nop,TS val 158172 ecr 1417732], length 0
17:17:41.476522 IP GalaxyPhone.lan.42318 > Pulpstone-OpenWrt.lan.2050: Flags [.], ack 148, win 829, options [nop,nop,TS val 1417742 ecr 158172], length 0
And dns I think works but im not good to interpret tcpdump:
17:17:41.494163 IP Pulpstone-OpenWrt.lan.52819 > 10.0.10.1.53: 40469+ A? www.samsung.com. (33)
17:17:41.537481 IP 10.0.10.1.53 > Pulpstone-OpenWrt.lan.52819: 40469 4/13/8 CNAME www.samsung.com.akadns.net., CNAME www.samsung.com.edgekey.net.globalredir.akadns.net., CNAME e1722.x.akamaiedge.net., A 92.122.248.68 (512))
Namely I think: set network->interfaces->br-lan-gateway .1 or .95 does not change because traceroute-path goes always through .1.. I think that nodogsplash force the gateway to 10.0.10.95 but in that case .95 cannot route ("waterfall-effect") the internet to .1).
That is: when I click on nodogsplash-splashpage “continue” (nodogsplash status says: <my phone ip> authenticated), but nothing happen (internet error).

Then I have this two problem in two different solution (dumb redirect in dumb case and internet error in the second case). If I resolve one, I follow that solution I think.

Thanks

**Comment by bluewavenet** [comment]
@pole28 
You seem to have a fundamental misunderstanding about how a captive portal works and this has led you to making a deep dive into areas that have nothing to do with your problem.

I would suggest you read the documentation, particularly the section on how NDS works:
https://nodogsplashdocs.readthedocs.io/en/stable/howitworks.html#how-nodogsplash-nds-works

You will note the documentation states:

> NoDogSplash MUST run on a device configured as an IPv4 router.
> 
> A wireless router will typically be running OpenWrt or some other Linux distribution.
> 
> A router, by definition, will have two or more interfaces, at least one to connect to the wide area network (WAN) or Internet feed, and at least one connecting to the local area network (LAN).
> 
> Each LAN interface must also act as the Default IP Gateway for its LAN, ideally with the interface serving IP addresses to client devices using DHCP.
> 

I don't see how the "Dumb/Not Dumb" terminology you are using relates to the requirements for NDS.

**Comment by bluewavenet** [comment]
@lynxis 
This issue can be closed.
