### ISSUE TITLE
What's authidletimeout?

### ISSUE THREAD

**Issue by MannyDo** [nodogsplash/nodogsplash#571]
I get quite confused about the "option authidletimeout " in the NDS configuration file, does it mean the client  not using the wifi for ## minutes will be forced out ? In case my sessiontimeout set to zero, my guess is that the client will never been forced out if it keep using the wifi?

and what's preauthidletimeout? why we need this option? plz help

**Comment by bluewavenet** [comment]
@MannyDo 
This is all documented in the config file
For reference, here it is:
```
# Parameter: SessionTimeout
# Default: 0
#
# Set the default session length in minutes. A value of 0 is for
# sessions without an end.
#

# Parameter: PreAuthIdleTimeout
# Default: 10
#
# Set PreAuthIdleTimeout to the desired number of minutes before
# an idle pre-authenticated user is automatically removed from the client list.
#

# Parameter: AuthIdleTimeout
# Default: 120
#
# Set AuthIdleTimeout to the desired number of minutes before
# an idle authenticated user is automatically 'deauthenticated'
# and removed from the client list.
#

```
PreAuthIdleTimeout is essential to free up client connection slots as these are limited by the "maxclients" setting.
