### ISSUE TITLE
Functionality of FirewallRuleSet users-to-router

### ISSUE THREAD

**Issue by TerryJColes** [nodogsplash/nodogsplash#573]
Can I please request some clarification on how the FirewallRuleSet users-to-router is supposed to work?  I initially installed nodogsplash on a Raspberry Pi at our local Model Town in 2017 and have recently updated the system to add some functionality.

Originally we used nodogsplash somewhat 'back-to-front' in that our network has a couple of outdoor WiFI Antennas so that Visitors can view some local content.  The Town is a charity so were unwilling to allow Visitors unfettered access to the Internet to preserve the limited bandwidth allocation.  I therefore provided sufficient access to Pre-authenticated users to satisfy Android phones and then blocked everything to Authenticated users.  However, I did use the users-to-router section of the Conf file to allow users actually on the network (ie us) to get to the Internet to update the software on the Pis on the network.  However, it doesn't work.

Back in 2017, we weren't too worried about this because there were only two Pis on the network but now there are around a dozen so allowing Internet access to us would be a distinct advantage now.  I have attached the current .conf file.  Can you tell if this should do what I need?
[nodogsplash.conf.zip](https://github.com/nodogsplash/nodogsplash/files/4809320/nodogsplash.conf.zip)

**Comment by bluewavenet** [comment]
@TerryJColes 
Rules in the users-to-router section allow clients (preauthenticated or authenticated) to access **something on the router**

It sounds to me like you need a typical "Museum Venue" type of setup where visitors are presented with a "splash" site with the local content. The splash site will have an option for a username/password login so "staff" can log in and have Internet access.
The multiple Pis would each be added to the trusted list so when a staff member logs in to NDS, they can for example SSH to the multiple Pis and do what is required on the Internet from the perspective of the individual Pi.

This is very easy to set up using forwarding authentication scripts (FAS), where a more functional splash page can be designed.

Unfortunately, NoDogSplash has recently split into two versions, a basic small footprint version for IoT devices with very limited resources (now known as NoDogSplash), and a full version providing multiple authentication options and an API (now known as openNDS)

openNDS is what you will need for the type of setup I described above, with one of its standard  login methods being simply modified to match your requirements.

Let me know if you need any further information.

openNDS:
https://github.com/openNDS/openNDS

**Comment by TerryJColes** [comment]
OK.  Thanks for the quick response.  Just to complicate things a bit; could openNDS be set up so that a user outside the Model Town, connecting via a VPN Server on the same Pi, could authenticate himself as a staff user and get the same functionality?

Or would this only work if the staff member was on site and connecting via the WiFi Antennas?

**Comment by bluewavenet** [comment]
@TerryJColes 
If a VPN tunnel exists between a (trusted) Pi and someone on the Internet, then NDS would not come into the equation.
It would depend on how that VPN tunnel established itself. For example, if the openNDS Pi was running the VPN server AND was accessible from the Internet, then it would work. 
Another way is to have a VPN client running on the Pi and have it connect to a remote server when it boots.
There are many ways.
A VPN is not necessary for remote access though, port translation and SSH would be good enough most likely.

**Comment by TerryJColes** [comment]
Thanks for the info.  I've shared it with the other members of the team at the Model Town.  We are closed at the moment, due to the lockdown, (this was what triggered the installation of the VPN), however, we are opening in about three weeks, so we may wait until the Winter shutdown.

In the meantime, I'll close this issue and open a new one if I have any problems configuring openNDS.

Thanks again for your help.
