### ISSUE TITLE
VERSION 4.x CAN'T INSTALL

### ISSUE THREAD

**Issue by giro0710** [nodogsplash/nodogsplash#574]
**I can't install NDS to my TP-Link TL-MR3420v5 router since version 4.x has released.** Anyone please help me fix this or suggest new router brand/model that will work on version 4.x or later

**Comment by bluewavenet** [comment]
@giro0710 
See:
https://github.com/openNDS/openNDS/issues/25

**Comment by lynxis** [comment]
@giro0710 as @bluewavenet written in the openNDS ticket, please update your image to the latest stable version of OpenWrt.

If you still have problems, please re-open this ticket.
