### ISSUE TITLE
Binauth is being sent 'na' from custom index inputs (not the input value)

### ISSUE THREAD

**Issue by Ryazbeck** [nodogsplash/nodogsplash#576]
fas is 0
custom binauth file
custom index file with two fields

```
        <form method="get" action="$authaction">
          <input type="hidden" name="tok" value="$tok">
          <input type="hidden" name="redir" value="$redir">

          <div>SSID:<br></div> 
            <input type="text" id="ssid" name="ssid" value="">
          <div>Password:<br></div> 
            <input type="password" id="wkey" name="wkey" value="">

          <input type="submit" value="Continue">
        </form>
```

When I submit that form it sends 'na' for both ssid and wkey

`BinAuth argv: /etc/nodogsplash/binauth_sitewide.sh auth_client d0:77:14:8f:4a:72 'na' 'na' 'http%3a%2f%2fconnectivitycheck.gstatic.com%2fgenerate_204' 'Mozilla%2f5.0%20%28Linux%3b%20Android%208.0.0%3b%20Moto%20Z%20%282%29%20Build%2fOCXS27.109-51-14-7%3b%20wv%29%20AppleWebKit%2f537.36%20%28KHTML%2c%20like%20Gecko%29%20Version%2f4.0%20Chrome%2f83.0.4103.106%20Mobile%20Safari%2f537.36' '192.168.100.115'
`

How do I pass the values from the inputs to binauth?

**Comment by Ryazbeck** [comment]
And I figured this one out too by finally realizing the vars you built in are username and password :smile: 

> Additional Variables that can be passed back via the HTTP get,
> or appended to the query string of the authtarget link:
>    username
>    password


Thank you for maintaining this CPD! It is super helpful.

**Comment by bluewavenet** [comment]
@Ryazbeck 
FAS/PreAuth/BinAuth support has been moved to the openNDS project, while NodogSplash will be stripped back to a minimal functionality, very low footprint version aimed at IoT devices with very restricted resources.

openNDS is currently at release 5.1.0 and includes custom variable support for BinAuth.

See:
https://github.com/openNDS/openNDS/tree/5.1.0
and:
https://opennds.readthedocs.io/en/stable/binauth.html#method-auth-client
