### ISSUE TITLE
opening ports for paypal in nodogsplash

### ISSUE THREAD

**Issue by maccored** [nodogsplash/nodogsplash#581]
Hi

(1) Im using the walled garden in nodogsplash and everything is working fine - except paypal.  I can set ips and ports in the config file and they work fine, but Ive put in every paypal ip I can find plus ip ranges, and I cant access paypal.com at all. Knock off NDS and I can access everywhere. Turn it on and I can access all the walled sites but still not paypal.

I assume NDS kicks in after the firewall and creates its iptables from the config so how do I get round this?  Suggestions welcome

Ideally I'd just like the user to connect to wifi and go straight to the web without logging in.  Ive tried the FAS and Splash pages and these work ... (2) but when I go to click a link within the portal, it asks me if I want to open the link in an external browser rather than continuing on.

Two separate issues I know .... an answer to either would work

**Comment by bluewavenet** [comment]
@maccored 
 1. I am not sure of the support for Walled Garden in NoDogSplash, but in openNDS you can define the Walled Garden by FQDN.

 2. Also FAS support has been moved to openNDS. FAS can be used to link various pages.

For support with these issues it would be better to open an issue at openNDS
https://github.com/openNDS/openNDS
https://opennds.readthedocs.io/en/stable/walledgarden.html#walled-garden

**Comment by maccored** [comment]
thanks - I need to upgrade then. Luci doesnt give an option to upgrade to V 5 ... is openNDS a completely new package replacing NoDogSplash?

**Comment by bluewavenet** [comment]
@maccored 
The original NoDogSplash project has forked. openNDS continues with development of the FAS API and NoDogSplash has FAS removed so it can be optimised for devices with limited resources.

If you are on OpenWrt 19.07.x then:
```
opkg remove nodogsplash
opkg update
opkg install opennds

```
If you are on OpenWrt 18.x or earlier then you will have to download openNDS v5.2.0 from the OpenWrt downloads site for 19.07.x (let me know your device and I can give you a specific link)
If you are on OpenWrt snapshot then you will need openNDS v6.0.0 or higher:
```
opkg remove nodogsplash
opkg update
opkg install opennds

```
If you are on a non-OpenWrt Linux then you must download the release and compile yourself.
https://opennds.readthedocs.io/en/stable/compile.html#linux-unix-compile-in-place-on-target-hardware

**Comment by maccored** [comment]
thank you. Ive installed and again all is working.  I also installed ipset and dnsmasq-full.  I still cant get the link to paypal to connect though.  it tells me it cant connect to the server.  Sorry for allt he questions, but below is how I have the wall garden set up in the config ... where am I going wrong? Thanks again for your help

ipset create openndsset hash:ip
    uci add_list dhcp.@dnsmasq[0].ipset='/paypal.com/paypalobjects.com/openndsset'
    uci commit dhcp
        # Configure opennds by uncommenting the following two lines:

    list preauthenticated_users 'allow tcp port 80 ipset openndsset'
    list preauthenticated_users 'allow tcp port 443 ipset openndsset'

**Comment by bluewavenet** [comment]
@maccored 
Please open a new issue at openNDS:
https://github.com/openNDS/openNDS/issues

**Comment by maccored** [comment]
will do!
