### ISSUE TITLE
PHP FAS?

### ISSUE THREAD

**Issue by katexu7** [nodogsplash/nodogsplash#583]
Hi,

I've tried following all the instructions to get a local PHP page hosted through nodogsplash captive portal. Everything works when I just use splash.html as the captive portal. However, when I try to change it to PHP by following the instructions for FAS (within the fas-aes.php file), it redirects the user to download the actual PHP file. This leads me to think that there is no Apache/lighttpd running the PHP file? Are there instructions anywhere detailing this? Do I need to host it in a different directory like /var/www/html/index.php to get it up and running? I'm a little confused because the instructions specify that the faspath has to be relative to the /etc/nodogsplash/htocs directory. 

I've changed the following in nodogsplash.conf

  option fasport '2050' (Should this be the same as the gateway port for locally hosted FAS?)
  option faskey '1234567890'
  option faspath '/fas-aes.php

everything else is default (fas_secure_enabled set at default 1) / same as non-FAS captive portal. 

Thanks and advance.

**Comment by katexu7** [comment]
And I read other sources that says nodogsplash does not support PHP. I assume this just means it can't be done directly as splash.php? Otherwise it's a little confusing why fas-aes.php be written in PHP?

I have also installed cli-php7.3 (or whatever it was called) as well as apache2 & lighttpd with the same problem persisting.

**Comment by bluewavenet** [comment]
@katexu7 
FAS support has been moved to the openNDS project.
From the NoDogSplash README.md:

> Nodogsplash has been splitted into 2 projects:
> 
>     OpenNDS containing the FAS (Forward Authentication Service)
>     Nodogsplash containing a minimal version.
> 

You can find openNDS at:
https://github.com/openNDS/openNDS

and the documentation for FAS at:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

**Please open an issue at openNDS for support.**
Remember to state your hardware and operating system/operating system version.
See you over there :-D

**Comment by katexu7** [comment]
Thanks. Will move it over.
