### ISSUE TITLE
Open Ports on Raspberry Pi Running nodogsplash

### ISSUE THREAD

**Issue by TerryJColes** [nodogsplash/nodogsplash#588]
Hi,

Could I ask a question about which ports are opened by nodogsplash.  In June I installed the then current version of nodogsplash on our (private) webserver at our local Model Town.  Subsequently, I installed a VPN Server on the same network, to allow us to access the network during lockdown.  Both packages are installed on Raspberry Pis (but not the same one).

Prior to this, the only access to the Internet from the private network was through nodogsplash for authentication of Android devices, but this changed with the VPN.  This triggered a query on how 'safe' the network was from being hacked, so we have recently done Port Scans on various machines in the private network and from the Router side of the Webserver to try to set minds at rest.  This has worked by and large, but the Webserver has thrown up a lot of UDP ports labelled 'Unknown' by nmap.  I'm assuming that these are related to the Firewall set up by nodogsplash, but I can't work out how they are set up to see if there any that shouldn't be there.

I have identified that the file fw_iptables.c probably sets up the routing tables, but I cannot see how it works (not being a programmer).  Can you point to a list?

Thanks in anticipation.

**Comment by bluewavenet** [comment]
@TerryJColes 
Firstly, be aware that if you are using any combination of FAS/PreAuth/Binauth then support for your issues can only be provided by the openNDS project. If this is the case, please open an issue there:
https://github.com/openNDS/openNDS

Ports opened by NDS are defined in, and only in, the config file.

Before helping, either here or at openNDS we would need a clearer description of what you actually have in your set up.

**Comment by TerryJColes** [comment]
OK,  Thanks.  That's all I needed to know.
