### ISSUE TITLE
Can we force the NDS splash.html

### ISSUE THREAD

**Issue by iTommix** [nodogsplash/nodogsplash#589]
Is it possible to show the splash.html every time a user connect to that network? Or with other words: How to logout a connected user completely?

It's of course not an issue at all, but the possibilities and info about might be usefull.

Thanks in advance.

Thomas

**Comment by bluewavenet** [comment]
@iTommix This obviously happens for all non authenticated clients.
If a client reconnects after returning to the area outside the authidletimeout interval then they will be served the splash page again, triggered by the client CPD.
The default value for authidletimeout is 120 minutes I think. Just reduce this to a much smaller value.

**Comment by iTommix** [comment]
@bluewavenet Yes, i understand this. But i'm using NDS in an "unusual" way, means not only as Captive Portal. So, reduce the timeout is not usefull in my case. I need some kind of "logout" and "forget me". I try to investigate the iptables, maybe there is a way to achieve this.

I've read the docs [here](https://nodogsplashdocs.readthedocs.io/en/stable/howitworks.html) but i dont get the meaning of "AllowedMACList". Maybe this is a way, too.

Regards

Thomas

**Comment by bluewavenet** [comment]
@iTommix 
Do you want:

1. an administrator to log them out?
2. the client to be able to log themselves out?

For 1. use ndsctl deauth [clientip/clientmac/clienttoken]
For 2. upgrade to openNDS, user logout can then be easily achieved by FAS

**Comment by iTommix** [comment]
@bluewavenet 

Yes, option 2 i need. If you know how to do it with NDS, it would be usefull. From my opinion there must be a "known user table" or something like this. My knowledge about iptables is too less.

But i will take a look to your suggested openNDS.

Thanks

**Comment by bluewavenet** [comment]
@iTommix 
You can either hack the code in Nodogsplash or edit the basic openNDS login option script file (login.sh) to add a logout button, a trivial change. If you want to ask questions about openNDS please open an issue there.
https://github.com/openNDS/openNDS

**Comment by iTommix** [comment]
Done it by calling

`http://gatewayaddress:gatewayport/nodogsplash_deny/`

in a browser. Then the user will be deauthenticated.

**Comment by bluewavenet** [comment]
@iTommix 
Excellent! From memory, this was deprecated around version 4, but I forgot NoDogSplash was forked at version 3 so this has found its way back in. Well spotted ;-)
