### ISSUE TITLE
FAS on Nodogsplash (Raspberry Pi)

### ISSUE THREAD

**Issue by laimermic** [nodogsplash/nodogsplash#595]
Hi,

I set up Nodogsplash on my Raspberry Pi and now i want to enable FAS to redirect to a php File. I was looking a lot in the Internet but i didn't find any unambiguous Solution. How do i enable FAS to redirect to a php File?

Best regards

**Comment by bluewavenet** [comment]
@laimermic 
NoDogSplash has been split, creating two separate projects:

 1. **NoDogSplash** which has had the FAS API stripped out for the purposes of optimisation for running on devices with very restricted resources. _It now supports only the original templated html splash page._

 2. **openNDS** which supports the full FAS API, very flexibly allowing development of an unlimited range of authentication scenarios. The Forwarding Authentication Service (FAS) component can range from a simple local bash script through to a sophisticated and secure https web service.

For help with using a PHP FAS, please open an issue at openNDS:
https://github.com/openNDS/openNDS

When creating your issue, please state the model of RPi you are using and the operating system you are using.

You can read the documentation for openNDS at:
https://opennds.readthedocs.io

**Comment by laimermic** [comment]
Ah Thank you
