### ISSUE TITLE
Nodogsplash with raspberry pi3b+

### ISSUE THREAD

**Issue by DheerajTecheureka** [nodogsplash/nodogsplash#596]
I wanted to work on raspberry pi 3b+ and its my first project on raspberry. I am using my raspberry as a hotspot and have connected my airtel router via data cable to my raspberry for Internet access. I wanted to create a captive portal using nodogsplash or opennds. I don't want only continue button. I want to verify my client mobile number before authentication. Where my verification process is located remotely on http server and which is in php language. Is it possible ir not?
I wanted to replace opennds_preauth with my remote server. Please guide me what changes i need to do with my .conf file and splash page or any another changes i need to do. Please answer me.

**Comment by DheerajTecheureka** [comment]
I am using rasbian os

**Comment by bluewavenet** [comment]
@DheerajTecheureka 
Yes this is not only possible, but also in fact a very common type of setup. You will need to use the openNDS FAS API and make some simple customisation changes to the standard scripts.

I would suggest you open an issue at openNDS to discuss this at:
https://github.com/openNDS/openNDS

You will find it to be very advantageous to read the documentation at:
https://opennds.readthedocs.io/en/stable/

To get started, you should take particular notice of the documentation section entitled "How to Compile openNDS" and NOT follow the numerous online tutorials for Rasbian, as these are generally very outdated and in many cases actually incorrect.

**Comment by DheerajTecheureka** [comment]
Sure

**Comment by DheerajTecheureka** [comment]
I have created issue in openNDS section at#83 please check out and give me solution on that
