### ISSUE TITLE
Opennds FAS issues with external fas

### ISSUE THREAD

**Issue by DheerajTecheureka** [nodogsplash/nodogsplash#597]
I wanted to work on raspberry pi 3b+ and its my first project on raspberry. I am using my raspberry as a hotspot and have connected my airtel router via data cable to my raspberry for Internet access. I wanted to create a captive portal using opennds. I don't want only continue button. I want to verify my client mobile number before authentication. Where my verification process is located remotely on http server and which is in php language. Is it possible ir not?
I wanted to replace opennds_preauth with my remote server. Please guide me what changes i need to do with my .conf file and splash page or any another changes i need to do. Please answer me.

**Comment by DheerajTecheureka** [comment]
I need to change router setting in openwrt if yes then plz give me steps what changes i need to do.
I have try this with nodogsolash several time bt it has not possible then simply i called the iframe and collect the mobile number bt it is not professional and for this process i have to provide authentication first bt my maine moto to provide internet to client is collecting verify mobile number.my old mobile is giving success msg after authentication.before this i istalled opennds insted of nodogsplash bt i am not getting what changes i need to do with

**Comment by DheerajTecheureka** [comment]
I have created a new issue in opennds with #83 plz guide there

**Comment by bluewavenet** [comment]
That will be https://github.com/openNDS/openNDS/issues/83
