### ISSUE TITLE
Ports are not opened

### ISSUE THREAD

**Issue by tobiaskastl** [nodogsplash/nodogsplash#599]
Hello!

I'm really desperate because I'm trying to fix this problem for a very long time:

Short summary: I recently got a Raspberry Pi 3b+ with two important websites running on **port 3000 and port 5000** (on 3000 you can show the data of sensors and on :5000 there is a REST-API) of the ip-address of the pi. For example: type **"172.16.0.3:5000"** in the browser and **you get the REST-API**. My goal is to have an access point running on my pi with a captive portal which _opens the ports_.

I managed to "upgrade" my pi to an access point with "hostapd" and "dnsmasq" already and it's running just fine. I want users to connect to the AP, but **not** be able to reach port 3000 and 5000 **yet** - they should authenticate themselves on the nodogsplash-captive portal before they can reach those ports. My iptables-rule for blocking a port looks like this (I only tried 3000 for testing - I am going to add 5000 later if I get port 3000 to work):
`
-A INPUT -i wlan0 -p tcp -m tcp --dport 3000 -j REJECT
`
If I connect my phone to the access point, port 3000 is rejected but 5000 is still accessible (so it works).

Now, I thought, that if I add port 3000 to the _"FirewallRuleSet authenticated-users" with "FirewallRule allow tcp port 3000"_, it "opens" the port and I can access it - but it is **still closed**.

Where are the iptable-commands saved? Is it maybe the wrong file so the iptable-commands are not activated?
NDS puts the commands at the beginning of the iptables-file, no? Is it maybe possible, that the "open" command gets overwritten by the "reject" command? I have never worked with iptables before, maybe I get this wrong.

Would be awesome, if someone could help me with this topic! As I said, I'm struggeling with this problem for a while now. Thanks in advance!

**Comment by bluewavenet** [comment]
@tobiaskastl 
Note that NoDogSplash is now supposed to be the optimised version for resource limited IoT devices and as such has very restricted configuration options. It is not a good fit for a Raspberry Pi and you are very unlikely to get any support here.
I would suggest you migrate to openNDS, the full API version, and open an issue there.
https://github.com/openNDS/openNDS

openNDS has built in support for most Linux distributions. Details for compiling and installing can be found at this link:
https://opennds.readthedocs.io/en/stable/compile.html#linux-unix-compile-in-place-on-target-hardware

**Comment by tobiaskastl** [comment]
Alright, thanks!

**Comment by tobiaskastl** [comment]
@bluewavenet Is it difficult to upgrade to openNDS? What is the exact difference - just a newer version with more functionalities? Can I even use a captive portal just for a private network? I don't want / need a wifi-connection. Do you think it will work with my "internal network"? Cheers

**Comment by bluewavenet** [comment]
@tobiaskastl 

> Is it difficult to upgrade to openNDS?

Very simple. See this: https://opennds.readthedocs.io/en/stable/compile.html#linux-unix-compile-in-place-on-target-hardware
Note that you must first remove/uninstall the old version of libmicrohttpd and NodogSplash.

> What is the exact difference - just a newer version with more functionalities?

openNDS (currently at v8.0.0) is based on NoDogSplash but has the FAS API allowing great flexibility to customise.

Your original post does not describe clearly what you are actually trying to achieve so I cannot say what customisation you need.

> Can I even use a captive portal just for a private network?

Please explain what you mean by this.

> I don't want / need a wifi-connection.

A captive portal should work on any type of connection.

If you want further help, please open an issue at openNDS.

**Comment by tobiaskastl** [comment]
@bluewavenet I have an access point running which people can connect to (with their smartphone). They should only be able to access 172.16.0.3:3000 and :5000 after they authenticated themselves on my captive portal (either by pressing a "Continue"-button or by entering username + login) - 172.16.0.3 is the IP address of the raspberry. I tried to block port 3000 with iptables (so that NDS opens it after the user authenticated himself) - but it did not work; the port was still blocked. Now I wanted to know if the upgrade is worth it and if the problem (port not opening) will be fixed by upgrading.

**Comment by bluewavenet** [comment]
@tobiaskastl 
It is still not clear what you are trying to achieve or even if you need a captive portal.

See if you can give "yes" or "no" replies the following statements:

1. I want a web page to automatically open when clients connect.
2. I want clients to **ONLY** have access to my two web pages and nothing else.
3. I want my Pi to be free standing and have no connection to the Internet.
4. I don't even need a portal login, just one of my web pages popping up would be perfect.

**Comment by tobiaskastl** [comment]
1. Yes
2. Yes
3. Yes
4. Not really - some type of 2nd security after entering the access-point-password would be nice

**Comment by bluewavenet** [comment]
@tobiaskastl 
This establishes that you want some kind of informational/monitoring system with no Internet connectivity.

The openNDS FAS API makes this fairly simple to implement. Firewall settings will be configured entirely within the openNDS config.

In NoDogSplash, the "popup" portal page will most likely close immediately the client taps Continue... depends very much on the client device. In any event, Nodogsplash can only display a simple html splash page such as splash.html.
