### ISSUE TITLE
Firewall rule being ignored

### ISSUE THREAD

**Issue by npateman** [nodogsplash/nodogsplash#60]
Hi there,

I have the following rule in /etc/config/nodogsplash and it appears to be getting ignored by the Firewall as when I attempt to navigate to the IP address, I get the splash page.

list_preauthenticated_users 'allow to x.x.x.x'

(IP hidden for obvious reasons but I have double and triple checked that it is correct)

I also tried the following incase it was a disallowed port, but it's over port 80 which i understand I don't need to include separately?

list_preauthenticated_users 'allow tcp port 80'

This made no difference though, I have tried explicitly restarting nodogsplash using,

/etc/init.d/nodogsplash stop
/etc/init.d/nodogsplash start

or even just rebooting the router but the rule hasn't worked once yet, what is odd is that other rules have worked previously, but not this one.

**Comment by npateman** [comment]
Although this is still an issue for me I can't persue getting the firewall to work for me anymore simply down to it being unusable in a CDN scenario unless I whitelist the entirety of Amazon AWS which isn't something I want to do. I'm going to try for a different tactic.

**Comment by mwarning** [comment]
yes, it is a tricky subject with CDNs.

**Comment by npateman** [comment]
I'm not entirely sure if the other method I have in mind will work, maybe I can pass it by you for your input if that is okay?

Basically I was thinking that if I allow all web traffic to any address but everything else is blocked as it normally would be.  Instead there would be an entry in the configuration which would detail the domain names of my SSO server, if a page request comes in for something other than one of those or the splash page to redirect to the splash page.
