### ISSUE TITLE
Log output

### ISSUE THREAD

**Issue by npateman** [nodogsplash/nodogsplash#61]
Hi there,

Small stupid question, where is the log file generated for nodogsplash?

Nick.

**Comment by mwarning** [comment]
See /var/log/syslog

**Comment by ihardiksharma** [comment]
this is not stupid question. how to divert nodogsplash to separate file?

**Comment by mwarning** [comment]
you have to start nodogplash from console and redirect stderr and stdout to a file: `nodogsplash > /tmp/log.txt 2>&1`

**Comment by ihardiksharma** [comment]
Actually this thing works. I have to first run it with foreground and debug mode 5. ` nodogsplash -f -d 5 > /root/nodogsplashlog.txt 2>&1  &`
