### ISSUE TITLE
Automatically going to CP? Is it possible?

### ISSUE THREAD

**Issue by SolarDiode** [nodogsplash/nodogsplash#610]
Hi all

I have achieved the CP on the Raspberry Pi, the issue I want to overcome is to have the CP Page appear automatically no matter what domain is entered, so the user has to see the CP page without entering the IP address of the portal.

Thanks

**Comment by bluewavenet** [comment]
@SolarDiode 

> Automatically going to CP? Is it possible?

Automatically going to the CP is fundamental to how a CP works. This is what happens unless you have a desktop operating system with Captive Portal Detection (CPD) disabled.

All mainstream operating systems and all mainstream browsers have built in CPD functionality and most have it enabled by default.

Note that NodogSplash is intended for use on resource restricted IoT devices or legacy routers.
For any model Rpi (even the zero W), you should really be using openNDS as it has full functionality (see the NoDogSplash README.md file)

For details about CPD, see the openNDS documentation here:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

**Try connecting using your mobile phone.**
If this does not work for you, then most likely you have a configuration problem.

The most common misconfiguration seen on a Rpi running Raspbian is _not having it configured as a nat router._
Reading this section of the documentation should help:
https://opennds.readthedocs.io/en/stable/howitworks.html#how-opennds-nds-works

I would suggest you change to openNDS as it will report fundamental configuration errors on startup.
See here:
https://opennds.readthedocs.io/en/stable/compile.html#how-to-compile-opennds
