### ISSUE TITLE
cant find fas docs

### ISSUE THREAD

**Issue by 404invalid-user** [nodogsplash/nodogsplash#614]
i am looking at authenticating clients from a db with php or even nodejs and have found out that i would need to use fas but the link to the documentation gives a 404 link: https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

**Comment by bluewavenet** [comment]
@404invalid-user 
Yes, FAS has been moved to openNDS.

See README.md
https://github.com/nodogsplash/nodogsplash#split-of-nodogsplash

openNDS:
https://github.com/openNDS/openNDS
Documentation:
https://opennds.readthedocs.io
