### ISSUE TITLE
@sqrt-1764

### ISSUE THREAD

**Issue by Atolley12** [nodogsplash/nodogsplash#622]
@sqrt-1764 
As promised I have tested v4.0.0 on OpenWrt 18.06.4 (nodogsplash_4.0.0-1_mips_24kc.ipk) and as expected it works fine.

_Originally posted by @bluewavenet in https://github.com/nodogsplash/nodogsplash/issues/387#issuecomment-513559557_

**Comment by bluewavenet** [comment]
@Atolley12 
And your point in mentioning this 4 years later?

**Comment by Atolley12** [comment]
How did you know its been 4 years

**Comment by bluewavenet** [comment]
@Atolley12 

> How did you know its been 4 years

Did you even read the original issue, or are you just posting randomly for no apparent reason?
Hint: Every issue and every reply is dated....

**Comment by Atolley12** [comment]
My mistake im new to this im just trying to sort my phone out and give it
more security at the same time login to an old account i locked my self out
of through github

**Comment by Atolley12** [comment]
Yes my mistake i have got it wrong
