### ISSUE TITLE
NDS v5.0.1 fails to compile on Debian Bookworm

### ISSUE THREAD

**Issue by martignoni** [nodogsplash/nodogsplash#624]
## Steps to reproduce

```bash
git clone https://github.com/nodogsplash/nodogsplash.git
cd nodogsplash/
git checkout v5.0.1
make deb
```

## Error occurring

```
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9) dh-systemd (>= 1.5) libmicrohttpd-dev (>= 0.9.51)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
make: *** [Makefile:79: deb] Error 3
```

## Notes

- `dh-systemd` is not present anymore in Bookworm and NDS builds its deb package successfully without it. I'm humbly suggesting to remove it from the deb package dependencies.
- File `debian/changelog` was not updated, so debian package is built with wrong version number.
- Build on bookworm throws many `warning: Compatibility levels before 10 are deprecated (level 9 in use)` warnings.

PRs will be provided.

**Comment by mwarning** [comment]
Awesome. :-)

Btw., one MR would have been fine.

**Comment by martignoni** [comment]
> Btw., one MR would have been fine.

Sorry. Since these are 3 different problems, was not sure if you'd like to precess them one at a time.
