### ISSUE TITLE
This link isn't work anymore.

### ISSUE THREAD

**Issue by lionelquellery** [nodogsplash/nodogsplash#635]
Inside the Readme, there is this link that is not working anymore, I think that this link is related to the original project. Wifidog: http://dev.wifidog.org/

**Comment by mwarning** [comment]
Looks like the project has moved to https://github.com/wifidog

**Comment by mwarning** [comment]
I have fixed the links. Thank you for the notice.

**Comment by bluewavenet** [comment]
@mwarning 
FYI the Wifidog project appears to be dead with the last release in 2015.
It has not worked properly, if at all, since 2018 as it depends on an ancient version of iptables.
