### ISSUE TITLE
Build errors on `master`

### ISSUE THREAD

**Issue by dtbayles** [nodogsplash/nodogsplash#637]
I am working on a Captive Portal solution for our R-Pi's. I'd like to use the `master` branch to keep up with any major updates/enhancements and vulnerability fixes since `stable` was last updated. I can checkout and build `stable` branch just fine. But when trying to build `master`, I get some silly compile errors like the one below. I have attached the entire .txt file with the output of running `make`. 

My `libmicrohttpd-dev` version is `0.9.62-1+deb10u1` so that should be ok ([doc reference](https://nodogsplashdocs.readthedocs.io/en/latest/install.html)). I tried going in and changing the return type of `send_error` from `enum MHD_Result` back to `int` but there are quite a few other silly errors that make me believe something is off. 

```
src/http_microhttpd.c:902:10: error: void value not ignored as it ought to be
   return send_error(connection, 404);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/http_microhttpd.c:326:10: error: invalid use of undefined type ‘enum MHD_Result’
   return send_error(connection, 503);
```
[output.txt](https://github.com/nodogsplash/nodogsplash/files/14155289/output.txt)

In the end, my goal is to just have a Captive Portal solution that doesn't allow end users to have access to the internet and allows me to display our .php (if possible) server in the Captive Portal. I've toyed with a few different options here but would appreciate if someone could also give some pointers/guidance here as to what would be a good and best practice solution.

**Comment by mwarning** [comment]
Hi, `enum MHD_Result` was introduced in libmicrohttpd 0.9.71. That means that your libmicrohttpd version is too old.

**Comment by mwarning** [comment]
Better update libmicrohttpd :-)
