### ISSUE TITLE
When the router WAN port has no Internet connection, there is no authentication pop-up window

### ISSUE THREAD

**Issue by TakinaNoa** [nodogsplash/nodogsplash#640]
I am using an openwrt router. After I installed and configured nodogsplash, when I unplugged the wan port cable and used my phone to connect to wifi, I found that there was no authentication pop-up window on my phone. However, as long as I plugged the wan port cable back in to allow the router to access the Internet, when I used my phone to connect to wifi again, the authentication pop-up window would appear normally. I have tried it many times and can confirm that this is 100% reproducible. Has anyone encountered the same situation? If so, can you tell me how to solve it?

**Comment by bluewavenet** [comment]
@TakinaNoa 
This is the captive portal working as designed, it is not a fault condition.
 **_It is a function of the CPD software on your phone._**

**Comment by TakinaNoa** [comment]
> @TakinaNoa This is the captive portal working as designed, it is not a fault condition. **_It is a function of the CPD software on your phone._**

Thank you.
