### ISSUE TITLE
No Internet

### ISSUE THREAD

**Issue by adibindrianto** [nodogsplash/nodogsplash#643]
When I try to change the interfaces "br-lan" to "br-guest" my guest network and activate it there is no internet, but when I disable NDS the internet runs normally
Device: linksys EA4500
OS: Openwrt 23.05

**Comment by bluewavenet** [comment]
@adibindrianto 
That is what is supposed to happen. The captive portal blocks Internet access until the client authenticates.

**Comment by adibindrianto** [comment]
that's not what happened, the client connected to wifi, what happened was there was no NDS portal and cleint still had no internet

**Comment by bluewavenet** [comment]
@adibindrianto 

> Openwrt 23.05

23.05 uses nftables, but NoDogSplash uses iptables, so most likely is incompatible with a standard "guest" configuration, assuming of course that you have configured the guest network in the normal way.

**Comment by adibindrianto** [comment]
how can it be used on openwrt 23?

**Comment by bluewavenet** [comment]
@adibindrianto 
If it worked on br-lan, then it is most likely an iptables/nftables issue.
It is probably possible to hack about and get it working, but in my opinion it would be better to remove nodogsplash and use opennds instead as it uses native nftables and is fully compatible with the openwt firewall (fw4).

In its default config openNDS works very similar to NoDogSplash with a click to continue splash page.
It can even be configured to use the legacy NoDogSplash splash.html template if you so desire.
See: https://github.com/openNDS/openNDS
Open an issue there if you need help.

**Comment by adibindrianto** [comment]
thank you, it's working
