### ISSUE TITLE
Set no session persistence

### ISSUE THREAD

**Issue by AdityaC4** [nodogsplash/nodogsplash#644]
How do I make sure that if a user disconnects, the router forgets about them. I need the user to login through the captive portal every time they connect to the router even if they had a authenticated session a min ago. Is there a way to disable persistent session so if the user disconnects, they are shown the captive portal again when reconnecting. 
Thank You.

**Comment by bluewavenet** [comment]
@AdityaC4 

> How do I make sure that if a user disconnects, the router forgets about them.

There is nothing in NoDogSplash to do this if they, for example, connected to a different SSID or turned their wireless off etc..

You could set AuthIdleTimeout to 1 minute, but this would probably make the system unusable.

```
# Parameter: AuthIdleTimeout
# Default: 120
#
# Set AuthIdleTimeout to the desired number of minutes before
# an authenticated user is automatically 'deauthenticated'
# and removed from the client list.
#
```

**Comment by AdityaC4** [comment]
Oh ok. Thank you!
