### ISSUE TITLE
对linux不在行，交叉编译一窍不通，请问如何单独编译

### ISSUE THREAD

**Issue by kings0527** [nodogsplash/nodogsplash#71]
想单独修改一个功能来进行编译。
交叉环境已经搞了三天了

http://www.it165.net/os/html/201405/8236.html

第五步开始，各种入坑，一个个解决。最后一步完全无法编译GCC。

现在终于用了buildroot搞好了编译，选的是 高位地址存储的MIPS，这个还不知道路由器到底是高位还是低位。

version信息如下：
mips-linux-gcc (Buildroot 2015.05-rc1-00020-g1f75157) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

但是我看到这个教程上面的命令是   mipsel-linux-gcc，貌似在跳坑的时候看到这个区别，忘记了，不知道有没关系。

现在改了make文件的CC方式，发现不能make，然后发现不使用mips，直接make也不行，请原谅对make的无知，求告诉下如何编译出来放在我的路由器上面。难道我一个个make C文件然后自己link吗？

找到些是说在openwrt的编译环境中重新编译openwrt的固件，编译时，勾选nodogsplash，我测试话就太麻烦了。

还有一个问题是token的问题，生成token的地方传入了IP和mac，但是没有使用，而是直接随机了，这个不知道是不是提交错误了还是就是这么偷懒了。。。

如果哪位能帮忙解决编译问题的话感激不尽，加班到现在，熬不住了。

**Comment by kings0527** [comment]
还有一个问题是关于白名单的问题。

配置文件中有一个预授权用户的可访问地址配置

FirewallRuleSet preauthenticated-users

这里面只能填写IP而不能填写域名，还没有看代码的实现，不知道是程序bug还是本身不能设置域名。

**Comment by lynxis** [comment]
Hi @kings0527
please create a new ticket in english and please only one thing within a ticket.
