### ISSUE TITLE
Client “Failed to obtain IP”

### ISSUE THREAD

**Issue by aaronchn** [nodogsplash/nodogsplash#72]
Thank you for your excellent work!

When I tried the version 0.9_beta9.9.8 and version 0.9_beta9.9.9 with has been customized nodogsplash.conf, the client which is not in “AllowedMACList” will be can’t get IP from the OpenWRT.

The normal logic is when the “MACMechanism” set “allow”, just the allowed MAC can get IP via dhcp services from the OpenWRT then triggered the splash page?

In my case, anyone who want to use my WiFi are popular, when they connected my SSID with none encryption, they can get IP then see the splash page. But just some MAC can through the authenticated which are in the allowed list. That should be wonderful.

Is this are real bug? Should I report it on Github? Any resolve tips? 
 
The key configurations are following:
<pre>
# Parameter: GatewayInterface
GatewayInterface br-lan
# FirewallRuleSet: users-to-router
FirewallRule allow tcp port 8080 (for my luci on this router)
# Parameter: GatewayAddress
GatewayAddress 192.168.1.1
# Parameter: ExternalInterface
ExternalInterface vlan1
# Parameter: RedirectURL
RedirectURL http://192.168.1.1/ (for my lighttpd on this router)
# ClientIdleTimeout
ClientIdleTimeout 30
# Parameter: ClientForceTimeout
ClientForceTimeout 60
# Parameter: MACMechanism
MACMechanism allow
# Parameter: AllowedMACList
AllowedMACList 00:16:XX:XX:XX,…
</pre>
 
Thank you！

**Comment by gazambuja** [comment]
If you want some VIP users, maybe is better idea you have a different SSID without nodogspalsh (in another interface).

**Comment by mwarning** [comment]
NDS does not interfere by with the DHCP server (the port is allowed by default by NDS)
