### ISSUE TITLE
traffic control

### ISSUE THREAD

**Issue by karlosa** [nodogsplash/nodogsplash#74]
I cant see any guides on correct traffic control setup. 

In /etc/config/nodogsplash I have

option trafficcontrol '1'
option downloadlimit '2000'

etc/init.d/nodogsplash start shows

 Testing module imq numdevs=2
   Module imq numdevs=2 needed
   Scanning disk for imq module
   imq module missing: please install it

these are not availible on latest Openwrt trunk though...

**Comment by karlosa** [comment]
So currently my understanding is as of barrier breaker traffic control does not work due to that module not been included... 
Is this correct?

**Comment by mwarning** [comment]
On 05/25/2015 05:45 AM, karlosa wrote:
> So currently my understanding is as of barrier breaker traffic control does not work due to that module not been included... 
> Is this correct?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nodogsplash/nodogsplash/issues/74#issuecomment-105115002
> 

Yes.

The traffic control code (https://github.com/nodogsplash/nodogsplash/blob/master/src/tc.c) needs to be changed
to use kmod-ifb instead of iptables-mod-imq:
http://www.linuxfoundation.org/collaborate/workgroups/networking/ifb

Nobody had the time to update the code yet. :/

**Comment by karlosa** [comment]
Oh I see, thanks very much for the responce, in the meantime I have found sqm-qos to be usable in my testing, cheers.

**Comment by gazambuja** [comment]
some news here? someone implement ifb over nodogsplash?
the goal is use BinVoucher to control bandwith per user.

Thanks.

**Comment by bluewavenet** [comment]
I have been using wshaper available in Barrier Breaker and above. Seems to do the job ....
