### ISSUE TITLE
Problem with iOS clients

### ISSUE THREAD

**Issue by josefglatz** [nodogsplash/nodogsplash#75]
I have runing nodogsplash 0.9_beta9.9.8 on latest OpenWrt stable.

There is the problem, that mostly iOS devices which where connected in the past didn't get the splash page anymore. These then remain preauthenticated. The funny thing is, that Whatsapp and facebook is working although there are just tcp/udp port 53 opened.
If I authenticate them manually it works.

Are there any special configuration necessary?

**Comment by 4L3Xx** [comment]
I have noticed there is some kind of issue with iptables configuration code.  HTTPS port (and any other port) is not blocked like it should be for preauthenticated users.

**Comment by bluewavenet** [comment]
I don't know about the ios issue but see issue #18 (closed) and releases. 0.9_beta9.9.8 is broken in that it lets all ports through except 80 when preauth. Fixed in 9.9.
