### ISSUE TITLE
BinVoucher script

### ISSUE THREAD

**Issue by marcosbontempo** [nodogsplash/nodogsplash#76]
Hello,

I want to use the BinVoucher functionality but I'm a little confused about how to write the authentication script. Can someone show me a simple example?

Any tip will be very helpful,
Thanks.

**Comment by 4L3Xx** [comment]
You simply need to create a bash script (or any executable file) and have it print the required line (see docs) to stdout.  Something like this should suffice,

```
#!/bin/bash

# do some kind of processing here

echo "60 1000 1000"
```

**Comment by anirudhkabi** [comment]
What does the numbers "60 1000 1000" stand for?

And How do I pass my token/voucher as input in splash.html?

**Comment by mwarning** [comment]
On 10/07/17 17:24, anirudhkabi wrote:
> What does the numbers "60 1000 1000" stand for?
> 
> And How do I pass my token/voucher as input in splash.html?
> 

The user is logged in for 60 seconds, and ist granted 1000 KBit/s up- and download (if traffic shaping is used, but it is defunct right now iirc).

**Comment by mwarning** [comment]
On 10/07/17 17:24, anirudhkabi wrote:
> What does the numbers "60 1000 1000" stand for?
> 
> And How do I pass my token/voucher as input in splash.html?
> 

Have a lock at resources/splash.html.
The $tok and $redir variables will be passed to nodogsplash on click on the submit button.
You could also use a link like this: <a href="$authaction?tok=$tok&redir=$redir">Click here</a>
