### ISSUE TITLE
suggest: download and upload the archive

### ISSUE THREAD

**Issue by sinkcup** [nodogsplash/nodogsplash#77]
suggest: download the archive, then upload it, the filename and link will changed.

docs:
https://github.com/wifidog/wifidog-gateway/wiki

now the archive download link is:
https://github.com/nodogsplash/nodogsplash/archive/v0.9_beta9.9.9.tar.gz

if we want to use it in openwrt package Makfile, the link should be:
https://github.com/nodogsplash/nodogsplash/releases/download/v0.9_beta9.9.9/nodogsplash-0.9_beta9.9.9.tar.gz

like:
https://github.com/nodogsplash/nodogsplash/releases/download/v0.9_beta9.9.9/nodogsplash_0.9_beta9.9.9-1_ar71xx.ipk

**Comment by mwarning** [comment]
I do not understand what you are proposing.
