### ISSUE TITLE
suggest: use Semantic Versioning 2.0.0

### ISSUE THREAD

**Issue by sinkcup** [nodogsplash/nodogsplash#78]
docs:
http://semver.org/

version number example:
0.9.8
0.9.9

or

0.9.8-beta
0.9.8-beta.2
0.9.9-beta
0.9.9-beta.2

**Comment by lynxis** [comment]
I agree

**Comment by lynxis** [comment]
@mwarning can we just release HEAD as 1.0.0?

**Comment by mwarning** [comment]
Yes. I am just quite busy (work, relocation, other projects).

**Comment by sinkcup** [comment]
Oh...does other members can release too?

**Comment by mwarning** [comment]
@sinkcup nope, you would need access to the project. We tend to give that to persons who have contributed more that one time.

**Comment by mwarning** [comment]
closing this issue - let's adapt semantic versioning.
