### ISSUE TITLE
FirewallRuleSet: users-to-router - not working in 0.9_beta9.9.9 ?

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#80]
FirewallRuleSet: users-to-router.
I might be misinterpreting how this works but the entry:
FirewallRule allow tcp port 80
should allow preauth users access to utttpd web server where post auth splash pages can be served up.
To achieve this I have to add a specific entry under FirewallRuleSet preauthenticated-users something like as follows:
FirewallRule allow tcp port 80 to 10.168.1.1
This works, but then I need a specific nodogsplash.conf to suit the ip of the router - inconvenient especially if someone later changes the router ip!

The potential DNS tunnelling issue could be resolved if this worked as only access to the router dns would be allowed.

**Comment by mwarning** [comment]
Actually, I do not know the intended behavior and working behind this. I do not like to break things for 1.0.0. :]

**Comment by bluewavenet** [comment]
I had a few moments to look into this again. 
iptables -L shows this:
Chain ndsRTR (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             mark match 0x100/0x700
DROP       all  --  anywhere             anywhere             state INVALID
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
DROP       tcp  --  anywhere             anywhere             tcp option=!2 flags:SYN/SYN
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2050
ACCEPT     all  --  anywhere             anywhere             mark match 0x200/0x700
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:www
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

As you can see, the first entry will block all packets marked 0x100 ie blocked ie preauth.
When a device connects to wifi (or lan), its packets are not marked at all so passes down the chain and is allowed to DHCP (bootps) and do an initial DNS (domain). Then the device will attempt a port 80 (using its CPD) and be marked as 0x100 (preauth). At this point any attempt to access the router will be blocked for all ports.(port 2050 is allowed prior to this in ndsOUT).
As things stand, allowing access to the router when in preauth has to be done in FirewallRuleSet: preauthenticated-users.
This works just fine, it is just a little misleading in the example nogogsplash.conf
