### ISSUE TITLE
$clientmac & $gatewaymac Doesn't work

### ISSUE THREAD

**Issue by aodzip** [nodogsplash/nodogsplash#81]
The splash page just show $clientmac
Doesn't replace by the real mac address
this is important for bin voucher pre auth
OpenWrt CC - RC3 x86
Sorry for my poor English

**Comment by aodzip** [comment]
poor English
lol
really poor

**Comment by mwarning** [comment]
It was implemented in nodogsplash 0.9-beta9.9.9. What version do you use?
https://github.com/nodogsplash/nodogsplash/blob/master/ChangeLog

**Comment by aodzip** [comment]
nodogsplash_0.9_beta9.9.9-5_x86.ipk
from openwrt official branch

**Comment by patricio-mosse-olx** [comment]
Hello! I compiled a IPK package using the last sources from Master branch and the variables are not working for me either.
@aodzip did you manage to solve this?

**Comment by pmosse** [comment]
Hello! I compiled a IPK package using the last sources from Master branch and the variables are not working for me either.
@aodzip did you manage to solve this?

**Comment by pmosse** [comment]
Finally managed to make it work with the last sources.

**Comment by aodzip** [comment]
you got it work?! How?😉

**Comment by mwarning** [comment]
The clientmac variable is not part of any release yet. You have to build NDS yourself from sources to use it.

**Comment by ArtMartin89** [comment]
@pmosse can you give .ipk with working $clientmac, I've compiled using the last sources from Master branch, but it still doesn't work, just shows $clientmac instead of real mac

**Comment by aodzip** [comment]
you should edit the MakeFile of nodogsplash feed from openwrt
change version from 0.9.9 to master
and compile
it should work

从我的 ASUS 发送

**Comment by ArtMartin89** [comment]
@aodzip thanks for you reply. I've done as you described: changed lines PKG_VERSION:=0.9_beta9.9.9 to PKG_VERSION:=master and PKG_SOURCE_VERSION:=v0.9_beta9.9.9 to PKG_SOURCE_VERSION:=master in Makefile https://github.com/nodogsplash/nodogsplash/blob/v2/openwrt/nodogsplash/Makefile compiled it & I have 2 problems: 1)NDS doesn't work 2) after I make it work by replasing nodogsplah file in /etc/init.d with similar file from NDS 9.9.9-1 it start working but still doesn't get $clientmac.
Can I get direct contacts of somebody who can help to solve the problem of $clientmac. Or contact me please: art.martin.89@gmail.com, skype: work.arthur
Is very important to get $clientmac, thanks for your help.

**Comment by gazambuja** [comment]
Hi, I try the same thing like @ArtMartin89, and when try to install the new package I get "Segmentation fault":

      opkg install --force-reinstall /tmp/nodogsplash_0.9_beta9.9.9-6_ramips_24kec.ipk 
      Installing nodogsplash (0.9_beta9.9.9-6) to root...
      Segmentation fault

After that I try to compile the master branch and all work fine... but the $clientmac var and $gatewatmac are not parsed :(

We need to compile v2 or master branch?
You know wich lines we have to verify in the code ?

**Comment by patricio-mosse-olx** [comment]
Sure, try with this version (rename the extension, remove the '.jpg' from the name). I just compiled the last version of the code.

![nodogsplash_0 9_beta9 9 9-pre-2_ar71xx ipk](https://cloud.githubusercontent.com/assets/12500966/10800061/cac31e56-7d8e-11e5-9301-39ee2de67775.jpg)

**Comment by pmosse** [comment]
Sure, here is the version that works fine (just remove the extension 'jpg' from the name). Consider that it is compiled for a specific router so it may not work for all devices.

![nodogsplash_0 9_beta9 9 9-pre-2_ar71xx ipk](https://cloud.githubusercontent.com/assets/6408341/10800446/98ef861a-7d90-11e5-80e5-2ef03f564195.jpg)

**Comment by gazambuja** [comment]
Thanks @pmosse I will try in some standard router... Right nowI have one with ramips arch (Xiaomi Mini). You can send me the source/link? so I make ipk file to this arch :)

**Comment by ArtMartin89** [comment]
Thank to @aodzip who sent me .ipk that gets $clientmac & thanks to @pmosse his .ipk also works and starts good)

**Comment by aodzip** [comment]
@gazambuja i think u can build it by openwrt sdk of ramps. just update feed and edit MakeFile of nds

**Comment by gazambuja** [comment]
I got it!! if any need help, here all steps:

		cd openwrt

		./scripts/feeds update -a
		./scripts/feeds install -a
		./scripts/feeds uninstall nodogsplash

		git clone https://github.com/openwrt-routing/packages.git
		cp -rf packages/nodogsplash/ package/
		rm -rf packages/

		make defconfig
		make menuconfig

now edit package/nodogsplash/Makefile file and change PKG_VERSION and PKG_SOURCE_VERSION to "master":

		PKG_VERSION:=master
		PKG_SOURCE_VERSION:=master

now make package:

		make package/nodogsplash/compile
		make package/nodogsplash/install

you new ipk file will be in:

		ls bin/ramips/packages/base/nodogsplash*

**Comment by mwarning** [comment]
The new release should include the features.

**Comment by BuZLuCaY** [comment]
I have this problem. How can I fix it?

**Comment by bluewavenet** [comment]
I think this is fixed in version 1.
The quickest way to get this is to reflash with the current release of LEDE and install NDS from there.
https://downloads.lede-project.org/releases/

**Comment by bluewavenet** [comment]
I can confirm that this works in v1.0.1-2 included in LEDE Reboot 17.01.0-rc2
