### ISSUE TITLE
nodogsplash on OpenWrt Chaos Calmer final release

### ISSUE THREAD

**Issue by geoffch** [nodogsplash/nodogsplash#84]
Trying out the OpenWrt Chaos Calmer final release, I found that nodogsplash cannot be installed because it depends on a specific kernel version.  This was not a problem with CC rc3.  I hope someone will take care of updating the dependencies.  Thanks.

**Comment by lynxis** [comment]
This is might a build problem of the CC.
Please try to verify:
* download CC final image for your router
* do sysupgrade onto new version
* `opkg update ; opkg install nodogsplash`

If the problem still exist please open a ticket on https://dev.openwrt.org/ describing kernel dependency problem.

**Comment by bluewavenet** [comment]
Just tried CHAOS CALMER (15.05.1, r48532), released last week.
There is a problem with the init.d script in that it fails to enable. Manual edit of /etc/config/nodogsplash is required to enable but then all runs fine.

**Comment by bluewavenet** [comment]
@lynxis - Is the "new" init.d script working towards uci integration? It obviously does not initially create the .conf file unless /etc/config/nodogsplash is edited manually to include option enabled 1. I guess this could be done with an enable_service() entry in the init.d script. Currently the services part of luci shows "enabled" when it is in fact disabled.
Just wondering what the plan is :)
