### ISSUE TITLE
Problem with (some) android clients.

### ISSUE THREAD

**Issue by bluewavenet** [nodogsplash/nodogsplash#85]
Android client connects and browser pops up with our Tos accept page and user accepts and has full internet access as normal.

Android goes to sleep. on waking up and reconnecting on Wifi reports "obtaining IP address" but then drops connection again, repeating in a rapid loop indefinitely. User selects nodog wifi ssid and tells android to forget the ssid, then selects that ssid again to get a good connection and ToS page again.

Anyone else seen this? 

Seen on Android 4.4.2 - will be trying others. NDS 0.9_beta9.9.9

**Comment by bluewavenet** [comment]
On first connection it all works with Firefox popping up with the splash ToS page.
If android goes to sleep, on waking it up I get the problem and here is a bit more detail, I get:
Obtaining IP address
[ip address obtained]
Checking the Quality of Your Internet Connection 
[android disables wifi]
[android enables wifi]
Obtaining IP address ...
Keeps looping...
It seems to be an Android problem, or more specific a Samsung Android problem. Sometimes it does work on wake up however!
Does anyone know what Android is doing for its check on internet quality?  It may be possible to do something on the NDS end .....
Talking to users on an NDS test public system - ios users think it is great and very usable.
Android users say it sometimes works but is a total pain...

**Comment by gareth41** [comment]
Might be a dhcp server issue, try running wireshark to see what's going on. It could be that the dhcp server is broadcasting replies instead of unicasting to clients, the dhcp options may also not be set correctly, look at lease time and rebind time option values.

**Comment by bluewavenet** [comment]
Further research - no problem in ICS, intermittent and sometimes severe in Jelly Bean and Kitkat but ok again in Lolipop. Not tried Marshmallow yet. So Android buglet I think.
