### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by tranduchieu** [nodogsplash/nodogsplash#91]
After I install & run `ndscl status` then error:

```
ndsctl: nodogsplash probably not started (Error: No such file or directory)
```

I tried reinstalling but still got this error. Did Anybody meet this error?
Tks.

**Comment by bluewavenet** [comment]
It means nodogsplash is not running. How are you trying to start it?

**Comment by mbaylet** [comment]
I got the same issue.
I install nodogsplash with the OpenWRT package manager in the LUCi interface.
Then i run
/etc/init.d/nodogsplash start
It returns without any messages.

Then i run:
ndsctl status
And i got the same message as tranduchieu.

Any ideas ? Thanks

**Comment by sfzy** [comment]
Yes,I got the same status as @mbaylet

**Comment by mbaylet** [comment]
Thanks a lot @sfzy that was it !
The solution is just to set the enable flag to 1. I can't believe i missed it.
I didn't get the error you got "nodogsplash uses obsolete" did you install the package with opkg, it will install all the dependencies correctly.

**Comment by mwarning** [comment]
This should be "fixed" now.

**Comment by MarkoTU** [comment]
Hi,

I have NDS running on PC (Lubuntu). For some reason NDS does not start after reboot. When checking the status It gives ndsctl: nodogsplash probably not started (Error: No such file or directory).
I was wondering should I add some file into /init.d folder to get it started. Thanks.

**Comment by bluewavenet** [comment]
So it "sometimes" starts on reboot?
On the OpenWrt/LEDE platform it was noticed that occasionally the network interface was not up when NodogSplash tried to start, so it would fail, depending on the actual hardware . 

An easy fix if this is the case for you. 

The simplest way to test this is to add a sleep() to the init.d in the correct section.

If this does the job then we should look at the way it is done in OpenWrt/LEDE.
 
I have not tried Lubuntu, does it use init.d?

**Comment by bluewavenet** [comment]
Here is a link to the init.d script for OpenWrt/LEDE
https://github.com/openwrt-routing/packages/blob/master/nodogsplash2/files/nodogsplash.init

**Comment by MarkoTU** [comment]
Hi,

Thanks for the help. Lubuntu uses init.d but NDS is not in that folder. Now it seems to start quite nicely as I run nodogspash stop and ndsctl stop several times and then nodogsplash start :) I have no glue why it started to work better after that. I'll try the script if it stops working. The Nodogsplash in this case is installed from the debian package (build using dpkg-buildpackage -b command).

**Comment by bluewavenet** [comment]
Try this script. I do not have Lubuntu to test it on. It is a very stripped down version. Copy to your Lubunto init.d directory (probably /etc/init.d/), rename as just nds without the .txt extension and run chmod +x /etc/init.d/nds
then type:
/etc/init.d/nds start

Finally if it all works type:
/etc/init.d/nds enable  to make it start automatically on boot.
You can edit the WAIT variable to tune the sleep interval required to ensure the lan interface is ready.
[nds.txt](https://github.com/nodogsplash/nodogsplash/files/1723959/nds.txt)

**Comment by MarkoTU** [comment]
Thank you very much! I'll try that.

**Comment by MarkoTU** [comment]
Hi,
I tried nds script but it gives after "/etc/init.d/nds start" an error " /bin/sh: 0: Can't open /etc/rc.common".
Any new ideas? Thanks in advance.

**Comment by bluewavenet** [comment]
@MarkoTU 
This is most likely an issue with the init.d process. 
Something is corrupted or missing in your OS
This will happen if you have edited rc.common (or even opened it then inadvertently saved) with a Microsoft editor eg notepad as it will change the unix end of line (newline) character to the Windows (cr/lf) character or characters thus corrupting the script.
I am not saying this is the problem in this case but I have seen it happen before.

**Comment by MarkoTU** [comment]
Hi,
I guess it is perhaps not the reason for the fault. I have three fresh Lubuntus running and none of them has rc.common. I'm also sure that I have not opened that after installation. There are several other rc-folders such as (/etc/rc5.d /etc/rc2.d /etc/rc3.d /etc/rc1.d /etc/rc0.d /etc/rc4.d /etc/rc6.d) :)
I keep on debugging the issue anyway. If you have any other good proposals I will definitely try them.
Thanks!

**Comment by bluewavenet** [comment]
That explains why it cannot open rc.common :-D
Do you have other startup scripts in /etc/init.d ?
Lubuntu might be doing things differently in its basic mode.

**Comment by MarkoTU** [comment]
update-rc.d command exists.
There are plenty of startup scripts in init.d, such as nginx.

I took a snapshot of the system log file. It somehow gives a feeling that some delay would be usefull?! So there is create_ap that starts earlier and after that the NDS. After several reboots it looks like either NDS or create_ap is started but not both :)
Feb 16 22:55:16 UN45 systemd[1]: Starting NoDogSplash Captive Portal...
Feb 16 22:55:16 UN45 dnsmasq[688]: dnsmasq: syntax check OK.
Feb 16 22:55:16 UN45 systemd[1]: Starting OpenBSD Secure Shell server...
Feb 16 22:55:16 UN45 systemd[1]: Starting A high performance web server and a reverse proxy server...
Feb 16 22:55:16 UN45 systemd[1]: Starting Network Name Resolution...
Feb 16 22:55:16 UN45 systemd[1]: Started Permit User Sessions.
Feb 16 22:55:16 UN45 systemd[1]: Started NoDogSplash Captive Portal.
Feb 16 22:55:16 UN45 create_ap[687]: WARN: Unrecognized configuration entry #GATEWAY
Feb 16 22:55:16 UN45 nodogsplash[689]: **[3][Fri Feb 16 22:55:16 2018][695](src/util.c:247) get_iface_mac ioctl(SIOCGIFHWADDR): No such device**
Feb 16 22:55:16 UN45 nodogsplash[689]: **[3][Fri Feb 16 22:55:16 2018][695](src/gateway.c:251) Could not get MAC address information of ap0, exiting...**


Thanks again, I appreciate your help! :)

**Comment by bluewavenet** [comment]
That's why I said you can edit the value of WAIT in the nds script.
You really need to familiarise your self with the startup systems of Lubuntu. It clearly uses systemd rather than init.d and only has an init.d compatibility mode.
There is a simple nodogsplash.service script for use with systemd, this might be a better way forward.

**Comment by MarkoTU** [comment]
Now it works :) Thanks for you help.
