### ISSUE TITLE
NoDogSplash - missing config file (Chaos Calmer)

### ISSUE THREAD

**Issue by arainzhao** [nodogsplash/nodogsplash#92]
Hi,
I tried to set up a captive portal using NoDogSplash on my Raspberry Pi with OpenWRT Chaos Calmer and I faced a problem. I installed nodogsplash package with opkg and wanted to change its configuration. Then I found that configuration file "/etc/nodogsplash/nodogsplash.conf" was missing so I made new configuration file by myself. Now, when I am trying to start nodogsplash with "/etc/init.d/nodogsplash start" command I get the message:
 nodogsplash: Configuration file '' doesn't exist" 
Also new, empty file "CONFIGFILE" in /etc/nodogsplash directory was created. I failed to find any cause and solution~ sad~ Can anyone help me with that problem? I am new to openWRT so it is possible that I did something wrong. Thank you for answers.

**Comment by lynxis** [comment]
Take a look into /etc/config/nodogsplash.
If you don't like uci configuration, you can use the config override.
<pre>
cat > /etc/config/nodogsplash <<EOF
config instance
        option enabled 1
        option config '/etc/nodogsplash/nodogsplash.conf'
EOF
</pre>

**Comment by sfzy** [comment]
I remove the '#' from the line 'option config '/etc/nodogsplash/nodogsplash.conf'' 
then start the nodogsplash,but I got this:
nodogsplash: Configuration file '' doesn't exist

**Comment by zhuzhengwen1983** [comment]
yes. I has the same issue. I run the /etc/init.d/nodogsplash start but it not load the nodogsplash/nodogsplash.conf

**Comment by sfzy** [comment]
@zhuzhengwen1983 see here https://github.com/nodogsplash/nodogsplash/issues/97

**Comment by netomx** [comment]
Fix:
 ( /etc/init.d/nodogsplash )

`config_get val "$cfg" config
  if [ -n "$val" ] ; then
    if [ -f "$val" ] ; then
      echo "Loading configuration file " $val
      cat $val > $CONFIGFILE
    else
        nolog error "Configuration file '$val' doesn't exist"
        return 1
    fi
  fi
`

And add:

( /etc/config/nodogsplash )

`option gatewayinterface 'YOURGATEWAY'`

**Comment by mwarning** [comment]
@netomx it would be nice if you could create a merge request here: https://github.com/openwrt-routing/packages/blob/master/nodogsplash/files/nodogsplash.init
If you need help, let me know.

**Comment by lynxis** [comment]
@all if this is still a problem, please open a ticket on https://github.com/openwrt-routing/packages
it's here quite in the wrong place, because the script isn't anymore maintained in this repository. Thanks for your work on the script.
