### ISSUE TITLE
I can't install nodogsplash in OpenWRT

### ISSUE THREAD

**Issue by zhuzhengwen1983** [nodogsplash/nodogsplash#93]
I want install last nodogsplash in OpenWRT. but I get a error.

Unknown package 'nodogsplash'.
Collected errors:
 * opkg_install_cmd: Cannot install package nodogsplash.

How to install it. Please help me. Thanks

**Comment by arainzhao** [comment]
opkg update
opkg install nodogsplash

**Comment by zhuzhengwen1983** [comment]
thanks arainzhao，I run your command in my openWRT.
it return this
Unknown package 'nodogsplash'.
Collected errors:
 * opkg_install_cmd: Cannot install package nodogsplash.

**Comment by zhuzhengwen1983** [comment]
I can't to find 'nodogsplash' in my opkg list

**Comment by zhuzhengwen1983** [comment]
this is my opkg config file. Have any issues?

dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
src/gz chaos_calmer_base http://downloads.openwrt.org/snapshots/trunk/sunxi/generic/packages/base
src/gz chaos_calmer_luci http://downloads.openwrt.org/snapshots/trunk/sunxi/generic/packages/luci
src/gz chaos_calmer_management http://downloads.openwrt.org/snapshots/trunk/sunxi/generic/packages/management
src/gz chaos_calmer_packages http://downloads.openwrt.org/snapshots/trunk/sunxi/generic/packages/packages
src/gz chaos_calmer_routing http://downloads.openwrt.org/snapshots/trunk/sunxi/generic/packages/routing
src/gz chaos_calmer_telephony http://downloads.openwrt.org/snapshots/trunk/sunxi/generic/packages/telephony
# src/gz chaos_calmer_targets http://downloads.openwrt.org/snapshots/trunk/sunxi/generic/packages/targets

**Comment by bluewavenet** [comment]
If you download the released version of Chaos Calmer to suit your router/processor from OpenWrt, you should be able to install from the software section of the luci GUI.
You will also find nodogsplash in the packages/routing/ folder in openwrt downloads.
http://downloads.openwrt.org/chaos_calmer/15.05/

**Comment by zhuzhengwen1983** [comment]
thanks everyone. this is OpenWrt error. I change other version it's work.
