### ISSUE TITLE
Ver10 kernel

### ISSUE THREAD

**Issue by bullszi** [nodogsplash/nodogsplash#95]
Hi NDS people,

I have been using the NDS ipk with the $clientmac for some time now. $clientmac is awesome, it really did allow me to develop some great functionality.

The problem is that there is now a Ver10 of the TP-Link 801N which has a kernel version 4.1.10
of which my previously built ipk cannot be installed. ( I get an opkg warning that the kernel version is different).

When I 'make' the menuconfig are the some settings which I need to include to be able to install on this kernel version?

Is there something that I have skipped, or need to include to be able to install the nds ipk onto this kernel version?

Your help would be greatly appreciated.

**Comment by bullszi** [comment]
here is an image for the full error message ... 
![nds_opkg_kernel_error](https://cloud.githubusercontent.com/assets/5288663/10914356/555227c0-8252-11e5-9c6e-95b7cd2be5b4.png)

**Comment by bluewavenet** [comment]
Is this running the stock TP-Link firmware? You are better off running a release version of OpenWrt, but it looks like the router is not fully supported - so for now a bad choice of hardware :(
You can pick up a Ubiquiti airRouter or airGateway for not much more money and you will be fully supported - high performance and loads of memory. I'm running nds, php and mysql on an airGateway with still a good headroom so worth thinking about....
