### ISSUE TITLE
MD5 hash to MAC addr

### ISSUE THREAD

**Issue by gazambuja** [nodogsplash/nodogsplash#96]
How I can apply MD5 hash to MAC addr on splash vars?
What is the file that need change? 

Thanks

**Comment by bluewavenet** [comment]
If you have enough memory on your router you can use opkg to install php support for httpd. I run a script to get the client ip address then parse the the openwrt dhcp database to get the mac address and hash the result. Depends on what you are trying to do. I wanted a central database to recognise a client logging in from another network.....
