### ISSUE TITLE
[close]'Use plain configuration file as well' seems does not worked

### ISSUE THREAD

**Issue by sfzy** [nodogsplash/nodogsplash#97]
# Use plain configuration file as well
  option config '/etc/nodogsplash/nodogsplash.conf'
It seems does not work,I got this:
____________________________________
nodogsplash: Configuration file '' doesn't exist
 Testing required modules
  Testing module ipt_mac 
   ipt_mac is working
  Testing module ipt_mark 
   ipt_mark is working
_______________________________________
The /etc/nodogsplash/nodogsplash.conf  is does there

I copy the nodogsplash.conf from openwrt wiki

If the new nodogsplash uses the different nodogsplash.conf from the old?

If there is some particular menu of /etc/config/nodogsplash ?

**Comment by sfzy** [comment]
Sorry I make a mistake.
nodogsplash is did to read the config file "/etc/nodogsplash/nodogsplash.conf" I found it frome the conf.c source code.
If run nodogsplash directly in sh, it in did worked.
But I installed nodogsplash from the openwrt offical ipk source,and run nodogsplash like this, run command in sh "/etc/init.d/nodogsplash start" , it read config file first from "/etc/config/nodogsplash"
I cat the /etc/init.d/nodogsplash the I got this
----------------
#!/bin/sh /etc/rc.common
#
# description: Startup/shutdown script for nodogsplash captive portal
#
# Alexander Couzens <lynxis@fe80.eu> 2014
# P. Kube 2007
#
# (Based on wifidog startup script
# Date    : 2004-08-25
# Version : 1.0
# Comment by that author: Could be better, but it's working as expected)
#
---------------
So the problem is not cause by nodogsplash but the etc/init.d/nodogsplash

**Comment by lynxis** [comment]
@sfzy please open a ticket within https://github.com/openwrt-routing/packages if this is still a problem, because it looks for me that this is produced by the openwrt' specific initscript.
