### ISSUE TITLE
delay the Redirects and no redirect of windows smartphones

### ISSUE THREAD

**Issue by pavlosipress** [nodogsplash/nodogsplash#98]
First of all I would like to thank you for the application.

I would like to mention a few bugs that I found.
1. It takes too long to load my page. Why is this happening?
2. When i connect to wifi via smartphone with windows operating system, shows the "sign in" but does not display the Splash page. Something like the hamstrings.

Best regards

**Comment by bluewavenet** [comment]
Possibly a result of OpenWrt ipv6 support. See #113 
[https://github.com/nodogsplash/nodogsplash/issues/113](url)

**Comment by bluewavenet** [comment]
Captive Portal Detection now seems to have matured to give a reliable experience on most OS and works, usually, very well with NDS.
